<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:ora="http://www.oracle.com/XSL/Transform/java" xmlns:supsfo="http://eds.com/supsfo" xmlns:fo="http://www.w3.org/1999/XSL/Format" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0" xmlns:ns0="xmlns" ns0:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:import href="supsfo.xsl"/><xsl:strip-space elements="*"/><xsl:output method="xml"/><xsl:template match="/"><editableSections><div class="EDITME" id="N100C6"><div><font size="2" face="Times New Roman">
		<div style="margin-bottom: 0.4cm; font-weight: bold;">
			ON THE <xsl:value-of xmlns="http://eds.com/supsfo" select="$vdJudgmentDate"/>, <xsl:value-of xmlns="http://eds.com/supsfo" select="$vdJudge"/>
		</div>
		<div style="margin-bottom: 0.4cm;">
			sitting at <xsl:value-of xmlns="http://eds.com/supsfo" select="$vdHearingAtCourtName"/> <xsl:value-of xmlns="http://eds.com/supsfo" select="$vdCourtOrDistrict"/>, <xsl:value-of xmlns="http://eds.com/supsfo" select="$vdHearingAtCourtAddress"/>
		</div>
		<div style="margin-bottom: 0.4cm;">
			<xsl:copy-of xmlns="http://eds.com/supsfo" select="$vdHearingAttendees"/>
		</div>
		<div style="margin-bottom: 0.4cm;">
			<span style="font-weight: bold;">and the court orders</span> that
		</div>
		<ol><xsl:call-template name="possession1"/></ol>		
		</font></div></div></editableSections></xsl:template><xsl:template name="pagesequence"><xsl:param name="addressee"/></xsl:template><xsl:template name="possession1"><xsl:param name="number">1</xsl:param><li><div>The defendant give the claimant possession of <xsl:value-of xmlns="http://eds.com/supsfo" select="$vdPossessionProperty"/></div><div style="margin-bottom: 0.4cm;">on or before <xsl:value-of xmlns="http://eds.com/supsfo" select="$vdPossessionDate"/>.</div></li><xsl:call-template name="possession2"><xsl:with-param name="number"><xsl:value-of select="$number + 1"/></xsl:with-param></xsl:call-template></xsl:template><xsl:template name="possession2"><xsl:param name="number">1</xsl:param><xsl:choose><xsl:when test="string-length($vdPossession2) &gt; 0"><li><div style="margin-bottom: 0.4cm;"><xsl:value-of xmlns="http://eds.com/supsfo" select="normalize-space($vdPossession2)"/>.</div></li><xsl:call-template name="possession3"><xsl:with-param name="number"><xsl:value-of select="$number + 1"/></xsl:with-param></xsl:call-template></xsl:when><xsl:otherwise><xsl:call-template name="possession3"><xsl:with-param name="number"><xsl:value-of select="$number"/></xsl:with-param></xsl:call-template></xsl:otherwise></xsl:choose></xsl:template><xsl:template name="possession3"><xsl:param name="number">1</xsl:param><xsl:choose><xsl:when test="string-length($vdPossessionCosts3) &gt; 0"><li><div style="margin-bottom: 0.4cm;"><xsl:value-of xmlns="http://eds.com/supsfo" select="normalize-space($vdPossessionCosts3)"/>.</div></li><xsl:call-template name="possession4"><xsl:with-param name="number"><xsl:value-of select="$number + 1"/></xsl:with-param></xsl:call-template></xsl:when><xsl:otherwise><xsl:call-template name="possession4"><xsl:with-param name="number"><xsl:value-of select="$number"/></xsl:with-param></xsl:call-template></xsl:otherwise></xsl:choose></xsl:template><xsl:template name="possession4"><xsl:param name="number">1</xsl:param><xsl:choose><xsl:when test="string-length($vdPossession4) &gt; 0"><li><div style="margin-bottom: 0.4cm;"><xsl:value-of xmlns="http://eds.com/supsfo" select="normalize-space($vdPossession4)"/>.</div></li></xsl:when><xsl:otherwise/></xsl:choose></xsl:template></xsl:stylesheet>