<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:ora="http://www.oracle.com/XSL/Transform/java" xmlns:supsfo="http://eds.com/supsfo" xmlns:fo="http://www.w3.org/1999/XSL/Format" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0" xmlns:ns0="xmlns" ns0:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:import href="supsfo.xsl"/><xsl:strip-space elements="*"/><xsl:output method="xml"/><xsl:template match="/"><editableSections><div class="EDITME" id="N100C8"><div><font size="2" face="Times New Roman">
		<div style="margin-bottom: 0.4cm;">
			Before <xsl:value-of xmlns="http://eds.com/supsfo" select="$vdJudge"/> sitting at <xsl:value-of xmlns="http://eds.com/supsfo" select="$vdHearingAtCourtName"/> <xsl:value-of xmlns="http://eds.com/supsfo" select="$vdCourtOrDistrict"/>, <xsl:value-of xmlns="http://eds.com/supsfo" select="$vdHearingAtCourtAddress"/>
		</div>
		<div style="margin-bottom: 0.4cm;"><xsl:copy-of xmlns="http://eds.com/supsfo" select="$vdHearingAttendees"/></div>
		<div style="margin-bottom: 0.4cm;">Upon the application of the <xsl:value-of xmlns="http://eds.com/supsfo" select="$vdDeponentClaimantDefendant"/>, <xsl:value-of xmlns="http://eds.com/supsfo" select="$vdJudge"/> has ordered you to attend at <xsl:value-of xmlns="http://eds.com/supsfo" select="$vdHearingTime"/> on <xsl:value-of xmlns="http://eds.com/supsfo" select="$vdHearingDate"/> at <xsl:value-of xmlns="http://eds.com/supsfo" select="$vdHearingCourtName"/> <xsl:value-of xmlns="http://eds.com/supsfo" select="$vdCourtOrDistrict"/>, <xsl:value-of xmlns="http://eds.com/supsfo" select="$vdHearingCourtAddress"/> to be examined on oath <xsl:if xmlns="http://eds.com/supsfo" test="$vdDocumentExists = 'Y'">and to produce the following document(s): <xsl:copy-of select="$vdDocumentToProduce"/> </xsl:if>
		</div>
		<div style="margin-bottom: 0.4cm;"><xsl:value-of xmlns="http://eds.com/supsfo" select="$vdDeponentExpensesWording"/></div>
	</font></div></div></editableSections></xsl:template><xsl:template name="pagesequence"><xsl:param name="addressee"/></xsl:template></xsl:stylesheet>