/**
 * About-panel content constants for the State Explorer page.
 * Each section has a key, heading, and body text.
 * Centralised here so tests can verify content without a DOM.
 */

const ABOUT_SECTIONS = {
  whatItDoes: {
    key: 'whatItDoes',
    heading: 'What this page does',
    body: 'An interactive graph of all possession case states and the transitions between them. Each node is a state; directed edges are transitions. Click any node to open a detail panel showing events, actors, and Work Allocation tasks at that state.',
  },
  graphLayout: {
    key: 'graphLayout',
    heading: 'Graph layout',
    body: 'Node positions are auto-generated by the dagre layout algorithm. The layout is readable — it minimises edge crossings and flows roughly top-to-bottom — but positions are not semantically meaningful. Left/right proximity between states does not imply a relationship.',
  },
  nodeColour: {
    key: 'nodeColour',
    heading: 'Node colour',
    body: 'Amber = draft or uncertain state (not yet confirmed in policy). Green = live or confirmed state. Dark / near-black = terminal end state (no outgoing transitions). Muted / low-contrast = low completeness (<50% of expected model fields populated). Colour is derived from the hand-authored uncertaintyLevel field in the model data — it reflects analyst confidence, not system status.',
  },
  completenessBadge: {
    key: 'completenessBadge',
    heading: 'Completeness badge',
    body: 'The percentage of expected model fields that have been populated for this state. Low (<50%) means the state has been named but not fully modelled — descriptions, events, and actors may be missing. 0% may mean the state has not yet been modelled at all. Treat low-completeness states as placeholders, not confirmed design decisions.',
  },
  waTaskBadge: {
    key: 'waTaskBadge',
    heading: 'WA task badge',
    body: 'The count of Work Allocation tasks associated with events at this state. Badge colour reflects the worst alignment across those tasks: red = at least one gap, amber = at least one partial alignment, green = all tasks aligned. Alignment data comes from wa-mappings.json — incomplete mappings will undercount tasks and may show green when gaps exist.',
  },
  edgeStyle: {
    key: 'edgeStyle',
    heading: 'Edge style',
    body: 'Solid line = user-initiated transition (a person takes an action). Dashed line = system-triggered transition (the service triggers it automatically, e.g. after a deadline). Dotted line = time-based transition (triggered by a calendar or deadline rule). Derived from the systemTriggered flag on each transition in the model data.',
  },
};

/**
 * Returns the section object for a given key, or null for unknown keys.
 * @param {string} key
 * @returns {{ key: string, heading: string, body: string } | null}
 */
export function getAboutSection(key) {
  return ABOUT_SECTIONS[key] ?? null;
}

/**
 * Returns all about sections as an ordered array.
 * @returns {Array<{ key: string, heading: string, body: string }>}
 */
export function getAboutSections() {
  return Object.values(ABOUT_SECTIONS);
}
