/*
 * Created on 21-Jul-2005
 *
 * TODO To change the template for this generated file go to
 * Window - Preferences - Java - Code Style - Code Templates
 */
package uk.gov.dca.db.util;

/**
 * @author Peter Neil
 *
 * This class is generated by the Framework at build time it will be used
 * by the Configuration Checking utility for anyone who's checking application
 * configuration from outside the container. ie: telnet
 *
 *
 */
public class FrameworkConfigParam {

    private final String value; 
    
    public static final FrameworkConfigParam APPLICATION_NAME = new FrameworkConfigParam("@APPLICATION_NAME@");
    public static final FrameworkConfigParam PROJECT_CONFIG = new FrameworkConfigParam("@PROJECT_CONFIG@");
    public static final FrameworkConfigParam FRAMEWORK_CONFIG = new FrameworkConfigParam("@FRAMEWORK_CONFIG@");    
    public static final FrameworkConfigParam FRAMEWORK_CVS_TAG = new FrameworkConfigParam("$Name$&lt;");
    
    //prevent anyone from creating this class
    private FrameworkConfigParam(String value){
        this.value = value;
    }   

    /**
     * 
     * @return the value of the configuration param
     * 
     */
    public String getValue(){
        return value;
    }
    
}
