# sets the domain controller and associated jcifs properties
# Look at http://jcifs.samba.org/src/docs/resolver.html for more information.

jcifs.smb.client.domain=opscs

# This property will determine which hostnames to
# attempt to connect to for authentication.
# Use this option if there is no appropriate entry in 
# DNS for the domain name.
#
# This is a comma (,) seperated list of hostnames or
# IP Addresses.
#
#sups.jcifs.domainController=ops.cs.root
#sups.jcifs.domainController=csdv00011,csdv00001
sups.jcifs.domainController=csdv00011.ops.cs.root