#####################################################
#													#
#server clearcase configuration					    #
#the same file is created for the client framework  #
#													#
#####################################################
cc.project.component.name=cs-frwk-dev\\cs-frwk-dev
cc.baseline.full=will be set for release
selector.application.baseline=selector for the baseline which will be used to create the release
selector.release.stream=selector for the stream which will be created to create the release
release.label=The label used to create the release stream ServerFramework_Release_9.0.34
cc.baseline.version=the baseline number frwk-9-00x

build.time=created by useing a formatted tstamp in the integration/release build file
build.machine=will be populated from the systm ${env.COMPUTERNAME}
build.username=will be populated from the systm ${env.USERNAME}
build.userdomain=will be populated from the systm ${env.USERDOMAIN}
build.userdnsdomain=will be populated from the systm ${env.USERDNSDOMAIN}
