#############################################################
#															#
# The server build will populate the followign tokens		#
# which are exposed through the FrameworkConfigParam class	#
#															#
#############################################################
sups.project.name=@APPLICATION_NAME@
sups.project.config=@PROJECT_CONFIG@
sups.framework.config=@FRAMEWORK_CONFIG@
    