###################################
# This file contains a list of Methods available for each of the Services we require to have 
# preloaded by the EJBServiceDelegate loadCache Methods
#
# The application will have a service-method-config.properties file generated and stored
# in the conf.jar of the ${application.name}.ear
#
# service-method-config.properties is loaded along with this file and each of the Methods 
# for each serivce are loaded and stored in the gov.uk.dca.db.invoke.util.HomeMander and 
# are retrieved using gov.uk.dca.db.invoke.util.ServiceLocator 
# loaded by the  
#
###################################
Security=getPrintersList,getADUserDetails,getAllRoles,getDefaultPrinter,getHomeCourt,getPrintersList,getRoles,getUserCourtDetails,insertUserCourt,setDefaultPrinter,updateUser,updateUserCourt,updateUserRoles
Authentication=login