printers=a,b,c

c.serverName=uktps570
c.printerName=Xerox570
c.description=Court Room 1 & 2
c.driverName=Xerox Phaser <4500DT>
c.location=Office
c.printMediaReady=Letter
c.printMediaSupported=C5 Envelope 162 x 229 mm;B5 Envelope 176 x 250mm
c.shortServerName=uktps570
c.uNCName=\\\\uktps570\\Xerox
c.printShareName=Xerox570

a.serverName=uktps550
a.printerName=Xerox
a.description=Court Room 1
a.driverName=Xerox Phaser 4500DT
a.location=Office
a.printMediaReady=Letter
a.printMediaSupported=C5 Envelope 162 x 229 mm;B5 Envelope 176 x 250mm
a.shortServerName=uktps550
a.uNCName=\\\\uktps550\\Xerox
a.printShareName=Xerox

b.serverName=uktps550
b.printerName=Xerox2
b.description=Court Room 2
b.driverName=Xerox Phaser 4500DT
b.location=Office
b.printMediaReady=Letter
b.printMediaSupported=C5 Envelope 162 x 229 mm;B5 Envelope 176 x 250mm
b.shortServerName=uktps550
b.uNCName=\\\\uktps550\\Xerox2
b.printShareName=Xerox2
