# define the Oracle/OC4J initail context factory
java.naming.factory.initial=com.evermind.server.ApplicationClientInitialContextFactory

# this is an OC4J Standalone url
java.naming.provider.url=ormi://localhost:23791/test_project_server

# this is an OPMN OC4J [OAS] url which is broken up into
# opmn:ormi://168.185.1.99:[RMI port exposed for this oc4j instance]:[component name]/ear-application-name
#java.naming.provider.url=opmn:ormi://168.185.1.99:3205/test_project/test_project_ear

# provider url for uktps900 Caseman because we have more than one OC4J deployed in OAS
#java.naming.provider.url=opmn:ormi://uktps900:FamilymanIntegration/familyman902RC3ear

invalid.java.naming.security.principal=jazn.com/nobody
invalid.java.naming.security.credentials=test

# these are the username/passwrod configured in the META-INF/jazn.xml file and is the user which may run the checker service
valid.java.naming.security.principal=jazn.com/checker
valid.java.naming.security.credentials=checker

# who would we try and log in as
# CommandLine options to load the OASCheckConfig application
#	-user=the_sups_id1 -pass=the_users_password -principal jazn.com/jaas_security_principal -credentials the_jaas_password
#
# To call the OASCheckConfiguration client against the test_project deployed on uktps900 in the test_projectIntegration component
#
# The call would be
#
# java -jar CheckConfig.jar -user id1 -pass password -principal checker -credentials checker

java.security.auth.login.config=file://elipse/workspace/tools/extracted/jboss-4.0.1/client/auth.conf