drop table output_details_ext;

create table output_details_ext (
OD_SEQ                                             NUMBER(8),
ORDER_TYPE_ID                                      VARCHAR2(20),
LAYOUT_GROUP                                       VARCHAR2(2),
CODE                                               NUMBER(3),
FORMAT_STYLE                                       VARCHAR2(2),
ITEM1                                              VARCHAR2(500),
FONT1                                              VARCHAR2(2),
ITEM2                                              VARCHAR2(500),
FONT2                                              VARCHAR2(2),
ITEM3                                              VARCHAR2(500),
FONT3                                              VARCHAR2(2),
ITEM4                                              VARCHAR2(500),
FONT4                                              VARCHAR2(2),
ITEM5                                              VARCHAR2(500),
FONT5                                              VARCHAR2(2),
ITEM6                                              VARCHAR2(500),
FONT6                                              VARCHAR2(2),
ITEM7                                              VARCHAR2(500),
FONT7                                              VARCHAR2(2),
ITEM8                                              VARCHAR2(500),
FONT8                                              VARCHAR2(2),
ITEM9                                              VARCHAR2(500),
FONT9                                              VARCHAR2(2),
ITEM10                                             VARCHAR2(500),
FONT10                                             VARCHAR2(2),
dummy                                              VARCHAR2(2))
organization external
(
  default directory caseman_rd_dir
  access parameters
  (
    records delimited by newline
    characterset WE8MSWIN1252
    fields terminated by ','
    missing field values are null
    (
       OD_SEQ  ,       
ORDER_TYPE_ID  ,
LAYOUT_GROUP   ,
CODE           ,
FORMAT_STYLE   ,
ITEM1  CHAR(500) terminated by ',' optionally enclosed by '"'        ,
FONT1          ,
ITEM2  CHAR(500) terminated by ',' optionally enclosed by '"'        ,
FONT2          ,
ITEM3  CHAR(500) terminated by ',' optionally enclosed by '"'        ,
FONT3          ,
ITEM4  CHAR(500) terminated by ',' optionally enclosed by '"'        ,
FONT4          ,
ITEM5  CHAR(500) terminated by ',' optionally enclosed by '"'        ,
FONT5          ,
ITEM6  CHAR(500) terminated by ',' optionally enclosed by '"'        ,
FONT6          ,
ITEM7  CHAR(500) terminated by ',' optionally enclosed by '"'        ,
FONT7          ,
ITEM8  CHAR(500) terminated by ',' optionally enclosed by '"'        ,
FONT8          ,
ITEM9  CHAR(500) terminated by ',' optionally enclosed by '"'        ,
FONT9          ,
ITEM10  CHAR(500) terminated by ',' optionally enclosed by '"'       ,
FONT10         ,
dummy        
    ))
  location ('output_details.csv')
);

merge into output_details REF
using 
(select OD_SEQ  ,       
ORDER_TYPE_ID  ,
LAYOUT_GROUP   ,
CODE           ,
FORMAT_STYLE   ,
ITEM1          ,
FONT1          ,
ITEM2          ,
FONT2          ,
ITEM3          ,
FONT3          ,
ITEM4          ,
FONT4          ,
ITEM5          ,
FONT5          ,
ITEM6          ,
FONT6          ,
ITEM7          ,
FONT7          ,
ITEM8          ,
FONT8          ,
ITEM9          ,
FONT9          ,
ITEM10         ,
FONT10   
from output_details_ext) TMP
on (TMP.OD_SEQ = REF.OD_SEQ)
when matched then update set
REF.ORDER_TYPE_ID = TMP.ORDER_TYPE_ID,
REF.LAYOUT_GROUP = TMP.LAYOUT_GROUP,
REF.CODE = TMP.CODE , 
REF.FORMAT_STYLE = TMP.FORMAT_STYLE  ,
REF.ITEM1 = TMP.ITEM1  ,
REF.FONT1 = TMP.FONT1  ,
REF.ITEM2 = TMP.ITEM2  ,
REF.FONT2 = TMP.FONT2  ,
REF.ITEM3 = TMP.ITEM3  ,
REF.FONT3 = TMP.FONT3  ,
REF.ITEM4 = TMP.ITEM4  ,
REF.FONT4 = TMP.FONT4,
REF.ITEM5 = TMP.ITEM5 , 
REF.FONT5 = TMP.FONT5  ,
REF.ITEM6 = TMP.ITEM6  ,
REF.FONT6 = TMP.FONT6,
REF.ITEM7 = TMP.ITEM7 , 
REF.FONT7 = TMP.FONT7,
REF.ITEM8 = TMP.ITEM8 , 
REF.FONT8 = TMP.FONT8  ,
REF.ITEM9 = TMP.ITEM9  ,
REF.FONT9 = TMP.FONT9,
REF.ITEM10 = TMP.ITEM10 ,
REF.FONT10 = TMP.FONT10
when not matched then insert (REF.OD_SEQ  ,       
REF.ORDER_TYPE_ID  ,
REF.LAYOUT_GROUP   ,
REF.CODE           ,
REF.FORMAT_STYLE   ,
REF.ITEM1          ,
REF.FONT1          ,
REF.ITEM2          ,
REF.FONT2          ,
REF.ITEM3          ,
REF.FONT3          ,
REF.ITEM4          ,
REF.FONT4          ,
REF.ITEM5          ,
REF.FONT5          ,
REF.ITEM6          ,
REF.FONT6          ,
REF.ITEM7          ,
REF.FONT7          ,
REF.ITEM8          ,
REF.FONT8          ,
REF.ITEM9          ,
REF.FONT9          ,
REF.ITEM10         ,
REF.FONT10   )
values (TMP.OD_SEQ  ,       
TMP.ORDER_TYPE_ID  ,
TMP.LAYOUT_GROUP   ,
TMP.CODE           ,
TMP.FORMAT_STYLE   ,
TMP.ITEM1          ,
TMP.FONT1          ,
TMP.ITEM2          ,
TMP.FONT2          ,
TMP.ITEM3          ,
TMP.FONT3          ,
TMP.ITEM4          ,
TMP.FONT4          ,
TMP.ITEM5          ,
TMP.FONT5          ,
TMP.ITEM6          ,
TMP.FONT6          ,
TMP.ITEM7          ,
TMP.FONT7          ,
TMP.ITEM8          ,
TMP.FONT8          ,
TMP.ITEM9          ,
TMP.FONT9          ,
TMP.ITEM10         ,
TMP.FONT10);

drop table output_details_ext;