update standard_events set category = 'C' where event_id = '9' ;
update standard_events set category = 'C' where event_id = '14' ;
update standard_events set category = 'C' where event_id = '16' ;
update standard_events set category = 'C' where event_id = '56' ;
update standard_events set category = 'C' where event_id = '83' ;
update standard_events set category = 'C' where event_id = '88' ;
update standard_events set category = 'B' where event_id = '182' ;
update standard_events set category = 'C' where event_id = '226' ;
update standard_events set category = 'C' where event_id = '258' ;



update standard_events set category = 'M' where event_id = '100' ;
update standard_events set category = 'E' where event_id = '105' ;
update standard_events set category = 'm' where event_id = '110' ;
update standard_events set category = 'N' where event_id = '111' ;
update standard_events set category = 'M' where event_id = '120' ;
update standard_events set category = 'E' where event_id = '122' ;
update standard_events set category = 'A' where event_id = '125' ;
update standard_events set category = 'A' where event_id = '126' ;
update standard_events set category = 'm' where event_id = '130' ;
update standard_events set category = 'K' where event_id = '174' ;
update standard_events set category = 'M' where event_id = '177' ;
update standard_events set category = 'G' where event_id = '179' ;
update standard_events set category = 'M' where event_id = '175' ;
update standard_events set category = 'm' where event_id = '180' ;
update standard_events set category = 'M' where event_id = '185' ;
update standard_events set category = 'm' where event_id = '190' ;
update standard_events set category = 'N' where event_id = '332' ;
update standard_events set category = 'K' where event_id = '555' ;
update standard_events set category = 'b' where event_id = '582' ;
update standard_events set category = 'U' where event_id = '610' ;
update standard_events set category = 'U' where event_id = '820' ;
update standard_events set category = 'A' where event_id = '823' ;
update standard_events set category = 'A' where event_id = '825' ;
update standard_events set category = 'A' where event_id = '826' ;
update standard_events set category = 'A' where event_id = '851' ;
update standard_events set category = 'E' where event_id = '852' ;
update standard_events set category = 'E' where event_id = '853' ;
update standard_events set category = 'E' where event_id = '854' ;
update standard_events set category = 'E' where event_id = '855' ;
update standard_events set category = 'E' where event_id = '856' ;
update standard_events set category = 'E' where event_id = '857' ;
update standard_events set category = 'E' where event_id = '858' ;
update standard_events set category = 'E' where event_id = '859' ;
update standard_events set category = 'E' where event_id = '860' ;
update standard_events set category = 'A' where event_id = '861' ;
update standard_events set category = 'A' where event_id = '862' ;
update standard_events set category = 'A' where event_id = '863' ;
update standard_events set category = 'E' where event_id = '864' ;
update standard_events set category = 'E' where event_id = '865' ;
update standard_events set category = 'Q' where event_id = '867' ;
update standard_events set category = 'Q' where event_id = '868' ;
update standard_events set category = 'Q' where event_id = '869' ;
update standard_events set category = 'E' where event_id = '871' ;
update standard_events set category = 'E' where event_id = '872' ;
update standard_events set category = 'E' where event_id = '873' ;
update standard_events set category = 'E' where event_id = '874' ;
update standard_events set category = 'E' where event_id = '876' ;
update standard_events set category = 'E' where event_id = '877' ;
update standard_events set category = 'E' where event_id = '878' ;
update standard_events set category = 'E' where event_id = '879' ;
update standard_events set category = 'A' where event_id = '880' ;
update standard_events set category = 'A' where event_id = '881' ;
update standard_events set category = 'A' where event_id = '882' ;
update standard_events set category = 'A' where event_id = '883' ;
update standard_events set category = 'A' where event_id = '884' ;
update standard_events set category = 'A' where event_id = '886' ;
update standard_events set category = 'A' where event_id = '887' ;
update standard_events set category = 'A' where event_id = '888' ;
update standard_events set category = 'A' where event_id = '889' ;
update standard_events set category = 'A' where event_id = '890' ;
update standard_events set category = 'A' where event_id = '892' ;
update standard_events set category = 'A' where event_id = '893' ;
update standard_events set category = 'A' where event_id = '894' ;
update standard_events set category = 'A' where event_id = '895' ;
update standard_events set category = 'E' where event_id = '896' ;
update standard_events set category = 'A' where event_id = '897' ;
update standard_events set category = 'A' where event_id = '898' ;
update standard_events set category = 'A' where event_id = '899' ;
update standard_events set category = 'A' where event_id = '900' ;
update standard_events set category = 'K' where event_id = '999' ;

update standard_events set category = 'E' where event_id = '815';
update standard_events set category = 'E' where event_id = '822';
update standard_events set category = 'E' where event_id = '852';
update standard_events set category = 'I' where event_id = '901';
update standard_events set category = 'I' where event_id = '902';
update standard_events set category = 'I' where event_id = '903';
update standard_events set category = 'I' where event_id = '910';
update standard_events set category = 'I' where event_id = '912';
update standard_events set category = 'I' where event_id = '915';
update standard_events set category = 'I' where event_id = '916';
update standard_events set category = 'I' where event_id = '917';
update standard_events set category = 'I' where event_id = '920';
update standard_events set category = 'I' where event_id = '921';
update standard_events set category = 'I' where event_id = '923';
update standard_events set category = 'I' where event_id = '924';
update standard_events set category = 'I' where event_id = '926';
update standard_events set category = 'I' where event_id = '927';
update standard_events set category = 'I' where event_id = '928';
update standard_events set category = 'I' where event_id = '929';
update standard_events set category = 'I' where event_id = '930';
update standard_events set category = 'I' where event_id = '931';
update standard_events set category = 'I' where event_id = '935';
update standard_events set category = 'I' where event_id = '936';
update standard_events set category = 'I' where event_id = '937';
update standard_events set category = 'I' where event_id = '938';
update standard_events set category = 'I' where event_id = '939';
update standard_events set category = 'I' where event_id = '940';
update standard_events set category = 'I' where event_id = '941';
update standard_events set category = 'I' where event_id = '942';
update standard_events set category = 'I' where event_id = '943';
update standard_events set category = 'I' where event_id = '944';
update standard_events set category = 'I' where event_id = '946';
update standard_events set category = 'I' where event_id = '947';
update standard_events set category = 'I' where event_id = '951';
update standard_events set category = 'I' where event_id = '954';
update standard_events set category = 'I' where event_id = '955';
update standard_events set category = 'I' where event_id = '956';
update standard_events set category = 'I' where event_id = '958';
update standard_events set category = 'I' where event_id = '960';
update standard_events set category = 'I' where event_id = '961';
update standard_events set category = 'I' where event_id = '965';
update standard_events set category = 'I' where event_id = '966';
update standard_events set category = 'I' where event_id = '967';
update standard_events set category = 'I' where event_id = '968';
update standard_events set category = 'I' where event_id = '971';
update standard_events set category = 'I' where event_id = '972';
update standard_events set category = 'I' where event_id = '975';
update standard_events set category = 'I' where event_id = '977';
update standard_events set category = 'I' where event_id = '981';
update standard_events set category = 'I' where event_id = '989';
update standard_events set category = 'I' where event_id = '990';
update standard_events set category = 'I' where event_id = '991';



