# set the authenticator class to use
security.authenticator.class=uk.gov.dca.db.security.HardcodedAuthenticator

# secret used in the generation of session key
security.session.keygeneration.secret=SECRET