###
#
# most basic params xml
#
# <params><param name="userId">nobody</param><param name="courtId">2</param></params>
#
###

# ------------------
# General properties
# ------------------
testservice.project.name=test_project


# Note:  If this property is not specified or points to an invalid directory, then the property will default to the 
#        user's home directory
testservice.gui.filechooser.initdirectory=..

testservice.remote.service.user=nobody
testservice.remote.service.password=test


# ------------------------------------
# Sample OAS 10g Configuration (OASWS)
# ------------------------------------

testservice.remote.service.endpoint=http://localhost:7070/test_project_server/${service.name}
testservice.remote.service.namespace=http://${testservice.local.project.package}/${service.name}ServiceRemote.wsdl

# ----------------------------------------
# Sample JBoss 4.0.1 Configuration (WS4EE)
# ----------------------------------------

#testservice.remote.service.endpoint=http://localhost:8080/test_project/${service.name}/${service.name}ServiceServicePort
#testservice.remote.service.namespace=


# ----------------------------------------------
# Sample JBoss 4.0 DR4 Configuration (JBoss.NET)
# ----------------------------------------------

#testservice.remote.service.endpoint=http://localhost:8080/jboss-net/services/${service.name}
#testservice.remote.service.namespace=
