### JBossNS properties
#java.naming.factory.initial=org.jnp.interfaces.NamingContextFactory
#java.naming.provider.url=jnp://localhost:1099
#java.naming.factory.url.pkgs=org.jboss.naming:org.jnp.interfaces

##OAS properties
#java.naming.factory.initial=com.evermind.server.RMIInitialContextFactory
#java.naming.provider.url=opmn:ormi://192.168.100.7:3222:home/test_project
#java.naming.security.principal=jazn.com/nobody
#java.naming.security.credentials=test


