# An example log4j configuration file that outputs to System.out.  The
# output information consists of relative time, log level, thread
# name, logger name, nested diagnostic context and the message in that
# order.

# For the general syntax of property based configuration files see the
# documenation of org.apache.log4j.PropertyConfigurator.

log4j.rootLogger=OFF, polarlake, rfaInfo, rfaError, rfaFatal, rfaPatrol

# A1 is set to be a ConsoleAppender which outputs to System.out. 
log4j.appender.polarlake=org.apache.log4j.ConsoleAppender

log4j.appender.rfaInfo=org.apache.log4j.DailyRollingFileAppender
log4j.appender.rfaInfo.Threshold=Info

log4j.appender.rfaError=org.apache.log4j.DailyRollingFileAppender
log4j.appender.rfaError.Threshold=Error

log4j.appender.rfaFatal=org.apache.log4j.DailyRollingFileAppender
log4j.appender.rfaFatal.Threshold=Fatal

log4j.appender.rfaDebug=org.apache.log4j.DailyRollingFileAppender
log4j.appender.rfaDebug.Threshold=Debug

log4j.appender.rfaPatrol=org.apache.log4j.DailyRollingFileAppender
log4j.appender.rfaPatrol.Threshold=Warn

log4j.logger.com.info=rfaInfo
#log4j.additivity.com.info=false

log4j.logger.com.debug=rfaDebug
#log4j.additivity.com.debug=false

log4j.logger.com.error=rfaError
#log4j.additivity.com.error=false

log4j.logger.com.fatal=rfaFatal
#log4j.additivity.com.fatal=false

log4j.logger.com.patrol=rfaPatrol
#log4j.additivity.com.patrol=false

log4j.appender.rfaInfo.File=${app_pl_log_dir}/Info/info.log
#log4j.appender.rfaInfo.Append=False
log4j.appender.rfaError.File=${app_pl_log_dir}/Error/error.log
#log4j.appender.rfaError.Append=False
log4j.appender.rfaDebug.File=${app_pl_log_dir}/Debug/debug.log
#log4j.appender.rfaDebug.Append=False
log4j.appender.rfaFatal.File=${app_pl_log_dir}/Fatal/fatal.log
#log4j.appender.rfaFatal.Append=False
log4j.appender.rfaPatrol.File=${app_pl_log_dir}/Patrol/patrol.log
log4j.appender.rfaPatrol.Append=False

#log4j.appender.rfaInfo.MaxFileSize=10000KB
#log4j.appender.rfaError.MaxFileSize=10000KB
#log4j.appender.rfaFatal.MaxFileSize=10000KB
#log4j.appender.rfaDebug.MaxFileSize=10000KB
#log4j.appender.rfaPatrol.MaxFileSize=10000KB

#Keep one backup file
#log4j.appender.rfaInfo.MaxBackupIndex=1
#log4j.appender.rfaError.MaxBackupIndex=1
#log4j.appender.rfaFatal.MaxBackupIndex=1
#log4j.appender.rfaDebug.MaxBackupIndex=1
#log4j.appender.rfaPatrol.MaxBackupIndex=1

#Keep one backup file
log4j.appender.rfaPatrol.DatePattern=.yyyy-MM-dd
log4j.appender.rfaInfo.DatePattern=.yyyy-MM-dd
log4j.appender.rfaError.DatePattern=.yyyy-MM-dd
log4j.appender.rfaFatal.DatePattern=.yyyy-MM-dd
log4j.appender.rfaDebug.DatePattern=.yyyy-MM-dd


# A1 uses PatternLayout.
log4j.appender.polarlake.layout=org.apache.log4j.PatternLayout
log4j.appender.rfaInfo.layout=org.apache.log4j.PatternLayout
log4j.appender.rfaDebug.layout=org.apache.log4j.PatternLayout
log4j.appender.rfaError.layout=org.apache.log4j.PatternLayout
log4j.appender.rfaFatal.layout=org.apache.log4j.PatternLayout
log4j.appender.rfaPatrol.layout=org.apache.log4j.PatternLayout

# The conversion pattern uses format specifiers. You might want to
# change the pattern an watch the output format change.
log4j.appender.polarlake.layout.ConversionPattern= %-5p %d{dd MMM yyyy HH:mm:ss}  [%t] %37c  %M %3x - %m%n
log4j.appender.rfaInfo.layout.ConversionPattern= %-5p %d{dd MMM yyyy HH:mm:ss}  [%t] %37c  %M %3x - %m%n
log4j.appender.rfaDebug.layout.ConversionPattern= %-5p %d{dd MMM yyyy HH:mm:ss} %-4r %l [%t] %37c  %M %3x - %m%n
log4j.appender.rfaError.layout.ConversionPattern= %-5p %d{dd MMM yyyy HH:mm:ss} %-4r %l [%t] %37c  %M %3x - %m%n
log4j.appender.rfaFatal.layout.ConversionPattern= %-5p %d{dd MMM yyyy HH:mm:ss} %-4r %l [%t] %37c  %M %3x - %m%n
log4j.appender.rfaPatrol.layout.ConversionPattern= %-5p %d{dd MMM yyyy HH:mm:ss} %-4r %l [%t] %37c  %M %3x - %m%n

# In this example, we are not really interested in INNER loop or SWAP
# messages. See the effects of uncommenting and changing the levels of
# the following loggers.
log4j.logger.com.polarlake.platform=ERROR
log4j.logger.com.polarlake.scheduler=ERROR 
log4j.logger.com.polarlake.platform.librarymodule.eventprocessors.PrintMessageEP=INFO
log4j.logger.org.quartz=ERROR
log4j.logger.org.apache.catalina=ERROR
log4j.logger.org.apache.catalina.startup.Embedded=ERROR
#log4j.logger.com.polarlake.pmc=ERROR
#log4j.logger.PMC=ERROR
#log4j.logger.SYSTEM=ERROR
#log4j.logger.com.polarlake.platform.librarymodule.eventprocessors=null, rfaPatrol
#log4j.additivity.com.polarlake.platform.librarymodule.eventprocessors=false

log4j.logger.com.polarlake.platform.databasemodule=INFO
log4j.logger.com.polarlake.eds.trunctest=INFO
