/*
 * Created on 21-Jul-2005
 *
 * TODO To change the template for this generated file go to
 * Window - Preferences - Java - Code Style - Code Templates
 */
package uk.gov.dca.db.util;

import java.io.InputStream;
import java.util.Properties;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import uk.gov.dca.db.impl.Util;

/**
 * @author Peter Neil
 *
 * This class is generated by the Framework at build time it will be used
 * by the Configuration Checking utility for anyone who checking application
 * configuration from outside the container. ie: telnet
 *
 */
public class FrameworkConfigParam {

    // Note, this should be the only place that LogFactory is used directly.
    private final static Log log = LogFactory.getLog(FrameworkConfigParam.class);
	private static Properties frameworkProperties = new Properties();
    
    
	static {
		//framework.config.properties
		try {
			InputStream propStream = Util.getInputStream(
					"framework.config.properties", new Object());
			frameworkProperties.load(propStream);
            System.out.println("Loaded properties: " + frameworkProperties);
		} catch (Exception e) {
			log.error("Unable to load framework.config.properties", e);
		}

	}
    

	private final String value;

	/**
	 * The parameters @APPLICATION_NAME@ and @PROJECT_CONFIG@ will be replaced during the building of an applicaton
	 * Populated by the release build file in the default_conf/framework.config.properites file 
	 * 
	 * sups.project.name=@APPLICATION_NAME@
	 * sups.project.config=@PROJECT_CONFIG@
	 * sups.framework.config=@FRAMEWORK_CONFIG@
	 */
	public static final FrameworkConfigParam APPLICATION_NAME = new FrameworkConfigParam(
			frameworkProperties.getProperty("sups.project.name"));

	public static final FrameworkConfigParam PROJECT_CONFIG = new FrameworkConfigParam(
			frameworkProperties.getProperty("sups.project.config"));

	public static final FrameworkConfigParam FRAMEWORK_CONFIG = new FrameworkConfigParam(
			frameworkProperties.getProperty("sups.framework.config"));

	//prevent anyone from creating this class
	private FrameworkConfigParam(String value) {
		this.value = value;
	}

	/**
	 * 
	 * @return the value of the configuration param
	 * 
	 */
	public String getValue() {
		return value;
	}

}
