PROMPT
PROMPT Creating View AE
-- SUPS changes: Replaced Defendant_id by party_against_party_role_code and party_against_case_party_no
--      Added party_for_party_role_code and party_for_case_party_no so that reports which
--      used to get the plaintiff details off CASES by joining to AE can get them off PARTIES.
--	Added tests on deleted_flag.

CREATE OR REPLACE VIEW ae
(
  ae_number
 ,case_number
 ,PARTY_AGAINST_PARTY_ROLE_CODE
 ,PARTY_AGAINST_CASE_PARTY_NO
 ,PARTY_FOR_PARTY_ROLE_CODE
 ,PARTY_FOR_CASE_PARTY_NO
 ,outstanding_balance
)
AS
SELECT
  A.AE_NUMBER,
  A.CASE_NUMBER,
  A.PARTY_AGAINST_PARTY_ROLE_CODE,
  A.PARTY_AGAINST_CASE_PARTY_NO,
  A.PARTY_FOR_PARTY_ROLE_CODE,
  A.PARTY_FOR_CASE_PARTY_NO,
  NVL( A.AMOUNT_OF_AE, 0 ) + DECODE( SUM( B.AMOUNT ), NULL, SUM( NVL( A.AE_FEE, 0 )), SUM( B.AMOUNT )) OUTSTANDING_BALANCE
FROM
  FEES_PAID B,
  AE_APPLICATIONS A
WHERE
  A.AE_NUMBER = B.PROCESS_NUMBER AND
  B.PROCESS_TYPE = 'A' AND
  B.DELETED_FLAG = 'N'
GROUP BY
  A.AE_NUMBER,
  A.CASE_NUMBER,
  A.AE_TYPE,
  A.PARTY_AGAINST_PARTY_ROLE_CODE,
  A.PARTY_AGAINST_CASE_PARTY_NO,
  A.PARTY_FOR_PARTY_ROLE_CODE,
  A.PARTY_FOR_CASE_PARTY_NO,
  A.AMOUNT_OF_AE
UNION
SELECT
  AE_NUMBER,
  CASE_NUMBER,
  PARTY_AGAINST_PARTY_ROLE_CODE,
  PARTY_AGAINST_CASE_PARTY_NO,
  PARTY_FOR_PARTY_ROLE_CODE,
  PARTY_FOR_CASE_PARTY_NO,
  NVL( AMOUNT_OF_AE, 0 ) + NVL( AE_FEE, 0 )	OUTSTANDING_BALANCE
FROM
  AE_APPLICATIONS
WHERE
  AE_NUMBER NOT IN (	SELECT	PROCESS_NUMBER
			FROM	FEES_PAID
			WHERE	PROCESS_TYPE = 'A'
			AND	DELETED_FLAG = 'N' );
