# If this property is not specified or points to an invalid directory, then the property will default to the 
# user's home directory
testservice.gui.filechooser.initdirectory=..

testservice.remote.service.endpoint=http://localhost:8080/caseman/
#testservice.remote.service.endpoint=http://localhost:8080/ws4ee/services/
testservice.remote.service.user=nobody
testservice.remote.service.password=test