application_name=transformation
drive=c:
jboss_server_dir=${drive}/tools/extracted/jboss-4.0.1/server/transformation
build_config=${drive}/build/transformationserver/config
source_config=${drive}/build/transformationserver/web-config
server_dist=${drive}/build/transformationserver/dist/${application_name}.ear