application.name=caseman
base.build.dir=c:/SUPS/build/caseman/caseman_client

# Properties moved into this file from the client build script
# caseman_client_build.xml in an attempt to centralise them and make
# them easier to maintain.
dist=clientframework/dist
caseman-dist=caseman-dist
src=.
tmpfrmwrk.dir=${base.build.dir}/framework/fwktmp
client.lib.dir=${basedir}/lib
build.dir=${base.build.dir}/OAS
wpctrl.dir=${basedir}/../wordprocessing/WPCtrl
oas.home=${env.SUPS_OAS_HOME}
sups.tools=${env.SUPS_TOOLS}
caseman-wp.dir=${basedir}/caseman/screens/caseman_wp
caseman-wp.server.dir=${basedir}/../../RPT/wordprocessing_templates
server-basedir=${basedir}/../server
lib.dir=${server-basedir}/lib

