###############################################################################
# Target environment: caseman DEV, build 3.xx
# THIS FILE IS NOT IN USE. SEE IDENTICAL FILE IN SERVER PROJECT.
# Properties that vary depending on the deployment environment
# (e.g. FT, UCT, DEV) ahould be placed here, and the relevant files tokenised.
###############################################################################
