######################################################################
#
# oc4j management properties, used to deploy to your oc4j 
#
######################################################################
oc4j_home_dir=D:/oc4j-9.0.4
oc4j_admin_password=oracle
oc4j_https_site_name=sups-https-web-site
oc4j_http_site_name=sups-http-web-site
oc4j_framework_lib=D:/eclipse/workspace/XMLQuery2_HEAD/build/release/lib

oc4j-check-server=localhost
oc4j-check-port=8080
oc4j_ormi_admin_url=ormi://localhost:23791