package uk.gov.dca.db.invoke.server.service;

import java.io.IOException;
import java.io.InputStream;
import java.util.Iterator;
import java.util.Properties;

import org.apache.commons.logging.Log;

import uk.gov.dca.db.impl.Util;
import uk.gov.dca.db.util.SUPSLogFactory;

public class ServiceMetaDataImpl implements ServiceMetaData {

	Log log = SUPSLogFactory.getLogger(ServiceMetaDataImpl.class);
	private static final String SERVICE_METHOD_REGITRY_FILE_NAME = "service-method-registry.properties";
	private static final String FRAMEWORK_SERVICE_METHOD_REGITRY_FILE_NAME = "framework-service-method-registry.properties";
	private Properties servicesAndMethods = new Properties();

	private static final ServiceMetaDataImpl instance = new ServiceMetaDataImpl();

	//The ping method will automatically be called and cached.
	private ServiceMetaDataImpl() {
		//	load file generated by the build script service-method-registry.properties
		InputStream is = null;
		InputStream fis = null;
		try {
			is = Util.getInputStream(SERVICE_METHOD_REGITRY_FILE_NAME, this);
			fis = Util.getInputStream(FRAMEWORK_SERVICE_METHOD_REGITRY_FILE_NAME, this);
			servicesAndMethods.load(fis);
			servicesAndMethods.load(is);
			
		} catch (Exception e) {
			log.error("Unable to Load file: " + SERVICE_METHOD_REGITRY_FILE_NAME);
		}
		finally{
			if(is != null){
				try {
					is.close();
				} catch (IOException e) {
					log.error("Unable to close InputStream: " + SERVICE_METHOD_REGITRY_FILE_NAME);
				}
			}
			if(fis != null){
				try {
					fis.close();
				} catch (IOException e) {
					log.error("Unable to close InputStream: " + SERVICE_METHOD_REGITRY_FILE_NAME);
				}
			}
		}
		
	}

	public static ServiceMetaDataImpl getInstance() {
		return instance;
	}

	public String[] getServices() {
		Iterator services = servicesAndMethods.keySet().iterator();
		String[] serviceNames = new String[servicesAndMethods.keySet().size()];
		int pos = 0;
		while(services.hasNext()){
			serviceNames[pos++] = (String)services.next(); 
		}
		return serviceNames;
	}

	public String[] getServiceMethods(String serviceName) {
		String methods = (String)servicesAndMethods.get(serviceName);
		String[] methodArray = new String[0];
		if(methods != null){
			methodArray = methods.split(",");
		}
		return methodArray;
	}
}
