# Property file supporting SUPS Caseman (non Polar Lake_ Batch build
# -------------------------------------------------------------------
# File history
# 27/06/2007 - Created. Chris Hutt
# 29/10/2009 - Chris Vincent: removed old ClearCase related properties and replaced with new ones
#

# default property values 
build.num=N
build.app.num=N
build.rep.num=N
build.ref.num=N
build.bat.num=N

# source 
caseman.location.batch=${env.PROJECT.BASE}/../Batch
caseman.location.batch.source=${caseman.location.batch}/shell/deliverables/app/caseman
caseman.location.batch.bin=${caseman.location.batch.source}/bin
caseman.location.batch.etc=${caseman.location.batch.source}/etc
caseman.location.batch.offline=${caseman.location.batch.bin}/offline
caseman.location.scripts=${env.PROJECT.BASE}/../caseman_database_source/scripts

# output
output.drive=c:
output.dir.name=${output.drive}/Caseman_CCBC_${build.bat.num}_Batch
output.dir.docs=${output.dir.name}
output.dir.bin=${output.dir.name}/bin
output.dir.sql=${output.dir.name}/sql
output.dir.etc=${output.dir.name}/etc
output.dir.offline=${output.dir.bin}/offline
output.zip.name=${output.dir.name}.zip






