------------------------------------------------
-- Create each of the schemas used by CASEMAN
------------------------------------------------

SET ECHO ON

CREATE USER CASEMAN IDENTIFIED BY CASEMAN DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp;
GRANT CONNECT,RESOURCE TO CASEMAN;
ALTER USER CASEMAN QUOTA UNLIMITED ON USERS;

-- Create FAMILYMAN schema because grants need to be made to it.
CREATE USER FAMILYMAN IDENTIFIED BY FAMILYMAN DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp;
GRANT CONNECT,RESOURCE TO FAMILYMAN;
ALTER USER FAMILYMAN QUOTA UNLIMITED ON USERS;


-- Additional users without schemas

-- CREATE USER WEB_USER IDENTIFIED BY WEB_USER DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp;
-- GRANT CONNECT,RESOURCE TO WEB_USER;

