<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:fo="http://www.w3.org/1999/XSL/Format" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2004/07/xpath-functions" xmlns:xdt="http://www.w3.org/2004/07/xpath-datatypes">
	<xsl:output method="text" indent="no"/>
	<xsl:param name="templateDir"/>
	<xsl:param name="webfileDir"/>
	
	<xsl:template match="Screen">
		<xsl:variable name="thisScreenId">
			<xsl:value-of select="Name"/>
		</xsl:variable>
		<xsl:variable name="returnMenu">
			<xsl:value-of select="ReturnMenu"/>
		</xsl:variable>
		<xsl:variable name="returnToMenu">
			<xsl:value-of select="ReturnToMenu"/>
		</xsl:variable>
		<xsl:variable name="wPScreen"><xsl:value-of select="WPScreen"/></xsl:variable>
		
		<xsl:variable name="thisReportModuleGroupName">
			<xsl:value-of select="ReportModuleGroup"/>
		</xsl:variable>
		
		var reportModuleGroup = "<xsl:value-of select="$thisReportModuleGroupName"/>"
		
		<xsl:text>
			/** 
			This JavaScript file has been generated by the Ant build script.  
			DO NOT EDIT as any changes will be overwritten in the next build.
			**/
			var __tabIdx = 300;
			
			
			// XPath constants
			var ROOT_XPATH = "/ds";
			var REF_DATA_XPATH = ROOT_XPATH + "/var/form/ReferenceData";
			var PAGE_XPATH = ROOT_XPATH + "/var/page";
			var PAGE_BMSR_XPATH = PAGE_XPATH + "/OracleReportForm";  // Place all input/output data in page context

			
			// Form element
			function OracleReportForm() {}
					
			OracleReportForm.refDataServices = [
				{name:"SystemDate", dataBinding:REF_DATA_XPATH, serviceName:"getSystemDate", serviceParams:[]},
				{name:"SystemData", dataBinding:REF_DATA_XPATH, serviceName:"getBmsLiveDate", serviceParams:[{name:"courtCode",value:CaseManFormParameters.COURTNUMBER_XPATH}]},
				{name:"CurrentCurrency", dataBinding:REF_DATA_XPATH, serviceName:"getCurrentCurrency", serviceParams:[] },
				{name:"Courts", dataBinding:REF_DATA_XPATH, serviceName:"getCourtsShort", serviceParams:[]}
			];
			
			function DefaultCurrency() {}
			DefaultCurrency.dataBinding = "/ds/OracleReportForm/curr";
			DefaultCurrency.tabIndex = -1;
			DefaultCurrency.maxLength = 1;
			DefaultCurrency.isReadOnly = function(){return true;}
			DefaultCurrency.isTemporary = function(){return true;}
			DefaultCurrency.retrieveOn = [REF_DATA_XPATH + "/CurrentCurrency/CurrencySymbol"];
			DefaultCurrency.transformToDisplay = function(value) 
			{
				return CaseManUtils.transformCurrencySymbolToDisplay(value, REF_DATA_XPATH + "/CurrentCurrency/CurrencySymbol");
			}
			DefaultCurrency.transformToModel = function(value)
			{
				return CaseManUtils.transformCurrencySymbolToModel(value, REF_DATA_XPATH + "/CurrentCurrency/CurrencyCode"); 
			}
			
		</xsl:text>
		
		// Header Fields and Save Button for WP Parameter form
		<xsl:choose>
			<xsl:when test="$wPScreen = 'Y'">
				var frmCtrl = null;
				var appCtrl = null;
				var session = null;
				var wpCtrl = null;
				var __req = null;
				var request = null;
				var output = null;
				var outputOrder = "";	
				var orderId = "";
				var hearingType = "";
				var eventDetails = null;
				
				// holder for group save functions.
				var onSave = new Array();			
				
				var VAR_PAGE_XPATH 		= "/ds/var/page";
				var DATA_XPATH 			= "/ds/ManageCase";
				var VAR_APP_XPATH		= "/ds/var/app";
				var OUTPUT_ORDER_XPATH 	= VAR_APP_XPATH + "/wp/order";
			
				function Header_CaseNumber() {}
				Header_CaseNumber.dataBinding 			= "/ds/ManageCase/CaseNumber";
				Header_CaseNumber.isReadOnly 			= function() { if (!_initForm)  {initForm(); } return true; }

				function Header_AENumber() {}
				Header_AENumber.dataBinding 			= "/ds/ManageAE/AENumber";
				Header_AENumber.isReadOnly 				= function() { return true; }

				function Header_AEType() {}
				Header_AEType.dataBinding 				= "/ds/ManageAE/AEType";
				Header_AEType.isReadOnly 				= function() { return true; }


				function Header_CONumber() {}
				Header_CONumber.dataBinding 			= "/ds/ManageCO/CONumber";
				Header_CONumber.isReadOnly 				= function() { if (!_initForm)  {initForm(); } return true; }
				
				function Header_DebtorName() {}
				Header_DebtorName.dataBinding 			= "/ds/ManageCO/DebtorName";
				Header_DebtorName.isReadOnly 			= function() { if (!_initForm)  {initForm(); } return true; }

				
				function Header_PartyTypeListGrid() {};
				Header_PartyTypeListGrid.tabIndex 		= 2;
				Header_PartyTypeListGrid.dataBinding 	= VAR_PAGE_XPATH + "/SelectedGridRow/SelectedParty";
				Header_PartyTypeListGrid.isReadOnly		= function() { return true; }
				Header_PartyTypeListGrid.srcData 		= DATA_XPATH + "/Parties";
				Header_PartyTypeListGrid.rowXPath 		= "LitigiousParty[./TypeCode = '" + PartyTypeCodesEnum.CLAIMANT + "' or ./TypeCode = '" + PartyTypeCodesEnum.DEFENDANT + "']";
				Header_PartyTypeListGrid.keyXPath 		= "PartyId";
				Header_PartyTypeListGrid.columns 		= [	{xpath: "Type"},
															{xpath: "Number", sort: "numerical", defaultSort:"true", defaultSortOrder:"ascending"},
															{xpath: "Name"}];
				
				function Header_Order() {}
				Header_Order.dataBinding 		= "/ds/EnterVariableData/Order";
				Header_Order.logicOn 			= [ OUTPUT_ORDER_XPATH ];
				Header_Order.logic 				= function() { Services.setValue(Header_Order.dataBinding, Services.getValue(OUTPUT_ORDER_XPATH)); }
				Header_Order.isReadOnly			= function() { return true; }
				//Header_Order.transformToDisplay	= function(value) { return outputOrder; }
				//Header_Order.transformToModel 	= function(value) {	return outputOrder; }	
				
				function Status_SaveButton() {}
				Status_SaveButton.tabIndex = 404;
				Status_SaveButton.actionBinding = function() 
				{
					invalidFields = frmCtrl.validateForm(true);
					if (invalidFields.length == 0) 
					{
						Save_All(); 
					} 
				}
				
				function Save_All() 
				{
					requestReport();
				}		
							
				var _initForm = false;
				
				function initForm()
				{
					frmCtrl = FormController.getInstance();
					_initForm = true;
					msg = "GenerateOracleReportsJavascript.js initForm() ";
					var proc = top.WP.GetScreenProcessORA();
					//session = top.WP._reportSession;
					if (null == proc)
					{
						alert("WARNING: Form Cannot be loaded in this context");
						Logging.error(msg + "did not find the expected request (key: WordProcessingEnterVariableDataRequest) in the sesion");
					}
					else
					{
						//wpEVDRequestName = "OracleReportVariableDataRequest";
						//__req = session.getAttribute(wpEVDRequestName);
						//request = __req;						
						output = proc.getOutput(); //__req._output;
						contextXml = proc.getRequest().getContext(); //__req._contextxml;
						var eventNode = contextXml.selectSingleNode("WordProcessing/Event/EventDetails")
						var completeEventDetailsNode = contextXml.selectSingleNode("WordProcessing/Event/CompleteEventDetails")
						eventDetails = "";
						if (completeEventDetailsNode != null)
						{
							eventDetails = XML.getNodeTextContent(completeEventDetailsNode);
						}
						orderId = output.mainOrderID; //XML.getNodeTextContent(contextXml.selectSingleNode("WordProcessing/Event/EventDetails"));
						if ((orderId == null) || (orderId == ""))
						{
							var node = contextXml.selectSingleNode("WordProcessing/Event/EventDetails");
							if(null != node){
								orderId = XML.getNodeTextContent(node);
							}
							//orderId = XML.getNodeTextContent(contextXml.selectSingleNode("WordProcessing/Event/EventDetails"));
						}
						outputOrder = orderId + " - " + output.getDescription();	
						
						manageCaseElement = contextXml.selectSingleNode("WordProcessing/ManageCase");
						
						Services.setValue(OUTPUT_ORDER_XPATH, outputOrder);
						Services.setValue(Header_Order.dataBinding, Services.getValue(OUTPUT_ORDER_XPATH))
						frmCtrl.getDataModel().addNodeSet(manageCaseElement, "/ds");
						
						hearingType = output.hearingType;
						
						if (reportModuleGroup == "CJR")
						{
							var caseEventSeq = XML.getNodeTextContent(contextXml.selectSingleNode("WordProcessing/Event/CaseEventSeq"));
							var caseEventId = XML.getNodeTextContent(contextXml.selectSingleNode("WordProcessing/Event/StandardEventId"));
							//alert("Case Event Sequence : " + caseEventSeq + ", Standard Case Event ID : " + caseEventId);
							
							Services.setValue("/ds/ManageCase/EventSequence", caseEventSeq);
							Services.setValue("/ds/ManageCase/StandardEventId", caseEventId);
							Services.setValue("/ds/ManageCase/OrderId", orderId);
						}						
						if (reportModuleGroup == "AE")
						{
							var aeNumber = XML.getNodeTextContent(contextXml.selectSingleNode("WordProcessing/Event/AENumber"));
							var aeType = XML.getNodeTextContent(contextXml.selectSingleNode("WordProcessing/Event/AEType"));
							var aeEventSeq = XML.getNodeTextContent(contextXml.selectSingleNode("WordProcessing/Event/CaseEventSeq"));
							var aeEventId = XML.getNodeTextContent(contextXml.selectSingleNode("WordProcessing/Event/StandardEventId"));
							var issueStage = XML.getNodeTextContent(contextXml.selectSingleNode("WordProcessing/Event/IssueStage"));
							var welshTrans = XML.getNodeTextContent(contextXml.selectSingleNode("WordProcessing/Case/WelshTranslation"));
							var jurisdiction = XML.getNodeTextContent(contextXml.selectSingleNode("WordProcessing/Case/Jurisdiction"));
							Services.setValue("/ds/ManageAE/AENumber", aeNumber);
							Services.setValue("/ds/ManageAE/AEType", aeType);
							Services.setValue("/ds/ManageCase/EventSequence", aeEventSeq);
							Services.setValue("/ds/ManageAE/AEEventId", aeEventId);
							Services.setValue("/ds/ManageAE/IssueStage", issueStage);
							Services.setValue("/ds/ManageCase/WelshTranslation", welshTrans);
							Services.setValue("/ds/ManageCase/Jurisdiction", jurisdiction);
						}
						if (reportModuleGroup == "CO")
						{
							var coNumber = XML.getNodeTextContent(contextXml.selectSingleNode("WordProcessing/Event/CONumber"));
							var caseEventSeq = XML.getNodeTextContent(contextXml.selectSingleNode("WordProcessing/Event/COEventSeq"));
							var caseEventId = XML.getNodeTextContent(contextXml.selectSingleNode("WordProcessing/Event/StandardEventId"));
							var debtorName = XML.getNodeTextContent(contextXml.selectSingleNode("WordProcessing/Event/DebtorName"));
							//alert("Case Event Sequence : " + caseEventSeq + ", Standard Case Event ID : " + caseEventId);
							Services.setValue(Header_CONumber.dataBinding, coNumber);
							Services.setValue(Header_DebtorName.dataBinding, debtorName);
							Services.setValue("/ds/ManageCase/EventSequence", caseEventSeq);
							Services.setValue("/ds/ManageCase/StandardEventId", caseEventId);
							Services.setValue("/ds/ManageCase/OrderId", orderId);
						}												
					}				
				}		
													
			// Form Keybindings
			OracleReportForm.keyBindings = [
				{ key: Key.F3, action: function() { Status_SaveButton.actionBinding(); } }
			];
			
			function getEventDetails()
			{
				return "HRG: " + CaseManUtils.convertDateToDisplay(Services.getValue(DateOfHearing.dataBinding)) + " at " + transformToDisplayTime(Services.getValue(TimeOfHearing.dataBinding), VAR_PAGE_XPATH + "/Tmp/Hearing/ValidTime");
			}
					
			</xsl:when >
			<xsl:otherwise>
			
				// Form Keybindings
				OracleReportForm.keyBindings = [
					{ key: Key.F3, action: function() { Status_RunReportButton.actionBinding(); } },
					{ key: Key.F4, action: exitScreen }
				];			
			</xsl:otherwise>
		</xsl:choose>

		
		// Generate the method for calling the service -start
			
		<xsl:variable name="thisReportName">
			<xsl:value-of select="ReportName"/>
		</xsl:variable>		
		<xsl:variable name="thisCreateWarrant">
			<xsl:value-of select="CreateWarrant"/>
		</xsl:variable>		
		<xsl:variable name="thisUpdateEventDetails">
			<xsl:value-of select="UpdateEventDetails"/>
		</xsl:variable>					
		//The Value of Module is :-<xsl:value-of select="$thisReportModuleGroupName"/>-
		
			function requestReport()
			{
				Popup_Cancel.cancelled = false;
				var dom = Reports.createReportDom("<xsl:value-of select="$thisReportName"/>"<xsl:if test="$thisReportModuleGroupName != ''">, reportModuleGroup</xsl:if>);
				<xsl:if test="$thisReportModuleGroupName != ''">
				Reports.setValue(dom, "P_DOCUMENT_ID", orderId, reportModuleGroup );
				Reports.setValue(dom, "P_EVENT_SEQ", Services.getValue(&quot;/ds/ManageCase/EventSequence&quot;), reportModuleGroup );
				Reports.setValue(dom, "P_PRINT_NOW", "Y", reportModuleGroup );

					<xsl:if test="$thisCreateWarrant = 'Y'">
						<xsl:if test="$thisReportModuleGroupName = 'AE'">
							Reports.setWarrantValue(dom, Services.getValue(&quot;/ds/ManageAE/AENumber&quot;), Services.getValue(&quot;/ds/ManageAE/AEEventId&quot;), Services.getValue(&quot;/ds/ManageCase/EventSequence&quot;), reportModuleGroup);
						</xsl:if>
						<xsl:if test="$thisReportModuleGroupName = 'CO'">
							Reports.setWarrantValueForCO(dom, Services.getValue(Header_CONumber.dataBinding), Services.getValue(&quot;/ds/ManageCase/StandardEventId&quot;), Services.getValue(&quot;/ds/ManageCase/EventSequence&quot;), reportModuleGroup);
						</xsl:if>
					</xsl:if>
				</xsl:if>
		
		<xsl:if test="$thisReportModuleGroupName = 'CJR'">		
			
				Reports.setColumnValue(dom, "TEXT_CASE_NUMBER", Services.getValue(&quot;/ds/ManageCase/CaseNumber&quot;), reportModuleGroup );							
				Reports.setColumnValue(dom, "TEXT_ORDER_ORD_ID", Services.getValue(&quot;/ds/ManageCase/OrderId&quot;), reportModuleGroup );		
				Reports.setColumnValue(dom, "CASE_EVENT_SEQUENCE", Services.getValue(&quot;/ds/ManageCase/EventSequence&quot;), reportModuleGroup );						
						
		</xsl:if>
		
		<xsl:if test="$thisReportModuleGroupName = 'AE'">

				Reports.setColumnValue(dom, "AE_EVENT_SEQ", Services.getValue(&quot;/ds/ManageCase/EventSequence&quot;), reportModuleGroup );
				Reports.setColumnValue(dom, "AE_NUMBER", Services.getValue(&quot;/ds/ManageAE/AENumber&quot;), reportModuleGroup );							
				Reports.setColumnValue(dom, "STD_EVENT_ID", Services.getValue(&quot;/ds/ManageAE/AEEventId&quot;), reportModuleGroup );		
				Reports.setColumnValue(dom, "ISSUE_STAGE", Services.getValue(&quot;/ds/ManageAE/IssueStage&quot;), reportModuleGroup );	
				Reports.setColumnValue(dom, "REPORT_VALUE_1", "", reportModuleGroup );						
				Reports.setColumnValue(dom, "REPORT_VALUE_2", "", reportModuleGroup );		
				Reports.setColumnValue(dom, "REPORT_VALUE_3", "", reportModuleGroup );		
				Reports.setColumnValue(dom, "REPORT_VALUE_4", "", reportModuleGroup );	
				Reports.setColumnValue(dom, "REPORT_VALUE_5", "", reportModuleGroup );	
				Reports.setColumnValue(dom, "REPORT_VALUE_6", "", reportModuleGroup );						
				Reports.setColumnValue(dom, "REPORT_VALUE_7", "", reportModuleGroup );		
				Reports.setColumnValue(dom, "REPORT_VALUE_8", "", reportModuleGroup );		
				Reports.setColumnValue(dom, "REPORT_VALUE_9", "", reportModuleGroup );	
				Reports.setColumnValue(dom, "REPORT_VALUE_10", "", reportModuleGroup );
				Reports.setColumnValue(dom, "REPORT_VALUE_11", "", reportModuleGroup );		
				Reports.setColumnValue(dom, "REPORT_VALUE_12", "", reportModuleGroup );		
				Reports.setColumnValue(dom, "REPORT_VALUE_13", "", reportModuleGroup );	
				Reports.setColumnValue(dom, "REPORT_VALUE_14", "", reportModuleGroup );	
				Reports.setColumnValue(dom, "HRG_SEQ", "", reportModuleGroup );	
				Reports.setColumnValue(dom, "WARRANT_ID", "", reportModuleGroup );
				Reports.setValue(dom, "WELSH_TRANS", Services.getValue(&quot;/ds/ManageCase/WelshTranslation&quot;), reportModuleGroup );
				Reports.setValue(dom, "JURISDICTION", Services.getValue(&quot;/ds/ManageCase/Jurisdiction&quot;), reportModuleGroup );
				
				<xsl:choose>
					<xsl:when test="$thisUpdateEventDetails = 'Y'">
					Reports.setColumnValue(dom, "DETAILS", getEventDetails(), reportModuleGroup );	
					</xsl:when>
					<xsl:otherwise>
						Reports.setColumnValue(dom, "DETAILS", eventDetails, reportModuleGroup );	
					</xsl:otherwise>
				</xsl:choose>							
		</xsl:if>
		
		<xsl:if test="$thisReportModuleGroupName = 'CO'">

				Reports.setColumnValue(dom, "CO_TEXT_CO_NUMBER", Services.getValue(&quot;/ds/ManageCO/CONumber&quot;), reportModuleGroup );							
				Reports.setColumnValue(dom, "CO_TEXT_ORDER_ID", orderId, reportModuleGroup );	
				Reports.setColumnValue(dom, "CO_TEXT_EVENT_SEQ", Services.getValue(&quot;/ds/ManageCase/EventSequence&quot;), reportModuleGroup );	
				Reports.setColumnValue(dom, "CO_TEXT_PROMPT", "DUMMY_PROMPT_VALUE", reportModuleGroup );		
				Reports.setColumnValue(dom, "CO_TEXT_HINT_LINE", "DUMMY_HINT_VALUE", reportModuleGroup );	
				Reports.setColumnValue(dom, "CO_TEXT_FORMAT", "DUMMY", reportModuleGroup );		
				Reports.setColumnValue(dom, "HRG_SEQ", "", reportModuleGroup );	
				Reports.setColumnValue(dom, "WARRANT_ID", "", reportModuleGroup );	
				Reports.setColumnValue(dom, "DETAILS", eventDetails, reportModuleGroup );		
		</xsl:if>				
				
		<xsl:for-each select="GroupId">
			<xsl:variable name="thisGroupId">
				<xsl:value-of select="."/>
			</xsl:variable>					
										
			<xsl:variable name="thisGroupFile">../Grouping.xml</xsl:variable>
			<xsl:for-each select="document($thisGroupFile)/Groups/Group[@GroupId=$thisGroupId]/QuestionId">
				<xsl:variable name="thisQuestionId">
					<xsl:value-of select="."/>
				</xsl:variable>
				<xsl:variable name="thisQuestionFile">
					<xsl:text>../Questions/</xsl:text>
					<xsl:value-of select="$thisQuestionId"/>
					<xsl:text>.xml</xsl:text>
				</xsl:variable>
				<xsl:for-each select="document($thisQuestionFile)/Question">
					<xsl:variable name="reportVariableName">
						<xsl:value-of select="Javascript/ReportVariableName"/>
					</xsl:variable>
					<xsl:variable name="reportVariableValue">
						<xsl:value-of select="Javascript/ReportVariableValue"/>
					</xsl:variable>
					<xsl:variable name="reportVariableCode">
						<xsl:value-of select="Javascript/ReportVariableCode"/>
					</xsl:variable>					
					<xsl:variable name="parameterType">
						<xsl:value-of select="Javascript/ParameterType"/>
					</xsl:variable> 	
					<xsl:variable name="isQuestion">
						<xsl:value-of select="IsQuestion"/>
					</xsl:variable>
					//Is Question : <xsl:value-of select="$isQuestion"/>
					
					<xsl:choose>
					
						<xsl:when test="$thisReportModuleGroupName = 'CJR'">


							<xsl:choose>
								<xsl:when test="$parameterType = 'A'">
								
								</xsl:when>	
								<xsl:when test="$parameterType = 'R'">
								
								</xsl:when>									
								<xsl:otherwise>
								
									<xsl:choose>
										<xsl:when test="$isQuestion = 'N'">
										</xsl:when>

										<xsl:otherwise>
				Reports.setModuleParameterValue(dom, "<xsl:value-of select="$reportVariableName"/>", <xsl:value-of select="$reportVariableValue"/> , <xsl:value-of select="$reportVariableCode"/>, reportModuleGroup );										
										</xsl:otherwise>
									</xsl:choose>	
								</xsl:otherwise>						
							</xsl:choose>
						</xsl:when>
						
						<xsl:when test="$thisReportModuleGroupName = 'CO'">


							<xsl:choose>
								<xsl:when test="$parameterType = 'A'">
								
								</xsl:when>	
								<xsl:when test="$parameterType = 'R'">
								
								</xsl:when>		
								<xsl:when test="$parameterType = 'S'">
				
								</xsl:when>									
								<xsl:when test="$parameterType = 'H'">
				Reports.setHearingColumnValueForCO(dom, "<xsl:value-of select="$reportVariableName"/>", <xsl:value-of select="$reportVariableValue"/>, <xsl:value-of select="$reportVariableCode"/>, reportModuleGroup, Services.getValue(Header_CONumber.dataBinding), hearingType, getCourtCodeForReport(), getAddressIdForReport() );				
								</xsl:when>	
								<xsl:when test="$parameterType = 'HT'">
				Reports.setHearingColumnValueForCO(dom, "<xsl:value-of select="$reportVariableName"/>", <xsl:value-of select="$reportVariableValue"/>, <xsl:value-of select="$reportVariableCode"/>, reportModuleGroup, Services.getValue(Header_CONumber.dataBinding), hearingType, getCourtCodeForReport(), getAddressIdForReport() );				
				Reports.setModuleParameterValueForCO(dom, "<xsl:value-of select="$reportVariableName"/>", <xsl:value-of select="$reportVariableValue"/> , <xsl:value-of select="$reportVariableCode"/>, reportModuleGroup );
								</xsl:when>																							
								<xsl:otherwise>
								
									<xsl:choose>
										<xsl:when test="$isQuestion = 'N'">
										</xsl:when>

										<xsl:otherwise>
				Reports.setModuleParameterValueForCO(dom, "<xsl:value-of select="$reportVariableName"/>", <xsl:value-of select="$reportVariableValue"/> , <xsl:value-of select="$reportVariableCode"/>, reportModuleGroup );										
										</xsl:otherwise>
									</xsl:choose>	
								</xsl:otherwise>						
							</xsl:choose>
						</xsl:when>
						
						<xsl:when test="$thisReportModuleGroupName = 'AE'">
							<xsl:variable name="tableName">
								<xsl:value-of select="Javascript/TableName"/>
							</xsl:variable>	
							<xsl:variable name="keyName">
								<xsl:value-of select="Javascript/KeyName"/>
							</xsl:variable>	
							<xsl:variable name="columnName">
								<xsl:value-of select="Javascript/ColumnName"/>
							</xsl:variable>	
							<xsl:variable name="fieldType">
								<xsl:value-of select="Javascript/FieldType"/>
							</xsl:variable>
												
							<xsl:choose>
								<xsl:when test="$parameterType = 'A'">
				Reports.setAppParameterValue(dom, "<xsl:value-of select="$reportVariableName"/>", <xsl:value-of select="$reportVariableValue"/>, "<xsl:value-of select="$tableName"/>", "<xsl:value-of select="$keyName"/>", "<xsl:value-of select="$columnName"/>", "<xsl:value-of select="$fieldType"/>", reportModuleGroup );
								</xsl:when>
								<xsl:when test="$parameterType = 'T'">
				Reports.setTextItemColumnValue(dom, "<xsl:value-of select="$reportVariableName"/>", <xsl:value-of select="$reportVariableValue"/>, <xsl:value-of select="$reportVariableCode"/>, reportModuleGroup, Services.getValue(&quot;/ds/ManageCase/CaseNumber&quot;), orderId );
								</xsl:when>										
								<xsl:when test="$parameterType = 'S'">
				
								</xsl:when>									
								<xsl:when test="$parameterType = 'H'">
				Reports.setHearingColumnValue(dom, "<xsl:value-of select="$reportVariableName"/>", <xsl:value-of select="$reportVariableValue"/>, <xsl:value-of select="$reportVariableCode"/>, reportModuleGroup, Services.getValue(&quot;/ds/ManageCase/CaseNumber&quot;), getHearingType(), getCourtCodeForReport(), getAddressIdForReport() );				
								</xsl:when>									
								<xsl:otherwise>
				Reports.setColumnValue(dom, "<xsl:value-of select="$reportVariableName"/>", <xsl:value-of select="$reportVariableValue"/>, reportModuleGroup );
								</xsl:otherwise>						
							</xsl:choose>
						</xsl:when>	
											
						<xsl:otherwise>
							
				Reports.setValue(dom, "<xsl:value-of select="$reportVariableName"/>",  <xsl:value-of select="$reportVariableValue"/> );								
						</xsl:otherwise>
						
					</xsl:choose>
					
				</xsl:for-each>
			</xsl:for-each>
		</xsl:for-each>
				<xsl:choose>
					<xsl:when test="$returnToMenu != ''">
				Reports.runReport(dom, <xsl:value-of select="$returnToMenu"/>);
					</xsl:when>
					<xsl:otherwise>
				Reports.runReport(dom);
					</xsl:otherwise>
				</xsl:choose>
			}	
		// Generate the methid for Calling the service - End
		
		// prepare the databindings for all questoins
		
		<xsl:for-each select="GroupId">
			<xsl:variable name="thisGroupId">
				<xsl:value-of select="."/>
			</xsl:variable>
			<xsl:variable name="thisGroupFile">../Grouping.xml</xsl:variable>
			<xsl:text>
				/**
				Screen 
			</xsl:text>
			<xsl:value-of select="$thisScreenId"/>
			<xsl:text> - Group </xsl:text>
			<xsl:value-of select="$thisGroupId"/>
			<xsl:text>
				GroupFile:
			</xsl:text>
			<xsl:value-of select="$thisGroupFile"/>
			<xsl:text>
				**/
			</xsl:text>

		/** Iterating the Groups' quetions **/

			<xsl:for-each select="document($thisGroupFile)/Groups/Group[@GroupId=$thisGroupId]/QuestionId">
				<xsl:variable name="thisQuestionId">
					<xsl:value-of select="."/>
				</xsl:variable>
				<xsl:variable name="thisQuestionFile">
					<xsl:text>../Questions/</xsl:text>
					<xsl:value-of select="$thisQuestionId"/>
					<xsl:text>.xml</xsl:text>
				</xsl:variable>
				<xsl:text>
					/**
					Question: 
				</xsl:text>
				<xsl:value-of select="$thisQuestionFile"/>
				<xsl:text>
					**/			
				</xsl:text>
				<xsl:call-template name="generateQuestionDefinitionsForScreen">
					<xsl:with-param name="currentQuestionFile">
						<xsl:value-of select="$thisQuestionFile"/>
					</xsl:with-param>
					<xsl:with-param name="currentScreenId">
						<xsl:value-of select="$thisScreenId"/>
					</xsl:with-param>
				</xsl:call-template>
			</xsl:for-each>
		</xsl:for-each>
		
		// prepare the full objects for all questions
		
		<xsl:for-each select="GroupId">
			<xsl:variable name="thisGroupId">
				<xsl:value-of select="."/>
			</xsl:variable>
			<xsl:variable name="thisGroupFile">../Grouping.xml</xsl:variable>
			<xsl:text>
				/**
				Screen 
			</xsl:text>
			<xsl:value-of select="$thisScreenId"/>
			<xsl:text> - Group </xsl:text>
			<xsl:value-of select="$thisGroupId"/>
			<xsl:text>
				GroupFile:
			</xsl:text>
			<xsl:value-of select="$thisGroupFile"/>
			<xsl:text>
				**/
			</xsl:text>
			<xsl:for-each select="document($thisGroupFile)/Groups/Group[@GroupId=$thisGroupId]/QuestionId">
				<xsl:variable name="thisQuestionId">
					<xsl:value-of select="."/>
				</xsl:variable>
				<xsl:variable name="thisQuestionFile">
					<xsl:text>../Questions/</xsl:text>
					<xsl:value-of select="$thisQuestionId"/>
					<xsl:text>.xml</xsl:text>
				</xsl:variable>
				<xsl:text>
					/**
					Question: 
				</xsl:text>
				<xsl:value-of select="$thisQuestionFile"/>
				<xsl:text>
					**/			
				</xsl:text>
				
				<xsl:call-template name="generateQuestionsForScreen">
					<xsl:with-param name="currentQuestionFile">
						<xsl:value-of select="$thisQuestionFile"/>
					</xsl:with-param>
					<xsl:with-param name="currentScreenId">
						<xsl:value-of select="$thisScreenId"/>
					</xsl:with-param>
				</xsl:call-template>
			</xsl:for-each>
		</xsl:for-each>
		
		<xsl:text>		
			function OwningCourt_Name() {}
			function OwningCourt_Code() {}
			
			OwningCourt_Code.dataBinding = PAGE_XPATH + "/tmp/OwningCourtCode";
			OwningCourt_Name.dataBinding = REF_DATA_XPATH + "/Courts/Court[Code = " + OwningCourt_Code.dataBinding + "]/Name";
			OwningCourt_Name.retrieveOn = [OwningCourt_Code.dataBinding];
			OwningCourt_Code.isReadOnly = function()
			{ 
				return true;
			}
			OwningCourt_Name.isReadOnly = function()
			{ 
				return true;
			}
			
			OracleReportForm.initialise = function()
			{
				//var ADMIN_CROWN_COURT = CaseManUtils.getUserParameter(CaseManFormParameters.COURTNUMBER_XPATH);
				// change to use Xpath Constant for Oracle Report Court Code - TRAC 2446
				var ADMIN_CROWN_COURT = null;
				if ( CaseManUtils.isBlank(Services.getValue(CaseManFormParameters.OR_COURT_CODE_XPATH)) ){
					// Xpath Constant for Oracle Report Court Code not setup, use user's home court instead
					ADMIN_CROWN_COURT = CaseManUtils.getUserParameter(CaseManFormParameters.COURTNUMBER_XPATH);
				}
				else{
					// Use Xpath Constant for Oracle Report Court Code
					ADMIN_CROWN_COURT = Services.getValue(CaseManFormParameters.OR_COURT_CODE_XPATH);
				}
				
				Services.setValue(PAGE_XPATH + "/tmp/OwningCourtCode", ADMIN_CROWN_COURT);
				var ADMIN_CROWN_COURT_NAME = CaseManUtils.getUserParameter(CaseManFormParameters.COURTNAME_XPATH);
				Services.setValue(PAGE_XPATH + "/tmp/OwningCourtName", ADMIN_CROWN_COURT_NAME);
			
				var currentCurrency = Services.getValue(REF_DATA_XPATH + "/CurrentCurrency/CurrencyCode");
				if ( CaseManUtils.isBlank(currentCurrency) )
				{
					var params = new ServiceParams();
					Services.callService("getCurrentCurrency", params, OracleReportForm, true);
				}
			}
			
			OracleReportForm.onSuccess = function(dom)
			{
				Services.replaceNode(REF_DATA_XPATH + "/CurrentCurrency", dom);
			}		
			
			function Status_RunReportButton() {}
			Status_RunReportButton.tabIndex = __tabIdx++;
			
			Status_RunReportButton.actionBinding = function() {
				if ( CaseManValidationHelper.validateFields(Status_RunReportButton.validationList) )
				{
					requestReport();
				}
			  	else
			  	{
			  		alert(Messages.POPUP_INVALID_MESSAGE);
			  	}				
			}
			
			function Status_Close_Btn() {};
			Status_Close_Btn.tabIndex = __tabIdx++;
			Status_Close_Btn.actionBinding = function()
			{
				exitScreen();
			};

			function validateStartDate(p_startDate, p_endDate)
			{
			    var startDate = Services.getValue(p_startDate.dataBinding);
			    var endDate = Services.getValue(p_endDate.dataBinding);
			    var startDateObj = CaseManUtils.isBlank(startDate) ? null : CaseManUtils.createDate(startDate);
				var endDateObj = CaseManUtils.isBlank(endDate) ? null : CaseManUtils.createDate(endDate);
			    var ec = null;
			    if(startDateObj != null)
			    {
			      ec = validateDate(startDateObj);
			      if(ec == null)
			      {
			      	if (endDateObj != null)
			      	{
				        if (CaseManUtils.compareDates(startDateObj, endDateObj) == -1)
					    {
					      ec = ErrorCode.getErrorCode("CaseMan_startDateCannotBeLaterThanEndDate_Msg");
					    }
				    }
			      }      
			    }
			    return ec;				
			}
			
			function validateEndDate(p_startDate, p_endDate)
			{
			    var endDate = Services.getValue(p_endDate.dataBinding);
			    var endDateObj = CaseManUtils.isBlank(endDate) ? null : CaseManUtils.createDate(endDate);    
			    var ec = null;
			    if (endDateObj != null)
			    {
			    	ec = validateDate(endDateObj);
			    	//p_startDate.validate();
			    }
			    return ec;				
			}

			function validateStartDateForBMSLiveDate(p_startDate, p_endDate)
			{
			    var startDate = Services.getValue(p_startDate.dataBinding);
			    var endDate = Services.getValue(p_endDate.dataBinding);
			    var startDateObj = CaseManUtils.isBlank(startDate) ? null : CaseManUtils.createDate(startDate);
				var endDateObj = CaseManUtils.isBlank(endDate) ? null : CaseManUtils.createDate(endDate);
			    var ec = null;
			    if(startDateObj != null)
			    {
			      ec = validateDateForBMSLiveDate(startDateObj);
			      if(ec == null)
			      {
			      	if (endDateObj != null)
			      	{
				        if (CaseManUtils.compareDates(startDateObj, endDateObj) == -1)
					    {
					      ec = ErrorCode.getErrorCode("CaseMan_startDateCannotBeLaterThanEndDate_Msg");
					    }
				    }
			      }      
			    }
			    return ec;				
			}

			function validateDateForBMSLiveDate(dateObj)
			{    
			  var todayDateObj = CaseManUtils.createDate(getTodaysDate());
			  var bmsLiveDateObj = CaseManUtils.getBMSLiveDateObject( REF_DATA_XPATH + "/ds/BMSLivedate/ItemValue" );
			  if(CaseManUtils.compareDates(todayDateObj, dateObj)!= 1 )
			  { 
			    if(CaseManUtils.compareDates(bmsLiveDateObj, dateObj) != -1)
			    {
			      return null;
			    }
			    else
			    {
			      ec = ErrorCode.getErrorCode("CaseMan_dateCannotBeEarlierThanBMSLiveDate_Msg");
			      return faildedValidation (ec);
			    }
			  }
			  else
			  {
			    ec = ErrorCode.getErrorCode("CaseMan_dateCannotBeInTheFuture_Msg");
			    return faildedValidation (ec);
			  }      
			  return null;   
			}	
			
			function validateDate(dateObj)
			{    
			  var todayDateObj = CaseManUtils.createDate(getTodaysDate());
			  if(CaseManUtils.compareDates(todayDateObj, dateObj)!= 1 )
			  {
			      return null;
			  }
			  else
			  {
			    ec = ErrorCode.getErrorCode("CaseMan_dateCannotBeInTheFuture_Msg");
			    return faildedValidation (ec);
			  }      
			  return null;   
			}
			
			function validateDateInPast(dateObj)
			{    
				var ec = null;
				var todayDateObj = CaseManUtils.createDate(getTodaysDate());
				if ( CaseManUtils.compareDates(dateObj, todayDateObj) != 1 ) 
				{
					ec = ErrorCode.getErrorCode("CaseMan_dateCanOnlyBeInThePast_Msg");
				}
				return ec;
			}

			function getMonthStartDate()
			{    
			  var todaysDate = CaseManUtils.createDate(getTodaysDate()); 
			  todaysDate.setDate("01");
			  var monthStartDateObj = CaseManUtils.convertDateToPattern(todaysDate,"YYYY-MM-DD");
			  return monthStartDateObj;
			}
		
			function getTodaysDate() 
			{
				var date = Services.getValue(REF_DATA_XPATH + "/SystemDate");
				return date;
			}
			
			function faildedValidation (ec)
			{
			  if(ec != null)
			  {
			    Services.setTransientStatusBarMessage(ec.getMessage());
			  }
			  return ec;
			}		
			
			function removeSpaces(inputString) {
			   // Removes any spaces from the passed string.
			   if (typeof inputString != "string") return inputString;
			   var retValue = inputString;
			   var ch = retValue.substring(0, 1);
				
			   while (ch == " ") { // Check for spaces at the beginning of the string
				  retValue = retValue.substring(1, retValue.length);
				  ch = retValue.substring(0, 1);
			   }
			   ch = retValue.substring(retValue.length - 1, retValue.length);
				
			   while (ch == " ") { // Check for spaces at the end of the string
				  retValue = retValue.substring(0, retValue.length - 1);
				  ch = retValue.substring(retValue.length - 1, retValue.length);
			   }
				
				// Note that there are two spaces in the string - look for multiple spaces within the string
			   while (retValue.indexOf(" ") != -1) {
					// Again, there are spaces in each of the strings
				  retValue = retValue.substring(0, retValue.indexOf(" ")) + retValue.substring(retValue.indexOf(" ") + 1, retValue.length);
			   }
			   return retValue; // Return the trimmed string back to the user
			}			

		  	// Function that gets the list of values to populate the LOV button above from a seperate XML file
		 	function getList(xmlFileName)
		  	{
		    	var dom = Services.loadDOMFromURL(xmlFileName);
				return dom;		
		  	}

			function Progress_Bar() {}
			Progress_Bar.dataBinding 	= "/ds/ProgressBar/Progress";

			Progress_Bar.isReadOnly = function() {
				return true;
			}	

			function Popup_Cancel() {};
			Popup_Cancel.cancelled = false;

		</xsl:text>

			Popup_Cancel.actionBinding = function() 
			{
				Popup_Cancel.cancelled = true;
				Services.dispatchEvent("ProgressIndicator_Popup", PopupGUIAdaptor.EVENT_LOWER);
				<xsl:if test="$thisReportModuleGroupName != ''">
					var process = top.WP.GetScreenProcessORA();
					top.WP.SetState(process, 'QADone', true );
				</xsl:if>
			}

			function exitScreen()
			{
				Services.navigate(NavigationController.<xsl:value-of select="$returnMenu"/>);
			}						
			Services.formConfigLoaded = true;
	</xsl:template>
	
	
	
	
	<xsl:template name="generateQuestionsForScreen">
		<xsl:param name="currentQuestionFile"/>
		<xsl:param name="currentScreenId"/>
		<xsl:for-each select="document($currentQuestionFile)/Question">
			<xsl:call-template name="Question">
				<xsl:with-param name="objectName">
					<xsl:value-of select="ObjectName"/>
				</xsl:with-param>
				<xsl:with-param name="componentName">
					<xsl:choose>
						<xsl:when test="Javascript/componentName = '##label##'">
							<xsl:value-of select="Label"/>
						</xsl:when>
						<xsl:otherwise>
							<xsl:choose>
								<xsl:when test="Javascript/componentName and Javascript/componentName != ''">
									<xsl:value-of select="Javascript/componentName"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:value-of select="Label"/>
								</xsl:otherwise>
							</xsl:choose>
						</xsl:otherwise>
					</xsl:choose>
				</xsl:with-param>
				<xsl:with-param name="dataBinding">
					<xsl:value-of select="Javascript/XPath"/>
				</xsl:with-param>
				<xsl:with-param name="srcData"/>
				<xsl:with-param name="rowXPath"/>
				<xsl:with-param name="keyXPath"/>
				<xsl:with-param name="displayXPath"/>
				<xsl:with-param name="hintText">
					<xsl:choose>
						<xsl:when test="Javascript/Context[@ScreenId = $currentScreenId]">
							
							<xsl:choose>
								<xsl:when test="Javascript/Context[@ScreenId = $currentScreenId]/HintText">
									<xsl:value-of select="Javascript/Context[@ScreenId = $currentScreenId]/HintText"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:value-of select="Javascript/HintText"/>
								</xsl:otherwise>
							</xsl:choose>
							
						</xsl:when>
						<xsl:otherwise>
							<xsl:value-of select="Javascript/HintText"/>
						</xsl:otherwise>
					</xsl:choose>
				</xsl:with-param>
				<xsl:with-param name="maxLength">
					<xsl:choose>
						<xsl:when test="Javascript/Context[@ScreenId = $currentScreenId]">
							<xsl:choose>
								<xsl:when test="Javascript/Context[@ScreenId = $currentScreenId]/maxLength">
								<xsl:value-of select="Javascript/Context[@ScreenId = $currentScreenId]/maxLength"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:value-of select="Javascript/maxLength"/>
								</xsl:otherwise>
							</xsl:choose>	
						</xsl:when>
						<xsl:otherwise>
							<xsl:value-of select="Javascript/maxLength"/>
						</xsl:otherwise>
					</xsl:choose>
				</xsl:with-param>
				<xsl:with-param name="mandatoryOn">
					<xsl:choose>
						<xsl:when test="Javascript/Context[@ScreenId = $currentScreenId]">
							
							
							<xsl:choose>
								<xsl:when test="Javascript/Context[@ScreenId = $currentScreenId]/mandatoryOn">
								<xsl:value-of select="Javascript/Context[@ScreenId = $currentScreenId]/mandatoryOn"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:value-of select="Javascript/mandatoryOn"/>
								</xsl:otherwise>
							</xsl:choose>
							
							
							
						</xsl:when>
						<xsl:otherwise>
							<xsl:value-of select="Javascript/mandatoryOn"/>
						</xsl:otherwise>
					</xsl:choose>
				</xsl:with-param>
				<xsl:with-param name="isMandatory">
					<xsl:choose>
						<xsl:when test="Javascript/Context[@ScreenId = $currentScreenId]">
							
							
							<xsl:choose>
								<xsl:when test="Javascript/Context[@ScreenId = $currentScreenId]/isMandatory">
								<xsl:value-of select="Javascript/Context[@ScreenId = $currentScreenId]/isMandatory"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:value-of select="Javascript/isMandatory"/>
								</xsl:otherwise>
							</xsl:choose>
							
							
							
						</xsl:when>
						<xsl:otherwise>
							<xsl:value-of select="Javascript/isMandatory"/>
						</xsl:otherwise>
					</xsl:choose>
				</xsl:with-param>
				<xsl:with-param name="validateOn">
					<xsl:choose>
						<xsl:when test="Javascript/Context[@ScreenId = $currentScreenId]">
							<xsl:choose>
							<xsl:when test="Javascript/Context[@ScreenId = $currentScreenId]/validateOn">
								<xsl:value-of select="Javascript/Context[@ScreenId = $currentScreenId]/validateOn"/>
							</xsl:when>
							<xsl:otherwise>
								<xsl:value-of select="Javascript/validateOn"/>
							</xsl:otherwise>
							</xsl:choose>
						</xsl:when>
						<xsl:otherwise>
							<xsl:value-of select="Javascript/validateOn"/>
						</xsl:otherwise>
					</xsl:choose>
				</xsl:with-param>
				<xsl:with-param name="validate">
					<xsl:choose>
						<xsl:when test="Javascript/Context[@ScreenId = $currentScreenId]">
							<xsl:choose>
							<xsl:when test="Javascript/Context[@ScreenId = $currentScreenId]/validate">
							   <xsl:value-of select="Javascript/Context[@ScreenId = $currentScreenId]/validate"/>
							</xsl:when>
							<xsl:otherwise>
							  <xsl:value-of select="Javascript/validate"/>
							</xsl:otherwise>
							</xsl:choose>
						</xsl:when>						  
						<xsl:otherwise>
							<xsl:value-of select="Javascript/validate"/>
						</xsl:otherwise>
					</xsl:choose>
				</xsl:with-param>
				
				<xsl:with-param name="initialise">
					<xsl:choose>
						<xsl:when test="Javascript/Context[@ScreenId = $currentScreenId]">
							<xsl:choose>
							<xsl:when test="Javascript/Context[@ScreenId = $currentScreenId]/initialise">
							   <xsl:value-of select="Javascript/Context[@ScreenId = $currentScreenId]/initialise"/>
							</xsl:when>
							<xsl:otherwise>
							  <xsl:value-of select="Javascript/initialise"/>
							</xsl:otherwise>
							</xsl:choose>
						</xsl:when>						  
						<xsl:otherwise>
							<xsl:value-of select="Javascript/initialise"/>
						</xsl:otherwise>
					</xsl:choose>
				</xsl:with-param>
				
				<xsl:with-param name="readOnlyOn">
					<xsl:choose>
						<xsl:when test="Javascript/Context[@ScreenId = $currentScreenId]">
							<xsl:choose>
							<xsl:when test="Javascript/Context[@ScreenId = $currentScreenId]/readOnlyOn">
								<xsl:value-of select="Javascript/Context[@ScreenId = $currentScreenId]/readOnlyOn"/>
							</xsl:when>
							<xsl:otherwise>
								<xsl:value-of select="Javascript/readOnlyOn"/>
							</xsl:otherwise>
							</xsl:choose>
						</xsl:when>
						<xsl:otherwise>
							<xsl:value-of select="Javascript/readOnlyOn"/>
						</xsl:otherwise>
					</xsl:choose>
				</xsl:with-param>
				<xsl:with-param name="isReadOnly">
					<xsl:choose>
						<xsl:when test="Javascript/Context[@ScreenId = $currentScreenId]">
							<xsl:choose>
							<xsl:when test="Javascript/Context[@ScreenId = $currentScreenId]/isReadOnly">
							   <xsl:value-of select="Javascript/Context[@ScreenId = $currentScreenId]/isReadOnly"/>
							</xsl:when>
							<xsl:otherwise>
							  <xsl:value-of select="Javascript/isReadOnly"/>
							</xsl:otherwise>
							</xsl:choose>
						</xsl:when>						  
						<xsl:otherwise>
							<xsl:value-of select="Javascript/isReadOnly"/>
						</xsl:otherwise>
					</xsl:choose>
				</xsl:with-param>
				<xsl:with-param name="logicOn">
					<xsl:choose>
						<xsl:when test="Javascript/Context[@ScreenId = $currentScreenId]">
							<xsl:choose>
						  <xsl:when test="Javascript/Context[@ScreenId = $currentScreenId]/logicOn">
							<xsl:value-of select="Javascript/Context[@ScreenId = $currentScreenId]/logicOn"/>
					      </xsl:when>
					      <xsl:otherwise>
								<xsl:value-of select="Javascript/logicOn"/>
							</xsl:otherwise>
							</xsl:choose>
						</xsl:when>
						<xsl:otherwise>
							<xsl:value-of select="Javascript/logicOn"/>
						</xsl:otherwise>
					</xsl:choose>
				</xsl:with-param>
				<xsl:with-param name="logic">
					<xsl:choose>
						<xsl:when test="Javascript/Context[@ScreenId = $currentScreenId]">
							<xsl:choose>
								
						  <xsl:when test="Javascript/Context[@ScreenId = $currentScreenId]/logic">
							<xsl:value-of select="Javascript/Context[@ScreenId = $currentScreenId]/logic"/>
						  </xsl:when>
						  <xsl:otherwise>
							  <xsl:value-of select="Javascript/logic"/>
							</xsl:otherwise>
							</xsl:choose>
						</xsl:when>
						<xsl:otherwise>
							<xsl:value-of select="Javascript/logic"/>
						</xsl:otherwise>
					</xsl:choose>
				</xsl:with-param>
				<xsl:with-param name="enableOn">
					<xsl:choose>
						<xsl:when test="Javascript/Context[@ScreenId = $currentScreenId]">
							<xsl:choose>
						  <xsl:when test="Javascript/Context[@ScreenId = $currentScreenId]/enableOn">
							<xsl:value-of select="Javascript/Context[@ScreenId = $currentScreenId]/enableOn"/>
						  </xsl:when>
					      <xsl:otherwise>
								<xsl:value-of select="Javascript/enableOn"/>
						  </xsl:otherwise>
						  </xsl:choose>
						</xsl:when>
						<xsl:otherwise>
							<xsl:value-of select="Javascript/enableOn"/>
						</xsl:otherwise>
					</xsl:choose>
				</xsl:with-param>
				<xsl:with-param name="enabled">
					<xsl:choose>
						<xsl:when test="Javascript/Context[@ScreenId = $currentScreenId]">
							<xsl:choose>
						  		<xsl:when test="Javascript/Context[@ScreenId = $currentScreenId]/enabled">						
									<xsl:value-of select="Javascript/Context[@ScreenId = $currentScreenId]/enabled"/>
								  </xsl:when>
								  <xsl:otherwise>
									  <xsl:value-of select="Javascript/enabled"/>
								  </xsl:otherwise>
							</xsl:choose>
						</xsl:when>
						<xsl:otherwise>
							<xsl:value-of select="Javascript/enabled"/>
						</xsl:otherwise>
					</xsl:choose>
				</xsl:with-param>
				<xsl:with-param name="isEnabled">
					<xsl:choose>
						<xsl:when test="Javascript/Context[@ScreenId = $currentScreenId]">
						  <xsl:choose>
						  		<xsl:when test="Javascript/Context[@ScreenId = $currentScreenId]/isEnabled">
								<xsl:value-of select="Javascript/Context[@ScreenId = $currentScreenId]/isEnabled"/>
							  </xsl:when>
							  <xsl:otherwise>
								  <xsl:value-of select="Javascript/isEnabled"/>
							  </xsl:otherwise>
						  </xsl:choose>
						</xsl:when>
						<xsl:otherwise>
							<xsl:value-of select="Javascript/isEnabled"/>
						</xsl:otherwise>
					</xsl:choose>
				</xsl:with-param>
				<xsl:with-param name="postSetValue">
					<xsl:choose>
						<xsl:when test="Javascript/Context[@ScreenId = $currentScreenId]">
							
							
							<xsl:choose>
								<xsl:when test="Javascript/Context[@ScreenId = $currentScreenId]/postSetValue">
								<xsl:value-of select="Javascript/Context[@ScreenId = $currentScreenId]/postSetValue"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:value-of select="Javascript/postSetValue"/>
								</xsl:otherwise>
							</xsl:choose>
							
							
						</xsl:when>
						<xsl:otherwise>
							<xsl:value-of select="Javascript/postSetValue"/>
						</xsl:otherwise>
					</xsl:choose>
				</xsl:with-param>
				<xsl:with-param name="transformToModel">
					<xsl:choose>
						<xsl:when test="Javascript/Context[@ScreenId = $currentScreenId]">
							<xsl:choose>
							<xsl:when test="Javascript/Context[@ScreenId = $currentScreenId]/transformToModel">
								<xsl:value-of select="Javascript/Context[@ScreenId = $currentScreenId]/transformToModel"/>
							</xsl:when>
							<xsl:otherwise>
								<xsl:value-of select="Javascript/transformToModel"/>	
							</xsl:otherwise>
						</xsl:choose>
						</xsl:when>
						<xsl:otherwise>
							<xsl:value-of select="Javascript/transformToModel"/>
						</xsl:otherwise>
					</xsl:choose>
				</xsl:with-param>
				<xsl:with-param name="transformToDisplay">
					<xsl:choose>
						<xsl:when test="Javascript/Context[@ScreenId = $currentScreenId]">
							<xsl:choose>
								<xsl:when test="Javascript/Context[@ScreenId = $currentScreenId]/transformToDisplay">
									<xsl:value-of select="Javascript/Context[@ScreenId = $currentScreenId]/transformToDisplay"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:value-of select="Javascript/transformToDisplay"/>
								</xsl:otherwise>				
							</xsl:choose>
						</xsl:when>
						<xsl:otherwise>
							<xsl:value-of select="Javascript/transformToDisplay"/>
						</xsl:otherwise>
					</xsl:choose>
				</xsl:with-param>
				<xsl:with-param name="modelValue">
					<xsl:choose>
						<xsl:when test="Javascript/Context[@ScreenId = $currentScreenId]">
							<xsl:choose>
								<xsl:when test="Javascript/Context[@ScreenId = $currentScreenId]/modelValue">
								<xsl:value-of select="Javascript/Context[@ScreenId = $currentScreenId]/modelValue"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:value-of select="Javascript/modelValue"/>
								</xsl:otherwise>
							</xsl:choose>
							
						</xsl:when>
						<xsl:otherwise>
							<xsl:value-of select="Javascript/modelValue"/>
						</xsl:otherwise>
					</xsl:choose>
				</xsl:with-param>
				<xsl:with-param name="miscCode">
					<xsl:choose>
						<xsl:when test="Javascript/Context[@ScreenId = $currentScreenId]">
							<xsl:choose>
							
							
						  <xsl:when test="Javascript/Context[@ScreenId = $currentScreenId]/miscCode">
						  	<xsl:value-of select="Javascript/miscCode"/>
							<xsl:value-of select="Javascript/Context[@ScreenId = $currentScreenId]/miscCode"/>
							
						  </xsl:when>
						  <xsl:otherwise>
							  <xsl:value-of select="Javascript/miscCode"/>
							</xsl:otherwise>
							</xsl:choose>
						</xsl:when>						
						<xsl:otherwise>
							<xsl:value-of select="Javascript/miscCode"/>
						</xsl:otherwise>
					</xsl:choose>
				</xsl:with-param>
				<xsl:with-param name="setDefault">
					<xsl:choose>
						<xsl:when test="Javascript/Context[@ScreenId = $currentScreenId]">
							<xsl:choose>
							
							
						  <xsl:when test="Javascript/Context[@ScreenId = $currentScreenId]/setDefault">
						  	<xsl:value-of select="Javascript/setDefault"/>
							<xsl:value-of select="Javascript/Context[@ScreenId = $currentScreenId]/setDefault"/>
							
						  </xsl:when>
						  <xsl:otherwise>
							  <xsl:value-of select="Javascript/setDefault"/>
							</xsl:otherwise>
							</xsl:choose>
						</xsl:when>						
						<xsl:otherwise>
							<xsl:value-of select="Javascript/setDefault"/>
						</xsl:otherwise>
					</xsl:choose>
				</xsl:with-param>				
			</xsl:call-template>
		</xsl:for-each>
	</xsl:template>
	
	
	
	<xsl:template name="generateQuestionDefinitionsForScreen">
		<xsl:param name="currentQuestionFile"/>
		<xsl:param name="currentScreenId"/>
		<xsl:for-each select="document($currentQuestionFile)/Question">
			<xsl:call-template name="QuestionDefinition">
				<xsl:with-param name="objectName">
					<xsl:value-of select="ObjectName"/>
				</xsl:with-param>
				<xsl:with-param name="dataBinding">
					<xsl:value-of select="Javascript/XPath"/>
				</xsl:with-param>
			</xsl:call-template>
		</xsl:for-each>
	</xsl:template>
	
	
	<xsl:template name="Question">
		<xsl:param name="objectName"/>
		<xsl:param name="componentName"/>
		<xsl:param name="maxLength"/>
		<xsl:param name="dataBinding"/>
		<xsl:param name="srcData">null</xsl:param>
		<xsl:param name="rowXPath">null</xsl:param>
		<xsl:param name="keyXPath">null</xsl:param>
		<xsl:param name="displayXPath">null</xsl:param>
		<xsl:param name="hintText"/>
		<xsl:param name="mandatoryOn"/>
		<xsl:param name="isMandatory"/> 
		<xsl:param name="validateOn"/>
		<xsl:param name="validate"/>
		<xsl:param name="initialise"/>		
		<xsl:param name="readOnlyOn"/>
		<xsl:param name="isReadOnly"/>				
		<xsl:param name="logicOn"/>
		<xsl:param name="logic"/>
		<xsl:param name="enableOn"/>
		<xsl:param name="enabled"/>
		<xsl:param name="isEnabled"/>
		<xsl:param name="postSetValue"/>
		<xsl:param name="transformToModel"/>
		<xsl:param name="transformToDisplay"/>
		<xsl:param name="modelValue"/>
		<xsl:param name="miscCode"/>
		<xsl:param name="setDefault"/>
		<xsl:value-of select="$objectName"/>
		<xsl:text>.tabIndex = __tabIdx++;
		</xsl:text>
		<xsl:value-of select="$objectName"/>
		<xsl:text>.componentName = "</xsl:text>
		<xsl:value-of select="$componentName"/>	
		<xsl:text>";		</xsl:text>
		<xsl:choose>
			<xsl:when test="$srcData = ''">
				<xsl:value-of select="$objectName"/>
				<xsl:text>.srcData = null;
				</xsl:text>
			</xsl:when>
			<xsl:otherwise>
				<xsl:value-of select="$objectName"/>
				<xsl:text>.srcData = </xsl:text>
				<xsl:value-of select="$srcData"/>
				<xsl:text>;
				</xsl:text>
			</xsl:otherwise>
		</xsl:choose>
		<xsl:choose>
			<xsl:when test="$rowXPath = ''">
				<xsl:value-of select="$objectName"/>
				<xsl:text>.rowXPath = null;
		</xsl:text>
			</xsl:when>
			<xsl:otherwise>
				<xsl:value-of select="$objectName"/>
				<xsl:text>.rowXPath = </xsl:text>
				<xsl:value-of select="$rowXPath"/>
				<xsl:text>;
				</xsl:text>
			</xsl:otherwise>
		</xsl:choose>
		<xsl:choose>
			<xsl:when test="$keyXPath = ''">
				<xsl:value-of select="$objectName"/>
				<xsl:text>.keyXPath = null;
				</xsl:text>
			</xsl:when>
			<xsl:otherwise>
				<xsl:value-of select="$objectName"/>
				<xsl:text>.keyXPath = </xsl:text>
				<xsl:value-of select="$keyXPath"/>
				<xsl:text>;
				</xsl:text>
			</xsl:otherwise>
		</xsl:choose>
		<xsl:choose>
			<xsl:when test="$displayXPath = ''">
				<xsl:value-of select="$objectName"/>
				<xsl:text>.displayXPath = null;
				</xsl:text>
			</xsl:when>
			<xsl:otherwise>
				<xsl:value-of select="$objectName"/>
				<xsl:text>.displayXPath =</xsl:text>
				<xsl:value-of select="$displayXPath"/>
				<xsl:text>;
				</xsl:text>
			</xsl:otherwise>
		</xsl:choose>
		<xsl:choose>
			<xsl:when test="$hintText = ''">
				<xsl:value-of select="$objectName"/>
				<xsl:text>.helpText = null;
				</xsl:text>
			</xsl:when>
			<xsl:otherwise>
				<xsl:value-of select="$objectName"/>
				<xsl:text>.helpText = "</xsl:text>
				<xsl:value-of select="$hintText"/>
				<xsl:text>";
				</xsl:text>
			</xsl:otherwise>
		</xsl:choose>
		<xsl:if test="$maxLength != ''">
			<xsl:value-of select="$objectName"/>
			<xsl:text>.maxLength = </xsl:text>
			<xsl:value-of select="$maxLength"/>
			<xsl:text>;
			</xsl:text>
		</xsl:if>
		<xsl:if test="$mandatoryOn != ''">
			<xsl:value-of select="$objectName"/>
			<xsl:text>.mandatoryOn = [</xsl:text>
			<xsl:value-of select="$mandatoryOn"/>
			<xsl:text>];
			</xsl:text>
		</xsl:if>
		<xsl:if test="$isMandatory != ''">
			<xsl:value-of select="$objectName"/>
			<xsl:text>.isMandatory = function()
				{
			</xsl:text>
			<xsl:value-of select="$isMandatory"/>
			<xsl:text>
				}
			</xsl:text>
		</xsl:if>
		<xsl:if test="$validateOn != ''">
			<xsl:value-of select="$objectName"/>
			<xsl:text>.validateOn = [</xsl:text>
			<xsl:value-of select="$validateOn"/>
			<xsl:text>];
			</xsl:text>
		</xsl:if>
		<xsl:if test="$validate != ''">
			<xsl:value-of select="$objectName"/>
			<xsl:text>.validate = function(value)
				{
			</xsl:text>
			<xsl:value-of select="$validate"/>
			<xsl:text>
				}
			</xsl:text>
		</xsl:if>		

		<xsl:if test="$setDefault != ''">
			<xsl:value-of select="$objectName"/>
			<xsl:text>.setDefault = function()
				{
			</xsl:text>
			<xsl:value-of select="$setDefault"/>
			<xsl:text>
				}
			</xsl:text>
		</xsl:if>	

		
		<xsl:if test="$initialise != ''">
			<xsl:value-of select="$objectName"/>
			<xsl:text>.initialise = function()
				{
			</xsl:text>
			<xsl:value-of select="$initialise"/>
			<xsl:text>
				}
			</xsl:text>
		</xsl:if>
		
		<xsl:if test="$readOnlyOn != ''">
			<xsl:value-of select="$objectName"/>
			<xsl:text>.readOnlyOn = [</xsl:text>
			<xsl:value-of select="$readOnlyOn"/>
			<xsl:text>];
			</xsl:text>
		</xsl:if>
		<xsl:if test="$isReadOnly != ''">
			<xsl:value-of select="$objectName"/>
			<xsl:text>.isReadOnly = function(value)
				{
			</xsl:text>
			<xsl:value-of select="$isReadOnly"/>
			<xsl:text>
				}
			</xsl:text>
		</xsl:if>		
		<xsl:if test="$logicOn != ''">
			<xsl:value-of select="$objectName"/>
			<xsl:text>.logicOn = [</xsl:text>
			<xsl:value-of select="$logicOn"/>
			<xsl:text>];
			</xsl:text>
		</xsl:if>
		<xsl:if test="$logic != ''">
			<xsl:value-of select="$objectName"/>
			<xsl:text>.logic = function(event)
				{
			</xsl:text>
			<xsl:value-of select="$logic"/>
			<xsl:text>
				}
			</xsl:text>
		</xsl:if>
		<xsl:if test="$enableOn != ''">
			<xsl:value-of select="$objectName"/>
			<xsl:text>.enableOn = [</xsl:text>
			<xsl:value-of select="$enableOn"/>
			<xsl:text>];
			</xsl:text>
		</xsl:if>
		<xsl:if test="$enabled != ''">
			<xsl:value-of select="$objectName"/>
			<xsl:text>.enabled = function()
				{
			</xsl:text>
			<xsl:value-of select="$enabled"/>
			<xsl:text>
				}
			</xsl:text>
		</xsl:if>
		<xsl:if test="$isEnabled != ''">
			<xsl:value-of select="$objectName"/>
			<xsl:text>.isEnabled = function()
				{
			</xsl:text>
			<xsl:value-of select="$isEnabled"/>
			<xsl:text>
				}
			</xsl:text>
		</xsl:if>
		<xsl:if test="$postSetValue != ''">
			<xsl:value-of select="$objectName"/>
			<xsl:text>.postSetValue = function(valid, value)
				{
			</xsl:text>
			<xsl:value-of select="$postSetValue"/>
			<xsl:text>
				}
			</xsl:text>
		</xsl:if>
		<xsl:if test="$transformToModel != ''">
			<xsl:value-of select="$objectName"/>
			<xsl:text>.transformToModel = function( value)
				{
			</xsl:text>
			<xsl:value-of select="$transformToModel"/>
			<xsl:text>
				}
			</xsl:text>
		</xsl:if>
		<xsl:if test="$transformToDisplay != ''">
			<xsl:value-of select="$objectName"/>
			<xsl:text>.transformToDisplay = function( value)
				{
			</xsl:text>
			<xsl:value-of select="$transformToDisplay"/>
			<xsl:text>
				}
			</xsl:text>
		</xsl:if>
		<xsl:if test="$modelValue != ''">
			<xsl:value-of select="$objectName"/>
			<xsl:text>.modelValue = { </xsl:text><xsl:value-of select="$modelValue"/> <xsl:text> };</xsl:text>
		</xsl:if>
		<xsl:if test="$miscCode != ''">
			<xsl:text>/** Misc Code for question </xsl:text><xsl:value-of select="$objectName"/><xsl:text> support**/
		</xsl:text>
			<xsl:value-of select="$miscCode"/>
			<xsl:text>/** End of Misc Code for question </xsl:text>
			<xsl:value-of select="$objectName"/>
			<xsl:text> support **/</xsl:text>
		</xsl:if>		
		/** End of <xsl:value-of select="$objectName"/> **/
	</xsl:template>
	
	
	<xsl:template name="QuestionDefinition">
		<xsl:param name="objectName"/>
		<xsl:param name="dataBinding"/>
		<xsl:text>function </xsl:text>
		<xsl:value-of select="$objectName"/>
		<xsl:text>() {}
		</xsl:text>
		<xsl:value-of select="$objectName"/>
		<xsl:text>.dataBinding = "</xsl:text>
		<xsl:value-of select="$dataBinding"/>
		<xsl:text>";
		</xsl:text>
	</xsl:template>
	
</xsl:stylesheet>
