
  CREATE INDEX "CASEMAN"."ACTION_TASK_XREF_TASK_NO" ON "CASEMAN"."ACTION_TASK_XREF" ("TASK_NUMBER")
  ;



  CREATE INDEX "CASEMAN"."AEV_AE_FRGN" ON "CASEMAN"."AE_EVENTS" ("AE_NUMBER")
  ;



  CREATE INDEX "CASEMAN"."AEV_HRG_FRGN" ON "CASEMAN"."AE_EVENTS" ("HRG_SEQ")
  ;



  CREATE INDEX "CASEMAN"."AEV_STD_FRGN" ON "CASEMAN"."AE_EVENTS" ("STD_EVENT_ID")
  ;



  CREATE INDEX "CASEMAN"."AE_APPLICATIONS_IX7" ON "CASEMAN"."AE_APPLICATIONS" ("CASE_NUMBER", "PARTY_AGAINST_CASE_PARTY_NO", "PARTY_AGAINST_PARTY_ROLE_CODE")
  ;



  CREATE INDEX "CASEMAN"."AE_APPLICATIONS_IX8" ON "CASEMAN"."AE_APPLICATIONS" ("CASE_NUMBER", "PARTY_FOR_CASE_PARTY_NO", "PARTY_FOR_PARTY_ROLE_CODE")
  ;



  CREATE INDEX "CASEMAN"."AE_APPLICATIONS_IX9" ON "CASEMAN"."AE_APPLICATIONS" ("JUDG_SEQ")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."AE_APPLICATIONS_PK" ON "CASEMAN"."AE_APPLICATIONS" ("AE_NUMBER")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."AE_APPLICATIONS_UX1" ON "CASEMAN"."AE_APPLICATIONS" ("AE_NUMBER", "CASE_NUMBER")
  ;



  CREATE INDEX "CASEMAN"."AE_EVENTS_FX1" ON "CASEMAN"."AE_EVENTS" (NVL("SERVICE_DATE",TO_DATE('9999-12-31 00:00:00', 'yyyy-mm-dd hh24:mi:ss')), NVL("SERVICE_STATUS",'NOT SERVED'), "ERROR_INDICATOR")
  ;



  CREATE INDEX "CASEMAN"."AE_EVENTS_FX2" ON "CASEMAN"."AE_EVENTS" (NVL("PROCESS_STAGE",' '))
  ;



  CREATE INDEX "CASEMAN"."AE_EVENTS_FX3" ON "CASEMAN"."AE_EVENTS" ("STD_EVENT_ID", TRUNC(NVL("SERVICE_DATE",TO_DATE('9999-12-31 00:00:00', 'yyyy-mm-dd hh24:mi:ss'))), "SERVICE_STATUS", "ERROR_INDICATOR")
  ;



  CREATE INDEX "CASEMAN"."AE_EVENTS_FX4" ON "CASEMAN"."AE_EVENTS" (NVL("SOD_REFERENCE",(-1)))
  ;



  CREATE INDEX "CASEMAN"."AE_EVENTS_IX6" ON "CASEMAN"."AE_EVENTS" ("AE_NUMBER", "STD_EVENT_ID")
  ;



  CREATE INDEX "CASEMAN"."AE_EVENTS_IX7" ON "CASEMAN"."AE_EVENTS" ("PROCESS_STAGE")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."AE_EVENTS_PK" ON "CASEMAN"."AE_EVENTS" ("AE_EVENT_SEQ")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."AE_PER_ITEMS_PK" ON "CASEMAN"."AE_PER_ITEMS" ("AE_PER_SEQ")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."AGE_PK" ON "CASEMAN"."AGE_CATEGORY" ("AGE_CATEGORY")
  ;



  CREATE INDEX "CASEMAN"."ALD_CO_FK" ON "CASEMAN"."ALLOWED_DEBTS" ("DEBT_CO_NUMBER")
  ;



  CREATE INDEX "CASEMAN"."ALD_CT_FK" ON "CASEMAN"."ALLOWED_DEBTS" ("DEBT_ADMIN_COURT_CODE")
  ;



  CREATE INDEX "CASEMAN"."ALLOWED_DEBTS_IX1" ON "CASEMAN"."ALLOWED_DEBTS" ("DEBT_CASE_NUMBER")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."ALLOW_DEBT_PK" ON "CASEMAN"."ALLOWED_DEBTS" ("DEBT_SEQ")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."AO_CAEO_PK" ON "CASEMAN"."AO_CAEO" ("AO_CAEO_NUMBER", "ADMIN_COURT_CODE")
  ;



  CREATE INDEX "CASEMAN"."API_AE_FRGN" ON "CASEMAN"."AE_PER_ITEMS" ("AE_NUMBER")
  ;



  CREATE INDEX "CASEMAN"."API_PDT_FRGN" ON "CASEMAN"."AE_PER_ITEMS" ("DETAIL_CODE")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."ATX_PK" ON "CASEMAN"."ACTION_TASK_XREF" ("ACTION_ID", "TASK_NUMBER")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."C0_EVENT_VALIDATIONS_PK" ON "CASEMAN"."CO_EVENT_VALIDATIONS" ("STD_EVENT_ID")
  ;



  CREATE INDEX "CASEMAN"."CANDIDATE_DIVIDEND_PMTS_IX2" ON "CASEMAN"."CANDIDATE_DIVIDEND_PAYMENTS" ("CDP_TRANSACTION_NUMBER", "ADMIN_COURT_CODE")
  ;



  CREATE INDEX "CASEMAN"."CASES_DELETION_DATE_IDX" ON "CASEMAN"."CASES" ("DELETION_DATE")
  ;



  CREATE INDEX "CASEMAN"."CASES_FX1" ON "CASEMAN"."CASES" (NVL("STATUS",'N/A'))
  ;



  CREATE INDEX "CASEMAN"."CASES_FX2" ON "CASEMAN"."CASES" ("CASE_NUMBER", "ADMIN_CRT_CODE", NVL("STATUS",'N/A'))
  ;



  CREATE INDEX "CASEMAN"."CASES_FX3" ON "CASEMAN"."CASES" (NVL("CRED_CODE",(-1)), "ADMIN_CRT_CODE")
  ;



  CREATE INDEX "CASEMAN"."CASES_INSOLVENCY_NUMBER" ON "CASEMAN"."CASES" ("INSOLVENCY_NUMBER")
  ;



  CREATE INDEX "CASEMAN"."CASES_LAST_EVENT_DATE_IDX" ON "CASEMAN"."CASES" ("LAST_EVENT_DATE")
  ;



  CREATE INDEX "CASEMAN"."CASES_PREV_CRT" ON "CASEMAN"."CASES" ("PREVIOUS_COURT")
  ;



  CREATE INDEX "CASEMAN"."CASE_EVENTS_IX14" ON "CASEMAN"."CASE_EVENTS" ("CASE_NUMBER", "CASE_PARTY_NO", "PARTY_ROLE_CODE")
  ;



  CREATE INDEX "CASEMAN"."CASE_EVENTS_IX15" ON "CASEMAN"."CASE_EVENTS" ("HRG_SEQ")
  ;



  CREATE INDEX "CASEMAN"."CASE_EVENTS_IX16" ON "CASEMAN"."CASE_EVENTS" ("CRT_CODE", "EVENT_DATE", "STATS_MODULE")
  ;



  CREATE INDEX "CASEMAN"."CASE_EVENTS_IX17" ON "CASEMAN"."CASE_EVENTS" ("CREATING_COURT", "EVENT_DATE")
  ;



  CREATE INDEX "CASEMAN"."CASE_EVENTS_IX18" ON "CASEMAN"."CASE_EVENTS" ("CASE_NUMBER", "STD_EVENT_ID", "DELETED_FLAG", "EVENT_SEQ")
  ;



  CREATE INDEX "CASEMAN"."CASE_ISSUE_DATE" ON "CASEMAN"."CASES" ("DATE_OF_ISSUE")
  ;



  CREATE INDEX "CASEMAN"."CASE_PARTY_ROLES_IX4" ON "CASEMAN"."CASE_PARTY_ROLES" ("CASE_NUMBER", "CASE_PARTY_NO", "PARTY_ROLE_CODE", "PARTY_ID")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."CASE_PK" ON "CASEMAN"."CASES" ("CASE_NUMBER")
  ;



  CREATE INDEX "CASEMAN"."CASE_TRANS_TO_FRGN" ON "CASEMAN"."CASES" ("TRANS_CRT_CODE")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."CCE_PK" ON "CASEMAN"."CO_CASE_EVENTS" ("ALD_DEBT_SEQ")
  ;



  CREATE INDEX "CASEMAN"."CDP_CO_FK" ON "CASEMAN"."CANDIDATE_DIVIDEND_PAYMENTS" ("CDP_CO_NUMBER")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."CHEVT_PK" ON "CASEMAN"."CHANGED_EVENTS" ("RELEASE_DATE", "STD_EVENT_ID")
  ;



  CREATE INDEX "CASEMAN"."CONSOLIDATED_ORDERS_IX1" ON "CASEMAN"."CONSOLIDATED_ORDERS" ("DELETION_DATE")
  ;



  CREATE INDEX "CASEMAN"."CONSOLIDATED_ORDERS_IX2" ON "CASEMAN"."CONSOLIDATED_ORDERS" ("LAST_EVENT_DATE")
  ;



  CREATE INDEX "CASEMAN"."COPS_MERGE_FIELDS_IX1" ON "CASEMAN"."COPS_MERGE_FIELDS" ("DV_CODE")
  ;



  CREATE INDEX "CASEMAN"."COPS_MERGE_FIELDS_IX2" ON "CASEMAN"."COPS_MERGE_FIELDS" ("ORDER_ID")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."COP_PK" ON "CASEMAN"."COPS_MERGE_FIELDS" ("CMF_SEQ_NO")
  ;



  CREATE INDEX "CASEMAN"."COURTS_CODE_NAME" ON "CASEMAN"."COURTS" ("CODE", "NAME")
  ;



  CREATE INDEX "CASEMAN"."COV_ALD_FK_I" ON "CASEMAN"."CO_EVENTS" ("ALD_DEBT_SEQ")
  ;



  CREATE INDEX "CASEMAN"."COV_SE_FK_I" ON "CASEMAN"."CO_EVENTS" ("STD_EVENT_ID")
  ;



  CREATE INDEX "CASEMAN"."CO_EVENTS_IX10" ON "CASEMAN"."CO_EVENTS" ("CREATING_COURT", "EVENT_DATE")
  ;



  CREATE INDEX "CASEMAN"."CO_EVENTS_IX8" ON "CASEMAN"."CO_EVENTS" ("HRG_SEQ")
  ;



  CREATE INDEX "CASEMAN"."CO_EVENTS_IX9" ON "CASEMAN"."CO_EVENTS" ("CO_NUMBER", "STD_EVENT_ID")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."CO_EVENTS_PK" ON "CASEMAN"."CO_EVENTS" ("CO_EVENT_SEQ")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."CO_PER_ITEMS_PK" ON "CASEMAN"."CO_PER_ITEMS" ("CO_PER_SEQ")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."CO_PK" ON "CASEMAN"."CONSOLIDATED_ORDERS" ("CO_NUMBER")
  ;



  CREATE INDEX "CASEMAN"."CPI_CO_FK_I" ON "CASEMAN"."CO_PER_ITEMS" ("CO_NUMBER")
  ;



  CREATE INDEX "CASEMAN"."CPR_TO_CPR_RELATIONSHIP_IX3" ON "CASEMAN"."CPR_TO_CPR_RELATIONSHIP" ("CPR_B_CASE_NUMBER", "CPR_B_CASE_PARTY_NO", "CPR_B_PARTY_ROLE_CODE")
  ;



  CREATE INDEX "CASEMAN"."CPT_CLAIMS_IDX1" ON "CASEMAN"."CPT_CLAIMS" ("STATUS")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."CPT_CLAIMS_PK" ON "CASEMAN"."CPT_CLAIMS" ("CLAIM_NUMBER")
  ;



  CREATE INDEX "CASEMAN"."CPT_STATISTICS_IDX1" ON "CASEMAN"."CPT_STATISTICS" ("CLAIM_NUMBER")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."CRT_PK" ON "CASEMAN"."COURTS" ("CODE")
  ;



  CREATE INDEX "CASEMAN"."CTI_COV_FK_I" ON "CASEMAN"."CO_TEXT_ITEMS" ("CO_TEXT_EVENT_SEQ")
  ;



  CREATE INDEX "CASEMAN"."CTI_CO_FK_I" ON "CASEMAN"."CO_TEXT_ITEMS" ("CO_TEXT_CO_NUMBER")
  ;



  CREATE INDEX "CASEMAN"."CTI_ITD_FK_I" ON "CASEMAN"."CO_TEXT_ITEMS" ("CO_TEXT_DETAIL_CODE")
  ;



  CREATE INDEX "CASEMAN"."CTI_ORD_FK_I" ON "CASEMAN"."CO_TEXT_ITEMS" ("CO_TEXT_ORDER_ID")
  ;



  CREATE INDEX "CASEMAN"."DD_ALD_FK" ON "CASEMAN"."DEBT_DIVIDENDS" ("DD_ALD_SEQ")
  ;



  CREATE INDEX "CASEMAN"."DD_DIV_FK" ON "CASEMAN"."DEBT_DIVIDENDS" ("DD_CO_NUMBER", "DD_DIV_NUMBER")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."DD_PK" ON "CASEMAN"."DEBT_DIVIDENDS" ("DD_SEQ")
  ;



  CREATE INDEX "CASEMAN"."DD_PK_PRIM" ON "CASEMAN"."DCS_DATA" ("VERIFICATION_REPORT_ID", "TRANSACTION_NUMBER")
  ;



  CREATE INDEX "CASEMAN"."DEFT_FK1" ON "CASEMAN"."CPT_DEFENDANTS" ("CLAIM_NUMBER")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."DEFT_PK" ON "CASEMAN"."CPT_DEFENDANTS" ("CLAIM_NUMBER", "ID")
  ;



  CREATE INDEX "CASEMAN"."DELETE_CANDIDATES_IX1" ON "CASEMAN"."DELETE_CANDIDATES" ("DELETE_INDEX", "DELETE_FLAG")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."DIVIDEND_PK" ON "CASEMAN"."DIVIDENDS" ("DIV_CO_NUMBER", "DIV_NUMBER")
  ;



  CREATE INDEX "CASEMAN"."DIV_AO" ON "CASEMAN"."AO_CAEO_DIVIDEND" ("AO_CAEO_NUMBER", "ADMIN_COURT_CODE")
  ;



  CREATE INDEX "CASEMAN"."DIV_CO_FK" ON "CASEMAN"."DIVIDENDS" ("DIV_CO_NUMBER")
  ;



  CREATE INDEX "CASEMAN"."DMS_AE_FK_I" ON "CASEMAN"."OBLIGATIONS" ("AE_EVENT_SEQ")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."DMS_EVENTS_PK_I" ON "CASEMAN"."OBLIGATION_EVENTS" ("EVENT_ID")
  ;



  CREATE INDEX "CASEMAN"."DMS_EVENT_FK_I" ON "CASEMAN"."OBLIGATIONS" ("EVENT_SEQ")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."DMS_OBLN_PK_I" ON "CASEMAN"."OBLIGATIONS" ("OBLIGATION_SEQ", "CASE_NUMBER")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."DMS_RULES_PK_I" ON "CASEMAN"."OBLIGATION_RULES" ("OBLIGATION_TYPE", "EVENT_ID")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."DMS_TYPES_PK_I" ON "CASEMAN"."OBLIGATION_TYPES" ("OBLIGATION_TYPE")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."DOC_VAR_PK" ON "CASEMAN"."DOCUMENT_VARIABLES" ("CODE")
  ;



  CREATE INDEX "CASEMAN"."EVENT_DELETION_RULES_IX1" ON "CASEMAN"."EVENT_DELETION_RULES" ("EVENT_TYPE", "STD_EVENT_ID")
  ;



  CREATE INDEX "CASEMAN"."EVENT_EVENT_DATE" ON "CASEMAN"."CASE_EVENTS" ("EVENT_DATE")
  ;



  CREATE INDEX "CASEMAN"."EVENT_FOR_FRGN" ON "CASEMAN"."CASE_EVENTS" ("CASE_NUMBER")
  ;



  CREATE INDEX "CASEMAN"."EVENT_JUDG_FRGN" ON "CASEMAN"."CASE_EVENTS" ("JUDG_SEQ")
  ;



  CREATE INDEX "CASEMAN"."EVENT_OCCURENCE_FRGN" ON "CASEMAN"."CASE_EVENTS" ("STD_EVENT_ID")
  ;



  CREATE INDEX "CASEMAN"."EVENT_OUTPUTS_IX1" ON "CASEMAN"."EVENT_OUTPUTS" ("ORDER_TYPE_ID")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."EVENT_PK" ON "CASEMAN"."CASE_EVENTS" ("EVENT_SEQ")
  ;



  CREATE INDEX "CASEMAN"."EVENT_TASK_XREF_TASK_NO" ON "CASEMAN"."EVENT_TASK_XREF" ("TASK_NUMBER")
  ;



  CREATE INDEX "CASEMAN"."EVENT_VARY_FRGN" ON "CASEMAN"."CASE_EVENTS" ("VARY_SEQ")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."EVT_OUT_PK" ON "CASEMAN"."EVENT_OUTPUTS" ("STD_EVENT_ID", "ORDER_TYPE_ID")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."EVT_TSK_PK" ON "CASEMAN"."EVENT_TASK_XREF" ("EVENT_ID", "TASK_NUMBER", "CASE_TYPE", "EVENT_TYPE_FLAG")
  ;



  CREATE INDEX "CASEMAN"."FEE_FOR" ON "CASEMAN"."FEES_PAID" ("PROCESS_NUMBER")
  ;



  CREATE INDEX "CASEMAN"."GIVEN_ADDRESSES_IX8" ON "CASEMAN"."GIVEN_ADDRESSES" ("CASE_NUMBER", "CASE_PARTY_NO", "PARTY_ROLE_CODE")
  ;



  CREATE INDEX "CASEMAN"."HEARINGS_FX1" ON "CASEMAN"."HEARINGS" ("HRG_TYPE", TRUNC("HRG_DATE"), "HRG_OUTCOME")
  ;



  CREATE INDEX "CASEMAN"."HRG_CASE_FRGN" ON "CASEMAN"."HEARINGS" ("CASE_NUMBER")
  ;



  CREATE INDEX "CASEMAN"."HRG_CRT_FRGN" ON "CASEMAN"."HEARINGS" ("CRT_CODE")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."HRG_PK" ON "CASEMAN"."HEARINGS" ("HRG_SEQ")
  ;



  CREATE INDEX "CASEMAN"."IDX1MV_CMAN_PARTIES" ON "CASEMAN"."MV_CMAN_PARTIES" ("PARTY_ID", "PARTY_ROLE_CODE", "CASE_PARTY_NO")
  ;



  CREATE INDEX "CASEMAN"."IDX1MV_CMAN_PARTY_ADDRESSES" ON "CASEMAN"."MV_CMAN_PARTY_ADDRESSES" ("ADMIN_CRT_CODE", "CASE_NUMBER", "CASE_PARTY_NO")
  ;



  CREATE INDEX "CASEMAN"."IDX2MV_CMAN_PARTY_ADDRESSES" ON "CASEMAN"."MV_CMAN_PARTY_ADDRESSES" ("CASE_NUMBER", "PARTY_ROLE_CODE", "CASE_PARTY_NO")
  ;



  CREATE INDEX "CASEMAN"."IDX2_CMAN_PARTIES" ON "CASEMAN"."MV_CMAN_PARTIES" ("PARTY_ROLE_CODE", "CASE_NUMBER", "CASE_PARTY_NO")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."ITEM_DETS_PK" ON "CASEMAN"."ITEM_DETAILS" ("CODE")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."ITEM_PK" ON "CASEMAN"."SYSTEM_DATA" ("ITEM", "ADMIN_COURT_CODE")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."I_SNAP$_MV_LATEST_WARRANT_" ON "CASEMAN"."MV_LATEST_WARRANT_RETURN_DATE" (SYS_OP_MAP_NONNULL("WARRANT_ID"), SYS_OP_MAP_NONNULL("RETURN_CODE_COURT_CODE"))
  ;



  CREATE INDEX "CASEMAN"."JUDGMENTS_IX6" ON "CASEMAN"."JUDGMENTS" ("CASE_NUMBER", "AGAINST_CASE_PARTY_NO", "AGAINST_PARTY_ROLE_CODE")
  ;



  CREATE INDEX "CASEMAN"."JUDGMENTS_IX7" ON "CASEMAN"."JUDGMENTS" ("CASE_NUMBER", "STATUS")
  ;



  CREATE INDEX "CASEMAN"."JUDG_DATE" ON "CASEMAN"."JUDGMENTS" ("JUDGMENT_DATE")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."JUDG_PK" ON "CASEMAN"."JUDGMENTS" ("JUDG_SEQ")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."LETTER_UK" ON "CASEMAN"."ENFORCEMENT_LETTERS" ("LETTER")
  ;



  CREATE INDEX "CASEMAN"."MCOL_MIG_CLAIM_DATA_IDX1" ON "CASEMAN"."MCOL_MIG_CLAIM_DATA" ("CRED_CODE")
  ;



  CREATE INDEX "CASEMAN"."MCOL_MIG_EVENT_DATA_IDX1" ON "CASEMAN"."MCOL_MIG_EVENT_DATA" ("CASE_NUMBER")
  ;



  CREATE INDEX "CASEMAN"."MCOL_MIG_EVENT_DATA_IDX2" ON "CASEMAN"."MCOL_MIG_EVENT_DATA" ("CRED_CODE")
  ;



  CREATE INDEX "CASEMAN"."MCOL_MIG_PARTY_DATA_IDX1" ON "CASEMAN"."MCOL_MIG_PARTY_DATA" ("CRED_CODE")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."MCOL_MIG_PARTY_DATA_PK" ON "CASEMAN"."MCOL_MIG_PARTY_DATA" ("CASE_NUMBER", "CASE_PARTY_NO", "PARTY_ROLE_CODE")
  ;



  CREATE INDEX "CASEMAN"."MCOL_MIG_WARRANT_DATA_IDX1" ON "CASEMAN"."MCOL_MIG_WARRANT_DATA" ("CRED_CODE")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."MCOL_MIG_WARRANT_DATA_PK" ON "CASEMAN"."MCOL_MIG_WARRANT_DATA" ("CASE_NUMBER", "WARRANT_NUMBER")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."MENU_ITEM_X1" ON "CASEMAN"."MENU_ITEM" ("MENU_ITEM_ID")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."MESSAGE_PK" ON "CASEMAN"."CCB_MESSAGES" ("MSG_ID")
  ;



  CREATE INDEX "CASEMAN"."MOD_FLAG_I" ON "CASEMAN"."EVENT_TASK_XREF" ("MODIFIED_FLAG")
  ;



  CREATE INDEX "CASEMAN"."NUK_NWD" ON "CASEMAN"."NON_WORKING_DAYS" ("NON_WORKING_DATE", "ERROR_INDICATOR")
  ;



  CREATE INDEX "CASEMAN"."OBLIGATIONS_IX4" ON "CASEMAN"."OBLIGATIONS" ("OBLIGATION_TYPE")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."ORDER_TYPE_PK" ON "CASEMAN"."ORDER_TYPES" ("ORDER_ID")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."OSW_PK" ON "CASEMAN"."OSW" ("ID", "ADMIN_COURT_CODE")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."OUTPUT_DETAILS_PK" ON "CASEMAN"."OUTPUT_DETAILS" ("OD_SEQ")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."OUTPUT_DETAILS_UK" ON "CASEMAN"."OUTPUT_DETAILS" ("ORDER_TYPE_ID", "LAYOUT_GROUP", "CODE")
  ;



  CREATE INDEX "CASEMAN"."PAYABLE_ORDER_ITEMS_IX1" ON "CASEMAN"."PAYABLE_ORDER_ITEMS" ("TRANSACTION_NUMBER", "ADMIN_COURT_CODE")
  ;



  CREATE INDEX "CASEMAN"."PAYMENTS_FX1" ON "CASEMAN"."PAYMENTS" (NVL("ENFORCEMENT_PARENT",'NOPARENT'))
  ;



  CREATE INDEX "CASEMAN"."PAYMENTS_IX3" ON "CASEMAN"."PAYMENTS" ("ENFORCEMENT_PARENT", "PAYOUT_DATE", "PASSTHROUGH", "RD_DATE", NVL("ERROR_INDICATOR",'N'))
  ;



  CREATE INDEX "CASEMAN"."PAY_ALD_FK" ON "CASEMAN"."PAYMENTS" ("ALD_DEBT_SEQ")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."PAY_PK" ON "CASEMAN"."PAYMENTS" ("TRANSACTION_NUMBER", "ADMIN_COURT_CODE")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."PER_DETAILS_PK" ON "CASEMAN"."PER_DETAILS" ("DETAIL_CODE")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."PER_DETAILS_UK" ON "CASEMAN"."PER_DETAILS" ("ORDER_NUMBER")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."PK_CANDIDATES" ON "CASEMAN"."DELETE_CANDIDATES" ("IDENTIFIER", "TYPE")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."PK_ECHR_DETAILS" ON "CASEMAN"."ECHR_DETAILS" ("EVENT_SEQ")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."PK_MCOL_MIG_JUDGMENT_DATA" ON "CASEMAN"."MCOL_MIG_JUDGMENT_DATA" ("CASE_NUMBER", "AGAINST_CASE_PARTY_NO")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."PK_NWD" ON "CASEMAN"."NON_WORKING_DAYS" ("NON_WD_SEQ")
  ;



  CREATE INDEX "CASEMAN"."PMT_RELEASE_IND" ON "CASEMAN"."PAYMENTS" ("RELEASE_DATE")
  ;



  CREATE INDEX "CASEMAN"."PMT_SUBJECT_IND" ON "CASEMAN"."PAYMENTS" ("PAYMENT_FOR", "ISSUING_COURT")
  ;



  CREATE INDEX "CASEMAN"."PMT_VER_IND" ON "CASEMAN"."PAYMENTS" ("VERIFICATION_REPORT_ID")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."POITEM" ON "CASEMAN"."PAYABLE_ORDER_ITEMS" ("TRANSACTION_NUMBER", "PO_NUMBER", "ADMIN_COURT_CODE")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."PONUM_PK" ON "CASEMAN"."PAYABLE_ORDERS" ("PO_NUMBER", "ADMIN_COURT_CODE")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."PRE_PK" ON "CASEMAN"."PRE_REQ_EVENTS" ("STD_EVENT_ID", "PRE_REQ_EVENT_ID1")
  ;



  CREATE INDEX "CASEMAN"."PRINTERS_CRT_ID" ON "CASEMAN"."PRINTERS" ("COURT_ID")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."PRINTERS_PK" ON "CASEMAN"."PRINTERS" ("PRINTER_ID")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."PRINT_CLAIMS_PK" ON "CASEMAN"."CPT_PRINT_CLAIMS" ("ISSUE_DATE", "REC_NO")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."PRINT_TYPES_PK" ON "CASEMAN"."PRINTER_TYPES" ("MODEL")
  ;



  CREATE INDEX "CASEMAN"."PRM_FK_FRGN" ON "CASEMAN"."REPORT_PARAMETERS" ("REPORT_NAME")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."PRM_ORD_UNIQ" ON "CASEMAN"."REPORT_PARAMETERS" ("REPORT_NAME", "ORDERING_SEQUENCE")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."PRM_PK" ON "CASEMAN"."REPORT_PARAMETERS" ("REPORT_NAME", "PARAMETER_NAME")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."PTY_PK" ON "CASEMAN"."CODED_PARTIES" ("CODE", "ADMIN_COURT_CODE")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."REPORT_MAP_PK" ON "CASEMAN"."REPORT_MAP" ("LEGACY_PATH", "FILE_NAME")
  ;



  CREATE INDEX "CASEMAN"."REPORT_QUEUE_IDX4" ON "CASEMAN"."REPORT_QUEUE" ("STORAGE_DURATION", "CREATED_DATE", "ID")
  ;



  CREATE INDEX "CASEMAN"."REPORT_QUEUE_IDX5" ON "CASEMAN"."REPORT_QUEUE" ("STORAGE_DURATION", "TYPE", "DOCUMENT_ID", "ID")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."REPORT_QUEUE_PK" ON "CASEMAN"."REPORT_QUEUE" ("ID")
  ;



  CREATE INDEX "CASEMAN"."REPORT_REPRINTS_XREF_IX4" ON "CASEMAN"."REPORT_REPRINTS_XREF" ("USERNAME", "REPORT_REPRINTS_ID")
  ;



  CREATE INDEX "CASEMAN"."REPRINTS_IX1" ON "CASEMAN"."REPRINTS" ("CASE_NUMBER")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."REPRINTS_PK" ON "CASEMAN"."REPRINTS" ("ID")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."REP_PK" ON "CASEMAN"."REPORTS" ("REPORT_NAME")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."REP_REP_XREF_PK" ON "CASEMAN"."REPORT_REPRINTS_XREF" ("REPRINTS_ID", "REPORT_REPRINTS_ID", "USERNAME")
  ;



  CREATE INDEX "CASEMAN"."RETURN_CODES_IX3" ON "CASEMAN"."RETURN_CODES" ("RETURN_CODE", "ADMIN_COURT_CODE", "RETURN_TYPE")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."RETURN_CODES_PK" ON "CASEMAN"."RETURN_CODES" ("RETURN_CODE", "ADMIN_COURT_CODE")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."SDV_PK" ON "CASEMAN"."SUB_DETAIL_VARIABLES" ("SDV_SEQ")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."SEC_PK" ON "CASEMAN"."SECTIONS" ("SECTION_NAME", "ADMIN_COURT_CODE")
  ;



  CREATE INDEX "CASEMAN"."STAT_ISSUE_DATE_IDX" ON "CASEMAN"."CPT_STATISTICS" ("ISSUE_DATE")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."STD_PK" ON "CASEMAN"."STANDARD_EVENTS" ("EVENT_ID")
  ;



  CREATE INDEX "CASEMAN"."SUB_DETAIL_VARIABLES_IX1" ON "CASEMAN"."SUB_DETAIL_VARIABLES" ("VARIABLE_CODE")
  ;



  CREATE INDEX "CASEMAN"."SUB_DETAIL_VARIABLES_IX2" ON "CASEMAN"."SUB_DETAIL_VARIABLES" ("OD_SEQ")
  ;



  CREATE INDEX "CASEMAN"."SUPS_AMENDMENTS_IX4" ON "CASEMAN"."SUPS_AMENDMENTS" ("PK01", "TABLE_NAME")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."SYS_C00416036" ON "CASEMAN"."CO_STATE" ("CO_NUMBER")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."SYS_C00416038" ON "CASEMAN"."CASE_STATE" ("CASE_NUMBER")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."SYS_C00417937" ON "CASEMAN"."CDR_MCOL_EVENT_MAPPING" ("STD_EVENT_ID")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."SYS_C00417939" ON "CASEMAN"."CDR_MCOL_STATUS_MAPPING" ("CLAIM_STATUS")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."SYS_C00417959" ON "CASEMAN"."CPT_LIBERATA_TOTAL_FEES" ("ISSUE_DATE")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."SYS_C00417998" ON "CASEMAN"."MCOL_MIG_CLAIM_DATA" ("CASE_NUMBER")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."SYS_C00418064" ON "CASEMAN"."TMP_DPA_PARTIES_CACHE" ("PARTY_ID") ;



  CREATE UNIQUE INDEX "CASEMAN"."SYS_C00418066" ON "CASEMAN"."TMP_MCOL_MIG_CRED_CLAIMS" ("CASE_NUMBER")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."SYS_C00418068" ON "CASEMAN"."TMP_MCOL_MIG_EVENT_MAPPING" ("STD_EVENT_ID")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."SYS_C00418073" ON "CASEMAN"."TMP_MCOL_MIG_INFO" ("CRED_CODE")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."SYS_C00418075" ON "CASEMAN"."TMP_MCOL_MIG_STATUS_MAPPING" ("CLAIM_STATUS")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."SYS_C00418144" ON "CASEMAN"."DELETE_EXCEPTION_REASONS" ("EXCEPTION_REASON")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."SYS_C00418160" ON "CASEMAN"."EVENT_DELETION_RULES" ("STD_EVENT_ID", "EVENT_TYPE")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."SYS_C00432371" ON "CASEMAN"."WFT_EXPORTS" ("FILENAME")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."TAL_PK" ON "CASEMAN"."TASK_ALLOCATIONS" ("TASK_NUMBER", "SECTION_NAME", "START_DATE", "ADMIN_COURT_CODE")
  ;



  CREATE INDEX "CASEMAN"."TASK_ALLOCATION_SECT_NAME" ON "CASEMAN"."TASK_ALLOCATIONS" ("SECTION_NAME", "ADMIN_COURT_CODE")
  ;



  CREATE INDEX "CASEMAN"."TASK_COUNTS_IX5" ON "CASEMAN"."TASK_COUNTS" ("AGE_CATEGORY")
  ;



  CREATE INDEX "CASEMAN"."TASK_COUNTS_IX6" ON "CASEMAN"."TASK_COUNTS" ("CREATING_COURT", "TASK_DATE")
  ;



  CREATE INDEX "CASEMAN"."TASK_DATE_I" ON "CASEMAN"."TASK_COUNTS" ("TASK_DATE")
  ;



  CREATE INDEX "CASEMAN"."TASK_TASK_TYPE" ON "CASEMAN"."TASKS" ("TASK_TYPE")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."TMP_MCOL_MIG_FAILURES_PK" ON "CASEMAN"."TMP_MCOL_MIG_FAILURES" ("CASE_NUMBER", "FAILURE_REASON")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."TMP_RTL_CHARACTER_MAP_PK" ON "CASEMAN"."TMP_RTL_CHARACTER_MAP" ("ASCII_CODE")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."TRAN_CP_I" ON "CASEMAN"."TRAN_CODED_PARTIES" ("CODE")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."TRAN_ITEM_I" ON "CASEMAN"."TRAN_SYSTEM_DATA" ("ITEM")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."TRAN_PER_DETS" ON "CASEMAN"."TRAN_PER_DETAILS" ("DETAIL_CODE")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."TSKCNT_UK" ON "CASEMAN"."TASK_COUNTS" ("TASK_NUMBER", "TASK_DATE", "AGE_CATEGORY", "ADMIN_COURT_CODE", "CREATING_COURT", "CREATING_SECTION")
  ;



  CREATE INDEX "CASEMAN"."TSK_MOD_I" ON "CASEMAN"."TASKS" ("MODIFIED_FLAG")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."TSK_PK" ON "CASEMAN"."TASKS" ("TASK_NUMBER")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."TSK_TYP_PK" ON "CASEMAN"."TASK_TYPES" ("TASK_TYPE")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."UNIX_OP_PK" ON "CASEMAN"."UNIX_OUTPUT" ("USERNAME", "LINE_NO")
  ;



  CREATE INDEX "CASEMAN"."USERS_DEFAULT_CRT" ON "CASEMAN"."USERS" ("DEFAULT_COURT")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."USERS_PK" ON "CASEMAN"."USERS" ("USERNAME")
  ;



  CREATE INDEX "CASEMAN"."USERS_PRINTERS_IX1" ON "CASEMAN"."USERS_PRINTERS" ("PRINTER_ID")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."USER_INFO_CE_PK" ON "CASEMAN"."USER_INFO_CASE_EVENTS" ("USER_ID")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."USER_PRINT_PK" ON "CASEMAN"."USERS_PRINTERS" ("USERNAME", "PRINTER_ID")
  ;



  CREATE INDEX "CASEMAN"."VARY_PAYABLE_FRGN" ON "CASEMAN"."VARIATIONS" ("JUDG_SEQ")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."VARY_PK" ON "CASEMAN"."VARIATIONS" ("VARY_SEQ")
  ;



  CREATE INDEX "CASEMAN"."WARRANTS_IX15" ON "CASEMAN"."WARRANTS" ("CASE_NUMBER", "DEF1_CASE_PARTY_NO", "DEF1_PARTY_ROLE_CODE")
  ;



  CREATE INDEX "CASEMAN"."WARRANTS_IX16" ON "CASEMAN"."WARRANTS" ("CASE_NUMBER", "DEF2_CASE_PARTY_NO", "DEF2_PARTY_ROLE_CODE")
  ;



  CREATE INDEX "CASEMAN"."WARRANTS_IX17" ON "CASEMAN"."WARRANTS" ("CASE_NUMBER", "REP_CASE_PARTY_NO", "REP_PARTY_ROLE_CODE")
  ;



  CREATE INDEX "CASEMAN"."WARRANTS_IX18" ON "CASEMAN"."WARRANTS" ("CASE_NUMBER", "WARRANT_ID", "DEFENDANT1", "DEFENDANT2")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."WARRANTS_PK" ON "CASEMAN"."WARRANTS" ("WARRANT_ID")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."WARRANTS_UK" ON "CASEMAN"."WARRANTS" ("WARRANT_NUMBER", "ISSUED_BY", "CURRENTLY_OWNED_BY", "LOCAL_WARRANT_NUMBER", "CASE_NUMBER")
  ;



  CREATE INDEX "CASEMAN"."WARRANT_RETURNS_IX5" ON "CASEMAN"."WARRANT_RETURNS" ("RETURN_CODE", "RETURN_CODE_COURT_CODE")
  ;



  CREATE INDEX "CASEMAN"."WARRANT_RETURNS_IX6" ON "CASEMAN"."WARRANT_RETURNS" ("WARRANT_ID", NVL("DEFENDANT_ID",1), "ERROR_INDICATOR", "RETURN_CODE", "RETURN_CODE_COURT_CODE")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."WFE_PK_1" ON "CASEMAN"."WFT_EXCLUSIONS" ("WFE_WFT_CASE_NUMBER", "WFE_WFT_ID", "WFE_EXCLUSION_DATE")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."WFT_PK_1" ON "CASEMAN"."WINDOW_FOR_TRIAL" ("WFT_CASE_NUMBER", "WFT_ID")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."WORKGROUP_ITEM_X1" ON "CASEMAN"."MENU_ITEM_GROUP" ("MENU_ITEM_ID", "CONTEXT", "USERS_ROLE")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."XAK1COURTS" ON "CASEMAN"."COURTS" ("ID")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."XAK1DCA_USER" ON "CASEMAN"."DCA_USER" ("USER_SHORT_NAME")
  ;



  CREATE INDEX "CASEMAN"."XIE1AE_APPLICATIONS" ON "CASEMAN"."AE_APPLICATIONS" ("CASE_NUMBER")
  ;



  CREATE INDEX "CASEMAN"."XIE1ASYNC_COMMAND" ON "CASEMAN"."ASYNC_COMMAND" (TO_CHAR("CREATED_DATE",'YYYY-MM-DD'))
  ;



  CREATE INDEX "CASEMAN"."XIE1CANDIDATE_DIVIDEND_PAYMENT" ON "CASEMAN"."CANDIDATE_DIVIDEND_PAYMENTS" ("ADMIN_COURT_CODE")
  ;



  CREATE INDEX "CASEMAN"."XIE1CCBC_REF_CODES" ON "CASEMAN"."CCBC_REF_CODES" ("RV_DOMAIN")
  ;



  CREATE INDEX "CASEMAN"."XIE1CHANGED_EVENTS" ON "CASEMAN"."CHANGED_EVENTS" ("STD_EVENT_ID")
  ;



  CREATE INDEX "CASEMAN"."XIE1CMCS_CASES" ON "CASEMAN"."CMCS_CASES" ("TRANS_CRT_CODE")
  ;



  CREATE INDEX "CASEMAN"."XIE1CONSOLIDATED_ORDERS" ON "CASEMAN"."CONSOLIDATED_ORDERS" ("OLD_NUMBER")
  ;



  CREATE INDEX "CASEMAN"."XIE1CO_EVENTS" ON "CASEMAN"."CO_EVENTS" ("CO_NUMBER")
  ;



  CREATE INDEX "CASEMAN"."XIE1DCS" ON "CASEMAN"."DCS" ("ADMIN_COURT_CODE", "REPORT_ID")
  ;



  CREATE INDEX "CASEMAN"."XIE1DEBT_DIVIDENDS" ON "CASEMAN"."DEBT_DIVIDENDS" ("DD_PO_ADMIN_COURT_CODE")
  ;



  CREATE INDEX "CASEMAN"."XIE1ENFORCEMENT_LETTERS" ON "CASEMAN"."ENFORCEMENT_LETTERS" ("YEAR_VALUE")
  ;



  CREATE INDEX "CASEMAN"."XIE1GIVEN_ADDRESSES" ON "CASEMAN"."GIVEN_ADDRESSES" ("ADDRESS_LINE1")
  ;



  CREATE INDEX "CASEMAN"."XIE1HEARINGS" ON "CASEMAN"."HEARINGS" ("CO_NUMBER")
  ;



  CREATE INDEX "CASEMAN"."XIE1OBLIGATIONS" ON "CASEMAN"."OBLIGATIONS" ("CASE_NUMBER", "AE_EVENT_SEQ", "DELETE_FLAG")
  ;



  CREATE INDEX "CASEMAN"."XIE1ORDER_TYPES" ON "CASEMAN"."ORDER_TYPES" ("MODULE_NAME")
  ;



  CREATE INDEX "CASEMAN"."XIE1REPORT_OUTPUT" ON "CASEMAN"."REPORT_OUTPUT" ("EVENT_SEQ", "REPORT_ID", "ORDER_ID")
  ;



  CREATE INDEX "CASEMAN"."XIE1REPORT_QUEUE" ON "CASEMAN"."REPORT_QUEUE" ("ID", "DOCUMENT_ID")
  ;



  CREATE INDEX "CASEMAN"."XIE1RETURN_CODES" ON "CASEMAN"."RETURN_CODES" ("ADMIN_COURT_CODE", "CURRENT_RETURN", "USER_LIST")
  ;



  CREATE INDEX "CASEMAN"."XIE1STANDARD_EVENTS" ON "CASEMAN"."STANDARD_EVENTS" ("CATEGORY")
  ;



  CREATE INDEX "CASEMAN"."XIE1SYSTEM_DATA" ON "CASEMAN"."SYSTEM_DATA" (SUBSTR("ITEM",LENGTH("ITEM")-1,2))
  ;



  CREATE INDEX "CASEMAN"."XIE1TEXT_ITEMS" ON "CASEMAN"."TEXT_ITEMS" ("TEXT_CASE_NUMBER")
  ;



  CREATE INDEX "CASEMAN"."XIE1TMP_REP" ON "CASEMAN"."TMP_REP" ("JOB_NUMBER")
  ;



  CREATE INDEX "CASEMAN"."XIE1WARRANTS" ON "CASEMAN"."WARRANTS" ("CO_NUMBER")
  ;



  CREATE INDEX "CASEMAN"."XIE1WARRANT_RETURNS" ON "CASEMAN"."WARRANT_RETURNS" ("WARRANT_ID", "ERROR_INDICATOR", TRUNC("WARRANT_RETURN_DATE"))
  ;



  CREATE INDEX "CASEMAN"."XIE2CASES" ON "CASEMAN"."CASES" ("ADMIN_CRT_CODE")
  ;



  CREATE INDEX "CASEMAN"."XIE2CMCS_CASES" ON "CASEMAN"."CMCS_CASES" ("CASE_NUMBER")
  ;



  CREATE INDEX "CASEMAN"."XIE2COURTS" ON "CASEMAN"."COURTS" ("CASEMAN_INSERVICE")
  ;



  CREATE INDEX "CASEMAN"."XIE2SUPS_AMENDMENTS" ON "CASEMAN"."SUPS_AMENDMENTS" ("COURT_ID", "TABLE_NAME", "COLUMN_NAME", "DATE_OF_CHANGE")
  ;



  CREATE INDEX "CASEMAN"."XIE2WARRANTS" ON "CASEMAN"."WARRANTS" ("BAILIFF_IDENTIFIER")
  ;



  CREATE INDEX "CASEMAN"."XIE3SUPS_AMENDMENTS" ON "CASEMAN"."SUPS_AMENDMENTS" ("COURT_ID", "TABLE_NAME", "USER_ID", "PROCESS_ID", "PK01", "PK02")
  ;



  CREATE INDEX "CASEMAN"."XIE3WARRANTS" ON "CASEMAN"."WARRANTS" ("WARRANT_ISSUE_DATE")
  ;



  CREATE INDEX "CASEMAN"."XIE4WARRANTS" ON "CASEMAN"."WARRANTS" ("LOCAL_WARRANT_NUMBER")
  ;



  CREATE INDEX "CASEMAN"."XIE6PAYMENTS" ON "CASEMAN"."PAYMENTS" ("SUBJECT_NO", "PAYMENT_FOR")
  ;



  CREATE INDEX "CASEMAN"."XIE6WARRANTS" ON "CASEMAN"."WARRANTS" ("CODED_PARTY_REP_CODE", "WARRANT_ID")
  ;



  CREATE INDEX "CASEMAN"."XIE7PAYMENTS" ON "CASEMAN"."PAYMENTS" ("PAYOUT_DATE", "SUBJECT_NO", "PAYMENT_FOR")
  ;



  CREATE INDEX "CASEMAN"."XIE8PAYMENTS" ON "CASEMAN"."PAYMENTS" ("SUBJECT_NO", "PAYMENT_FOR", "ENFORCEMENT_COURT_CODE")
  ;



  CREATE INDEX "CASEMAN"."XIE9PAYMENTS" ON "CASEMAN"."PAYMENTS" ("ADMIN_COURT_CODE", "DATE_ENTERED")
  ;



  CREATE INDEX "CASEMAN"."XIE9WP_OUTPUT" ON "CASEMAN"."WP_OUTPUT" ("VINCENT_CMAN"."XMLSOURCE_NUMCHECK"("XMLSOURCE"), NVL("FINAL_IND",'N'))
  ;



  CREATE INDEX "CASEMAN"."XIF11CASE_EVENTS" ON "CASEMAN"."CASE_EVENTS" ("CRT_CODE")
  ;



  CREATE INDEX "CASEMAN"."XIF11PAYMENTS" ON "CASEMAN"."PAYMENTS" ("RELATED_TRANSACTION_NUMBER", "RELATED_ADMIN_COURT_CODE")
  ;



  CREATE INDEX "CASEMAN"."XIF12CASE_EVENTS" ON "CASEMAN"."CASE_EVENTS" ("CASE_NUMBER", "PARTY_ROLE_CODE", "CASE_PARTY_NO")
  ;



  CREATE INDEX "CASEMAN"."XIF12PAYMENTS" ON "CASEMAN"."PAYMENTS" ("ENFORCEMENT_COURT_CODE")
  ;



  CREATE INDEX "CASEMAN"."XIF13CASE_EVENTS" ON "CASEMAN"."CASE_EVENTS" ("CREATING_SECTION", "CREATING_COURT")
  ;



  CREATE INDEX "CASEMAN"."XIF1AMR_REPORTS" ON "CASEMAN"."AMR_REPORTS" ("ADMIN_COURT_CODE")
  ;



  CREATE INDEX "CASEMAN"."XIF1AO_CAEO" ON "CASEMAN"."AO_CAEO" ("ADMIN_COURT_CODE")
  ;



  CREATE INDEX "CASEMAN"."XIF1CASE_EVENT_INSTIGATORS" ON "CASEMAN"."CASE_EVENT_INSTIGATORS" ("EVENT_SEQ")
  ;



  CREATE INDEX "CASEMAN"."XIF1CASE_PARTY_ROLES" ON "CASEMAN"."CASE_PARTY_ROLES" ("CASE_NUMBER")
  ;



  CREATE INDEX "CASEMAN"."XIF1CMCS_DEFENDANTS" ON "CASEMAN"."CMCS_DEFENDANTS" ("TRANS_SEQ")
  ;



  CREATE INDEX "CASEMAN"."XIF1CMCS_DEFENDANT_ADDRESSES" ON "CASEMAN"."CMCS_DEFENDANT_ADDRESSES" ("TRANS_SEQ", "DEFT_CASE_NUMBER", "DEFT_ID")
  ;



  CREATE INDEX "CASEMAN"."XIF1CONSOLIDATED_ORDERS" ON "CASEMAN"."CONSOLIDATED_ORDERS" ("ADMIN_COURT_CODE")
  ;



  CREATE INDEX "CASEMAN"."XIF1CO_CASE_EVENTS" ON "CASEMAN"."CO_CASE_EVENTS" ("STD_EVENT_ID")
  ;



  CREATE INDEX "CASEMAN"."XIF1CO_REPRINTS" ON "CASEMAN"."CO_REPRINTS" ("ADMIN_COURT_CODE")
  ;



  CREATE INDEX "CASEMAN"."XIF1CPR_TO_CPR_RELATIONSHIP" ON "CASEMAN"."CPR_TO_CPR_RELATIONSHIP" ("CPR_A_CASE_NUMBER", "CPR_A_PARTY_ROLE_CODE", "CPR_A_CASE_PARTY_NO")
  ;



  CREATE INDEX "CASEMAN"."XIF1DCS" ON "CASEMAN"."DCS" ("ADMIN_COURT_CODE")
  ;



  CREATE INDEX "CASEMAN"."XIF1DJPRINT_TEMP" ON "CASEMAN"."DJPRINT_TEMP" ("ID")
  ;



  CREATE INDEX "CASEMAN"."XIF1ECHR_ARTICLE_PROTOCOL" ON "CASEMAN"."ECHR_ARTICLE_PROTOCOL" ("EVENT_SEQ")
  ;



  CREATE INDEX "CASEMAN"."XIF1FTP_QUEUE" ON "CASEMAN"."FTP_QUEUE" ("DOCUMENT_ID")
  ;



  CREATE INDEX "CASEMAN"."XIF1GIVEN_ADDRESSES" ON "CASEMAN"."GIVEN_ADDRESSES" ("PARTY_ID")
  ;



  CREATE INDEX "CASEMAN"."XIF1INFAVOUR_PARTIES" ON "CASEMAN"."INFAVOUR_PARTIES" ("JUDG_SEQ")
  ;



  CREATE INDEX "CASEMAN"."XIF1JUDGES" ON "CASEMAN"."JUDGES" ("COURT_CODE")
  ;



  CREATE INDEX "CASEMAN"."XIF1JUDGMENTS" ON "CASEMAN"."JUDGMENTS" ("CASE_NUMBER", "AGAINST_PARTY_ROLE_CODE", "AGAINST_CASE_PARTY_NO")
  ;



  CREATE INDEX "CASEMAN"."XIF1LOAD_CASES" ON "CASEMAN"."LOAD_CASES" ("REJECT_CODE")
  ;



  CREATE INDEX "CASEMAN"."XIF1LOAD_JUDGMENTS" ON "CASEMAN"."LOAD_JUDGMENTS" ("REJECT_CODE")
  ;



  CREATE INDEX "CASEMAN"."XIF1LOAD_PAID_WO_DETAILS" ON "CASEMAN"."LOAD_PAID_WO_DETAILS" ("REJECT_CODE")
  ;



  CREATE INDEX "CASEMAN"."XIF1LOAD_WARRANTS" ON "CASEMAN"."LOAD_WARRANTS" ("REJECT_CODE")
  ;



  CREATE INDEX "CASEMAN"."XIF1LOCALCOPS_TEMP" ON "CASEMAN"."LOCALCOPS_TEMP" ("ID")
  ;



  CREATE INDEX "CASEMAN"."XIF1MCOL_DATA" ON "CASEMAN"."MCOL_DATA" ("REJECT_CODE")
  ;



  CREATE INDEX "CASEMAN"."XIF1MENU_ITEM" ON "CASEMAN"."MENU_ITEM" ("PARENT_MENU_ITEM_ID")
  ;



  CREATE INDEX "CASEMAN"."XIF1NATIONAL_CODED_PARTIES" ON "CASEMAN"."NATIONAL_CODED_PARTIES" ("CODE", "ADMIN_COURT_CODE")
  ;



  CREATE INDEX "CASEMAN"."XIF1NON_WORKING_DAYS_EXCEPTION" ON "CASEMAN"."NON_WORKING_DAYS_EXCEPTIONS" ("NON_WD_SEQ")
  ;



  CREATE INDEX "CASEMAN"."XIF1PARTIES" ON "CASEMAN"."PARTIES" ("ETHNIC_ORIGIN_CODE")
  ;



  CREATE INDEX "CASEMAN"."XIF1PARTY_TO_PARTY_RELATIONSHI" ON "CASEMAN"."PARTY_TO_PARTY_RELATIONSHIP" ("PARTY_B_ID")
  ;



  CREATE INDEX "CASEMAN"."XIF1PAYABLE_ORDERS" ON "CASEMAN"."PAYABLE_ORDERS" ("ADMIN_COURT_CODE")
  ;



  CREATE INDEX "CASEMAN"."XIF1PAYABLE_ORDER_HEADER" ON "CASEMAN"."PAYABLE_ORDER_HEADER" ("ADMIN_COURT_CODE")
  ;



  CREATE INDEX "CASEMAN"."XIF1PAYMENT_SUMMARY" ON "CASEMAN"."PAYMENT_SUMMARY" ("ADMIN_COURT_CODE")
  ;



  CREATE INDEX "CASEMAN"."XIF1PL_RECORDLEVEL_PREVAL_STAT" ON "CASEMAN"."PL_RECORDLEVEL_PREVAL_STATUS" ("FILE_NAME")
  ;



  CREATE INDEX "CASEMAN"."XIF1REJECT_CASES" ON "CASEMAN"."REJECT_CASES" ("REJECT_CODE")
  ;



  CREATE INDEX "CASEMAN"."XIF1REJECT_JUDGMENTS" ON "CASEMAN"."REJECT_JUDGMENTS" ("REJECT_CODE")
  ;



  CREATE INDEX "CASEMAN"."XIF1REJECT_PAID_WO_DETAILS" ON "CASEMAN"."REJECT_PAID_WO_DETAILS" ("REJECT_CODE")
  ;



  CREATE INDEX "CASEMAN"."XIF1REJECT_WARRANTS" ON "CASEMAN"."REJECT_WARRANTS" ("REJECT_CODE")
  ;



  CREATE INDEX "CASEMAN"."XIF1REPORT_DATA" ON "CASEMAN"."REPORT_DATA" ("ADMIN_COURT_CODE")
  ;



  CREATE INDEX "CASEMAN"."XIF1REPORT_MAP" ON "CASEMAN"."REPORT_MAP" ("REPORT_QUEUE_ID")
  ;



  CREATE INDEX "CASEMAN"."XIF1REPORT_OUTPUT" ON "CASEMAN"."REPORT_OUTPUT" ("CO_EVENT_SEQ")
  ;



  CREATE INDEX "CASEMAN"."XIF1REPORT_QUEUE" ON "CASEMAN"."REPORT_QUEUE" ("DOCUMENT_ID")
  ;



  CREATE INDEX "CASEMAN"."XIF1REPORT_REPRINTS" ON "CASEMAN"."REPORT_REPRINTS" ("FW_REPORT_ID")
  ;



  CREATE INDEX "CASEMAN"."XIF1REPRINT_TEXT_ITEMS" ON "CASEMAN"."REPRINT_TEXT_ITEMS" ("EVENT_SEQ")
  ;



  CREATE INDEX "CASEMAN"."XIF1RETURN_CODES" ON "CASEMAN"."RETURN_CODES" ("ADMIN_COURT_CODE")
  ;



  CREATE INDEX "CASEMAN"."XIF1SECTIONS" ON "CASEMAN"."SECTIONS" ("ADMIN_COURT_CODE")
  ;



  CREATE INDEX "CASEMAN"."XIF1SOD_LOCK" ON "CASEMAN"."SOD_LOCK" ("ADMIN_COURT_CODE")
  ;



  CREATE INDEX "CASEMAN"."XIF1SUPS_AMENDMENTS" ON "CASEMAN"."SUPS_AMENDMENTS" ("PK01", "PK02", "PK03", "PK04", "PK05", "PK06")
  ;



  CREATE INDEX "CASEMAN"."XIF1SYSTEM_DATA" ON "CASEMAN"."SYSTEM_DATA" ("ADMIN_COURT_CODE")
  ;



  CREATE INDEX "CASEMAN"."XIF1TAPES" ON "CASEMAN"."TAPES" ("CUST_CODE")
  ;



  CREATE INDEX "CASEMAN"."XIF1TAPE_FILES" ON "CASEMAN"."TAPE_FILES" ("SEQNO")
  ;



  CREATE INDEX "CASEMAN"."XIF1TEMP" ON "CASEMAN"."TEMP" ("ID")
  ;



  CREATE INDEX "CASEMAN"."XIF1VALID_VALUES" ON "CASEMAN"."VALID_VALUES" ("VALS_DETAILS_CODE")
  ;



  CREATE INDEX "CASEMAN"."XIF1WARRANT_RETURNS" ON "CASEMAN"."WARRANT_RETURNS" ("WARRANT_ID")
  ;



  CREATE INDEX "CASEMAN"."XIF1WORK_WF" ON "CASEMAN"."WORK_WF" ("ADMIN_COURT_CODE")
  ;



  CREATE INDEX "CASEMAN"."XIF2CASE_EVENT_INSTIGATORS" ON "CASEMAN"."CASE_EVENT_INSTIGATORS" ("CASE_NUMBER", "CASE_PARTY_NO", "PARTY_ROLE_CODE")
  ;



  CREATE INDEX "CASEMAN"."XIF2CASE_PARTY_ROLES" ON "CASEMAN"."CASE_PARTY_ROLES" ("PARTY_ID")
  ;



  CREATE INDEX "CASEMAN"."XIF2CONSOLIDATED_ORDERS" ON "CASEMAN"."CONSOLIDATED_ORDERS" ("COURT_OF_TRANSFER")
  ;



  CREATE INDEX "CASEMAN"."XIF2CO_CASE_EVENTS" ON "CASEMAN"."CO_CASE_EVENTS" ("ADMIN_COURT_CODE")
  ;



  CREATE INDEX "CASEMAN"."XIF2CO_EVENT_VALIDATIONS" ON "CASEMAN"."CO_EVENT_VALIDATIONS" ("PRE_REQ_EVENT1")
  ;



  CREATE INDEX "CASEMAN"."XIF2CPR_TO_CPR_RELATIONSHIP" ON "CASEMAN"."CPR_TO_CPR_RELATIONSHIP" ("CPR_B_CASE_NUMBER", "CPR_B_PARTY_ROLE_CODE", "CPR_B_CASE_PARTY_NO")
  ;



  CREATE INDEX "CASEMAN"."XIF2EVENT_TASK_XREF" ON "CASEMAN"."EVENT_TASK_XREF" ("EVENT_ID")
  ;



  CREATE INDEX "CASEMAN"."XIF2GIVEN_ADDRESSES" ON "CASEMAN"."GIVEN_ADDRESSES" ("CASE_NUMBER", "PARTY_ROLE_CODE", "CASE_PARTY_NO")
  ;



  CREATE INDEX "CASEMAN"."XIF2INFAVOUR_PARTIES" ON "CASEMAN"."INFAVOUR_PARTIES" ("CASE_NUMBER", "CASE_PARTY_NO", "PARTY_ROLE_CODE")
  ;



  CREATE INDEX "CASEMAN"."XIF2JUDGMENTS" ON "CASEMAN"."JUDGMENTS" ("JUDGMENT_COURT_CODE")
  ;



  CREATE INDEX "CASEMAN"."XIF2NON_WORKING_DAYS_EXCEPTION" ON "CASEMAN"."NON_WORKING_DAYS_EXCEPTIONS" ("COURT_CODE")
  ;



  CREATE INDEX "CASEMAN"."XIF2OBLIGATION_RULES" ON "CASEMAN"."OBLIGATION_RULES" ("EVENT_ID")
  ;



  CREATE INDEX "CASEMAN"."XIF2PARTIES" ON "CASEMAN"."PARTIES" ("PARTY_TYPE_CODE")
  ;



  CREATE INDEX "CASEMAN"."XIF2PARTY_TO_PARTY_RELATIONSHI" ON "CASEMAN"."PARTY_TO_PARTY_RELATIONSHIP" ("PARTY_A_ID")
  ;



  CREATE INDEX "CASEMAN"."XIF2PL_FILELEVEL_PREVALIDATION" ON "CASEMAN"."PL_FILELEVEL_PREVAL_STATUS" ("FILE_TYPE")
  ;



  CREATE INDEX "CASEMAN"."XIF2PRE_REQ_EVENTS" ON "CASEMAN"."PRE_REQ_EVENTS" ("STD_EVENT_ID")
  ;



  CREATE INDEX "CASEMAN"."XIF2PRINTERS" ON "CASEMAN"."PRINTERS" ("MODEL")
  ;



  CREATE INDEX "CASEMAN"."XIF2REPORT_OUTPUT" ON "CASEMAN"."REPORT_OUTPUT" ("AE_EVENT_SEQ")
  ;



  CREATE INDEX "CASEMAN"."XIF2REPORT_QUEUE" ON "CASEMAN"."REPORT_QUEUE" ("PARENT_ID")
  ;



  CREATE INDEX "CASEMAN"."XIF2REPORT_REPRINTS_XREF" ON "CASEMAN"."REPORT_REPRINTS_XREF" ("REPRINTS_ID")
  ;



  CREATE INDEX "CASEMAN"."XIF2USER_COURT" ON "CASEMAN"."USER_COURT" ("COURT_CODE")
  ;



  CREATE INDEX "CASEMAN"."XIF3AE_APPLICATIONS" ON "CASEMAN"."AE_APPLICATIONS" ("ISSUING_CRT_CODE")
  ;



  CREATE INDEX "CASEMAN"."XIF3CASE_PARTY_ROLES" ON "CASEMAN"."CASE_PARTY_ROLES" ("PARTY_ROLE_CODE")
  ;



  CREATE INDEX "CASEMAN"."XIF3CO_EVENT_VALIDATIONS" ON "CASEMAN"."CO_EVENT_VALIDATIONS" ("PRE_REQ_EVENT2")
  ;



  CREATE INDEX "CASEMAN"."XIF3GIVEN_ADDRESSES" ON "CASEMAN"."GIVEN_ADDRESSES" ("ADDRESS_TYPE_CODE")
  ;



  CREATE INDEX "CASEMAN"."XIF3JUDGMENTS" ON "CASEMAN"."JUDGMENTS" ("WARRANT_ID")
  ;



  CREATE INDEX "CASEMAN"."XIF3MENU_ITEM_GROUP" ON "CASEMAN"."MENU_ITEM_GROUP" ("MENU_ITEM_ID")
  ;



  CREATE INDEX "CASEMAN"."XIF3PARTY_TO_PARTY_RELATIONSHI" ON "CASEMAN"."PARTY_TO_PARTY_RELATIONSHIP" ("PARTY_A_ROLE_CODE")
  ;



  CREATE INDEX "CASEMAN"."XIF3REPORT_OUTPUT" ON "CASEMAN"."REPORT_OUTPUT" ("EVENT_SEQ")
  ;



  CREATE INDEX "CASEMAN"."XIF3REPORT_REPRINTS_XREF" ON "CASEMAN"."REPORT_REPRINTS_XREF" ("REPORT_REPRINTS_ID", "USERNAME")
  ;



  CREATE INDEX "CASEMAN"."XIF3TASK_COUNTS" ON "CASEMAN"."TASK_COUNTS" ("ADMIN_COURT_CODE")
  ;



  CREATE INDEX "CASEMAN"."XIF3USER_COURT" ON "CASEMAN"."USER_COURT" ("SECTION_NAME", "COURT_CODE")
  ;



  CREATE INDEX "CASEMAN"."XIF3WARRANTS" ON "CASEMAN"."WARRANTS" ("EXECUTED_BY")
  ;



  CREATE INDEX "CASEMAN"."XIF3WARRANT_RETURNS" ON "CASEMAN"."WARRANT_RETURNS" ("EVENT_SEQ")
  ;



  CREATE INDEX "CASEMAN"."XIF4AE_APPLICATIONS" ON "CASEMAN"."AE_APPLICATIONS" ("CASE_NUMBER", "PARTY_AGAINST_PARTY_ROLE_CODE", "PARTY_AGAINST_CASE_PARTY_NO")
  ;



  CREATE INDEX "CASEMAN"."XIF4AE_EVENTS" ON "CASEMAN"."AE_EVENTS" ("WARRANT_ID")
  ;



  CREATE INDEX "CASEMAN"."XIF4CODED_PARTIES" ON "CASEMAN"."CODED_PARTIES" ("PARTY_ID")
  ;



  CREATE INDEX "CASEMAN"."XIF4CO_EVENT_VALIDATIONS" ON "CASEMAN"."CO_EVENT_VALIDATIONS" ("PRE_REQ_EVENT3")
  ;



  CREATE INDEX "CASEMAN"."XIF4HEARINGS" ON "CASEMAN"."HEARINGS" ("ADDRESS_ID")
  ;



  CREATE INDEX "CASEMAN"."XIF4JUDGMENTS" ON "CASEMAN"."JUDGMENTS" ("AGAINST_PARTY_ADDR_ID_JUDG_REG")
  ;



  CREATE INDEX "CASEMAN"."XIF4REPORT_OUTPUT" ON "CASEMAN"."REPORT_OUTPUT" ("USER_ID")
  ;



  CREATE INDEX "CASEMAN"."XIF4TASK_COUNTS" ON "CASEMAN"."TASK_COUNTS" ("CREATING_SECTION", "CREATING_COURT")
  ;



  CREATE INDEX "CASEMAN"."XIF4WARRANTS" ON "CASEMAN"."WARRANTS" ("ISSUED_BY")
  ;



  CREATE INDEX "CASEMAN"."XIF4WARRANT_RETURNS" ON "CASEMAN"."WARRANT_RETURNS" ("CO_EVENT_SEQ")
  ;



  CREATE INDEX "CASEMAN"."XIF4WP_OUTPUT" ON "CASEMAN"."WP_OUTPUT" ("CO_EVENT_SEQ")
  ;



  CREATE INDEX "CASEMAN"."XIF5AE_APPLICATIONS" ON "CASEMAN"."AE_APPLICATIONS" ("CASE_NUMBER", "PARTY_FOR_PARTY_ROLE_CODE", "PARTY_FOR_CASE_PARTY_NO")
  ;



  CREATE INDEX "CASEMAN"."XIF5AE_EVENTS" ON "CASEMAN"."AE_EVENTS" ("CASE_EVENT_SEQ")
  ;



  CREATE INDEX "CASEMAN"."XIF5ALLOWED_DEBTS" ON "CASEMAN"."ALLOWED_DEBTS" ("CP_CREDITOR_ID")
  ;



  CREATE INDEX "CASEMAN"."XIF5CODED_PARTIES" ON "CASEMAN"."CODED_PARTIES" ("ADMIN_COURT_CODE")
  ;



  CREATE INDEX "CASEMAN"."XIF5CO_EVENTS" ON "CASEMAN"."CO_EVENTS" ("BMS_TASK_NUMBER")
  ;



  CREATE INDEX "CASEMAN"."XIF5GIVEN_ADDRESSES" ON "CASEMAN"."GIVEN_ADDRESSES" ("CO_NUMBER")
  ;



  CREATE INDEX "CASEMAN"."XIF5PARTY_TO_PARTY_RELATIONSHI" ON "CASEMAN"."PARTY_TO_PARTY_RELATIONSHIP" ("PARTY_B_ROLE_CODE")
  ;



  CREATE INDEX "CASEMAN"."XIF5WARRANTS" ON "CASEMAN"."WARRANTS" ("CURRENTLY_OWNED_BY")
  ;



  CREATE INDEX "CASEMAN"."XIF5WP_OUTPUT" ON "CASEMAN"."WP_OUTPUT" ("EVENT_SEQ")
  ;



  CREATE INDEX "CASEMAN"."XIF6AE_APPLICATIONS" ON "CASEMAN"."AE_APPLICATIONS" ("DEBTORS_EMPLOYERS_PARTY_ID")
  ;



  CREATE INDEX "CASEMAN"."XIF6ALLOWED_DEBTS" ON "CASEMAN"."ALLOWED_DEBTS" ("CP_PAYEE_ID")
  ;



  CREATE INDEX "CASEMAN"."XIF6GIVEN_ADDRESSES" ON "CASEMAN"."GIVEN_ADDRESSES" ("ALD_SEQ")
  ;



  CREATE INDEX "CASEMAN"."XIF6WARRANTS" ON "CASEMAN"."WARRANTS" ("CASE_NUMBER", "DEF1_PARTY_ROLE_CODE", "DEF1_CASE_PARTY_NO")
  ;



  CREATE INDEX "CASEMAN"."XIF6WP_OUTPUT" ON "CASEMAN"."WP_OUTPUT" ("AE_EVENT_SEQ")
  ;



  CREATE INDEX "CASEMAN"."XIF7CASE_EVENTS" ON "CASEMAN"."CASE_EVENTS" ("WARRANT_ID")
  ;



  CREATE INDEX "CASEMAN"."XIF7CO_EVENTS" ON "CASEMAN"."CO_EVENTS" ("AGE_CATEGORY")
  ;



  CREATE INDEX "CASEMAN"."XIF7GIVEN_ADDRESSES" ON "CASEMAN"."GIVEN_ADDRESSES" ("COURT_CODE")
  ;



  CREATE INDEX "CASEMAN"."XIF7WARRANTS" ON "CASEMAN"."WARRANTS" ("CASE_NUMBER", "DEF2_PARTY_ROLE_CODE", "DEF2_CASE_PARTY_NO")
  ;



  CREATE INDEX "CASEMAN"."XIF7WP_OUTPUT" ON "CASEMAN"."WP_OUTPUT" ("USER_ID")
  ;



  CREATE INDEX "CASEMAN"."XIF8CASE_EVENTS" ON "CASEMAN"."CASE_EVENTS" ("BMS_TASK_NUMBER")
  ;



  CREATE INDEX "CASEMAN"."XIF8CO_EVENTS" ON "CASEMAN"."CO_EVENTS" ("WARRANT_ID")
  ;



  CREATE INDEX "CASEMAN"."XIF8PAYMENTS" ON "CASEMAN"."PAYMENTS" ("PAYEE_ID")
  ;



  CREATE INDEX "CASEMAN"."XIF8WARRANTS" ON "CASEMAN"."WARRANTS" ("CASE_NUMBER", "REP_PARTY_ROLE_CODE", "REP_CASE_PARTY_NO")
  ;



  CREATE INDEX "CASEMAN"."XIF8WP_OUTPUT" ON "CASEMAN"."WP_OUTPUT" ("WARRANT_RETURNS_ID")
  ;



  CREATE INDEX "CASEMAN"."XIF99" ON "CASEMAN"."COURTS" ("DFJ_AREA_ID")
  ;



  CREATE INDEX "CASEMAN"."XIF9CASE_EVENTS" ON "CASEMAN"."CASE_EVENTS" ("AGE_CATEGORY")
  ;



  CREATE INDEX "CASEMAN"."XIF9CO_EVENTS" ON "CASEMAN"."CO_EVENTS" ("CREATING_SECTION", "CREATING_COURT")
  ;



  CREATE INDEX "CASEMAN"."XIF9PAYMENTS" ON "CASEMAN"."PAYMENTS" ("ADMIN_COURT_CODE")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."XPKADDRESS_TYPES" ON "CASEMAN"."ADDRESS_TYPES" ("ADDRESS_TYPE_CODE")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."XPKASYNC_COMMAND" ON "CASEMAN"."ASYNC_COMMAND" ("ID")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."XPKCASE_EVENT_INSTIGATORS" ON "CASEMAN"."CASE_EVENT_INSTIGATORS" ("EVENT_SEQ", "CASE_NUMBER", "CASE_PARTY_NO", "PARTY_ROLE_CODE")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."XPKCASE_PARTY_ROLES" ON "CASEMAN"."CASE_PARTY_ROLES" ("CASE_NUMBER", "CASE_PARTY_NO", "PARTY_ROLE_CODE")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."XPKCCBC_MEDIA_FILE_TYPE" ON "CASEMAN"."CCBC_MEDIA_FILE_TYPE" ("FILE_TYPE_CODE")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."XPKCMCS_CAPS_ORDERS" ON "CASEMAN"."CMCS_CAPS_ORDERS" ("TRANS_SEQ")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."XPKCMCS_CASES" ON "CASEMAN"."CMCS_CASES" ("TRANS_SEQ")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."XPKCMCS_DEFENDANTS" ON "CASEMAN"."CMCS_DEFENDANTS" ("TRANS_SEQ", "CASE_NUMBER", "ID")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."XPKCMCS_DEFENDANT_ADDRESSES" ON "CASEMAN"."CMCS_DEFENDANT_ADDRESSES" ("TRANS_SEQ", "DEFT_CASE_NUMBER", "DEFT_ID", "ADDR_SEQ")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."XPKCMCS_TRANSFER_CONTROL" ON "CASEMAN"."CMCS_TRANSFER_CONTROL" ("TRANS_SEQ")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."XPKCMCS_TRANSFER_STATUS" ON "CASEMAN"."CMCS_TRANSFER_STATUS" ("TS_STATUS")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."XPKCODED_CREDITORS" ON "CASEMAN"."PAYEES" ("PARTY_ID")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."XPKCONTENT_STORE" ON "CASEMAN"."CONTENT_STORE" ("ID")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."XPKCPR_TO_CPR_RELATIONSHIP" ON "CASEMAN"."CPR_TO_CPR_RELATIONSHIP" ("CPR_A_CASE_NUMBER", "CPR_A_CASE_PARTY_NO", "CPR_A_PARTY_ROLE_CODE", "CPR_B_CASE_NUMBER", "CPR_B_CASE_PARTY_NO", "CPR_B_PARTY_ROLE_CODE")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."XPKCURRENCY" ON "CASEMAN"."CURRENCY" ("CURRENCY_CODE")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."XPKDCA_USER" ON "CASEMAN"."DCA_USER" ("USER_ID")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."XPKDFJ_AREAS" ON "CASEMAN"."DFJ_AREAS" ("DFJ_AREA_ID")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."XPKDOCUMENT_STORE" ON "CASEMAN"."DOCUMENT_STORE" ("ID")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."XPKETHNIC_ORIGIN" ON "CASEMAN"."ETHNIC_ORIGIN" ("ETHNIC_ORIGIN_CODE")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."XPKFEES_PAID" ON "CASEMAN"."FEES_PAID" ("FEES_PAID_ID")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."XPKFTP_QUEUE" ON "CASEMAN"."FTP_QUEUE" ("REQUEST_ID")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."XPKGIVEN_ADDRESSES" ON "CASEMAN"."GIVEN_ADDRESSES" ("ADDRESS_ID")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."XPKINFAVOUR_PARTIES" ON "CASEMAN"."INFAVOUR_PARTIES" ("JUDG_SEQ", "CASE_NUMBER", "CASE_PARTY_NO", "PARTY_ROLE_CODE")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."XPKJUDGES" ON "CASEMAN"."JUDGES" ("JUDGE_ID")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."XPKLOCAL_AUTHORITY_CODES" ON "CASEMAN"."LOCAL_AUTHORITY_CODES" ("LAC_CODE")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."XPKNATIONAL_CODED_PARTIES" ON "CASEMAN"."NATIONAL_CODED_PARTIES" ("CODE")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."XPKNON_WORKING_DAYS_EXCEPTIONS" ON "CASEMAN"."NON_WORKING_DAYS_EXCEPTIONS" ("NON_WD_EX_SEQ")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."XPKPARTIES" ON "CASEMAN"."PARTIES" ("PARTY_ID")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."XPKPARTY_ROLES" ON "CASEMAN"."PARTY_ROLES" ("PARTY_ROLE_CODE")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."XPKPARTY_TO_PARTY_RELATIONSHIP" ON "CASEMAN"."PARTY_TO_PARTY_RELATIONSHIP" ("PARTY_A_ID", "PARTY_A_ROLE_CODE", "PARTY_B_ID", "PARTY_B_ROLE_CODE")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."XPKPARTY_TYPES" ON "CASEMAN"."PARTY_TYPES" ("PARTY_TYPE_CODE")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."XPKPERSONALISE" ON "CASEMAN"."PERSONALISE" ("CRT_CODE")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."XPKPL_FILELEVEL_PREVAL_STATUS" ON "CASEMAN"."PL_FILELEVEL_PREVAL_STATUS" ("FILE_NAME")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."XPKPL_JOB_QUEUE" ON "CASEMAN"."PL_JOB_QUEUE" ("REQUEST_ID")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."XPKPL_RECORDLEVEL_PREVAL_STATU" ON "CASEMAN"."PL_RECORDLEVEL_PREVAL_STATUS" ("RECORDSEQNO", "FILE_NAME")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."XPKPL_XML_STATUS" ON "CASEMAN"."PL_XML_STATUS" ("SEQUENCE_NO")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."XPKPRINT_JOB" ON "CASEMAN"."PRINT_JOB" ("PRINT_JOB_ID")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."XPKREJECT_REASONS" ON "CASEMAN"."REJECT_REASONS" ("REJECT_CODE")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."XPKREPORTS" ON "CASEMAN"."CCBC_REPORTS" ("ID")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."XPKREPORT_OUTPUT" ON "CASEMAN"."REPORT_OUTPUT" ("OUTPUT_ID")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."XPKREPORT_REPRINTS" ON "CASEMAN"."REPORT_REPRINTS" ("USERNAME", "REPORT_ID")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."XPKREPORT_SEQUENCES" ON "CASEMAN"."REPORT_SEQUENCES" ("FORM_NAME")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."XPKSERVER_SECRET" ON "CASEMAN"."SERVER_SECRET" ("SERVER_SECRET_ID")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."XPKTAPES" ON "CASEMAN"."TAPES" ("SEQNO")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."XPKTAPE_FILES" ON "CASEMAN"."TAPE_FILES" ("ORDERSEQ")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."XPKTRAN_ADDRESS" ON "CASEMAN"."TRAN_ADDRESS" ("CRT_CODE", "ADDR_TYPE", "ADDR_TYPE_SEQ")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."XPKTRAN_COURTS" ON "CASEMAN"."TRAN_COURTS" ("CODE")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."XPKUSER_COURT" ON "CASEMAN"."USER_COURT" ("USER_ID", "COURT_CODE")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."XPKUSER_ROLE" ON "CASEMAN"."USER_ROLE" ("USER_ID", "COURT_CODE", "ROLE_ID")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."XPKWARRANT_RETURNS" ON "CASEMAN"."WARRANT_RETURNS" ("WARRANT_RETURNS_ID")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."XPKWP_OUTPUT" ON "CASEMAN"."WP_OUTPUT" ("OUTPUT_ID")
  ;



  CREATE UNIQUE INDEX "CASEMAN"."XPKWP_TRANSFORMATIONS" ON "CASEMAN"."WP_TRANSFORMATIONS" ("DOCUMENT_TEMPLATE")
  ;


