
  ALTER TABLE "CASEMAN"."ALLOWED_DEBTS" ADD CONSTRAINT "ALLO_CRED_VALI_1434816115" CHECK (CREDITOR_WELSH_INDICATOR IN ('Y', 'N')) ENABLE;



  ALTER TABLE "CASEMAN"."ALLOWED_DEBTS" ADD CONSTRAINT "ALLO_PAYE_VALI_709768263" CHECK (PAYEE_WELSH_INDICATOR IN ('Y', 'N')) ENABLE;



  ALTER TABLE "CASEMAN"."CASE_PARTY_ROLES" ADD CONSTRAINT "CASE_DEFT_VALI_749842598" CHECK (DEFT_BAR_JUDGMENT IN ('Y', 'N')) ENABLE;



  ALTER TABLE "CASEMAN"."CASE_EVENT_INSTIGATORS" ADD CONSTRAINT "CASE_DELE_VALI_683604599" CHECK (DELETE_FLAG IN ('Y', 'N')) ENABLE;



  ALTER TABLE "CASEMAN"."CASE_PARTY_ROLES" ADD CONSTRAINT "CASE_PAYE_VALI_878210149" CHECK (PAYEE_FLAG IN ('Y', 'N')) ENABLE;



  ALTER TABLE "CASEMAN"."CASE_EVENTS" ADD CONSTRAINT "CASE_REGI_VALI_1533542914" CHECK (REGISTER_JUDGMENT IN ('Y', 'N')) ENABLE;



  ALTER TABLE "CASEMAN"."CASE_EVENTS" ADD CONSTRAINT "CASE__CASE__VALID_82815417" CHECK (CASE_FLAG IN ('Y', 'N')) ENABLE;



  ALTER TABLE "CASEMAN"."HEARINGS" ADD CONSTRAINT "CHECK_HRG_FK" CHECK (  (case_number is null and co_number is not null ) or (co_number is null and case_number is not null)) ENABLE;



  ALTER TABLE "CASEMAN"."WARRANTS" ADD CONSTRAINT "CHECK_WARR_FK" CHECK (  (case_number is null and co_number is not null ) or (co_number is null and case_number is not null)) ENABLE;



  ALTER TABLE "CASEMAN"."CODED_PARTIES" ADD CONSTRAINT "CODE_CASC_VALI_440868667" CHECK (CASCADE_UPDATE_FLAG IN ('Y')) ENABLE;



  ALTER TABLE "CASEMAN"."COURTS" ADD CONSTRAINT "COUR_SUPS_VALI_1650219759" CHECK (SUPS_CENTRALISED_FLAG IN ('Y', 'N')) ENABLE;



  ALTER TABLE "CASEMAN"."CPR_TO_CPR_RELATIONSHIP" ADD CONSTRAINT "CPR__DELE_VALI_960386185" CHECK (DELETED_FLAG IN ('Y', 'N')) ENABLE;



  ALTER TABLE "CASEMAN"."CASES" ADD CONSTRAINT "DATE_OF_TRANSFER_CHK" CHECK ( trunc(DATE_OF_TRANSFER) >= trunc(DATE_OF_ISSUE)) ENABLE;



  ALTER TABLE "CASEMAN"."DEFENCE_DOC_EVENT" ADD CONSTRAINT "DDE_PRINT_CHK" CHECK (print_now  IN  ('Y', 'N')) ENABLE;



  ALTER TABLE "CASEMAN"."DEFENCE_DOC_EVENT" ADD CONSTRAINT "DED_VS_CHECK" CHECK (via_sdt      IN ('Y', 'N')) ENABLE;



  ALTER TABLE "CASEMAN"."DEFENCE_DOC_EVENT" ADD CONSTRAINT "DED_V_CHECK" CHECK (validated    IN ('Y', 'N')) ENABLE;



  ALTER TABLE "CASEMAN"."ECHR_ARTICLE_PROTOCOL" ADD CONSTRAINT "ECHRAP_ART_OR_PROT" CHECK (art_or_prot IN ('A','P')) ENABLE;



  ALTER TABLE "CASEMAN"."FEES_PAID" ADD CONSTRAINT "FEES__DELET_VALID_13152944" CHECK (DELETED_FLAG IN ('Y', 'N')) ENABLE;



  ALTER TABLE "CASEMAN"."JUDGMENTS" ADD CONSTRAINT "FINAL_PAY_DATE_CHK" CHECK ( trunc(date_of_final_payment) >= trunc(judgment_date)) ENABLE;



  ALTER TABLE "CASEMAN"."JUDGMENTS" ADD CONSTRAINT "FIRST_PAY_DATE_CHK" CHECK ( trunc(first_payment_date) >= trunc(judgment_date)) ENABLE;



  ALTER TABLE "CASEMAN"."INFAVOUR_PARTIES" ADD CONSTRAINT "INFA_DELE_VALI_2071524607" CHECK (DELETED_FLAG IN ('Y', 'N')) ENABLE;



  ALTER TABLE "CASEMAN"."LOAD_CASES" ADD CONSTRAINT "LC_VS_CHECK" CHECK (via_sdt      IN ('Y', 'N')) ENABLE;



  ALTER TABLE "CASEMAN"."LOAD_JUDGMENTS" ADD CONSTRAINT "LJ_VS_CHECK" CHECK (via_sdt      IN ('Y', 'N')) ENABLE;



  ALTER TABLE "CASEMAN"."LOAD_PAID_WO_DETAILS" ADD CONSTRAINT "LPWO_VS_CHECK" CHECK (via_sdt      IN ('Y', 'N')) ENABLE;



  ALTER TABLE "CASEMAN"."LOAD_WARRANTS" ADD CONSTRAINT "LW_VS_CHECK" CHECK (via_sdt      IN ('Y', 'N')) ENABLE;



  ALTER TABLE "CASEMAN"."MCOL_PDF_STATUS" ADD CONSTRAINT "MPS_DELETED_CHK" CHECK (deleted   IN ('Y', 'N')) ENABLE;



  ALTER TABLE "CASEMAN"."MCOL_PDF_STATUS" ADD CONSTRAINT "MPS_LOADED_CHK" CHECK (loaded    IN ('Y', 'N')) ENABLE;



  ALTER TABLE "CASEMAN"."MCOL_PDF_STATUS" ADD CONSTRAINT "MPS_PRINTED_CHK" CHECK (printed   IN ('Y', 'N')) ENABLE;



  ALTER TABLE "CASEMAN"."MCOL_PDF_STATUS" ADD CONSTRAINT "MPS_PRINT_CHK" CHECK (print_now IN ('Y', 'N')) ENABLE;



  ALTER TABLE "CASEMAN"."JUDGMENTS" ADD CONSTRAINT "PAID_BEFORE_JUDG_CHK" CHECK ( paid_before_judgment < nvl(judgment_amount, 0) + nvl(total_costs, 0)) ENABLE;



  ALTER TABLE "CASEMAN"."PL_FILELEVEL_PREVAL_STATUS" ADD CONSTRAINT "PL_F_FILE_VALI_1640478128" CHECK (filename_val_passed IN ('Y', 'N')) ENABLE;



  ALTER TABLE "CASEMAN"."VARIATIONS" ADD CONSTRAINT "RESULT_DATE_CHK" CHECK ( trunc(RESULT_DATE) >= trunc(APPLICATION_DATE)) ENABLE;



  ALTER TABLE "CASEMAN"."SET_ASIDE_REQUESTS" ADD CONSTRAINT "SAR_DEF_CHK" CHECK (defendant_id         IN ( 1 , 2 )) ENABLE;



  ALTER TABLE "CASEMAN"."SET_ASIDE_REQUESTS" ADD CONSTRAINT "SAR_PRC_CHK" CHECK (party_role_code         IN ('DEFENDANT', 'CLAIMANT')) ENABLE;



  ALTER TABLE "CASEMAN"."SET_ASIDE_REQUESTS" ADD CONSTRAINT "SAR_VALID_CHK" CHECK (validated            IN ('Y', 'N')) ENABLE;



  ALTER TABLE "CASEMAN"."SET_ASIDE_REQUESTS" ADD CONSTRAINT "SAR_VIA_CHK" CHECK (via_sdt              IN ('Y', 'N')) ENABLE;



  ALTER TABLE "CASEMAN"."STANDARD_EVENTS" ADD CONSTRAINT "STD_EVENT_EDIT_DETAILS_CHK" CHECK (EDIT_DETAILS IN ('N', 'O', 'M')) ENABLE;



  ALTER TABLE "CASEMAN"."ACTION_TASK_XREF" MODIFY ("ACTION_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."ACTION_TASK_XREF" MODIFY ("TASK_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."AE_APPLICATIONS" MODIFY ("AE_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."AE_APPLICATIONS" MODIFY ("AE_TYPE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."AE_APPLICATIONS" MODIFY ("DATE_OF_CREATION" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."AE_APPLICATIONS" MODIFY ("CASE_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."AE_EVENTS" MODIFY ("AE_EVENT_SEQ" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."AE_EVENTS" MODIFY ("AE_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."AE_EVENTS" MODIFY ("EVENT_DATE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."AE_EVENTS" MODIFY ("DATE_ENTERED" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."AE_EVENTS" MODIFY ("STD_EVENT_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."AE_EVENTS" MODIFY ("ERROR_INDICATOR" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."AE_EVENTS" MODIFY ("USERNAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."AE_PER_ITEMS" MODIFY ("AE_PER_SEQ" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."AE_PER_ITEMS" MODIFY ("AE_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."AE_PER_ITEMS" MODIFY ("DETAIL_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."AE_PER_ITEMS" MODIFY ("USERNAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."AE_PER_ITEMS" MODIFY ("ERROR_INDICATOR" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."AGE_CATEGORY" MODIFY ("AGE_CATEGORY" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."AGE_CATEGORY" MODIFY ("LOWER_LIMIT" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."ALLOWED_DEBTS" MODIFY ("DEBT_SEQ" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."ALLOWED_DEBTS" MODIFY ("DEBT_CO_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."ALLOWED_DEBTS" MODIFY ("DEBT_STATUS" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."ALLOWED_DEBTS" MODIFY ("DEBT_PAYEE_INDICATOR" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."AMR_REPORTS" MODIFY ("TRANSACTION_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."AMR_REPORTS" MODIFY ("ADMIN_COURT_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."AO_CAEO" MODIFY ("AO_CAEO_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."AO_CAEO" MODIFY ("DEBTOR_NAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."AO_CAEO" MODIFY ("ADMIN_COURT_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."AO_CAEO_DIVIDEND" MODIFY ("AO_CAEO_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."AO_CAEO_DIVIDEND" MODIFY ("DIVIDEND_DATE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."AO_CAEO_DIVIDEND" MODIFY ("VERIFICATION_REPORT_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."AO_CAEO_DIVIDEND" MODIFY ("CREATED_BY" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."AO_CAEO_DIVIDEND" MODIFY ("ADMIN_COURT_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."AUDIT_CONFIG" MODIFY ("TABLE_NAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CANDIDATE_DIVIDEND_PAYMENTS" MODIFY ("CDP_TRANSACTION_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CANDIDATE_DIVIDEND_PAYMENTS" MODIFY ("CDP_CO_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CANDIDATE_DIVIDEND_PAYMENTS" MODIFY ("ADMIN_COURT_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CAPS_PAYMENTS" MODIFY ("AE_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CAPS_PAYMENTS" MODIFY ("CAPS_TRANS_NO" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CAPS_PAYMENTS" MODIFY ("PAYMENT_DATE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CASES" MODIFY ("CASE_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CASES" MODIFY ("CASE_TYPE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CASES" MODIFY ("ADMIN_CRT_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CASE_EVENTS" MODIFY ("EVENT_SEQ" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CASE_EVENTS" MODIFY ("CASE_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CASE_EVENTS" MODIFY ("STD_EVENT_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CASE_EVENTS" MODIFY ("EVENT_DATE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CASE_EVENTS" MODIFY ("DELETED_FLAG" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CASE_EVENT_INSTIGATORS" MODIFY ("EVENT_SEQ" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CASE_EVENT_INSTIGATORS" MODIFY ("CASE_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CASE_EVENT_INSTIGATORS" MODIFY ("CASE_PARTY_NO" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CASE_EVENT_INSTIGATORS" MODIFY ("PARTY_ROLE_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CASE_PARTY_ROLES" MODIFY ("CASE_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CASE_PARTY_ROLES" MODIFY ("PARTY_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CASE_PARTY_ROLES" MODIFY ("PARTY_ROLE_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CASE_PARTY_ROLES" MODIFY ("CASE_PARTY_NO" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CCBC_MEDIA_FILE_TYPE" MODIFY ("FILE_TYPE_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CCBC_MEDIA_FILE_TYPE" MODIFY ("FILE_TYPE_DESCRIPTION" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CCBC_REPORTS" MODIFY ("ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CCBC_REPORTS" MODIFY ("NAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CCB_MESSAGES" MODIFY ("MSG_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CCB_MESSAGES" MODIFY ("DICT" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CMCS_AE_EVENTS" MODIFY ("TRANS_SEQ" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CMCS_AE_EVENTS" MODIFY ("AE_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CMCS_AE_EVENTS" MODIFY ("EVENT_DATE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CMCS_AE_EVENTS" MODIFY ("DATE_ENTERED" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CMCS_AE_EVENTS" MODIFY ("STD_EVENT_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CMCS_AE_EVENTS" MODIFY ("USERNAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CMCS_CAPS_ORDERS" MODIFY ("TRANS_SEQ" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CMCS_CAPS_ORDERS" MODIFY ("ISSUED_BY" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CMCS_CAPS_ORDERS" MODIFY ("ORDER_STATUS" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CMCS_CAPS_ORDERS" MODIFY ("CASE_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CMCS_CAPS_ORDERS" MODIFY ("AE_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CMCS_CAPS_ORDERS" MODIFY ("AE_TYPE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CMCS_CAPS_ORDERS" MODIFY ("PLTF_NAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CMCS_CAPS_ORDERS" MODIFY ("PLTF_ADDR1" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CMCS_CAPS_ORDERS" MODIFY ("PLTF_ADDR2" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CMCS_CAPS_ORDERS" MODIFY ("PAYEE_NAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CMCS_CAPS_ORDERS" MODIFY ("PAYEE_ADDR1" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CMCS_CAPS_ORDERS" MODIFY ("PAYEE_ADDR2" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CMCS_CAPS_ORDERS" MODIFY ("DEF_NAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CMCS_CAPS_ORDERS" MODIFY ("DEF_ADDR1" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CMCS_CAPS_ORDERS" MODIFY ("DEF_ADDR2" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CMCS_CAPS_ORDERS" MODIFY ("EMPL_NAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CMCS_CAPS_ORDERS" MODIFY ("EMPL_ADDR1" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CMCS_CAPS_ORDERS" MODIFY ("EMPL_ADDR2" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CMCS_CAPS_ORDERS" MODIFY ("NDR_AMOUNT" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CMCS_CAPS_ORDERS" MODIFY ("NDR_PERIOD" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CMCS_CAPS_ORDERS" MODIFY ("PER_AMOUNT" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CMCS_CAPS_ORDERS" MODIFY ("PER_PERIOD" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CMCS_CAPS_ORDERS" MODIFY ("PAID_MONTHLY_FLAG" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CMCS_CAPS_ORDERS" MODIFY ("DATE_OF_ORDER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CMCS_CAPS_ORDERS" MODIFY ("ORDER_REQUIRED_FLAG" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CMCS_CAPS_ORDERS" MODIFY ("DJ_ORDER_FLAG" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CMCS_CAPS_ORDERS" MODIFY ("TRANSFER_STATUS" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CMCS_CAPS_PAYMENTS" MODIFY ("AE_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CMCS_CAPS_PAYMENTS" MODIFY ("CAPS_EVENT_SEQ" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CMCS_CAPS_PAYMENTS" MODIFY ("TRANS_SEQ" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CMCS_CAPS_PAYMENTS" MODIFY ("CAPS_TRANS_NO" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CMCS_CAPS_PAYMENTS" MODIFY ("PAYMENT_DATE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CMCS_CASES" MODIFY ("TRANS_SEQ" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CMCS_CASES" MODIFY ("CASE_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CMCS_DEFENDANTS" MODIFY ("CASE_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CMCS_DEFENDANTS" MODIFY ("TRANS_SEQ" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CMCS_DEFENDANTS" MODIFY ("ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CMCS_DEFENDANT_ADDRESSES" MODIFY ("TRANS_SEQ" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CMCS_DEFENDANT_ADDRESSES" MODIFY ("ADDR_SEQ" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CMCS_DEFENDANT_ADDRESSES" MODIFY ("DEFT_CASE_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CMCS_DEFENDANT_ADDRESSES" MODIFY ("DEFT_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CMCS_TRANSFER_CONTROL" MODIFY ("TRANS_SEQ" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CMCS_TRANSFER_STATUS" MODIFY ("TS_STATUS" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CODED_PARTIES" MODIFY ("PARTY_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CODED_PARTIES" MODIFY ("CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CODED_PARTIES" MODIFY ("ADMIN_COURT_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CONSOLIDATED_ORDERS" MODIFY ("CO_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CONSOLIDATED_ORDERS" MODIFY ("CO_STATUS" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CONSOLIDATED_ORDERS" MODIFY ("CO_TYPE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CONSOLIDATED_ORDERS" MODIFY ("DEBTOR_NAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CONSOLIDATED_ORDERS" MODIFY ("FEE_RATE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."COPS_MERGE_FIELDS" MODIFY ("CMF_SEQ_NO" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."COPS_MERGE_FIELDS" MODIFY ("ORDER_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."COPS_MERGE_FIELDS" MODIFY ("WP_FIELD_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CO_CASE_EVENTS" MODIFY ("ADMIN_COURT_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CO_CASE_EVENTS" MODIFY ("CO_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CO_CASE_EVENTS" MODIFY ("STD_EVENT_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CO_CASE_EVENTS" MODIFY ("CREATED_DATE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CO_CASE_EVENTS" MODIFY ("EVENT_DETAILS" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CO_CASE_EVENTS" MODIFY ("TRANSFER_STATUS" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CO_CASE_EVENTS" MODIFY ("ALD_DEBT_SEQ" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CO_CASE_EVENTS" MODIFY ("CASE_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CO_EVENTS" MODIFY ("CO_EVENT_SEQ" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CO_EVENTS" MODIFY ("EVENT_DATE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CO_EVENTS" MODIFY ("STD_EVENT_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CO_EVENTS" MODIFY ("ERROR_INDICATOR" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CO_EVENTS" MODIFY ("USERNAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CO_EVENTS" MODIFY ("RECEIPT_DATE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CO_EVENTS" MODIFY ("CO_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CO_PER_ITEMS" MODIFY ("CO_PER_SEQ" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CO_PER_ITEMS" MODIFY ("CO_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CO_PER_ITEMS" MODIFY ("DETAIL_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CO_PER_ITEMS" MODIFY ("USERNAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CO_PER_ITEMS" MODIFY ("ERROR_INDICATOR" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CO_REPRINTS" MODIFY ("ORDER_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CO_REPRINTS" MODIFY ("PRINTED" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CO_REPRINTS" MODIFY ("REPORT_DATE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CO_REPRINTS" MODIFY ("WP_INDICATOR" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CO_REPRINTS" MODIFY ("USERNAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CPR_TO_CPR_RELATIONSHIP" MODIFY ("CPR_A_CASE_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CPR_TO_CPR_RELATIONSHIP" MODIFY ("CPR_A_PARTY_ROLE_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CPR_TO_CPR_RELATIONSHIP" MODIFY ("CPR_B_PARTY_ROLE_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CPR_TO_CPR_RELATIONSHIP" MODIFY ("CPR_B_CASE_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CPR_TO_CPR_RELATIONSHIP" MODIFY ("CPR_B_CASE_PARTY_NO" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CPR_TO_CPR_RELATIONSHIP" MODIFY ("CPR_A_CASE_PARTY_NO" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CPR_TO_CPR_RELATIONSHIP" MODIFY ("DELETED_FLAG" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."DCA_USER" MODIFY ("USER_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."DCA_USER" MODIFY ("SURNAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."DCA_USER" MODIFY ("USER_SHORT_NAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."DCA_USER" MODIFY ("ACTIVE_USER_FLAG" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."DCS" MODIFY ("ITEM_DATE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."DCS" MODIFY ("REPORT_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."DCS" MODIFY ("TRANSACTION" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."DCS" MODIFY ("INOUT" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."DCS_DATA" MODIFY ("CREATED_BY" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."DCS_DATA" MODIFY ("VERIFICATION_REPORT_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."DCS_DATA" MODIFY ("DATE_CREATED" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."DCS_DATA" MODIFY ("RETENTION_TYPE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."DEBT_DIVIDENDS" MODIFY ("DD_SEQ" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."DEBT_DIVIDENDS" MODIFY ("DD_CO_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."DEBT_DIVIDENDS" MODIFY ("DD_DIV_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."DEBT_DIVIDENDS" MODIFY ("DD_ALD_SEQ" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."DEBT_DIVIDENDS" MODIFY ("CREATED" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."DIVIDENDS" MODIFY ("DIV_CO_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."DIVIDENDS" MODIFY ("DIV_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."DIVIDENDS" MODIFY ("DIV_DATE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."DIVIDENDS" MODIFY ("DIV_REPORT_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."DIVIDENDS" MODIFY ("DIV_CREATED_BY" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."DIVIDENDS" MODIFY ("CREATED" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."DJPRINT_TEMP" MODIFY ("COPSDATA" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."DJPRINT_TEMP" MODIFY ("USERNAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."ECHR_DETAILS" MODIFY ("DEFT_CASE_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."ECHR_DETAILS" MODIFY ("EVENT_SEQ" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."ECHR_DETAILS" MODIFY ("PLAINTIFF_DETAILS_1" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."ECHR_DETAILS" MODIFY ("EVENT_DATE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."ECHR_DETAILS" MODIFY ("DATE_OF_APPLN" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."ECHR_DETAILS" MODIFY ("USERNAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."ECHR_DETAILS" MODIFY ("JUDGE_NAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."ECHR_DETAILS" MODIFY ("DELETED_FLAG" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."ETHNIC_ORIGIN" MODIFY ("ETHNIC_ORIGIN_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."EVENT_OUTPUTS" MODIFY ("STD_EVENT_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."EVENT_OUTPUTS" MODIFY ("ORDER_TYPE_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."EVENT_OUTPUTS" MODIFY ("CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."EVENT_TASK_XREF" MODIFY ("TASK_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."EVENT_TASK_XREF" MODIFY ("CASE_TYPE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."EVENT_TASK_XREF" MODIFY ("EVENT_TYPE_FLAG" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."EVENT_TASK_XREF" MODIFY ("EVENT_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."FEES_PAID" MODIFY ("FEES_PAID_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."FEES_PAID" MODIFY ("PROCESS_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."FEES_PAID" MODIFY ("PROCESS_TYPE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."FEES_PAID" MODIFY ("ALLOCATION_DATE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."FEES_PAID" MODIFY ("ISSUING_COURT" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."FEES_PAID" MODIFY ("DELETED_FLAG" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."FEES_PAID" MODIFY ("USER_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."FEES_PAID" MODIFY ("DATE_CREATED" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."FTP_QUEUE" MODIFY ("REQUEST_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."FTP_QUEUE" MODIFY ("DOCUMENT_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."FTP_QUEUE" MODIFY ("TIME_OF_REQUEST" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."FTP_QUEUE" MODIFY ("FTP_SERVER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."FTP_QUEUE" MODIFY ("FTP_USER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."FTP_QUEUE" MODIFY ("FTP_PASSWORD" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."FTP_QUEUE" MODIFY ("FILENAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."FTP_QUEUE" MODIFY ("FTP_TRANSFER_TYPE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."FTP_QUEUE" MODIFY ("STATUS" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."HEARINGS" MODIFY ("HRG_SEQ" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."HEARINGS" MODIFY ("HRG_DATE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."HEARINGS" MODIFY ("HRG_TIME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."HEARINGS" MODIFY ("HRG_TYPE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."HEARINGS" MODIFY ("VENUE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."INFAVOUR_PARTIES" MODIFY ("JUDG_SEQ" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."INFAVOUR_PARTIES" MODIFY ("CASE_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."INFAVOUR_PARTIES" MODIFY ("CASE_PARTY_NO" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."INFAVOUR_PARTIES" MODIFY ("PARTY_ROLE_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."JUDGMENTS" MODIFY ("JUDG_SEQ" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."JUDGMENTS" MODIFY ("JUDGMENT_TYPE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."LOCALCOPS_TEMP" MODIFY ("COPSDATA" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."LOCALCOPS_TEMP" MODIFY ("USERNAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."LOCAL_AUTHORITY_CODES" MODIFY ("LAC_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."LOCAL_AUTHORITY_CODES" MODIFY ("LAC_NAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."MCOL_DATA" MODIFY ("CLAIM_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."MCOL_UPDATE_LOG" MODIFY ("LOG_DATE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."MENU_ITEM" MODIFY ("MENU_ITEM_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."MENU_ITEM_GROUP" MODIFY ("MENU_ITEM_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."MENU_ITEM_GROUP" MODIFY ("CONTEXT" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."MENU_ITEM_GROUP" MODIFY ("USERS_ROLE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."NATIONAL_CODED_PARTIES" MODIFY ("CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."OBLIGATIONS" MODIFY ("OBLIGATION_SEQ" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."OBLIGATIONS" MODIFY ("OBLIGATION_TYPE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."OBLIGATIONS" MODIFY ("EXPIRY_DATE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."OBLIGATIONS" MODIFY ("LAST_USED_BY" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."OBLIGATIONS" MODIFY ("DELETE_FLAG" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."OBLIGATIONS" MODIFY ("CASE_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."OLD_AE" MODIFY ("AE_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."OLD_AE" MODIFY ("CASE_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."OLD_AE" MODIFY ("DEFENDANT_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."OLD_REPORT_REPRINTS" MODIFY ("USERNAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."OLD_REPORT_REPRINTS" MODIFY ("REPORT_NAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."OLD_REPORT_REPRINTS" MODIFY ("REPORT_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."OLD_REPORT_REPRINTS" MODIFY ("FILENAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."OLD_REPORT_REPRINTS" MODIFY ("REPORT_DATE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."OLD_REPORT_REPRINTS" MODIFY ("MODULE_GROUP" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."ORDERS" MODIFY ("ORDER_CASE_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."ORDERS" MODIFY ("ORDER_ORD_TYPE_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."OSW" MODIFY ("ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."OSW" MODIFY ("ADMIN_COURT_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PARTIES" MODIFY ("PARTY_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PARTY_TO_PARTY_RELATIONSHIP" MODIFY ("PARTY_A_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PARTY_TO_PARTY_RELATIONSHIP" MODIFY ("PARTY_B_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PARTY_TO_PARTY_RELATIONSHIP" MODIFY ("PARTY_A_ROLE_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PARTY_TO_PARTY_RELATIONSHIP" MODIFY ("PARTY_B_ROLE_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PAYABLE_ORDERS" MODIFY ("PAYEE_NAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PAYABLE_ORDERS" MODIFY ("PO_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PAYABLE_ORDERS" MODIFY ("PRINT" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PAYABLE_ORDERS" MODIFY ("ADMIN_COURT_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PAYABLE_ORDER_HEADER" MODIFY ("ITEM_DATE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PAYABLE_ORDER_HEADER" MODIFY ("REPORT_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PAYABLE_ORDER_HEADER" MODIFY ("TRANSACTION" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PAYABLE_ORDER_HEADER" MODIFY ("INOUT" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PAYABLE_ORDER_ITEMS" MODIFY ("TRANSACTION_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PAYABLE_ORDER_ITEMS" MODIFY ("PPL_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PAYABLE_ORDER_ITEMS" MODIFY ("ADMIN_COURT_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PAYABLE_ORDER_ITEMS" MODIFY ("PO_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PAYEES" MODIFY ("PARTY_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PAYMENTS" MODIFY ("COUNTER_PAYMENT" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PAYMENTS" MODIFY ("TRANSACTION_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PAYMENTS" MODIFY ("CREATED_BY" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PAYMENTS" MODIFY ("BAILIFF_KNOWLEDGE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PAYMENTS" MODIFY ("DATE_ENTERED" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PAYMENTS" MODIFY ("PAYMENT_FOR" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PAYMENTS" MODIFY ("ISSUING_COURT" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PAYMENTS" MODIFY ("RETENTION_TYPE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PAYMENTS" MODIFY ("ERROR_INDICATOR" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PAYMENTS" MODIFY ("ADMIN_COURT_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PAYMENTS" MODIFY ("SUBJECT_NO" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PAYMENTS" MODIFY ("ENFORCEMENT_COURT_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PAYMENT_SUMMARY" MODIFY ("DCS_DATE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PAYMENT_SUMMARY" MODIFY ("REPORT_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PAYMENT_SUMMARY" MODIFY ("TRANSACTION_TOTAL" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PAYMENT_SUMMARY" MODIFY ("INOUT" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PAYMENT_SUMMARY" MODIFY ("VALID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PL_FILELEVEL_PREVAL_STATUS" MODIFY ("FILE_NAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PL_FILELEVEL_PREVAL_STATUS" MODIFY ("FILESIZE_VAL_PASSED" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PL_FILELEVEL_PREVAL_STATUS" MODIFY ("FILENAME_VAL_PASSED" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PL_FILELEVEL_PREVAL_STATUS" MODIFY ("PREVALIDATION_STATUS" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PL_FILELEVEL_PREVAL_STATUS" MODIFY ("FILE_TYPE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PL_JOB_QUEUE" MODIFY ("REQUEST_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PL_JOB_QUEUE" MODIFY ("REQUEST_DATE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PL_JOB_QUEUE" MODIFY ("CIRCUIT_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PL_JOB_QUEUE" MODIFY ("JOB_STATUS" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PL_RECORDLEVEL_PREVAL_STATUS" MODIFY ("RECORDSEQNO" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PL_RECORDLEVEL_PREVAL_STATUS" MODIFY ("FILE_NAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PL_XML_STATUS" MODIFY ("SEQUENCE_NO" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PL_XML_STATUS" MODIFY ("CIRCUIT_NAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PL_XML_STATUS" MODIFY ("SHELL_CIRCUIT_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PL_XML_STATUS" MODIFY ("DATE_TIME_STAMP" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PL_XML_STATUS" MODIFY ("STATUS" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PRE_REQ_EVENTS" MODIFY ("PRE_REQ_EVENT_ID1" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PRE_REQ_EVENTS" MODIFY ("STD_EVENT_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PRINTERS" MODIFY ("PRINTER_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PRINTERS" MODIFY ("QUEUENAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PRINTERS" MODIFY ("DESCRIPTION" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PRINTERS" MODIFY ("COURT_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PRINTER_TYPES" MODIFY ("MODEL" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PRINTER_TYPES" MODIFY ("DUPLEX" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PRINTER_TYPES" MODIFY ("POSTSCRIPT" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PRINTER_TYPES" MODIFY ("A5_POSTSCRIPT" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PRINTER_TYPES" MODIFY ("GENERAL" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PRINTER_TYPES" MODIFY ("WARRANT" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PRINTER_TYPES" MODIFY ("IMPACT" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PRINTER_TYPES" MODIFY ("RECEIPT" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PRINT_JOB" MODIFY ("PRINT_JOB_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PRINT_JOB" MODIFY ("REPORT_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PRINT_JOB" MODIFY ("COURT" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PRINT_JOB" MODIFY ("USER_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PRINT_JUDGMENTS" MODIFY ("CRED_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PRINT_JUDGMENTS" MODIFY ("JUDGMENT_TYPE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PRINT_JUDGMENTS" MODIFY ("REC_NO" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PRINT_JUDGMENTS" MODIFY ("PRINTED" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PRINT_RECORD_CARDS" MODIFY ("REC_NO" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."REJECT_REASONS" MODIFY ("REJECT_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."REJECT_REASONS" MODIFY ("REJECT_TEXT" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."REPORTS" MODIFY ("REPORT_NAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."REPORTS" MODIFY ("REPORT_TITLE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."REPORTS" MODIFY ("VALIDATION_FUNCTION" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."REPORTS" MODIFY ("ORIENTATION" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."REPORTS" MODIFY ("TRAY" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."REPORT_DATA" MODIFY ("USER_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."REPORT_DATA" MODIFY ("REPORT_TYPE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."REPORT_DATA" MODIFY ("REPORT_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."REPORT_DATA" MODIFY ("REPORT_DATE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."REPORT_MAP" MODIFY ("REPORT_QUEUE_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."REPORT_MAP" MODIFY ("REPORT_NAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."REPORT_MAP" MODIFY ("LEGACY_PATH" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."REPORT_MAP" MODIFY ("FILE_NAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."REPORT_OUTPUT" MODIFY ("OUTPUT_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."REPORT_OUTPUT" MODIFY ("REPORT_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."REPORT_PARAMETERS" MODIFY ("REPORT_NAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."REPORT_PARAMETERS" MODIFY ("PARAMETER_PROMPT" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."REPORT_PARAMETERS" MODIFY ("PARAMETER_NAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."REPORT_PARAMETERS" MODIFY ("DATA_TYPE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."REPORT_PARAMETERS" MODIFY ("REQUIRED" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."REPORT_PARAMETERS" MODIFY ("ORDERING_SEQUENCE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."REPORT_REPRINTS" MODIFY ("USERNAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."REPORT_REPRINTS" MODIFY ("REPORT_NAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."REPORT_REPRINTS" MODIFY ("REPORT_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."REPORT_REPRINTS" MODIFY ("REPORT_DATE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."REPORT_REPRINTS" MODIFY ("MODULE_GROUP" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."REPORT_REPRINTS" MODIFY ("PRINTED" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."REPORT_REPRINTS_XREF" MODIFY ("REPRINTS_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."REPORT_REPRINTS_XREF" MODIFY ("REPORT_REPRINTS_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."REPORT_REPRINTS_XREF" MODIFY ("USERNAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."REPORT_SEQUENCES" MODIFY ("FORM_NAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."REPRINTS" MODIFY ("CASE_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."REPRINTS" MODIFY ("USERNAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."REPRINTS" MODIFY ("REPORT_TYPE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."REPRINTS" MODIFY ("REPORT_DATE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."REPRINTS" MODIFY ("LOCATION" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."REPRINTS" MODIFY ("ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."REPRINT_TEXT_ITEMS" MODIFY ("ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."REPRINT_TEXT_ITEMS" MODIFY ("EVENT_SEQ" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."REPRINT_TEXT_ITEMS" MODIFY ("TEXT_CASE_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."REPRINT_TEXT_ITEMS" MODIFY ("TEXT_ORDER_ORD_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."REPRINT_TEXT_ITEMS" MODIFY ("DOMAIN" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."SECTIONS" MODIFY ("SECTION_NAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."SECTIONS" MODIFY ("ADMIN_COURT_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."SERVER_SECRET" MODIFY ("SERVER_SECRET_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."SUPS_AMENDMENTS" MODIFY ("TIME_STAMP" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."SUPS_AMENDMENTS" MODIFY ("DATE_OF_CHANGE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."SUPS_AMENDMENTS" MODIFY ("COURT_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."SUPS_AMENDMENTS" MODIFY ("USER_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."SUPS_AMENDMENTS" MODIFY ("PROCESS_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."SUPS_AMENDMENTS" MODIFY ("TABLE_NAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."SUPS_AMENDMENTS" MODIFY ("AMENDMENT_TYPE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."TAPES" MODIFY ("SEQNO" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."TAPES" MODIFY ("CUST_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."TAPE_FILES" MODIFY ("ORDERSEQ" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."TAPE_FILES" MODIFY ("SEQNO" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."TAPE_FILES" MODIFY ("FILE_NAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."TASK_ALLOCATIONS" MODIFY ("TASK_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."TASK_ALLOCATIONS" MODIFY ("SECTION_NAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."TASK_ALLOCATIONS" MODIFY ("START_DATE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."TASK_ALLOCATIONS" MODIFY ("ADMIN_COURT_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."TASK_COUNTS" MODIFY ("TASK_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."TASK_COUNTS" MODIFY ("TASK_DATE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."TASK_COUNTS" MODIFY ("AGE_CATEGORY" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."TASK_COUNTS" MODIFY ("ADMIN_COURT_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."TEMP" MODIFY ("COPSDATA" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."TEMP_PRINTERS" MODIFY ("PRINTER_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."TEMP_PRINTERS" MODIFY ("QUEUENAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."TEMP_PRINTERS" MODIFY ("DESCRIPTION" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."TEMP_PRINTERS" MODIFY ("COURT_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."TEMP_PRINTERS" MODIFY ("MODEL" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."TEMP_PRINTER_TYPES" MODIFY ("MODEL" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."TEMP_PRINTER_TYPES" MODIFY ("PRINTER_TYPE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."TEMP_USERS_PRINTERS" MODIFY ("USERNAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."TEMP_USERS_PRINTERS" MODIFY ("PRINTER_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."TEMP_USERS_PRINTERS" MODIFY ("PRINTER_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."TMP_REP" MODIFY ("REPORT_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."TRANSACTION_LIST" MODIFY ("TRANSACTION_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."TRAN_ADDRESS" MODIFY ("CRT_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."TRAN_ADDRESS" MODIFY ("ADDR_TYPE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."TRAN_ADDRESS" MODIFY ("ADDR_TYPE_SEQ" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."TRAN_CODED_PARTIES" MODIFY ("CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."TRAN_CODED_PARTIES" MODIFY ("NAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."TRAN_COURTS" MODIFY ("CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."TRAN_COURTS" MODIFY ("NAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."TRAN_PER_DETAILS" MODIFY ("DETAIL_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."TRAN_PER_DETAILS" MODIFY ("ORDER_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."TRAN_SYSTEM_DATA" MODIFY ("ITEM" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."UNIX_OUTPUT" MODIFY ("USERNAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."UNIX_OUTPUT" MODIFY ("LINE_NO" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."UNIX_OUTPUT" MODIFY ("UNIX_COMMAND" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."USERS" MODIFY ("USERNAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."USERS" MODIFY ("REMOTE_USER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."USERS" MODIFY ("DEFAULT_COURT" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."USERS_PRINTERS" MODIFY ("PRINTER_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."USERS_PRINTERS" MODIFY ("PRINTER_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."USERS_PRINTERS" MODIFY ("USERNAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."USER_COURT" MODIFY ("USER_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."USER_COURT" MODIFY ("DATE_FROM" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."USER_COURT" MODIFY ("HOME_FLAG" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."USER_COURT" MODIFY ("COURT_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."USER_COURT" MODIFY ("SECTION_NAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."USER_INFO_CASE_EVENTS" MODIFY ("USER_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."USER_ROLE" MODIFY ("USER_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."USER_ROLE" MODIFY ("ROLE_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."USER_ROLE" MODIFY ("COURT_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."VARIATIONS" MODIFY ("VARY_SEQ" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."VARIATIONS" MODIFY ("JUDG_SEQ" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."VARIATIONS" MODIFY ("APPLICATION_DATE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."VARIATIONS" MODIFY ("REQUESTER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."VARIATIONS" MODIFY ("OFFER_PERIOD" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."VARIATIONS" MODIFY ("OFFER_AMOUNT_CURRENCY" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."WARRANTS" MODIFY ("WARRANT_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."WARRANTS" MODIFY ("WARRANT_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."WARRANTS" MODIFY ("WARRANT_ISSUE_DATE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."WARRANTS" MODIFY ("WARRANT_TYPE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."WARRANTS" MODIFY ("PLAINTIFF_NAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."WARRANTS" MODIFY ("DEFENDANT1" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."WARRANTS" MODIFY ("CURRENTLY_OWNED_BY" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."WARRANT_RETURNS" MODIFY ("WARRANT_RETURNS_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."WARRANT_RETURNS" MODIFY ("WARRANT_RETURN_DATE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."WARRANT_RETURNS" MODIFY ("ERROR_INDICATOR" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."WARRANT_RETURNS" MODIFY ("NOTICE_REQUIRED" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."WARRANT_RETURNS" MODIFY ("RETURN_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."WARRANT_RETURNS" MODIFY ("WARRANT_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."WARRANT_RETURNS" MODIFY ("RETURN_CODE_COURT_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."WARRANT_RETURNS" MODIFY ("ADMIN_COURT_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."WFT_DM_TEMP" MODIFY ("WDT_CASE_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."WFT_DM_TEMP" MODIFY ("WDT_WFT_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."WFT_EXCLUSIONS" MODIFY ("WFE_EXCLUSION_DATE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."WFT_EXCLUSIONS" MODIFY ("WFE_WFT_CASE_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."WFT_EXCLUSIONS" MODIFY ("WFE_WFT_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."WFT_EXCLUSIONS_TEMP" MODIFY ("WET_CASE_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."WFT_EXCLUSIONS_TEMP" MODIFY ("WET_WFT_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."WFT_EXCLUSIONS_TEMP" MODIFY ("WET_DATE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."WFT_EXCLUSIONS_TEMP" MODIFY ("WET_USERID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."WINDOW_FOR_TRIAL" MODIFY ("WFT_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."WINDOW_FOR_TRIAL" MODIFY ("WFT_CASE_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."WINDOW_FOR_TRIAL" MODIFY ("WFT_CURRENT_COURT" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."WINDOW_FOR_TRIAL" MODIFY ("WFT_STATUS" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."WINDOW_FOR_TRIAL" MODIFY ("WFT_OUTCOME_DATE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."WORK_WF" MODIFY ("CASE_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."WORK_WF" MODIFY ("WARRANT_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."WORK_WF" MODIFY ("WARRANT_TYPE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."WORK_WF" MODIFY ("COURT" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."WORK_WF" MODIFY ("FEE_DATE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."WORK_WF" MODIFY ("WARRANT_ISSUE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."WP_TRANSFORMATIONS" MODIFY ("DOCUMENT_TEMPLATE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."WP_TRANSFORMATIONS" MODIFY ("TO_XHTML" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."WP_TRANSFORMATIONS" MODIFY ("TO_PDF" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."ASYNC_COMMAND" MODIFY ("ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."ASYNC_COMMAND" MODIFY ("USER_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."ASYNC_COMMAND" MODIFY ("COURT_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."ASYNC_COMMAND" MODIFY ("NODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."ASYNC_COMMAND" MODIFY ("SERVICE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."ASYNC_COMMAND" MODIFY ("METHOD" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."ASYNC_COMMAND" MODIFY ("DESTINATION" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."ASYNC_COMMAND" MODIFY ("REQUEST_TYPE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."ASYNC_COMMAND" MODIFY ("REQUEST" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."ASYNC_COMMAND" MODIFY ("STATE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CONTENT_STORE" MODIFY ("ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."DOCUMENT_STORE" MODIFY ("ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."DOCUMENT_STORE" MODIFY ("IS_VIEWED" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."DOCUMENT_STORE" MODIFY ("IS_PERSISTENT" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."REPORT_QUEUE" MODIFY ("ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."REPORT_QUEUE" MODIFY ("STATUS" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."REPORT_QUEUE" MODIFY ("MIME_TYPE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."REPORT_QUEUE" MODIFY ("TYPE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."REPORT_QUEUE" MODIFY ("CREATED_DATE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."REPORT_QUEUE" MODIFY ("STORAGE_DURATION" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."REPORT_QUEUE" MODIFY ("SEND_STATUS" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."WP_OUTPUT" MODIFY ("OUTPUT_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."WP_OUTPUT" MODIFY ("USER_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."MV_CMAN_PARTIES" MODIFY ("CASE_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."MV_CMAN_PARTIES" MODIFY ("PARTY_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."MV_CMAN_PARTIES" MODIFY ("PARTY_ROLE_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."MV_CMAN_PARTIES" MODIFY ("CASE_PARTY_NO" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."MV_CMAN_PARTY_ADDRESSES" MODIFY ("ADMIN_CRT_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."MV_CMAN_PARTY_ADDRESSES" MODIFY ("CASE_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."MV_CMAN_PARTY_ADDRESSES" MODIFY ("CASE_PARTY_NO" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."MV_CMAN_PARTY_ADDRESSES" MODIFY ("PARTY_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."MV_CMAN_PARTY_ADDRESSES" MODIFY ("PARTY_ROLE_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."MV_LATEST_WARRANT_RETURN_DATE" MODIFY ("WARRANT_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."MV_LATEST_WARRANT_RETURN_DATE" MODIFY ("RETURN_CODE_COURT_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."WINDOW_FOR_TRIAL" ADD CONSTRAINT "SYS_C002954" CHECK ( wft_estimated_hours BETWEEN 0 AND 5) ENABLE;



  ALTER TABLE "CASEMAN"."WINDOW_FOR_TRIAL" ADD CONSTRAINT "SYS_C002955" CHECK ( wft_estimated_mins BETWEEN 0 AND 59) ENABLE;



  ALTER TABLE "CASEMAN"."DELETE_SQL_ERRORS" MODIFY ("TYPE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."DELETE_SQL_ERRORS" MODIFY ("IDENTIFIER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."DELETE_SQL_ERRORS" MODIFY ("ERROR_MESSAGE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."DELETE_CANDIDATES" MODIFY ("TYPE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."DELETE_CANDIDATES" MODIFY ("IDENTIFIER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CO_STATE" MODIFY ("CO_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CASE_STATE" MODIFY ("CASE_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CDR_MCOL_EVENT_MAPPING" MODIFY ("STD_EVENT_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CDR_MCOL_STATUS_MAPPING" MODIFY ("CLAIM_STATUS" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CPT_CLAIMS" MODIFY ("CLAIM_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CPT_CLAIMS" MODIFY ("COURT_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CPT_CLAIMS" MODIFY ("CLAIM_AMOUNT" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CPT_CLAIMS" MODIFY ("COURT_FEE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CPT_CLAIMS" MODIFY ("SOLICITORS_COSTS" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CPT_CLAIMS" MODIFY ("TOTAL_AMOUNT" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CPT_CLAIMS" MODIFY ("ISSUE_DATE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CPT_CLAIMS" MODIFY ("SERVICE_DATE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CPT_CLAIMS" MODIFY ("STATUS" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CPT_CLAIMS" MODIFY ("CREDITOR_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CPT_DEFENDANTS" MODIFY ("CLAIM_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CPT_DEFENDANTS" MODIFY ("ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CPT_DEFENDANTS" MODIFY ("NAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CPT_DEFENDANTS" MODIFY ("ADDR_1" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CPT_LIBERATA_TOTAL_FEES" MODIFY ("ISSUE_DATE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CPT_LIBERATA_TOTAL_FEES" MODIFY ("REPORT_LINE_STRING" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CPT_PRINT_CLAIMS" MODIFY ("REC_NO" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CPT_PRINT_CLAIMS" MODIFY ("OMR_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CPT_PRINT_CLAIMS" MODIFY ("CREDITOR_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CPT_PRINT_CLAIMS" MODIFY ("BAR_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CPT_PRINT_CLAIMS" MODIFY ("CLAIM_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CPT_PRINT_CLAIMS" MODIFY ("COURT_NAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CPT_PRINT_CLAIMS" MODIFY ("COURT_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CPT_PRINT_CLAIMS" MODIFY ("AMOUNT" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CPT_PRINT_CLAIMS" MODIFY ("FEE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CPT_PRINT_CLAIMS" MODIFY ("COSTS" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CPT_PRINT_CLAIMS" MODIFY ("TOTAL" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CPT_PRINT_CLAIMS" MODIFY ("ISSUE_DATE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CPT_PRINT_CLAIMS" MODIFY ("PAGE_1_COUNT" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CPT_PRINT_CLAIMS" MODIFY ("PAGE_3_COUNT" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CPT_PRINT_CLAIMS" MODIFY ("PAGE_2_COUNT" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CPT_PRINT_CLAIMS" MODIFY ("PAGE_4_COUNT" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CPT_STATISTICS" MODIFY ("ISSUE_DATE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CPT_STATISTICS" MODIFY ("VALID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CPT_STATISTICS" MODIFY ("CREDITOR_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."DEFENCE_DOC_EVENT" MODIFY ("CASE_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."DEFENCE_DOC_EVENT" MODIFY ("VALIDATED" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."DEFENCE_DOC_EVENT" MODIFY ("VIA_SDT" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."DEFENCE_DOC_EVENT" MODIFY ("PRINT_NOW" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."LOAD_CASES" MODIFY ("VIA_SDT" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."LOAD_JUDGMENTS" MODIFY ("VIA_SDT" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."LOAD_PAID_WO_DETAILS" MODIFY ("VIA_SDT" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."LOAD_WARRANTS" MODIFY ("VIA_SDT" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."MCOL_MIG_CLAIM_DATA" MODIFY ("CASE_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."MCOL_MIG_CLAIM_DATA" MODIFY ("CRED_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."MCOL_MIG_EVENT_DATA" MODIFY ("CASE_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."MCOL_MIG_EVENT_DATA" MODIFY ("CRED_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."MCOL_MIG_EVENT_DATA" MODIFY ("EVENT_DATE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."MCOL_MIG_JUDGMENT_DATA" MODIFY ("CASE_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."MCOL_MIG_JUDGMENT_DATA" MODIFY ("CRED_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."MCOL_MIG_JUDGMENT_DATA" MODIFY ("AGAINST_CASE_PARTY_NO" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."MCOL_MIG_JUDGMENT_DATA" MODIFY ("JUDGMENT_DATE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."MCOL_MIG_PARTY_DATA" MODIFY ("CASE_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."MCOL_MIG_PARTY_DATA" MODIFY ("CRED_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."MCOL_MIG_PARTY_DATA" MODIFY ("PARTY_ROLE_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."MCOL_MIG_PARTY_DATA" MODIFY ("CASE_PARTY_NO" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."MCOL_MIG_WARRANT_DATA" MODIFY ("CASE_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."MCOL_MIG_WARRANT_DATA" MODIFY ("WARRANT_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."MCOL_MIG_WARRANT_DATA" MODIFY ("CRED_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."MCOL_PDF_STATUS" MODIFY ("CREATED_TS" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."MCOL_PDF_STATUS" MODIFY ("PDF_FILE_NAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."MCOL_PDF_STATUS" MODIFY ("LOADED" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."MCOL_PDF_STATUS" MODIFY ("PRINTED" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."MCOL_PDF_STATUS" MODIFY ("DELETED" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."MCOL_PDF_STATUS" MODIFY ("PRINT_NOW" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."MCOL_PDF_STATUS" MODIFY ("CASE_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."MCOL_PDF_STATUS" MODIFY ("ORDER_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PCOL_CASES" MODIFY ("CASE_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PCOL_DEFENDANTS" MODIFY ("CASE_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PCOL_DEFENDANTS" MODIFY ("ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PCOL_JUDGMENTS" MODIFY ("JUDG_SEQ" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PCOL_TRANSFER_CONTROL" MODIFY ("TRANSFER_TYPE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PCOL_TRANSFER_CONTROL" MODIFY ("TRANSFER_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PCOL_TRANSFER_CONTROL" MODIFY ("TRANSFER_DATE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PCOL_TRANSFER_CONTROL" MODIFY ("TRANS_SEQ" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PCOL_TRANS_FAILURES" MODIFY ("TRANSFER_TYPE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PCOL_TRANS_FAILURES" MODIFY ("CASE_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PCOL_TRANS_FAILURES" MODIFY ("TRANS_SEQ" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PCOL_TRANS_FAILURES" MODIFY ("FAILURE_DATE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PCOL_TRANS_FAILURES" MODIFY ("FAILURE_REASON" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PCOL_VARIATIONS" MODIFY ("VARY_SEQ" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PCOL_VARIATIONS" MODIFY ("JUDG_SEQ" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PCOL_VARIATIONS" MODIFY ("CASE_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PCOL_VARIATIONS" MODIFY ("APPLICATION_DATE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PCOL_VARIATIONS" MODIFY ("REQUESTER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PCOL_VARIATIONS" MODIFY ("OFFER_AMOUNT" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PCOL_VARIATIONS" MODIFY ("OFFER_PERIOD" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PCOL_WARRANTS" MODIFY ("WARRANT_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PCOL_WARRANTS" MODIFY ("ISSUED_BY" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."SET_ASIDE_REQUESTS" MODIFY ("CASE_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."SET_ASIDE_REQUESTS" MODIFY ("PARTY_ROLE_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."SET_ASIDE_REQUESTS" MODIFY ("DEFENDANT_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."SET_ASIDE_REQUESTS" MODIFY ("FEE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."SET_ASIDE_REQUESTS" MODIFY ("PDF_FILE_NAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."SET_ASIDE_REQUESTS" MODIFY ("CUST_FILE_SEQUENCE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."SET_ASIDE_REQUESTS" MODIFY ("VALIDATED" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."SET_ASIDE_REQUESTS" MODIFY ("VIA_SDT" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."SET_ASIDE_REQUESTS" MODIFY ("MCOL_REFERENCE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."TMP_DPA_PARTIES_CACHE" MODIFY ("PARTY_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."TMP_MCOL_MIG_CRED_CLAIMS" MODIFY ("CASE_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."TMP_MCOL_MIG_EVENT_MAPPING" MODIFY ("STD_EVENT_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."TMP_MCOL_MIG_FAILURES" MODIFY ("CASE_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."TMP_MCOL_MIG_FAILURES" MODIFY ("FAILURE_REASON" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."TMP_MCOL_MIG_INFO" MODIFY ("CRED_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."TMP_MCOL_MIG_STATUS_MAPPING" MODIFY ("CLAIM_STATUS" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."TMP_RTL_CHARACTER_MAP" MODIFY ("ASCII_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."TMP_RTL_JUDGMENTS" MODIFY ("JUDG_SEQ" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."TMP_RTL_JUDGMENTS" MODIFY ("JUDGMENT_TYPE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."ADDRESS_TYPES" MODIFY ("ADDRESS_TYPE_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."STANDARD_EVENTS" MODIFY ("EVENT_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."STANDARD_EVENTS" MODIFY ("CATEGORY" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."STANDARD_EVENTS" MODIFY ("DESCRIPTION" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."STANDARD_EVENTS" MODIFY ("DATABASE_EVENT" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."STANDARD_EVENTS" MODIFY ("EDIT_DETAILS" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CHANGED_EVENTS" MODIFY ("STD_EVENT_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CHANGED_EVENTS" MODIFY ("RELEASE_DATE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CHANGED_EVENTS" MODIFY ("FINAL_DATE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."DFJ_AREAS" MODIFY ("DFJ_AREA_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."DFJ_AREAS" MODIFY ("DESCRIPTION" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."COURTS" MODIFY ("CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."COURTS" MODIFY ("NAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."COURTS" MODIFY ("DFJ_AREA_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CO_EVENT_VALIDATIONS" MODIFY ("STD_EVENT_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CO_EVENT_VALIDATIONS" MODIFY ("CO_EVENT_SUB_TYPE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."ITEM_DETAILS" MODIFY ("CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."ITEM_DETAILS" MODIFY ("ORDER_TYPE_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."ITEM_DETAILS" MODIFY ("LIST" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."ITEM_DETAILS" MODIFY ("FORMAT" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."ITEM_DETAILS" MODIFY ("PROMPT" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."ORDER_TYPES" MODIFY ("ORDER_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."ORDER_TYPES" MODIFY ("ORDER_DESCRIPTION" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."ORDER_TYPES" MODIFY ("DISPLAY_ORDER_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."ORDER_TYPES" MODIFY ("DOCUMENT_TYPE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."ORDER_TYPES" MODIFY ("LEGAL_DESCRIPTION" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."ORDER_TYPES" MODIFY ("MODULE_NAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."ORDER_TYPES" MODIFY ("PRINTER_TYPE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."ORDER_TYPES" MODIFY ("REPORT_TYPE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."ORDER_TYPES" MODIFY ("TRAY" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CO_TEXT_ITEMS" MODIFY ("CO_TEXT_CO_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CO_TEXT_ITEMS" MODIFY ("CO_TEXT_EVENT_SEQ" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CO_TEXT_ITEMS" MODIFY ("CO_TEXT_ORDER_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CO_TEXT_ITEMS" MODIFY ("CO_TEXT_DETAIL_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CO_TEXT_ITEMS" MODIFY ("CO_TEXT_PROMPT" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CO_TEXT_ITEMS" MODIFY ("CO_TEXT_HINT_LINE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CO_TEXT_ITEMS" MODIFY ("CO_TEXT_FORMAT" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."CURRENCY" MODIFY ("CURRENCY_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."DELETE_EXCEPTION_REASONS" MODIFY ("EXCEPTION_REASON" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."DELETE_EXCEPTION_REASONS" MODIFY ("DESCRIPTION" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."DELETE_EXCEPTION_REASONS" MODIFY ("REPORT" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."DOCUMENT_VARIABLES" MODIFY ("CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."DOCUMENT_VARIABLES" MODIFY ("DESCRIPTION" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."ECHR_ARTICLE_PROTOCOL" MODIFY ("EVENT_SEQ" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."ECHR_ARTICLE_PROTOCOL" MODIFY ("ART_OR_PROT" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."ECHR_ARTICLE_PROTOCOL" MODIFY ("VALS_LOW_VALUE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."ECHR_ARTICLE_PROTOCOL" MODIFY ("DESCRIPTION" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."ECHR_ARTICLE_PROTOCOL" MODIFY ("DEFT_CASE_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."ENFORCEMENT_LETTERS" MODIFY ("YEAR_VALUE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."ENFORCEMENT_LETTERS" MODIFY ("LETTER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."EVENT_DELETION_RULES" MODIFY ("STD_EVENT_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."EVENT_DELETION_RULES" MODIFY ("EVENT_TYPE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."GIVEN_ADDRESSES" MODIFY ("ADDRESS_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."JUDGES" MODIFY ("JUDGE_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."JUDGES" MODIFY ("JUDGE_TYPE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."JUDGES" MODIFY ("REQUESTED_NAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."JUDGES" MODIFY ("COURT_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."NON_WORKING_DAYS" MODIFY ("NON_WD_SEQ" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."NON_WORKING_DAYS" MODIFY ("NON_WORKING_DATE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."NON_WORKING_DAYS" MODIFY ("USERNAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."NON_WORKING_DAYS" MODIFY ("CREATION_DATE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."NON_WORKING_DAYS" MODIFY ("ERROR_INDICATOR" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."NON_WORKING_DAYS_EXCEPTIONS" MODIFY ("NON_WD_EX_SEQ" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."NON_WORKING_DAYS_EXCEPTIONS" MODIFY ("NON_WORKING_DATE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."NON_WORKING_DAYS_EXCEPTIONS" MODIFY ("USERNAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."NON_WORKING_DAYS_EXCEPTIONS" MODIFY ("CREATION_DATE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."NON_WORKING_DAYS_EXCEPTIONS" MODIFY ("ERROR_INDICATOR" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."NON_WORKING_DAYS_EXCEPTIONS" MODIFY ("COURT_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."NON_WORKING_DAYS_EXCEPTIONS" MODIFY ("NON_WD_SEQ" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."OBLIGATION_EVENTS" MODIFY ("EVENT_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."OBLIGATION_EVENTS" MODIFY ("MAINTENANCE_MODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."OBLIGATION_EVENTS" ADD CHECK ( maintenance_mode IN ( 'C' , 'M' )) ENABLE;



  ALTER TABLE "CASEMAN"."OBLIGATION_TYPES" MODIFY ("OBLIGATION_TYPE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."OBLIGATION_TYPES" MODIFY ("OBLIGATION_TEXT" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."OBLIGATION_TYPES" MODIFY ("MULTI_USE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."OBLIGATION_RULES" MODIFY ("OBLIGATION_TYPE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."OBLIGATION_RULES" MODIFY ("MECHANISM" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."OBLIGATION_RULES" MODIFY ("ACTION" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."OBLIGATION_RULES" MODIFY ("EVENT_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."OBLIGATION_RULES" ADD CHECK ( mechanism IN ( 'A' , 'M' , 'O' )) ENABLE;



  ALTER TABLE "CASEMAN"."OBLIGATION_RULES" ADD CHECK ( action IN ( 'C' , 'M' , 'D' )) ENABLE;



  ALTER TABLE "CASEMAN"."OUTPUT_DETAILS" MODIFY ("OD_SEQ" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."OUTPUT_DETAILS" MODIFY ("ORDER_TYPE_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."OUTPUT_DETAILS" MODIFY ("LAYOUT_GROUP" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."OUTPUT_DETAILS" MODIFY ("CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."OUTPUT_DETAILS" MODIFY ("FORMAT_STYLE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."OUTPUT_DETAILS" MODIFY ("FONT1" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PARTY_ROLES" MODIFY ("PARTY_ROLE_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PARTY_ROLES" MODIFY ("REPORTING_ROLE_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PARTY_TYPES" MODIFY ("PARTY_TYPE_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PERSONALISE" MODIFY ("CRT_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PERSONALISE" MODIFY ("ACCOUNT_TYPE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PERSONALISE" MODIFY ("ACCOUNTING_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PER_DETAILS" MODIFY ("DETAIL_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PER_DETAILS" MODIFY ("PER_CATEGORY" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PER_DETAILS" MODIFY ("ORDER_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PER_DETAILS" MODIFY ("PROMPT" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."PER_DETAILS" MODIFY ("AMOUNT_ALLOWED_EDITABLE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."RETURN_CODES" MODIFY ("RETURN_CATEGORY" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."RETURN_CODES" MODIFY ("RETURN_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."RETURN_CODES" MODIFY ("RETURN_TYPE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."RETURN_CODES" MODIFY ("RETURN_CLASS" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."RETURN_CODES" MODIFY ("RETURN_CODE_SUMMARY" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."RETURN_CODES" MODIFY ("CURRENT_RETURN" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."RETURN_CODES" MODIFY ("ADMIN_COURT_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."SUB_DETAIL_VARIABLES" MODIFY ("SDV_SEQ" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."SUB_DETAIL_VARIABLES" MODIFY ("OD_SEQ" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."SUB_DETAIL_VARIABLES" MODIFY ("SUB_ITEM_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."SUB_DETAIL_VARIABLES" MODIFY ("VARIABLE_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."SYSTEM_DATA" MODIFY ("ITEM" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."SYSTEM_DATA" MODIFY ("ADMIN_COURT_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."TASK_TYPES" MODIFY ("TASK_TYPE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."TASKS" MODIFY ("TASK_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."TASKS" MODIFY ("TASK_TYPE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."TEXT_ITEMS" MODIFY ("TEXT_CASE_NUMBER" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."TEXT_ITEMS" MODIFY ("TEXT_ORDER_ORD_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."TEXT_ITEMS" MODIFY ("TEXT_DETAIL_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."VALID_VALUES" MODIFY ("VALS_SEQ" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."WFT_EXPORTS" MODIFY ("FILENAME" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."WFT_EXPORTS" MODIFY ("COURT_CODE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."WFT_EXPORTS" MODIFY ("EXPORT_DATE" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."WFT_EXPORTS" MODIFY ("REPORT_QUEUE_ID" NOT NULL ENABLE);



  ALTER TABLE "CASEMAN"."TAPES" ADD CONSTRAINT "TAPE_DEGA_VALI_150866426" CHECK (degaussed IN ('Y', 'N')) ENABLE;



  ALTER TABLE "CASEMAN"."ASYNC_COMMAND" ADD CONSTRAINT "VALID_ASYNCH_COMM_REQ_TYPE" CHECK (REQUEST_TYPE IN (0, 1)) ENABLE;



  ALTER TABLE "CASEMAN"."ASYNC_COMMAND" ADD CONSTRAINT "VALID_ASYNCH_COMM_STATE" CHECK (STATE IN (0, 1, 2, 3, 4)) ENABLE;



  ALTER TABLE "CASEMAN"."FTP_QUEUE" ADD CONSTRAINT "VALID_FTP_TRANSFER_STATUS" CHECK (STATUS IN (0, 1, 2, 4, 5)) ENABLE;



  ALTER TABLE "CASEMAN"."FTP_QUEUE" ADD CONSTRAINT "VALID_FTP_TRANSFER_TYPE" CHECK (FTP_TRANSFER_TYPE IN ('binary', 'ascii')) ENABLE;



  ALTER TABLE "CASEMAN"."LOCAL_AUTHORITY_CODES" ADD CONSTRAINT "VALID_LAC_ACTION" CHECK (LAC_ACTION IN ('D', 'I', 'U')) ENABLE;



  ALTER TABLE "CASEMAN"."PL_JOB_QUEUE" ADD CONSTRAINT "VALID_PL_JOB_QUEUE_STATUS" CHECK (JOB_STATUS IN (0, 1, 2, 3, 4)) ENABLE;



  ALTER TABLE "CASEMAN"."PL_XML_STATUS" ADD CONSTRAINT "VALID_PL_XML_STATUS2" CHECK (STATUS IN ('S', 'H', 'F', 'X')) ENABLE;



  ALTER TABLE "CASEMAN"."PL_FILELEVEL_PREVAL_STATUS" ADD CONSTRAINT "VALID_PREVALIDATION_STATUS" CHECK (prevalidation_status IN ('PASSED', 'FAILED', 'PENDING')) ENABLE;



  ALTER TABLE "CASEMAN"."PARTY_ROLES" ADD CONSTRAINT "VALID_REPORTING_ROLE_CODE" CHECK (REPORTING_ROLE_CODE IN ('CLAIMANT', 'DEFENDANT', 'SOLICITOR', 'OTHER')) ENABLE;



  ALTER TABLE "CASEMAN"."CPT_STATISTICS" ADD CONSTRAINT "VALID_RULE_6" CHECK (valid in ( 'Y' , 'N' )) ENABLE;



  ALTER TABLE "CASEMAN"."TAPE_FILES" ADD CONSTRAINT "VALID_TAPE_FILES_STATUS" CHECK (status IN ('L', 'H', 'E', 'X', 'T')) ENABLE;



  ALTER TABLE "CASEMAN"."REPORT_QUEUE" ADD CONSTRAINT "VALID_TRUE_FALSE_INDICATOR" CHECK (PRINT_REQUIRED IN ('T', 'F')) ENABLE;



  ALTER TABLE "CASEMAN"."REPORT_QUEUE" ADD CONSTRAINT "VALID_TRUE_FALSE_INDICATOR1" CHECK (SEND_REQUIRED IN ('T', 'F')) ENABLE;



  ALTER TABLE "CASEMAN"."DOCUMENT_STORE" ADD CONSTRAINT "VALID_TRUE_FALSE_INDICATOR2" CHECK (IS_VIEWED IN ('T', 'F')) ENABLE;



  ALTER TABLE "CASEMAN"."DOCUMENT_STORE" ADD CONSTRAINT "VALID_TRUE_FALSE_INDICATOR3" CHECK (IS_PERSISTENT IN ('T', 'F')) ENABLE;



  ALTER TABLE "CASEMAN"."COURTS" ADD CONSTRAINT "VALID_TUCS_IN_USE" CHECK (TUCS_IN_USE IN ('Y', 'N', 'F')) ENABLE;



  ALTER TABLE "CASEMAN"."JUDGES" ADD CONSTRAINT "VALID_YES_NO_INDICATOR1" CHECK (DELETE_FLAG IN ('Y', 'N')) ENABLE;



  ALTER TABLE "CASEMAN"."NON_WORKING_DAYS_EXCEPTIONS" ADD CONSTRAINT "VALID_YES_NO_INDICATOR10" CHECK (ERROR_INDICATOR IN ('Y', 'N')) ENABLE;



  ALTER TABLE "CASEMAN"."USER_COURT" ADD CONSTRAINT "VALID_YES_NO_INDICATOR2" CHECK (HOME_FLAG IN ('Y', 'N')) ENABLE;



  ALTER TABLE "CASEMAN"."DCA_USER" ADD CONSTRAINT "VALID_YES_NO_INDICATOR3" CHECK (ACTIVE_USER_FLAG IN ('Y', 'N')) ENABLE;



  ALTER TABLE "CASEMAN"."AUDIT_CONFIG" ADD CONSTRAINT "VALID_YES_NO_INDICATOR4" CHECK (AUDITED IN ('Y', 'N')) ENABLE;



  ALTER TABLE "CASEMAN"."PRINT_JUDGMENTS" ADD CONSTRAINT "VALID_YES_NO_INDICATOR5" CHECK (printed IN ('Y', 'N')) ENABLE;



  ALTER TABLE "CASEMAN"."LOAD_WARRANTS" ADD CONSTRAINT "VALID_YES_NO_INDICATOR6" CHECK (validated IN ('Y', 'N')) ENABLE;



  ALTER TABLE "CASEMAN"."OBLIGATION_TYPES" ADD CONSTRAINT "VALID_YES_NO_INDICATOR7" CHECK (MULTI_USE IN ('Y', 'N')) ENABLE;



  ALTER TABLE "CASEMAN"."OBLIGATIONS" ADD CONSTRAINT "VALID_YES_NO_INDICATOR8" CHECK (DELETE_FLAG IN ('Y', 'N')) ENABLE;



  ALTER TABLE "CASEMAN"."PL_FILELEVEL_PREVAL_STATUS" ADD CONSTRAINT "VALID_YES_NO_INDICATOR9" CHECK (filesize_val_passed IN ('Y', 'N')) ENABLE;



  ALTER TABLE "CASEMAN"."WFT_EXCLUSIONS" ADD CONSTRAINT "WFT__WFE__VALI_989868546" CHECK (WFE_DELETE_FLAG IN ('Y', 'N')) ENABLE;



  ALTER TABLE "CASEMAN"."WP_OUTPUT" ADD CONSTRAINT "WP_O_FINA_VALI_539106815" CHECK (FINAL_IND IN ('Y', 'N')) ENABLE;



  ALTER TABLE "CASEMAN"."WP_OUTPUT" ADD CONSTRAINT "WP_O_PRIN_VALI_590541033" CHECK (PRINTED IN ('Y', 'N')) ENABLE;


