#!/bin/bash
########################################
#
# FILENAME      : $HeadURL$:
#
# SYNOPSIS      : Shell script to run the the mv_qbp creation script present in ddl_trac_3122.sql.
#                 Run at the Database tier.
#
#
# $Author$:       Author of last commit
#
# CLIENT        : Ministry of Justice
#
# COPYRIGHT     : (c) 2009 Logica plc.
#                 This file contains information which is confidential and of
#                 value to Logica. It may be used only for the specific purpose for
#                 which it has been provided. Logica's prior written consent is
#                 required before any part is reproduced.
#
# COMMENTS      : This script is to be invoked with the following command line parameters:
#                 $1 - This parameter to contain the Oracle SID
#
#                 $2 - This parameter to contain the Oracle schema login username
#
#                 $3 - This parameter to contain the Oracle schema login password
#
#
###########################################
#
# $Rev$:          Revision of last commit
# $Date$:         Date of last commit
# $Id$            Revision at last change

#############################################
# Read functions in from common file
#############################################
APP_DIR_PATH=/filestore/app/caseman
. $APP_DIR_PATH/etc/cm-common-variables

#############################
# ScriptName variables
#############################
SCRIPT_NAME_FULL=$0
SCRIPT_NAME=${SCRIPT_NAME_FULL##*/}
SCRIPT_NAME_NOEXT=${SCRIPT_NAME%%\.sh}
REMOVE_OLDER_THAN=30

#############################
# Date Variables
#############################
START_DATE=`date`
DATE_LOG=`date +%Y%m%d_%H%M`
TODAY=${DATE_LOG}

#############################
# Log File Variables
#############################
LOG_FILE_NAME=${SCRIPT_NAME_NOEXT}_${DATE_LOG}.log

#############################
# Define all global functions
#############################
# Function to display message to the log file
function w1
{

    echo "${1}" >>${APP_DIR_PATH}/log/mview/${LOG_FILE_NAME}

}

function initialiseScript
{

        rm -f  ${BASE_DIR}/${APP_NAME}/log/mview/${LOG_FILE_NAME}
        touch  ${BASE_DIR}/${APP_NAME}/log/mview/${LOG_FILE_NAME}
}

#############################
# SCRIT STARTS HERE
#############################

initialiseScript

w1 " "
w1 "INFO: RUNNING SCRIPT $SCRIPT_NAME." >>$APP_DIR_PATH/log/mview/${LOG_FILE_NAME}
w1 " "
w1 "INFO: START: TIMESTAMP: $START_DATE"  >>$APP_DIR_PATH/log/mview/${LOG_FILE_NAME}

###################################################################
# Execute the ddl_trac_3122.sql script for the specified user and password
###################################################################
START_TIMESTAMP=$(/bin/date +%s)

${SQLPLUS} ${DB_USER}/${DB_IDENTIFIER}@${DB_INSTANCE}<<ENDSQL
@$APP_DIR_PATH/sql/ddl_trac_3122.sql
exit
ENDSQL
SQLPLUS_RETURN_CODE=$?

########################################
# Log the end of script date/time entry
########################################
END_TIMESTAMP=$(/bin/date +%s)
RUNTIME=$((${END_TIMESTAMP} - ${START_TIMESTAMP}))
END_DATE=`date`

w1 " "
w1 "INFO: END: TIMESTAMP: ${END_DATE}" >>$APP_DIR_PATH/log/mview/${LOG_FILE_NAME}
w1 "INFO: RUNTIME = ${RUNTIME} seconds" >>$APP_DIR_PATH/log/mview/${LOG_FILE_NAME}
w1 " "

#########################################################################
# Now let's remove old log files greater than the specified days old, as
# determined by the $4 parameter. Log this to the output log file.
# Note: this applies to the sql script's .out file as well as the .log
# file generated by this bash script.
#########################################################################
w1 " "
w1 "Removing old .log files greater than: $REMOVE_OLDER_THAN day(s) old." >>$APP_DIR_PATH/log/mview/${LOG_FILE_NAME}
w1 " "
find $APP_DIR_PATH/log/mview/ddl_trac_3122* -mtime $REMOVE_OLDER_THAN  -exec rm -v {} \;

