#!/bin/bash
########################################
#
# FILENAME      : $HeadURL: http://sups/svn/trunk/Caseman-CCBC/DDL/ddl_trac_1071_a.sh $:
#
# SYNOPSIS      : Shell script to run the the v_cman_parties creation script present in ddl_trac_1071_a.sql.
#                 Run at the Database tier.
#
#
# $Author: westm $:       Author of last commit
#
# CLIENT        : Ministry of Justice
#
# COPYRIGHT     : (c) 2009 Logica plc.
#                 This file contains information which is confidential and of
#                 value to Logica. It may be used only for the specific purpose for
#                 which it has been provided. Logica's prior written consent is
#                 required before any part is reproduced.
#
# COMMENTS      : This script is to be invoked with the following command line parameters:
#                 $1 - This parameter to contain the Oracle SID
#
#                 $2 - This parameter to contain the Oracle schema login username
#
#                 $3 - This parameter to contain the Oracle schema login password
#
#
###########################################
#
# $Rev: 3409 $:          Revision of last commit
# $Date: 2009-07-22 13:51:38 +0100 (Wed, 22 Jul 2009) $:         Date of last commit
# $Id: ddl_trac_1071_a.sh 3409 2009-07-22 12:51:38Z westm $            Revision at last change

#############################################
# Read functions in from common file
#############################################
. ${BASE_DIR}/${APP_NAME}/bin/${APP_ID}-common-functions

#############################
# ScriptName variables
#############################
SCRIPT_NAME_FULL=$0
SCRIPT_NAME=${SCRIPT_NAME_FULL##*/}
SCRIPT_NAME_NOEXT=${SCRIPT_NAME%%\.sh}
REMOVE_OLDER_THAN=30


#############################
# Date Variables
#############################
START_DATE=`date`
DATE_LOG=`date +%Y%m%d_%H%M`
TODAY=${DATE_LOG}

#############################
# Log File Variables
#############################
LOG_FILE_NAME=${SCRIPT_NAME_NOEXT}_${DATE_LOG}.log



#############################
# Define all global functions
#############################

# Function to display message to the log file
function w1
{

    echo "${1}" >> ${BASE_DIR}/${APP_NAME}/log/mview/${LOG_FILE_NAME}
    echo "${1}"

}


function initialiseScript
{

    rm -f ${LOG_FILE_NAME}

}

#############################
# SCRIT STARTS HERE
#############################

initialiseScript

w1 " "
w1 "INFO: RUNNING SCRIPT $SCRIPT_NAME."
w1 " "
w1 "INFO: START: TIMESTAMP: $START_DATE"

###################################################################
# Execute the ddl_trac_1071_a.sql script for the specified user and password
###################################################################
START_TIMESTAMP=$(/bin/date +%s)

${SQLPLUS} ${DB_USER}/${DB_IDENTIFIER}@${DB_INSTANCE}<<ENDSQL
SET SERVEROUT ON
SET TERMOUT   ON
SET VERIFY    OFF
@${BASE_DIR}/${APP_NAME}/sql/ddl_trac_1071_a.sql
exit
ENDSQL
SQLPLUS_RETURN_CODE=$?


#define the expected location of the ddl_trac_1071_a.sql .out files
DBA=`echo ${BASE_DIR}/${APP_NAME}/log/mview`

########################################
# Log the end of script date/time entry
########################################
END_TIMESTAMP=$(/bin/date +%s)
RUNTIME=$((${END_TIMESTAMP} - ${START_TIMESTAMP}))
END_DATE=`date`

w1 " "
w1 "INFO: END: TIMESTAMP: ${END_DATE}"
w1 "INFO: RUNTIME = ${RUNTIME} seconds"
w1 " "


#########################################################################
# Now let's remove old log files greater than the specified days old, as
# determined by the $4 parameter. Log this to the output log file.
# Note: this applies to the sql script's .out file as well as the .log
# file generated by this bash script.
#########################################################################
w1 " "
w1 "Removing old .log files greater than: $REMOVE_OLDER_THAN day(s) old."
w1 " "

find  ${BASE_DIR}/${APP_NAME}/log/mview -name /ddl_trac_1071_a* -mtime $REMOVE_OLDER_THAN  -exec rm -v {} \;
