WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
WHENEVER OSERROR EXIT FAILURE

SET SERVEROUT ON
SET TERMOUT   ON
SET VERIFY    OFF

/*-------------------------------------------------------------------------------
|
| $HeadURL$:
|
| SYNOPSIS      :  Schema changes required for the Window for Trial PolarLake
|				   replacement.
|
| $Author$:       Author of last commit
|
| CLIENT        : Ministry of Justice
|
| COPYRIGHT     : (c) 2015 CGI UK Limited.
|                 This file contains information which is confidential and of
|                 value to CGI. It may be used only for the specific purpose for
|                 which it has been provided. CGI's prior written consent is
|                 required before any part is reproduced.
|
| COMMENTS      : Indexes to improve the document cleardown process
|
|---------------------------------------------------------------------------------
|
| $Rev$:          Revision of last commit
| $Date$:         Date of last commit
| $Id$         Revision at last change
|
--------------------------------------------------------------------------------*/

SPOOL ddl_trac_5887.log

PROMPT ************************************************************************
PROMPT Creating WFT_EXPORTS table
PROMPT ************************************************************************

BEGIN

	EXECUTE IMMEDIATE 'DROP TABLE wft_exports';

	EXCEPTION

	WHEN OTHERS THEN
		   NULL;
END;
/

CREATE TABLE wft_exports
(
	filename		VARCHAR2(50)	NOT NULL	PRIMARY KEY,
	court_code      NUMBER(3)		NOT NULL,
	export_date 	DATE			NOT NULL,
	report_queue_id	NUMBER			NOT NULL
);

COMMENT ON TABLE wft_exports IS 'Holds details on the window for trial exports generated by the batch';

PROMPT ************************************************************************
PROMPT table created
PROMPT ************************************************************************

PROMPT ************************************************************************
PROMPT Alter COURTS table
PROMPT ************************************************************************

BEGIN

	EXECUTE IMMEDIATE 'ALTER TABLE courts DROP COLUMN dm_court_code';

	EXCEPTION

	WHEN OTHERS THEN
		   NULL;
END;
/

ALTER TABLE courts
ADD (dm_court_code	NUMBER(3));

--ALTER TABLE courts
--DROP COLUMN wft_dm_email_address;

PROMPT ************************************************************************
PROMPT COURTS table altered
PROMPT ************************************************************************

SPOOL OFF