###############################################################################################
#
#	refer to XMLQuery2/release_notes/serverside-build-readme.txt for properties in this file
#
################################################################################################

#Mandatory properties
application.name=test_project
#D:/eclipse/workspace/tools/extracted/jboss-4.0.1/server/default
jboss.server.dir=D:/eclipse/workspace/tools/extracted/jboss-4.0.1/server/default
oas.server.dir=Replace with local value if target.platform=OAS
project.config=uk/gov/dca/${application.name}/project_config.xml
using.async=true

#Optional properties
#application.src
#application.base
#application.build
#application.dist
#application.lib
#application.bin
application.conf=${application.base}/config


oas.deploy.dir=D:/oc4j-9.0.4/j2ee/home/applications

application.service.uri.prefix=/test_project

#custom.path
#custom.ant.build.file
#custom.ant.build.dir
#target.platform=OAS

# See the documentation for a proper description of each item.
ant-contrib-jar=D:/eclipse/workspace/tools/extracted/ant-contrib-1.0b1/ant-contrib/lib/ant-contrib-1.0b1.jar

oracle.https.port=7443
jboss.https.port=8443

# add this property in if you require the webservices to be configured
#create.web.services=true

SERVICE_CONFIG_DIRECTORY=${oas.deploy.dir}/testProjectConfig
