########################################################################
#
# set the directory where oc4j standalone is installed by either 
# configuring an environment variable OC4J_HOME using your advanced settings 
# in your Computer properties. 
#
#########################################################################

oc4j.home.dir=c:/oc4j-9.0.4
oc4j.admin.password=oracle

framework.release=D:/eclipse/workspace/XMLQuery2_HEAD/build/release

debug.socket=-Xrunjdwp:transport=dt_socket,address=8787,server=y,suspend=y

oc4j.check.server=localhost
oc4j.check.port=7070

oc4j.secure.port=7443

ocj4.https.site=sups-https-web-site
ocj4.http.site=sups-http-web-site

oc4j.admin.url=ormi://localhost:23791

oc4j.xbootclasspath=-Xbootclasspath/a:${oc4j.home.dir}/jdbc/lib/ojdbc14.jar;${oc4j.home.dir}/jdbc/lib/orai18n.jar;${oc4j.home.dir}/xalan/xalan.jar;${oc4j.home.dir}/xalan/xml-apis.jar;${oc4j.home.dir}/xalan/xercesImpl.jar