# environment dependant properties:
# userid=@oracle.db.user@/@oracle.db.password@@@oracle.db.sid@
# server.name=@oracle.reportserver.name@
# soapURL=http://@oracle.reportserver.host@:@oracle.reportserver.port@/reports/rwwebservice 
# 
# general properties:
# Chnage History:
# 26-Mar-2010, Chris Vincent, upped completionAttempts to 1200.  Trac 2621.
outputType=pdf
mode=bitmap
desType=cache
synchronous=false
completionAttempts=1200
completionAttemptInterval=1000
desTypeFW=DB
# service=@report.service@
# Temporary property until we can get it from Courts table
# fap_server=CSF20069
# Temporary property used if the anonymous user has loggged in
# printer=csp00002
report_storage_duration=7