tools.ep_analyzer.schema=CASEMAN
tools.ep_analyzer.password=password
tools.ep_analyzer.connection_url=jdbc:oracle:thin:@127.0.0.1:1521:orcl
tools.ep_analyzer.db_driver=oracle.jdbc.driver.OracleDriver
tools.ep_analyzer.explain_plan_table=PLAN_TABLE
tools.ep_analyzer.p6spy_log=D:\\PerfData\\spy logs\\WP\\spy9.log
tools.ep_analyzer.output_log_dir=D:\\PerfData\\spy logs\\WP\\9

# properties used to control output
tools.ep_analyzer.cardinality_threshold=50
tools.ep_analyzer.cost_threshold=30