/****************************************************************************************************************
						Run CM_RCPT Postal Receipts

 * Change History *
 26 July 2006 Kevin Gichohi (EDS) - Exception handling was changed on the server, hence it should also change
 									on the client as wrong message was being displayed. CaseMan TD4061	
****************************************************************************************************************/

/*****************************************************************************************************************
											GLOBAL VARIABLES
*****************************************************************************************************************/
		
var reportModuleGroup = ""
		
var __tabIdx = 300;
			
// XPath constants
var ROOT_XPATH = "/ds";
var REF_XPATH = "/ds/var/form";
var REF_DATA_XPATH = ROOT_XPATH + "/var/form/ReferenceData";
var PAGE_XPATH = ROOT_XPATH + "/var/page";
var PAGE_BMSR_XPATH = PAGE_XPATH + "/OracleReportForm";  // Place all input/output data in page context

var _paymentsExistsXPath = "/ds/var/page/OracleReportForm/PaymentsExists";

var dateCreated = null;

/*****************************************************************************************************************
												MAIN FORM
*****************************************************************************************************************/
		
/**
 * Form element
 * @author bz6s80
 * 
 */
function OracleReportForm() {}
		
OracleReportForm.refDataServices = [
	{name:"SystemDate", dataBinding:REF_DATA_XPATH, serviceName:"getSystemDate", serviceParams:[]},
	{name:"Courts", dataBinding:REF_DATA_XPATH, serviceName:"getCourtsShort", serviceParams:[]}
];
			
		
// Header Fields and Save Button for WP Parameter form

	
// Form Keybindings
OracleReportForm.keyBindings = [
/**
 * @author bz6s80
 * 
 */
	{ key: Key.F3, action: function() { Status_RunReportButton.actionBinding(); } },
	{ key: Key.F4, action: exitScreen }];			
			

/*****************************************************************************************************************
												DATA BINDINGS
*****************************************************************************************************************/
function OwningCourt_Name() {}
function OwningCourt_Code() {}
function YesOrNo() {}

OwningCourt_Code.dataBinding = PAGE_XPATH + "/tmp/OwningCourtCode";
OwningCourt_Name.dataBinding = REF_DATA_XPATH + "/Courts/Court[Code = " + OwningCourt_Code.dataBinding + "]/Name";

YesOrNo.dataBinding = "/ds/var/page/OracleReportForm/YesOrNo";

/*****************************************************************************************************************
												READ ONLY FIELDS 
*****************************************************************************************************************/
OwningCourt_Code.isReadOnly = function() { return true; }
OwningCourt_Name.isReadOnly = function() { return true; }
			
/*****************************************************************************************************************
												INITIALISATION
*****************************************************************************************************************/
/**
 * @author bz6s80
 * 
 */
OracleReportForm.initialise = function()
{
	var ADMIN_CROWN_COURT = CaseManUtils.getUserParameter(CaseManFormParameters.COURTNUMBER_XPATH);
	Services.setValue(PAGE_XPATH + "/tmp/OwningCourtCode", ADMIN_CROWN_COURT);

	var paymentDateXSD = CaseManUtils.createDate( Services.getValue(REF_DATA_XPATH + "/SystemDate") );
	dateCreated = CaseManUtils.convertDateToPattern(paymentDateXSD, "DD-MMM-YYYY");

	Services.setValue(_paymentsExistsXPath, "false");

	StartOfDayUtils.checkSuitorsCashStartOfDay("PostalPaymentReceipts");
	
	checkPostalReceipts();
}			
	
/*****************************************************************************************************************
                                         CHECK POSTAL RECEIPTS
*****************************************************************************************************************/
/**
 * @author bz6s80
 * 
 */
function checkPostalReceipts() {

	var dom = XML.createDOM(null, null, null);
 	   
 	// generate a parameter dom that we shall pass to the interface service that will run the reports
	var params = new ServiceParams();
	params.addSimpleParameter("userId",  CaseManUtils.getUserParameter(CaseManFormParameters.USERNAME_XPATH ));
   	params.addSimpleParameter("dateCreated", dateCreated);
    params.addSimpleParameter("adminCrownCourt", Services.getValue(OwningCourt_Code.dataBinding));
	Services.callService("checkPostalReceipts", params, checkPostalReceiptsHandler, true);
}

/*****************************************************************************************************************
											CHECK NON COUNTER PAYMENTS BY USER EXISTS HANDLER
					        Handles any errors generated by the checkNonCounterPaymentsByUserExists() method 						
*****************************************************************************************************************/
function checkPostalReceiptsHandler (){};
         	
/**
 * @param exception
 * @author bz6s80
 * 
 */
checkPostalReceiptsHandler.onError = function(exception) 
{  

	var message = "An error occurred checking payment receipts";
	/*  26 July 2006 Kevin Gichohi (EDS) - Exception handling was changed on the server, hence it should also change
 		on the client as wrong message was being displayed. */
	if  (null != exception.message) 
	{
	    if ("" != exception.message)
	    {
	       message = exception.message;
		}   
	} 
	Services.setTransientStatusBarMessage(message);
	alert(message);
}
	
/**
 * @param dom
 * @author bz6s80
 * 
 */
checkPostalReceiptsHandler.onSuccess = function(dom) {
	// check if any payments exist
    if (dom == null) {
        Services.setTransientStatusBarMessage("There are no receipts to be printed today");
    } else {
        var node = dom.selectSingleNode("/PostalReceipts");
    	// replace the empty node to the XPATH
        Services.replaceNode(REF_DATA_XPATH + "/PostalReceipts", node );
        
        // if it is empty, inform the user that no receipts were found
        if (node == null || Services.getValue(REF_DATA_XPATH + "/PostalReceipts/NoOfPayments") == 0) {
		    Services.setTransientStatusBarMessage("There are no receipts to be printed today");
		} else {
        	// enable the Run Report button
        	Services.setValue(_paymentsExistsXPath, "true");
		}
    }
}
		
/*****************************************************************************************************************
                                         REQUEST REPORT
*****************************************************************************************************************/
/**
 * @author bz6s80
 * 
 */
function requestReport()
{
	Services.setTransientStatusBarMessage("Report Generation Requested. Please Wait..");

	// If the validation of the run report button status succeeds, request the report. 
	if ( CaseManValidationHelper.validateFields(Status_RunReportButton.validationList) ) { 
		//create a dom to pass to the interface service
		var dom = XML.createDOM(null, null, null);
	   
		var params = new ServiceParams();
		params.addSimpleParameter("inputBy",  CaseManUtils.getUserParameter(CaseManFormParameters.USERNAME_XPATH ));
		params.addSimpleParameter("dateCreated", dateCreated);
		params.addSimpleParameter("runBy", "clerk");
	   
		//Services.callService("producePaymentReceiptsReport", params, runReportHandler, true);
		Reports.callAsync("asyncPaymentReceiptsReport", params, CaseMan_AsyncMonitor.srcData);
	    Util.openPopup("CaseMan_AsyncMonitorPopup");		
	}
}	

/*****************************************************************************************************************
											RUN REPORT HANDLER
*****************************************************************************************************************/

 function runReportHandler (){};
         	
/**
 * @param dom
 * @author bz6s80
 * 
 */
runReportHandler.onSuccess = function(dom)
{ 
//	Services.setTransientStatusBarMessage("Report Completed");
	exitScreen();
}
       	

/**
 * @param exception
 * @author bz6s80
 * 
 */
runReportHandler.onError = function(exception)
{  
	var message = "An error occurred running the payment receipts report";
	/*  26 July 2006 Kevin Gichohi (EDS) - Exception handling was changed on the server, hence it should also change
 		on the client as wrong message was being displayed. */
	if  (null != exception.message) 
	{
	    if ("" != exception.message)
	    {
	       message = exception.message;
		}   
	} 
	Services.setTransientStatusBarMessage(message);
	alert(message);
}


/*****************************************************************************************************************
                                         FIELD CODE
*****************************************************************************************************************/
OwningCourt_Name.retrieveOn = [OwningCourt_Code.dataBinding];

Status_RunReportButton.validationList = [];

function Status_Close_Btn() {};
Status_Close_Btn.tabIndex = __tabIdx++;
/**
 * @author bz6s80
 * 
 */
Status_Close_Btn.actionBinding = function() {exitScreen(); };

function Status_RunReportButton() {}
Status_RunReportButton.tabIndex = __tabIdx++;

/**
 * @author bz6s80
 * 
 */
Status_RunReportButton.actionBinding = function() {
	if ( CaseManValidationHelper.validateFields(Status_RunReportButton.validationList) )
	{
		requestReport();
	}
  	else
  	{
  		alert(Messages.POPUP_INVALID_MESSAGE);
  	}				
}
Status_RunReportButton.enableOn = [_paymentsExistsXPath];
Status_RunReportButton.isEnabled = function()
{
	if(Services.getValue(_paymentsExistsXPath) == "true") {
		return true;
	}
	return false;
}

YesOrNo.tabIndex = __tabIdx++;
YesOrNo.componentName = "Click on Run Report button to print this report.";		
YesOrNo.srcData = null;
YesOrNo.rowXPath = null;
YesOrNo.keyXPath = null;
YesOrNo.displayXPath = null;
YesOrNo.helpText = null;

/*****************************************************************************************************************
                                         HELPER CODE
*****************************************************************************************************************/
/**
 * @param ec
 * @author bz6s80
 * @return ec  
 */
function faildedValidation (ec)
{
  if(ec != null)
  {
    Services.setTransientStatusBarMessage(ec.getMessage());
  }
  return ec;
}			

/**
 * @author bz6s80
 * 
 */
function exitScreen()
{
	Services.navigate(NavigationController.MAIN_MENU);
}	

/**
 * Async Stuff
 * @author bz6s80
 * 
 */
function CaseMan_AsyncMonitorPopup() {};
function CaseMan_AsyncMonitor() {};


CaseMan_AsyncMonitor.srcData = "/ds/var/form/Async";
CaseMan_AsyncMonitor.dataBinding = CaseMan_AsyncMonitor.srcData + "/Id";
CaseMan_AsyncMonitor.asyncStateService = "getState";
CaseMan_AsyncMonitor.asyncCancelService = "cancel";
/**
 * @author bz6s80
 * 
 */
CaseMan_AsyncMonitor.onComplete = function()
{
	//debugger;
	Util.closePopup("CaseMan_AsyncMonitorPopup");
	Services.setTransientStatusBarMessage("Report Completed");
	exitScreen();
}

/**
 * @param exception
 * @author bz6s80
 * 
 */
CaseMan_AsyncMonitor.onError = function(exception)
{
	//debugger;
	var message = "An error occurred running the counter verification report";
	/*  26 July 2006 Kevin Gichohi (EDS) - Exception handling was changed on the server, hence it should also change
 		on the client as wrong message was being displayed. */
	if  (null != exception.message) 
	{
	    if ("" != exception.message)
	    {
	       message = exception.message;
		}   
	} 
	Services.setTransientStatusBarMessage(message);
	alert(message);
    Util.closePopup("CaseMan_AsyncMonitorPopup");
    //exitScreen();
}

/**
 * @author bz6s80
 * 
 */
CaseMan_AsyncMonitor.onCancel = function()
{
	
    Util.closePopup("CaseMan_AsyncMonitorPopup");
}

/**
 * @param error
 * @author bz6s80
 * 
 */
CaseMan_AsyncMonitor.onCancelError = function(error)
{
	//debugger;
    alert("Unable to cancel report: " + error.message);
    Util.closePopup("CaseMan_AsyncMonitorPopup");
}				
	
