/* Copyrights and Licenses
 * 
 * Copyright (c) 2008-2009 by the Ministry of Justice. All rights reserved.
 * Redistribution and use in source and binary forms, with or without modification, are permitted
 * provided that the following conditions are met:
 * - Redistributions of source code must retain the above copyright notice, this list of conditions
 * and the following disclaimer.
 * - Redistributions in binary form must reproduce the above copyright notice, this list of
 * conditions and the following disclaimer in the documentation and/or other materials
 * provided with the distribution.
 * - All advertising materials mentioning features or use of this software must display the
 * following acknowledgment: "This product includes Money Claims OnLine."
 * - Products derived from this software may not be called "Money Claims OnLine" nor may
 * "Money Claims OnLine" appear in their names without prior written permission of the
 * Ministry of Justice.
 * - Redistributions of any form whatsoever must retain the following acknowledgment: "This
 * product includes Money Claims OnLine."
 * This software is provided "as is" and any expressed or implied warranties, including, but
 * not limited to, the implied warranties of merchantability and fitness for a particular purpose are
 * disclaimed. In no event shall the Ministry of Justice or its contributors be liable for any
 * direct, indirect, incidental, special, exemplary, or consequential damages (including, but
 * not limited to, procurement of substitute goods or services; loss of use, data, or profits;
 * or business interruption). However caused any on any theory of liability, whether in contract,
 * strict liability, or tort (including negligence or otherwise) arising in any way out of the use of this
 * software, even if advised of the possibility of such damage.
 * 
 * $Id: AbstractActionServiceTest.java 15899 2013-01-09 14:10:43Z compstonr $
 * $LastChangedRevision: 15899 $
 * $LastChangedDate: 2013-01-09 14:10:43 +0000 (Wed, 09 Jan 2013) $
 * $LastChangedBy: compstonr $ */
package uk.gov.dca.caseman.util;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Iterator;
import java.util.List;

import org.junit.Assert;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;


/**
 * PdsMigDbTestBase this used to call the database unit tests.
 * <p/>
 * 
 * @author Robin Compston
 * @version $Revision: 1.21 $
 */
public abstract class AbstractDbTest extends AbstractTest
{
    /**
     * Output directory used when running DBSRC PL/SQL Unit Tests.
     */
    public static final String TEST_OUT_DIR = "./test/out";

    /**
     * Text that is expected to appear in a PL/SQL test script output to identify that the script
     * has started.
     */
    public static final String TESTS_STARTED_MSG = "TESTS STARTED";

    /**
     * Text that is expected to appear in a PL/SQL test script output to identify that the script
     * has completed.
     */
    public static final String TESTS_COMPLETED_MSG = "TESTS COMPLETED";

    /**
     * Text that is generated by ORACLE for DOC. We want to recognize these lines to avoid
     * comparison as they often contain date or releases.
     */
    public static final String SQL_DOC = "DOC> ";

    /**
     * Some time we can get a revision number in the file we want to compare (out and good files),
     * but we don't want to compare this number as it is likely to change each time something is
     * fixed. This string is used to strip off lines containing $Revision:.
     */
    public static final String REVISION_STRING = "Revision:";

    /**
     * Date line must be excluded from comparison.
     */
    public static final String DATE_STRING = "Date:";

    /**
     * Author line must be excluded from comparison.
     */
    public static final String AUTHOR_STRING = "Author:";

    /**
     * The validation reports contain a date that cannot be
     * stubbed with the common package. This needs to be ignored.
     */
    public static final String REPORT_DATE_STRING = "Report date";

    /**
     * Flags to indicate comparison with good file is required.
     */
    public static final boolean COMPARE_TO_GOOD = true;

    /**
     * Flags to indicate comparison with good file is not required.
     */
    public static final boolean NO_COMPARE_TO_GOOD = false;

    /**
     * Logger instance.
     */
    private static final Logger LOGGER = LoggerFactory.getLogger (AbstractDbTest.class);

    /**
     * File separator for pathnames.
     */
    private static final String FILE_SEPARATOR = "/";

    /**
     * Default time a test will wait for a sql script to return before terminating the script and
     * reporting an error, in milliseconds.
     */
    // CHECKSTYLE:OFF
    private static int SQL_SCRIPT_MS_WAIT_TIME = 60000;
    // CHECKSTYLE:ON

    /**
     * The first lines in 'out' and 'good' files that do not match.
     */
    private String badLine = "";

    /**
     * Constructor for PdsMigDbTestBase class.
     */
    public AbstractDbTest ()
    {
    }

    /**
     * Compares the contents of two named text files and returns true if they are exatcly the same.
     * Note - Any data not required to be compared, e.g. run dates and timing information etc.
     * should be placed outside of the "test section" ie. either before the message "Tests Started"
     * or after the message "Tests Completed" otherwise the files will not match.
     * 
     * @param outFilePath Name of output file.
     * @param goodFilePath Name of good file.
     * @return true - files match, false - files do not match.
     */
    private boolean compareTestOutputFiles (final String outFilePath, final String goodFilePath)
    {
        boolean filesMatch = false;
        boolean foundDifference = false;
        final BufferedReader outFileBuf;
        final BufferedReader goodFileBuf;

        if (outFilePath != null && goodFilePath != null)
        {
            try
            {
                final File outFile = new File (outFilePath);
                final File goodFile = new File (goodFilePath);

                // Check we have an output file.
                if ( !outFile.exists ())
                {
                    LOGGER.debug ("** TestUtil Detected an ERROR - " +
                            "Unable to find the output file from the script (" + outFile.getAbsolutePath () + ")");
                    throw new IOException ("** TestUtil Detected an ERROR - " +
                            "Unable to find the output file from the script (" + outFile.getAbsolutePath () + ")");
                }

                // Check we have a good file.
                if ( !goodFile.exists ())
                {
                    LOGGER.debug ("** TestUtil Detected an ERROR - " + "Unable to find the good file for the script (" +
                            goodFile.getAbsolutePath () + ")");
                    throw new IOException ("** TestUtil Detected an ERROR - " +
                            "Unable to find the good file for the script (" + goodFile.getAbsolutePath () + ")");
                }

                outFileBuf = new BufferedReader (new FileReader (outFile));
                goodFileBuf = new BufferedReader (new FileReader (goodFile));
                String outStr;
                String goodStr;
                final List<String> outList = new ArrayList<String> (500);
                final List<String> goodList = new ArrayList<String> (500);

                // Read to the start of the test section in both files. Anything before this is not considered for
                // comparison.
                outStr = outFileBuf.readLine ();
                while (outStr != null && outStr.toUpperCase ().indexOf (TESTS_STARTED_MSG) < 0)
                {
                    outStr = outFileBuf.readLine ();
                }

                goodStr = goodFileBuf.readLine ();
                while (goodStr != null && goodStr.toUpperCase ().indexOf (TESTS_STARTED_MSG) < 0)
                {
                    goodStr = goodFileBuf.readLine ();
                }

                boolean completed1 = false;

                // If out file found a test started message ...
                if (outStr != null && outStr.toUpperCase ().indexOf (TESTS_STARTED_MSG) >= 0)
                {
                    // Read thru out files until EOF or test completed message.
                    outStr = outFileBuf.readLine ();
                    while ( !completed1 && outStr != null)
                    {
                        // We search for "DOC>" at the beginning of the line, return -1 if not found, and revision
                        // numbers.
                        if (outStr.indexOf (DATE_STRING) == -1 && outStr.indexOf (AUTHOR_STRING) == -1 &&
                                outStr.indexOf (REVISION_STRING) == -1 && outStr.indexOf (REPORT_DATE_STRING) == -1 &&
                                outStr.indexOf (REVISION_STRING) == -1)
                        {
                            outList.add (dos2Unix (outStr));
                        }

                        // Look for 'test completed' message in out file.
                        if (outStr.toUpperCase ().indexOf (TESTS_COMPLETED_MSG) >= 0)
                        {
                            completed1 = true;
                        }

                        outStr = outFileBuf.readLine ();
                    }
                }

                boolean completed2 = false;

                // If good file found a 'test started' message ...
                if (goodStr != null && goodStr.toUpperCase ().indexOf (TESTS_STARTED_MSG) >= 0)
                {
                    // Read thru good files until EOF or 'test completed' message.
                    goodStr = goodFileBuf.readLine ();
                    while ( !completed2 && goodStr != null)
                    {
                        // We search for "DOC>" at the beginning of the line
                        // return -1 if not found
                        if (goodStr.indexOf (SQL_DOC) != 0 && goodStr.indexOf (DATE_STRING) == -1 &&
                                goodStr.indexOf (AUTHOR_STRING) == -1 && goodStr.indexOf (REVISION_STRING) == -1 &&
                                goodStr.indexOf (REPORT_DATE_STRING) == -1 && goodStr.indexOf (REVISION_STRING) == -1)
                        {
                            goodList.add (dos2Unix (goodStr));
                        }

                        // Look for 'test completed' message in good file.
                        if (goodStr.toUpperCase ().indexOf (TESTS_COMPLETED_MSG) >= 0)
                        {
                            completed2 = true;
                        }

                        goodStr = goodFileBuf.readLine ();
                    }
                }

                final boolean testsCompleted = completed1 && completed2;

                // Sort both list to cater for ordering differences in the data
                // returned from the db.
                // Collections.sort (outList);
                // Collections.sort (goodList);
                final Iterator<String> outIter = outList.iterator ();
                final Iterator<String> goodIter = goodList.iterator ();

                badLine = "";

                // Check both lists match, stop processing if a difference is
                // encountered.
                while (outIter.hasNext () && goodIter.hasNext () && !foundDifference)
                {
                    outStr = (String) outIter.next ();
                    goodStr = (String) goodIter.next ();

                    // Compare each sorted record.
                    if (outStr.compareTo (goodStr) != 0)
                    {
                        foundDifference = true;
                        LOGGER.debug ("Differences detected between OUT and OUT.GOOD files");

                        // Output the line with the difference and the expected line to the console for review
                        badLine = "out file:  " + outStr + "\ngood file: " + goodStr;
                    }
                }

                // Match if all lines within test zone compare.
                if ( !foundDifference && testsCompleted)
                {
                    filesMatch = true;
                }

                outFileBuf.close ();
                goodFileBuf.close ();
            }
            catch (final IOException e)
            {
                filesMatch = false;
            }
        }

        return filesMatch;
    }

    /**
     * Runs a SQL test harness script. Completion is detected by the phrase "TESTING COMPLETED"
     * output by the script comparisonGoodOutputFileName can be set to compare the output file
     * produced from the script to a previous known output "good" output file Even if the tests
     * pass, if the files are different then they will be deemed to have failed.
     * 
     * @param specificConString SpecificConnexion String to override properties for this call.
     * @param outDirectoryName Location of the output files.
     * @param sqlScriptName Name of SQL script to run.
     * @param sqlScriptParameters parameters for SQL script.
     * @param compareToGoodFile Flag to say whether we should compare output with a good output
     *            file.
     * @throws IOException Problem accessing database.
     */
    public void runSqlTestScript (final String specificConString, final String outDirectoryName,
                                  final String sqlScriptName, final String[] sqlScriptParameters,
                                  final boolean compareToGoodFile) throws IOException
    {
        // This is the name of a file containing the output from a known
        // good run that we can compare against the output from this run.
        String outFilePath;
        boolean filesMatch = false;
        final String scriptFileNameNoExtension;

        // Validate input parameters.
        if (outDirectoryName == null || sqlScriptName == null)
        {
            LOGGER.debug ("** TestUtil Detected an ERROR - One or more parameters " + "are null: " +
                    "outDirectoryName(" + outDirectoryName + "), " + "sqlScriptName(" + sqlScriptName + ").");
            throw new IOException ("** TestUtil Detected an ERROR - One or more parameters " + "are null: " +
                    "outDirectoryName(" + outDirectoryName + ") " + "sqlScriptName(" + sqlScriptName + ").");
        }

        // Double check that script name does not have a SQL suffix and if so remove it.
        final int fileExtPos = sqlScriptName.toUpperCase ().indexOf (".SQL");
        if (fileExtPos >= 0)
        {
            scriptFileNameNoExtension = sqlScriptName.substring (0, fileExtPos);
        }
        else
        {
            scriptFileNameNoExtension = sqlScriptName;
        }

        // Get the absolute path of the resource.
        outFilePath = outDirectoryName + FILE_SEPARATOR + scriptFileNameNoExtension + ".out";
        outFilePath = new File (outFilePath).getCanonicalPath ();

        boolean testPassed =
                runSqlTestScript (specificConString, outDirectoryName, scriptFileNameNoExtension, sqlScriptParameters);

        if (testPassed && compareToGoodFile)
        {
            // Get the good file path. Assume file name is based on out file path.
            final URL goodFileUrl = this.getClass ().getResource (scriptFileNameNoExtension + ".out.good");
            String goodFilePath = goodFileUrl.getPath ();

            // Convert good file path to local operating system form.
            final File goodFile = new File (goodFilePath);
            goodFilePath = goodFile.getCanonicalPath ();

            // Compare the output file produced by the test script with the
            // output from a know good run of the script.
            LOGGER.debug ("Comparing output file against the good file ...");
            filesMatch = compareTestOutputFiles (outFilePath, goodFilePath);

            if ( !filesMatch)
            {
                LOGGER.debug ("** Check the block of text between the (" + TESTS_STARTED_MSG + ") and (" +
                        TESTS_COMPLETED_MSG + ") messages.");
                LOGGER.debug ("** All other text before and after this block is " + "ignored for comparison purposes.");
                LOGGER.debug ("** NOTE - during testing, both files are sorted in "
                        + "memory to avoid ordering differences");
                LOGGER.debug ("** in data returned from the db.  Hence ordering "
                        + "of lines in the 'out' and 'good' files");
                LOGGER.debug ("** will not cause problems.");

                Assert.fail ("Comparison failure between out file [" + outFilePath + "] and good file [" +
                        goodFilePath + "].\nFirst mismatch: \n[" + badLine + "]");
            }
            else
            {
                LOGGER.debug ("... output file matches the 'good' file and test passes.");
            }
        }

        testPassed = testPassed && ( !compareToGoodFile || filesMatch);

        if ( !testPassed)
        {
            Assert.fail ("Failures detected when running tests package (" + sqlScriptName + ")");
        }
    }

    /**
     * Runs a SQL test harness script. Completion is detected by the phrase "TESTING COMPLETED"
     * output by the script
     * 
     * @param specificConnString Connection to overide defaults.
     * @param outDirectoryName Location of the output files.
     * @param sqlScriptName Name of SQL script to run.
     * @param sqlScriptParameters parameters for SQL script.
     * @return true if the tests run without failures.
     * @throws IOException Problem accessing database.
     */
    private boolean runSqlTestScript (final String specificConnString, final String outDirectoryName,
                                      final String sqlScriptName, final String[] sqlScriptParameters)
        throws IOException
    {
        final boolean testsFailed = false;
        boolean testsCompleted = false;
        boolean foundStartOfTests = false;

        final String outputFilePath;
        final int testsFailedCnt = 0;
        final int testsPassedCnt = 0;

        LOGGER.debug ("About to run SQL Test Script (" + sqlScriptName + ")");
        LOGGER.debug ("The script output will be monitored and will be deemed " + "to have failed");
        LOGGER.debug ("if the script does not run through to completion, " + "identified by the phrase '" +
                TESTS_COMPLETED_MSG + "'.");

        // Get the SID from the URL.
        final String connectString;
        if (specificConnString != null)
        {
            connectString = specificConnString;
        }
        else
        {
            connectString = getLoginUserId () + FILE_SEPARATOR + getLoginPassword () + "@" + getSid ();
        }

        final String script;
        TimeLimitedProcessBuilder processBuilder = null;

        String scriptSuffix = "";
        try
        {
            // Check the sql file is there with various alternate suffixes.
            final URL scriptUrl = this.getClass ().getResource (sqlScriptName + ".sql");

            // Get the path of the resource.
            String scriptUrlPath = scriptUrl.getPath ();

            // Check the SQL script file exists.
            final File scriptFile = new File (scriptUrlPath);

            // Convert to form for local operating system.
            scriptUrlPath = scriptFile.getCanonicalPath ();

            if (scriptFile.exists ())
            {
                scriptSuffix = "sql";
            }
            else
            {
                LOGGER.debug ("** TestUtil Detected an ERROR - Unable to " + "find the script to run (" +
                        scriptFile.getAbsolutePath () + ")");
                throw new IOException ("** TestUtil Detected an ERROR - Unable to " + "find the script to run (" +
                        scriptFile.getAbsolutePath () + ")");
            }

            // Build sqlplus full file name.
            script = "@" + scriptUrlPath;

            // Process builder need an array of String. Each String will be seen as a parameter even if it contains
            // spaces. This mean we need to break the parameter string
            final List<String> processParameters = new ArrayList<String> ();

            // We want to call sqlplus.
            processParameters.add ("sqlplus");

            // Option -L make sqlplus exit if wrong user/password.
            processParameters.add ("-L");

            // This is the parameter of sqlplus command.
            processParameters.add (connectString);

            // This is the first command executed by sqlplus (@file).
            processParameters.add (script);

            // These are the parameters of our script
            processParameters.addAll (Arrays.asList (sqlScriptParameters));

            // We then add a list of parameters in case the caller forgot, just to avoid being stuck in sqlplus.
            processParameters.add ("!!! parameter added by the tool!!!");
            processParameters.add ("!!! parameter added by the tool!!!");
            processParameters.add ("!!! parameter added by the tool!!!");
            processParameters.add ("!!! parameter added by the tool!!!");
            processParameters.add ("!!! parameter added by the tool!!!");
            processParameters.add ("!!! parameter added by the tool!!!");
            processParameters.add ("!!! parameter added by the tool!!!");
            processParameters.add ("!!! parameter added by the tool!!!");
            processParameters.add ("!!! parameter added by the tool!!!");

            // Create the process builder. The list is changed into an array.
            processBuilder = new TimeLimitedProcessBuilder (processParameters.toArray (new String[0]));

            // The process must be started from the current directory as all the scripts are designed in this way. So no
            // setDirectory! processBuilder.setDirectory(workingDir);

            // Need to remove any old output file as this may be readonly and
            // prevent the script from writing its output.
            outputFilePath = outDirectoryName + FILE_SEPARATOR + sqlScriptName + ".out";

            final File outFile = new File (outputFilePath);
            outFile.delete ();

            // Redirect output so that both output and error are merged.
            processBuilder.redirectErrorStream (true);

            processBuilder.setTimeMilliSeconds (SQL_SCRIPT_MS_WAIT_TIME);
            processBuilder.start ();

            // Send the output from the script to the command line.
            String currentLine = processBuilder.readLine ();

            // Skip all lines prior to the test's started block.
            while (currentLine != null && !foundStartOfTests)
            {
                if (currentLine.toUpperCase ().indexOf (TESTS_STARTED_MSG) >= 0)
                {
                    foundStartOfTests = true;
                }
                LOGGER.debug (currentLine);

                currentLine = processBuilder.readLine ();
            }

            // Complain if test start string not found.
            if ( !foundStartOfTests)
            {
                LOGGER.debug ("** TestUtil Detected an ERROR - Unable to find the start of tests marker (" +
                        TESTS_STARTED_MSG + ").");
                throw new IOException ("** TestUtil Detected an ERROR - Unable to find the start of tests marker (" +
                        TESTS_STARTED_MSG + ").");
            }

            currentLine = processBuilder.readLine ();
            while (currentLine != null)
            {
                LOGGER.debug (currentLine);

                // Check the tests reached completion, i.e. didn't fail to run.
                if (currentLine.toUpperCase ().indexOf (TESTS_COMPLETED_MSG) >= 0)
                {
                    testsCompleted = true;
                }

                currentLine = processBuilder.readLine ();
            }
        }
        catch (final Exception e)
        {
            testsCompleted = false;
        }
        finally
        {
            if (processBuilder != null)
            {
                processBuilder.close ();
            }
        }

        if (testsFailed)
        {
            LOGGER.debug ("** TestUtil Detected an ERROR - (" + testsFailedCnt + ") Tests failed out of (" +
                    (testsFailedCnt + testsPassedCnt) + ")");
        }
        else if (processBuilder != null && processBuilder.timedOut ())
        {
            LOGGER.debug ("** TestUtil Detected an ERROR - Script timed out and " + "did not return after waiting (" +
                    processBuilder.getTimeMilliSeconds () + ")ms." + " - Please note the timeout limit can be " +
                    "configured by calling TestUtil.setSQLScriptMsWaitTime().");
        }
        else if ( !testsCompleted)
        {
            LOGGER.debug ("** TestUtil Detected an ERROR - Script exited before completing all tests");
        }
        else
        {
            LOGGER.debug ("All (" + testsPassedCnt + ") tests passed.");
        }

        return testsCompleted && !testsFailed;
    }

    /**
     * Runs the specified test script and reports any errors.
     * 
     * @param testScript Name of test script to run.
     * @param compareToGoodFile True or False
     * @param testScriptParameters script parameters.
     */
    protected void runTest (final String testScript, final boolean compareToGoodFile,
                            final String... testScriptParameters)
    {
        // Use default connection String.
        runTest (null, testScript, compareToGoodFile, testScriptParameters);
    }

    /**
     * Runs the specified test script and reports any errors.
     * 
     * @param connectionString Connection String if don't want to use default one
     * @param testScript Name of test script to run.
     * @param compareToGoodFile True or False
     * @param testScriptParameters script parameters.
     */
    protected void runTest (final String connectionString, final String testScript, final boolean compareToGoodFile,
                            final String... testScriptParameters)
    {
        LOGGER.debug ("Enter runTest: " + testScript);

        String testScriptTrimmed = testScript;

        try
        {
            // Remove the optional sql extension
            if (testScriptTrimmed.toUpperCase ().endsWith (".SQL"))
            {
                testScriptTrimmed = testScriptTrimmed.substring (0, testScriptTrimmed.length () - 4);
            }

            runSqlTestScript (connectionString, TEST_OUT_DIR, testScriptTrimmed, testScriptParameters,
                    compareToGoodFile);
        }
        catch (final Exception e)
        {
            Assert.fail ("Method should not throw any Exception: Exception Message: " + e);
        }

        LOGGER.debug ("Exiting runTest: " + testScriptTrimmed);
    }

    /**
     * Convert windows String to UNIX by removing all Hex 0d.
     * 
     * @param in String from Windows platform.
     * @return String for UNIX platform.
     */
    private String dos2Unix (final String in)
    {
        // Array to hold input.
        final char[] win = in.toCharArray ();
        final int len = in.length ();

        // Array to hold output.
        final char[] unix = new char[len];

        int pos2 = 0;
        for (int pos1 = 0; pos1 < len; pos1++)
        {
            // Copy all but CARRIAGE RETURN.
            if (win[pos1] != '\r')
            {
                unix[pos2++] = win[pos1];
            }
        }

        return new String (unix);
    }

    /**
     * Return the expected name of the SQL test harness script to be run in association with this test. The name is
     * based on the test class name and the test method name and is worked out dynamically, i.e. 
     * "<class name>.<method name>.sql".
     * 
     * @return expected name of SQL script.
     */
    protected String getScriptName ()
    {
        // Get class name.
        final String resourceName = this.getClass ().getSimpleName ();

        // Find out method that called us and get test method name (2 stack frames deep).
        final StackTraceElement[] stackTraceElements = Thread.currentThread ().getStackTrace ();
        final String methodName = stackTraceElements[2].getMethodName ();

        return resourceName + "." + methodName + ".sql";
    }
}
