
com.sun.jndi.ldap.connect.pool=true
java.naming.ldap.derefAliases=never
java.naming.referral=ignore
java.naming.factory.initial=com.sun.jndi.ldap.LdapCtxFactory
java.naming.provider.url=ldap://uktps800:389
java.naming.security.authentication=simple
java.naming.security.principal=cn=ediaryuser,cn=users,dc=sups
java.naming.security.credentials=Ediary01

