com.sun.jndi.ldap.connect.pool=true
java.naming.ldap.derefAliases=never
java.naming.referral=ignore
java.naming.factory.initial=com.sun.jndi.ldap.LdapCtxFactory
java.naming.provider.url=ldap://csdv00011.ops.cs.root:389
java.naming.security.authentication=simple
java.naming.security.principal=cn=sups_internal,ou=Service Accounts,ou=Administrators,dc=ops,dc=cs,dc=root
java.naming.security.credentials=password
searchbase=ou=Court Service,dc=ops,dc=cs,dc=root
query=(&(samaccountname={0})(objectclass=person))
printerbase=cn={0},ou=Distributed FAPs,ou=Member Servers,dc=ops,dc=cs,dc=root
printerquery=(objectclass=printQueue)
trainingou=SUPS Site Training

