printers=a,b,c
a.serverName=Server
a.printerName=Printer1
a.description=Court Room 1
a.driverName=Xerox Phaser 4500DT
a.location=Office
a.printMediaReady=Letter
a.printMediaSupported=C5 Envelope 162 x 229 mm;B5 Envelope 176 x 250mm
a.shortServerName=Server
a.uNCName=\\\\Server\\Printer1
a.printShareName=Printer1

b.serverName=Server
b.printerName=Printer2
b.description=Court Room 2
b.driverName=Xerox Phaser 4500DT
b.location=Office
b.printMediaReady=Letter
b.printMediaSupported=C5 Envelope 162 x 229 mm;B5 Envelope 176 x 250mm
b.shortServerName=Server
b.uNCName=\\\\Server\\Printer2
b.printShareName=Printer2


c.serverName=Server
c.printerName=Printer3
c.description=Court Room 3
c.driverName=Xerox Phaser 4500DT
c.location=Office
c.printMediaReady=Letter
c.printMediaSupported=C5 Envelope 162 x 229 mm;B5 Envelope 176 x 250mm
c.shortServerName=Server
c.uNCName=\\\\Server\\Printer3
c.printShareName=Printer3
