# -----------------------------------------
# File history
# 07/12/2006 - Created. Chris Hutt
# 12/12/2006 - Chris Hutt: 1. Added properties so that consistent with main build script 
#			      and supports extract of all dbase related artefacts
#                          2. Name change CasemanRefData.properties -> CasemanDBhandover.properties
# 15/06/2007 - Chris Hutt: extended to include scripts directory (the one used to hold shell scripts)
# 29/10/2009 - Chris Vincent: removed old ClearCase related properties and replaced with new ones
#

# default propert values 
build.num=N
build.app.num=N
build.rep.num=N
build.ref.num=N
build.bat.num=N

# source 
caseman.location.views=${env.PROJECT.BASE}/../caseman_database_source/views
caseman.location.scripts=${env.PROJECT.BASE}/../caseman_database_source/scripts
caseman.location.packages=${env.PROJECT.BASE}/../caseman_database_source/packages
caseman.location.refdata=${env.REFDATA.BASE}
caseman.location.refdata.data.common=${env.REFDATA.BASE}/data/common
caseman.location.refdata.data.test=${env.REFDATA.BASE}/data/test
caseman.location.refdata.data.migration=${env.REFDATA.BASE}/data/migration
caseman.location.refdata.data.postmigration=${env.REFDATA.BASE}/data/post_migration
caseman.location.refdata.scripts.common=${env.REFDATA.BASE}/scripts/common
caseman.location.refdata.scripts.test=${env.REFDATA.BASE}/scripts/test
caseman.location.refdata.scripts.migration=${env.REFDATA.BASE}/scripts/migration
caseman.location.refdata.scripts.postmigration=${env.REFDATA.BASE}/scripts/post_migration

# output
output.drive=c:
output.dir.name=${output.drive}/Caseman_CCBC_${build.ref.num}_DB
output.refdata.dir.name=${output.dir.name}/reference_data
output.refdata.test.dir.name=${output.dir.name}/reference_data/test
output.refdata.migration.dir.name=${output.dir.name}/reference_data/migration
output.views.dir.name=${output.dir.name}/views
output.packages.dir.name=${output.dir.name}/packages
output.zip.name=${output.dir.name}.zip



