/****************************************
 *
 * DISC SUPS
 * Copyright Logica UK Ltd. 2008
 *
 * $Revision: 781 $
 * $Author: mistryn $
 * $Date: 2008-10-07 18:19:47 +0100 (Tue, 07 Oct 2008) $
 *
 *****************************************/

package uk.gov.dca.utils.tests.releases.cm6_0;

import uk.gov.dca.utils.common.AbstractCmTestBase;
import uk.gov.dca.utils.navigate.Navigator;
import uk.gov.dca.utils.screens.UC029CreateHomeWarrantUtils;
import uk.gov.dca.utils.screens.UC031ReissueWarrantUtils;
import uk.gov.dca.utils.screens.UC039MaintainWarrantUtils;
import uk.gov.dca.utils.velo.db.DBUtil;

/**
 * Automated tests for the CaseMan Defect 2848. This covers a change to the way in which
 * Reissued Warrants are forwarded to foreign Courts. An automatic copy should NOT be created
 * when an original Reissued Warrant is forwarded to another Court.
 *
 * @author Chris Vincent
 */
public class CaseManTrac2848_Test extends AbstractCmTestBase
{
    
    /** The my UC 029 create home warrant utils. */
    // Private member variables for the screen utils
    private UC029CreateHomeWarrantUtils myUC029CreateHomeWarrantUtils;
    
    /** The my UC 039 maintain warrant utils. */
    private UC039MaintainWarrantUtils myUC039MaintainWarrantUtils;
    
    /** The my UC 031 reissue warrant utils. */
    private UC031ReissueWarrantUtils myUC031ReissueWarrantUtils;

    /** The s 1 case no. */
    // Scenario One: Northampton Case with Judgment but no Warrants
    String s1_case_no = "0NN00001";

    /** The s 2 case no. */
    // Scenario Two: Northampton Case with Judgment and Home Warrant with final return
    String s2_case_no = "0NN00002";
    
    /** The s 2 warrant no. */
    String s2_warrant_no = "Y0000001";

    /** The s 3 case no. */
    // Scenario Three: Northampton Case with Judgment and Live Home Warrant
    String s3_case_no = "0NN00003";
    
    /** The s 3 warrant no. */
    String s3_warrant_no = "Y0000002";

    /** The s 4 case no. */
    // Scenario Four: Coventry Case with Judgment and Warrant forwarded to Northampton
    String s4_case_no = "0CV00001";
    
    /** The s 4 warrant no. */
    String s4_warrant_no = "Y0000001";
    
    /** The s 4 local warrant no. */
    String s4_local_warrant_no = "FWY00001";

    /** The s 5 case no. */
    // Scenario Five: Northampton Case with Judgment and Reisued Warrant
    String s5_case_no = "0NN00004";
    
    /** The s 5 warrant no. */
    String s5_warrant_no = "Y0000003";
    
    /** The s 5 reissue no. */
    String s5_reissue_no = "00001/10";

    /** The s 6 case no. */
    // Scenario Six: Foreign Warrant executed by Northampton, issued by Chester (Legacy) for a Reissued Warrant
    String s6_case_no = "0CH00001";
    
    /** The s 6 warrant no. */
    String s6_warrant_no = "00001/10";
    
    /** The s 6 local warrant no. */
    String s6_local_warrant_no = "FWY00002";

    /** The hw warrant forwarded message. */
    // Alert messages generated by Warrant screens when Warrant forwarded
    String hw_warrant_forwarded_message =
            "Warrant created successfully. Warrant number is XXX. Warrant sent to foreign court.";
    
    /** The ri warrant reissued message. */
    String ri_warrant_reissued_message = "Warrant re-issued successfully. Re-issued warrant number is XXX.";
    
    /** The mn printed fw forwarded message. */
    String mn_printed_fw_forwarded_message = "Manually entered foreign warrant should be sent to foreign court.";
    
    /** The mn hw forwarded message. */
    String mn_hw_forwarded_message = "Warrant saved successfully. Warrant sent to foreign court.";
    
    /** The mn fw forwarded message. */
    String mn_fw_forwarded_message = "Warrant saved successfully. Warrant sent to foreign court.";
    
    /** The mn rw forwarded message. */
    String mn_rw_forwarded_message = "Warrant saved successfully.";

    /**
     * Constructor.
     */
    public CaseManTrac2848_Test ()
    {
        super (CaseManTrac2848_Test.class.getName ());
        this.nav = new Navigator (this);
        myUC029CreateHomeWarrantUtils = new UC029CreateHomeWarrantUtils (this);
        myUC031ReissueWarrantUtils = new UC031ReissueWarrantUtils (this);
        myUC039MaintainWarrantUtils = new UC039MaintainWarrantUtils (this);
    }

    /**
     * Scenario One.
     * Create Home Warrant on Create Home Warrants screen and set Executing Court to Foreign Court
     * Home Warrant will be created, as will the Foreign Warrant and the final return 147 on the
     * Home Warrant.
     *
     * Need to check correct alert message displayed when new Warrant added
     */
    public void testWarrantScenario1 ()
    {
        try
        {
            // Log into SUPS CaseMan
            logOn (AbstractCmTestBase.COURT_NORTHAMPTON, AbstractCmTestBase.ROLE_WARRANT);

            // Navigate to the Create Home Warrants screen
            this.nav.navigateFromMainMenu (MAINMENU_HOME_WARRANTS_PATH);

            // Check in correct screen
            mCheckPageTitle (myUC029CreateHomeWarrantUtils.getScreenTitle ());

            // Set the Header fields
            myUC029CreateHomeWarrantUtils.setCaseNumber (s1_case_no);

            // Set the footer fields
            myUC029CreateHomeWarrantUtils.setExecutingCourtCode ("180");
            myUC029CreateHomeWarrantUtils.setAdditionalDetails ("Additional Details");

            // Set the Warrant Details Popup fields
            myUC029CreateHomeWarrantUtils.clickDetailsOfWarrantButton (); // Raise popup
            myUC029CreateHomeWarrantUtils.setBalanceOfDebt ("500.00");
            myUC029CreateHomeWarrantUtils.setAmountOfWarrant ("450.00");
            myUC029CreateHomeWarrantUtils.setWarrantFee ("50.00");
            myUC029CreateHomeWarrantUtils.setSolicitorsCosts ("100.00");
            myUC029CreateHomeWarrantUtils.setLandRegistryFee ("25.00");
            myUC029CreateHomeWarrantUtils.clickDetailsOfWarrantPopupOk (); // Close popup

            // Save
            final String alertString = myUC029CreateHomeWarrantUtils.saveAndReturnAlertString ();
            final String searchString = "Warrant number is ";
            final int startIndex = alertString.indexOf (searchString) + searchString.length ();
            final String warrantNumber = alertString.substring (startIndex, startIndex + 8);
            assertTrue (
                    "\nExpected save message: " + hw_warrant_forwarded_message.replaceAll ("XXX", warrantNumber) +
                            " \nactual: " + alertString,
                    alertString.equals (hw_warrant_forwarded_message.replaceAll ("XXX", warrantNumber)));

            // Check that an automatic foreign warrant has been created
            assertTrue ("Foreign Warrant not automatically created",
                    DBUtil.checkAutomaticForeignWarrantExists (s1_case_no, warrantNumber, "282", "180"));

            // Check that an automatic final return 147 (Warrant forwarded) has been created
            assertTrue ("No Final Return 147 exists for this Warrant",
                    DBUtil.checkWarrantForwardedReturnCreated (s1_case_no, warrantNumber, "282", "180", "282"));
        }
        catch (final Exception e)
        {
            e.printStackTrace ();
            fail (e.getMessage ());
        }
    }

    /**
     * Scenario Two
     * Reissue an existing non live Home Warrant on the Reissue Warrants screen and set Executing Court
     * to foreign Court. New Reissued Warrant will be created, but NO Foreign Warrant will be created.
     * Final return 147 should be created as well.
     *
     * Need to check correct alert message displayed when new Warrant added
     */
    public void testWarrantScenario2 ()
    {
        try
        {
            // Log into SUPS CaseMan
            logOn (AbstractCmTestBase.COURT_NORTHAMPTON, AbstractCmTestBase.ROLE_WARRANT);

            // Navigate to the Reissue Warrants screen
            this.nav.navigateFromMainMenu (MAINMENU_REISSUE_WARRANTS_PATH);

            // Check in correct screen
            mCheckPageTitle (myUC031ReissueWarrantUtils.getScreenTitle ());

            // Set the Header fields and load warrant record
            myUC031ReissueWarrantUtils.setCaseNumber (s2_case_no);
            myUC031ReissueWarrantUtils.setWarrantNumber (s2_warrant_no);
            myUC031ReissueWarrantUtils.clickSearchButton ();

            // Set the footer fields
            myUC031ReissueWarrantUtils.setExecutingCourtCode ("180");
            myUC031ReissueWarrantUtils.setAdditionalDetails ("Additional Details");

            // Set the Warrant Details Amount fields
            myUC031ReissueWarrantUtils.setBalanceOfDebt ("1.00");
            myUC031ReissueWarrantUtils.setAmountOfWarrant ("1.00");
            myUC031ReissueWarrantUtils.setWarrantFee ("1.00");
            myUC031ReissueWarrantUtils.setLandRegistryFee ("1.00");

            // Save
            final String alertString = myUC031ReissueWarrantUtils.saveAndReturnAlertString ();
            final String searchString = "Re-issued warrant number is ";
            final int startIndex = alertString.indexOf (searchString) + searchString.length ();
            final String warrantNumber = alertString.substring (startIndex, startIndex + 8);
            assertTrue (
                    "\nExpected save message: " + ri_warrant_reissued_message.replaceAll ("XXX", warrantNumber) +
                            " \nactual: " + alertString,
                    alertString.equals (ri_warrant_reissued_message.replaceAll ("XXX", warrantNumber)));

            // Check that an automatic foreign warrant has NOT been created
            assertFalse ("Foreign Warrant automatically created in error",
                    DBUtil.checkAutomaticForeignWarrantExists (s2_case_no, warrantNumber, "282", "180"));

            // Check that an automatic final return 147 (Warrant forwarded) has been created
            assertTrue ("No Final Return 147 exists for this Warrant",
                    DBUtil.checkWarrantForwardedReturnCreated (s2_case_no, warrantNumber, "282", "180", "282"));
        }
        catch (final Exception e)
        {
            e.printStackTrace ();
            fail (e.getMessage ());
        }
    }

    /**
     * Scenario Three
     * On the Maintain/Query Warrants screen, forward an existing Home Warrant to a Foreign Court.
     * This will create a new Foreign Warrant copy and the Home Warrant will have a 147 final return
     * added.
     *
     * Need to check correct alert message displayed when new Warrant added
     */
    public void testWarrantScenario3 ()
    {
        try
        {
            // Log into SUPS CaseMan
            logOn (AbstractCmTestBase.COURT_NORTHAMPTON, AbstractCmTestBase.ROLE_WARRANT);

            // Navigate to the Maintain Warrants screen
            this.nav.navigateFromMainMenu (MAINMENU_MAINTAIN_WARRANTS_PATH);

            // Check in correct screen
            mCheckPageTitle (myUC039MaintainWarrantUtils.getScreenTitle ());

            // Retrieve the Warrant record
            myUC039MaintainWarrantUtils.setWarrantNumber (s3_warrant_no);
            myUC039MaintainWarrantUtils.setCaseNumber (s3_case_no);
            myUC039MaintainWarrantUtils.clickSearchButton ();

            // Forward to another SUPS Court and click Save
            myUC039MaintainWarrantUtils.setExecutingCourtCode ("180");
            final String alertString = myUC039MaintainWarrantUtils.saveAndReturnAlertString ();
            assertEquals (mn_hw_forwarded_message, alertString);

            // Check that an automatic foreign warrant has been created
            assertTrue ("Foreign Warrant not automatically created",
                    DBUtil.checkAutomaticForeignWarrantExists (s3_case_no, s3_warrant_no, "282", "180"));

            // Check that an automatic final return 147 (Warrant forwarded) has been created
            assertTrue ("No Final Return 147 exists for this Warrant",
                    DBUtil.checkWarrantForwardedReturnCreated (s3_case_no, s3_warrant_no, "282", "180", "282"));
        }
        catch (final Exception e)
        {
            e.printStackTrace ();
            fail (e.getMessage ());
        }
    }

    /**
     * Scenario Four
     * On the Maintain/Query Warrants screen, forward an existing Foreign Warrant to a Foreign Court.
     * This will create a new Foreign Warrant copy and the Foreign Warrant will have a 147 final return
     * added.
     *
     * Need to check correct alert message displayed when new Warrant added
     */
    public void testWarrantScenario4 ()
    {
        try
        {
            // Log into SUPS CaseMan
            logOn (AbstractCmTestBase.COURT_NORTHAMPTON, AbstractCmTestBase.ROLE_WARRANT);

            // Navigate to the Maintain Warrants screen
            this.nav.navigateFromMainMenu (MAINMENU_MAINTAIN_WARRANTS_PATH);

            // Check in correct screen
            mCheckPageTitle (myUC039MaintainWarrantUtils.getScreenTitle ());

            // Retrieve the Warrant record
            myUC039MaintainWarrantUtils.setLocalWarrantNumber (s4_local_warrant_no);
            myUC039MaintainWarrantUtils.setCaseNumber (s4_case_no);
            myUC039MaintainWarrantUtils.clickSearchButton ();

            // Forward to another SUPS Court and click Save
            myUC039MaintainWarrantUtils.setExecutingCourtCode ("378");
            final String alertString = myUC039MaintainWarrantUtils.saveAndReturnAlertString ();
            assertEquals (mn_fw_forwarded_message, alertString);

            // Check that an automatic foreign warrant has been created
            assertTrue ("Foreign Warrant not automatically created",
                    DBUtil.checkAutomaticForeignWarrantExists (s4_case_no, s4_warrant_no, "180", "378"));

            // Check that an automatic final return 147 (Warrant forwarded) has been created
            assertTrue ("No Final Return 147 exists for this Warrant",
                    DBUtil.checkWarrantForwardedReturnCreated (s4_case_no, s4_warrant_no, "180", "378", "282"));
        }
        catch (final Exception e)
        {
            e.printStackTrace ();
            fail (e.getMessage ());
        }
    }

    /**
     * Scenario Five
     * On the Maintain/Query Warrants screen, forward an existing Reissued Warrant to a Foreign Court.
     * This will NOT create a new Foreign Warrant copy but the Reissued Warrant will have a 147 final return
     * added.
     *
     * Need to check correct alert message displayed when new Warrant added
     */
    public void testWarrantScenario5 ()
    {
        try
        {
            // Log into SUPS CaseMan
            logOn (AbstractCmTestBase.COURT_NORTHAMPTON, AbstractCmTestBase.ROLE_WARRANT);

            // Navigate to the Maintain Warrants screen
            this.nav.navigateFromMainMenu (MAINMENU_MAINTAIN_WARRANTS_PATH);

            // Check in correct screen
            mCheckPageTitle (myUC039MaintainWarrantUtils.getScreenTitle ());

            // Retrieve the Warrant record
            myUC039MaintainWarrantUtils.setWarrantNumber (s5_reissue_no);
            myUC039MaintainWarrantUtils.setCaseNumber (s5_case_no);
            myUC039MaintainWarrantUtils.clickSearchButton ();

            // Forward to another SUPS Court and click Save
            myUC039MaintainWarrantUtils.setExecutingCourtCode ("180");
            final String alertString = myUC039MaintainWarrantUtils.saveAndReturnAlertString ();
            assertEquals (mn_rw_forwarded_message, alertString);

            // Check that an automatic foreign warrant has NOT been created
            assertFalse ("Foreign Warrant automatically created in error",
                    DBUtil.checkAutomaticForeignWarrantExists (s5_case_no, s5_reissue_no, "282", "180"));

            // Check that an automatic final return 147 (Warrant forwarded) has been created
            assertTrue ("No Final Return 147 exists for this Warrant",
                    DBUtil.checkWarrantForwardedReturnCreated (s5_case_no, s5_reissue_no, "282", "180", "282"));
        }
        catch (final Exception e)
        {
            e.printStackTrace ();
            fail (e.getMessage ());
        }
    }

    /**
     * Scenario Six
     * On the Maintain/Query Warrants screen, forward an existing Foreign Warrant copy of a Reissued Warrant
     * to a Foreign Court. This will NOT create a new Foreign Warrant copy (as Warrant will have been added via the
     * Create Foreign Warrants screen so will be printed). The Warrant forwarded will have a 147 final return
     * added.
     *
     * Need to check correct alert message displayed when new Warrant added
     */
    public void testWarrantScenario6 ()
    {
        try
        {
            // Log into SUPS CaseMan
            logOn (AbstractCmTestBase.COURT_NORTHAMPTON, AbstractCmTestBase.ROLE_WARRANT);

            // Navigate to the Maintain Warrants screen
            this.nav.navigateFromMainMenu (MAINMENU_MAINTAIN_WARRANTS_PATH);

            // Check in correct screen
            mCheckPageTitle (myUC039MaintainWarrantUtils.getScreenTitle ());

            // Retrieve the Warrant record
            myUC039MaintainWarrantUtils.setLocalWarrantNumber (s6_local_warrant_no);
            myUC039MaintainWarrantUtils.setCaseNumber (s6_case_no);
            myUC039MaintainWarrantUtils.clickSearchButton ();

            // Forward to another SUPS Court and click Save
            myUC039MaintainWarrantUtils.setExecutingCourtCode ("180");
            final String alertString = myUC039MaintainWarrantUtils.saveAndReturnAlertString ();
            assertEquals (mn_printed_fw_forwarded_message, alertString);

            // Check that an automatic foreign warrant has NOT been created
            assertFalse ("Foreign Warrant not automatically created",
                    DBUtil.checkAutomaticForeignWarrantExists (s6_case_no, s6_warrant_no, "170", "180"));

            // Check that an automatic final return 147 (Warrant forwarded) has been created
            assertTrue ("No Final Return 147 exists for this Warrant",
                    DBUtil.checkWarrantForwardedReturnCreated (s6_case_no, s6_warrant_no, "170", "180", "282"));
        }
        catch (final Exception e)
        {
            e.printStackTrace ();
            fail (e.getMessage ());
        }
    }

    /**
     * Private function which checks the current screen title against the expected screen title.
     *
     * @param control The expected screen title
     */
    private void mCheckPageTitle (final String control)
    {
        assertTrue ("Page title does not contain pattern '" + control + "'",
                session.getPageTitle ().indexOf (control) != -1);
    }

}