/*
 * Created on 06-Sep-2004
 *
 */
package uk.gov.dca.db.impl;

import uk.gov.dca.db.exception.*;

/**
 * An exception class for exceptions generated by implementations of 
 * IConfigurationItem
 * 
 * @author Grant Miller
 *
 */
public class ConfigurationItemException extends SystemException {

	
    private static final long serialVersionUID = -5902951110270903004L;

    /**
	 * 
	 */
	public ConfigurationItemException() {
		super();
		// TODO Auto-generated constructor stub
	}

	/**
	 * @param message
	 */
	public ConfigurationItemException(String message) {
		super(message);
		// TODO Auto-generated constructor stub
	}

	/**
	 * @param cause
	 */
	public ConfigurationItemException(Throwable cause) {
		super(cause);
		// TODO Auto-generated constructor stub
	}

	/**
	 * @param message
	 * @param cause
	 */
	public ConfigurationItemException(String message, Throwable cause) {
		super(message, cause);
		// TODO Auto-generated constructor stub
	}

}
