application.service.uri.prefix=/caseman

application.name=caseman
base.build.dir=c:/SUPS/build/caseman/caseman_server

custom.path=c:/tools/extracted/avalon-framework/avalon-framework-4.1.5.jar;c:/tools/extracted/fop-0.20.5/build/fop.jar;c:/tools/extracted/oracle/ojdbc14.jar;c:/tools/extracted/xalan-j_2_6_0/bin/xalan.jar;c:/tools/extracted/jboss-4.0.1/server/default/lib/javax.servlet.jar;c:/tools/extracted/junit3.8.1/junit.jar
custom.ant.build.file=../../wp_build.xml

# Defines values which vary depending on the deployment. 
# This is a common file shared by client and server, but stored in the server project.
# If client/server separation is required, an identical copy should be used.
# environment.properties.file=environment.properties 

# name of the folder which contains the server side caching files
service.config.directory=cache-config

oas.home=${env.SUPS_OAS_HOME}
oas.deploy.dir=${oas.home}/j2ee/caseman/applications

# Workaround for problem introduced by framework 9.0.33
application.conf=${base.build.dir}/conf
default_ant_file=${base.build.dir}/frwk-build.xml

# Properties included from caseman_server_build.xml in an attempt to
# centralise them, making them easier to maintain. 
serverframework.dir=${basedir}/serverframework/release
serverframework.lib.dir=${serverframework.dir}/lib
build.dir=${base.build.dir}
dist.dir=${build.dir}/dist/OAS
target.platform=OAS