application_name=caseman
drive=c:
jboss_server_dir=${drive}/tools/extracted/jboss-4.0.1/server/default
build_config=${drive}/build/casemanserver/config
source_config=${drive}/build/casemanserver/web-config
server_dist=${drive}/build/casemanserver/dist/${application_name}.ear