######################################################################
#
# oc4j management properties, used to deploy to your oc4j 
#
######################################################################
oc4j.home.dir=${env.SUPS_OC4J_HOME}
oc4j.framework.lib=./serverframework/release/lib

oc4j.admin.password=oracle

ocj4.https.site=sups-https-web-site
ocj4.http.site=sups-http-web-site

oc4j.check.server=localhost
oc4j.check.port=7070

#oc4j.ormi.admin.url=ormi://localhost:23791
oc4j.admin.url=ormi://localhost:23791

oc4j.xbootclasspath=-Xbootclasspath/a:${oc4j.home.dir}/jdbc/lib/ojdbc14.jar;${oc4j.home.dir}/jdbc/lib/ojdbc14dms.jar;${oc4j.home.dir}/jdbc/lib/orai18n.jar;${oc4j.home.dir}/xalan/xalan.jar;${oc4j.home.dir}/xalan/xml-apis.jar;${oc4j.home.dir}/xalan/xercesImpl.jar

debug.socket=-Xrunjdwp:transport=dt_socket,address=8787,server=y,suspend=y