-----------------
--- Object Grants
-----------------

  GRANT EXECUTE ON "SYS"."SET_SUPS_APP_CTX" TO "FAMILYMAN";
 
  GRANT READ ON DIRECTORY "SOURCE_DIR" TO "FAMILYMAN";
 
  GRANT WRITE ON DIRECTORY "SOURCE_DIR" TO "FAMILYMAN";
 
  GRANT SELECT ON "CASEMAN"."CODED_PARTIES" TO "FAMILYMAN";
 
  GRANT SELECT ON "CASEMAN"."LOCAL_AUTHORITY_CODES" TO "FAMILYMAN";
 
  GRANT SELECT ON "CASEMAN"."DFJ_AREAS" TO "FAMILYMAN";
 
  GRANT SELECT ON "CASEMAN"."COURTS" TO "FAMILYMAN";
 
  GRANT SELECT ON "CASEMAN"."GIVEN_ADDRESSES" TO "FAMILYMAN";
 
  GRANT SELECT ON "CASEMAN"."JUDGES" TO "FAMILYMAN";
 
  GRANT SELECT ON "CASEMAN"."NON_WORKING_DAYS" TO "FAMILYMAN";
 
  GRANT SELECT ON "CASEMAN"."NON_WORKING_DAYS_EXCEPTIONS" TO "FAMILYMAN";
 
  GRANT SELECT ON "CASEMAN"."PERSONALISE" TO "FAMILYMAN";

-----------------
--- System Grants
-----------------
