
  ALTER TABLE "CASEMAN"."AE_EVENTS" ADD CONSTRAINT "AEV_AE_FK" FOREIGN KEY ("AE_NUMBER")
      REFERENCES "CASEMAN"."AE_APPLICATIONS" ("AE_NUMBER") ENABLE;



  ALTER TABLE "CASEMAN"."AE_EVENTS" ADD CONSTRAINT "AEV_HRG_FK" FOREIGN KEY ("HRG_SEQ")
      REFERENCES "CASEMAN"."HEARINGS" ("HRG_SEQ") ENABLE;



  ALTER TABLE "CASEMAN"."TASK_COUNTS" ADD CONSTRAINT "AGE_CNT_FK" FOREIGN KEY ("AGE_CATEGORY")
      REFERENCES "CASEMAN"."AGE_CATEGORY" ("AGE_CATEGORY") ENABLE;



  ALTER TABLE "CASEMAN"."ALLOWED_DEBTS" ADD CONSTRAINT "ALD_CO_FK" FOREIGN KEY ("DEBT_CO_NUMBER")
      REFERENCES "CASEMAN"."CONSOLIDATED_ORDERS" ("CO_NUMBER") ENABLE;



  ALTER TABLE "CASEMAN"."ALLOWED_DEBTS" ADD CONSTRAINT "ALD_CT_FK" FOREIGN KEY ("DEBT_ADMIN_COURT_CODE")
      REFERENCES "CASEMAN"."COURTS" ("CODE") ENABLE;



  ALTER TABLE "CASEMAN"."TASK_ALLOCATIONS" ADD CONSTRAINT "ALLOC_SEC_FK" FOREIGN KEY ("SECTION_NAME", "ADMIN_COURT_CODE")
      REFERENCES "CASEMAN"."SECTIONS" ("SECTION_NAME", "ADMIN_COURT_CODE") DISABLE;



  ALTER TABLE "CASEMAN"."AO_CAEO_DIVIDEND" ADD CONSTRAINT "AODIV_FK" FOREIGN KEY ("AO_CAEO_NUMBER", "ADMIN_COURT_CODE")
      REFERENCES "CASEMAN"."AO_CAEO" ("AO_CAEO_NUMBER", "ADMIN_COURT_CODE") DISABLE;



  ALTER TABLE "CASEMAN"."AE_PER_ITEMS" ADD CONSTRAINT "API_AE_FK" FOREIGN KEY ("AE_NUMBER")
      REFERENCES "CASEMAN"."AE_APPLICATIONS" ("AE_NUMBER") ENABLE;



  ALTER TABLE "CASEMAN"."AE_PER_ITEMS" ADD CONSTRAINT "API_PDT_FK" FOREIGN KEY ("DETAIL_CODE")
      REFERENCES "CASEMAN"."PER_DETAILS" ("DETAIL_CODE") ENABLE;



  ALTER TABLE "CASEMAN"."ACTION_TASK_XREF" ADD CONSTRAINT "ATX_TSK_FK" FOREIGN KEY ("TASK_NUMBER")
      REFERENCES "CASEMAN"."TASKS" ("TASK_NUMBER") ENABLE;



  ALTER TABLE "CASEMAN"."AE_EVENTS" ADD CONSTRAINT "AVE_STD_FK" FOREIGN KEY ("STD_EVENT_ID")
      REFERENCES "CASEMAN"."STANDARD_EVENTS" ("EVENT_ID") ENABLE;



  ALTER TABLE "CASEMAN"."CASES" ADD CONSTRAINT "CASE_ADMIN_BY" FOREIGN KEY ("ADMIN_CRT_CODE")
      REFERENCES "CASEMAN"."COURTS" ("CODE") ENABLE;



  ALTER TABLE "CASEMAN"."CASES" ADD CONSTRAINT "CASE_PREV_CT_FK" FOREIGN KEY ("PREVIOUS_COURT")
      REFERENCES "CASEMAN"."COURTS" ("CODE") ENABLE;



  ALTER TABLE "CASEMAN"."CASES" ADD CONSTRAINT "CASE_TRANS_TO" FOREIGN KEY ("TRANS_CRT_CODE")
      REFERENCES "CASEMAN"."COURTS" ("CODE") ENABLE;



  ALTER TABLE "CASEMAN"."TAPE_FILES" ADD CONSTRAINT "CCBC_R_1687" FOREIGN KEY ("SEQNO")
      REFERENCES "CASEMAN"."TAPES" ("SEQNO") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."MCOL_DATA" ADD CONSTRAINT "CCBC_R_1690" FOREIGN KEY ("REJECT_CODE")
      REFERENCES "CASEMAN"."REJECT_REASONS" ("REJECT_CODE") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."CANDIDATE_DIVIDEND_PAYMENTS" ADD CONSTRAINT "CDP_CO_FK" FOREIGN KEY ("CDP_CO_NUMBER")
      REFERENCES "CASEMAN"."CONSOLIDATED_ORDERS" ("CO_NUMBER") ENABLE;



  ALTER TABLE "CASEMAN"."CANDIDATE_DIVIDEND_PAYMENTS" ADD CONSTRAINT "CDP_PAY_FK" FOREIGN KEY ("CDP_TRANSACTION_NUMBER", "ADMIN_COURT_CODE")
      REFERENCES "CASEMAN"."PAYMENTS" ("TRANSACTION_NUMBER", "ADMIN_COURT_CODE") ENABLE;



  ALTER TABLE "CASEMAN"."CHANGED_EVENTS" ADD CONSTRAINT "CHEVT_STDEVT_FK" FOREIGN KEY ("STD_EVENT_ID")
      REFERENCES "CASEMAN"."STANDARD_EVENTS" ("EVENT_ID") ENABLE;



  ALTER TABLE "CASEMAN"."CO_EVENTS" ADD CONSTRAINT "COV_ALD_FK" FOREIGN KEY ("ALD_DEBT_SEQ")
      REFERENCES "CASEMAN"."ALLOWED_DEBTS" ("DEBT_SEQ") ENABLE;



  ALTER TABLE "CASEMAN"."CO_EVENTS" ADD CONSTRAINT "COV_SE_FK" FOREIGN KEY ("STD_EVENT_ID")
      REFERENCES "CASEMAN"."STANDARD_EVENTS" ("EVENT_ID") ENABLE;



  ALTER TABLE "CASEMAN"."CO_PER_ITEMS" ADD CONSTRAINT "CPI_CO_FK" FOREIGN KEY ("CO_NUMBER")
      REFERENCES "CASEMAN"."CONSOLIDATED_ORDERS" ("CO_NUMBER") ENABLE;



  ALTER TABLE "CASEMAN"."CO_TEXT_ITEMS" ADD CONSTRAINT "CTI_COV_FK" FOREIGN KEY ("CO_TEXT_EVENT_SEQ")
      REFERENCES "CASEMAN"."CO_EVENTS" ("CO_EVENT_SEQ") ENABLE;



  ALTER TABLE "CASEMAN"."CO_TEXT_ITEMS" ADD CONSTRAINT "CTI_CO_FK" FOREIGN KEY ("CO_TEXT_CO_NUMBER")
      REFERENCES "CASEMAN"."CONSOLIDATED_ORDERS" ("CO_NUMBER") ENABLE;



  ALTER TABLE "CASEMAN"."CO_TEXT_ITEMS" ADD CONSTRAINT "CTI_ITD_FK" FOREIGN KEY ("CO_TEXT_DETAIL_CODE")
      REFERENCES "CASEMAN"."ITEM_DETAILS" ("CODE") ENABLE;



  ALTER TABLE "CASEMAN"."CO_TEXT_ITEMS" ADD CONSTRAINT "CTI_ORD_FK" FOREIGN KEY ("CO_TEXT_ORDER_ID")
      REFERENCES "CASEMAN"."ORDER_TYPES" ("ORDER_ID") ENABLE;



  ALTER TABLE "CASEMAN"."DEBT_DIVIDENDS" ADD CONSTRAINT "DD_ALD_FK" FOREIGN KEY ("DD_ALD_SEQ")
      REFERENCES "CASEMAN"."ALLOWED_DEBTS" ("DEBT_SEQ") ENABLE;



  ALTER TABLE "CASEMAN"."DEBT_DIVIDENDS" ADD CONSTRAINT "DD_DIV_FK" FOREIGN KEY ("DD_CO_NUMBER", "DD_DIV_NUMBER")
      REFERENCES "CASEMAN"."DIVIDENDS" ("DIV_CO_NUMBER", "DIV_NUMBER") ENABLE;



  ALTER TABLE "CASEMAN"."CPT_DEFENDANTS" ADD CONSTRAINT "DEFT_FK1" FOREIGN KEY ("CLAIM_NUMBER")
      REFERENCES "CASEMAN"."CPT_CLAIMS" ("CLAIM_NUMBER") DISABLE;



  ALTER TABLE "CASEMAN"."DIVIDENDS" ADD CONSTRAINT "DIV_CO_FK" FOREIGN KEY ("DIV_CO_NUMBER")
      REFERENCES "CASEMAN"."CONSOLIDATED_ORDERS" ("CO_NUMBER") ENABLE;



  ALTER TABLE "CASEMAN"."OBLIGATIONS" ADD CONSTRAINT "DMS_AE_FK" FOREIGN KEY ("AE_EVENT_SEQ")
      REFERENCES "CASEMAN"."AE_EVENTS" ("AE_EVENT_SEQ") ENABLE;



  ALTER TABLE "CASEMAN"."OBLIGATIONS" ADD CONSTRAINT "DMS_EVENT_FK" FOREIGN KEY ("EVENT_SEQ")
      REFERENCES "CASEMAN"."CASE_EVENTS" ("EVENT_SEQ") ENABLE;



  ALTER TABLE "CASEMAN"."OBLIGATIONS" ADD CONSTRAINT "DMS_OBLN_FK" FOREIGN KEY ("OBLIGATION_TYPE")
      REFERENCES "CASEMAN"."OBLIGATION_TYPES" ("OBLIGATION_TYPE") ENABLE;



  ALTER TABLE "CASEMAN"."OBLIGATION_RULES" ADD CONSTRAINT "DMS_RULES_FK" FOREIGN KEY ("OBLIGATION_TYPE")
      REFERENCES "CASEMAN"."OBLIGATION_TYPES" ("OBLIGATION_TYPE") DISABLE;



  ALTER TABLE "CASEMAN"."ECHR_ARTICLE_PROTOCOL" ADD CONSTRAINT "ECHRAP_DETAILS_FK" FOREIGN KEY ("EVENT_SEQ")
      REFERENCES "CASEMAN"."ECHR_DETAILS" ("EVENT_SEQ") ENABLE;



  ALTER TABLE "CASEMAN"."ECHR_DETAILS" ADD CONSTRAINT "ECHR_CASE_EVENT_FK" FOREIGN KEY ("EVENT_SEQ")
      REFERENCES "CASEMAN"."CASE_EVENTS" ("EVENT_SEQ") ENABLE;



  ALTER TABLE "CASEMAN"."CASE_EVENTS" ADD CONSTRAINT "EVENT_FOR" FOREIGN KEY ("CASE_NUMBER")
      REFERENCES "CASEMAN"."CASES" ("CASE_NUMBER") ENABLE;



  ALTER TABLE "CASEMAN"."CASE_EVENTS" ADD CONSTRAINT "EVENT_HRG" FOREIGN KEY ("HRG_SEQ")
      REFERENCES "CASEMAN"."HEARINGS" ("HRG_SEQ") ENABLE;



  ALTER TABLE "CASEMAN"."CASE_EVENTS" ADD CONSTRAINT "EVENT_JUDG" FOREIGN KEY ("JUDG_SEQ")
      REFERENCES "CASEMAN"."JUDGMENTS" ("JUDG_SEQ") ENABLE;



  ALTER TABLE "CASEMAN"."CASE_EVENTS" ADD CONSTRAINT "EVENT_OCCURENCE_OF" FOREIGN KEY ("STD_EVENT_ID")
      REFERENCES "CASEMAN"."STANDARD_EVENTS" ("EVENT_ID") ENABLE;



  ALTER TABLE "CASEMAN"."CASE_EVENTS" ADD CONSTRAINT "EVENT_VARY" FOREIGN KEY ("VARY_SEQ")
      REFERENCES "CASEMAN"."VARIATIONS" ("VARY_SEQ") ENABLE;



  ALTER TABLE "CASEMAN"."EVENT_OUTPUTS" ADD CONSTRAINT "EVTOUT_ORDTYP_FK" FOREIGN KEY ("ORDER_TYPE_ID")
      REFERENCES "CASEMAN"."ORDER_TYPES" ("ORDER_ID") ENABLE;



  ALTER TABLE "CASEMAN"."EVENT_OUTPUTS" ADD CONSTRAINT "EVTOUT_STDEVT_FK" FOREIGN KEY ("STD_EVENT_ID")
      REFERENCES "CASEMAN"."STANDARD_EVENTS" ("EVENT_ID") ENABLE;



  ALTER TABLE "CASEMAN"."DELETE_CANDIDATES" ADD CONSTRAINT "FK_EXCEPTIONS" FOREIGN KEY ("EXCEPTION_REASON")
      REFERENCES "CASEMAN"."DELETE_EXCEPTION_REASONS" ("EXCEPTION_REASON") ENABLE;



  ALTER TABLE "CASEMAN"."HEARINGS" ADD CONSTRAINT "HRG_CASE_FK" FOREIGN KEY ("CASE_NUMBER")
      REFERENCES "CASEMAN"."CASES" ("CASE_NUMBER") ENABLE;



  ALTER TABLE "CASEMAN"."HEARINGS" ADD CONSTRAINT "HRG_CRT_FK" FOREIGN KEY ("CRT_CODE")
      REFERENCES "CASEMAN"."COURTS" ("CODE") ENABLE;



  ALTER TABLE "CASEMAN"."OUTPUT_DETAILS" ADD CONSTRAINT "ODT_ORD_TYPE_FK" FOREIGN KEY ("ORDER_TYPE_ID")
      REFERENCES "CASEMAN"."ORDER_TYPES" ("ORDER_ID") ENABLE;



  ALTER TABLE "CASEMAN"."PAYMENTS" ADD CONSTRAINT "PAY_ALD_FK" FOREIGN KEY ("ALD_DEBT_SEQ")
      REFERENCES "CASEMAN"."ALLOWED_DEBTS" ("DEBT_SEQ") ENABLE;



  ALTER TABLE "CASEMAN"."PAYABLE_ORDER_ITEMS" ADD CONSTRAINT "PMNT_ITM_FK" FOREIGN KEY ("TRANSACTION_NUMBER", "ADMIN_COURT_CODE")
      REFERENCES "CASEMAN"."PAYMENTS" ("TRANSACTION_NUMBER", "ADMIN_COURT_CODE") ENABLE;



  ALTER TABLE "CASEMAN"."PRINTERS" ADD CONSTRAINT "PRINT_CT_FK" FOREIGN KEY ("COURT_ID")
      REFERENCES "CASEMAN"."COURTS" ("CODE") ENABLE;



  ALTER TABLE "CASEMAN"."REPORT_PARAMETERS" ADD CONSTRAINT "PRM_FK" FOREIGN KEY ("REPORT_NAME")
      REFERENCES "CASEMAN"."REPORTS" ("REPORT_NAME") DISABLE;



  ALTER TABLE "CASEMAN"."REPRINTS" ADD CONSTRAINT "REPRINT_CASE_FK" FOREIGN KEY ("CASE_NUMBER")
      REFERENCES "CASEMAN"."CASES" ("CASE_NUMBER") ENABLE;



  ALTER TABLE "CASEMAN"."USER_COURT" ADD CONSTRAINT "R_1" FOREIGN KEY ("USER_ID")
      REFERENCES "CASEMAN"."DCA_USER" ("USER_ID") ENABLE;



  ALTER TABLE "CASEMAN"."AE_APPLICATIONS" ADD CONSTRAINT "R_1333" FOREIGN KEY ("JUDG_SEQ")
      REFERENCES "CASEMAN"."JUDGMENTS" ("JUDG_SEQ") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."WARRANT_RETURNS" ADD CONSTRAINT "R_1339" FOREIGN KEY ("WARRANT_ID")
      REFERENCES "CASEMAN"."WARRANTS" ("WARRANT_ID") DISABLE;



  ALTER TABLE "CASEMAN"."WARRANT_RETURNS" ADD CONSTRAINT "R_1340" FOREIGN KEY ("RETURN_CODE", "RETURN_CODE_COURT_CODE")
      REFERENCES "CASEMAN"."RETURN_CODES" ("RETURN_CODE", "ADMIN_COURT_CODE") ENABLE;



  ALTER TABLE "CASEMAN"."WARRANTS" ADD CONSTRAINT "R_1342" FOREIGN KEY ("CO_NUMBER")
      REFERENCES "CASEMAN"."CONSOLIDATED_ORDERS" ("CO_NUMBER") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."HEARINGS" ADD CONSTRAINT "R_1358" FOREIGN KEY ("CO_NUMBER")
      REFERENCES "CASEMAN"."CONSOLIDATED_ORDERS" ("CO_NUMBER") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."OBLIGATIONS" ADD CONSTRAINT "R_1419" FOREIGN KEY ("CASE_NUMBER")
      REFERENCES "CASEMAN"."CASES" ("CASE_NUMBER") ENABLE;



  ALTER TABLE "CASEMAN"."CO_EVENTS" ADD CONSTRAINT "R_1442" FOREIGN KEY ("HRG_SEQ")
      REFERENCES "CASEMAN"."HEARINGS" ("HRG_SEQ") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."CO_EVENTS" ADD CONSTRAINT "R_1443" FOREIGN KEY ("CO_NUMBER")
      REFERENCES "CASEMAN"."CONSOLIDATED_ORDERS" ("CO_NUMBER") ENABLE;



  ALTER TABLE "CASEMAN"."PRINTERS" ADD CONSTRAINT "R_1615" FOREIGN KEY ("MODEL")
      REFERENCES "CASEMAN"."PRINTER_TYPES" ("MODEL") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."CASE_EVENTS" ADD CONSTRAINT "R_1625" FOREIGN KEY ("WARRANT_ID")
      REFERENCES "CASEMAN"."WARRANTS" ("WARRANT_ID") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."CO_CASE_EVENTS" ADD CONSTRAINT "R_1626" FOREIGN KEY ("STD_EVENT_ID")
      REFERENCES "CASEMAN"."STANDARD_EVENTS" ("EVENT_ID") ENABLE;



  ALTER TABLE "CASEMAN"."CO_CASE_EVENTS" ADD CONSTRAINT "R_1627" FOREIGN KEY ("ADMIN_COURT_CODE")
      REFERENCES "CASEMAN"."COURTS" ("CODE") ENABLE;



  ALTER TABLE "CASEMAN"."CO_CASE_EVENTS" ADD CONSTRAINT "R_1629" FOREIGN KEY ("ALD_DEBT_SEQ")
      REFERENCES "CASEMAN"."ALLOWED_DEBTS" ("DEBT_SEQ") ENABLE;



  ALTER TABLE "CASEMAN"."CO_EVENT_VALIDATIONS" ADD CONSTRAINT "R_1630" FOREIGN KEY ("STD_EVENT_ID")
      REFERENCES "CASEMAN"."STANDARD_EVENTS" ("EVENT_ID") ENABLE;



  ALTER TABLE "CASEMAN"."CO_EVENT_VALIDATIONS" ADD CONSTRAINT "R_1631" FOREIGN KEY ("PRE_REQ_EVENT1")
      REFERENCES "CASEMAN"."STANDARD_EVENTS" ("EVENT_ID") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."CO_EVENT_VALIDATIONS" ADD CONSTRAINT "R_1632" FOREIGN KEY ("PRE_REQ_EVENT2")
      REFERENCES "CASEMAN"."STANDARD_EVENTS" ("EVENT_ID") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."CO_EVENT_VALIDATIONS" ADD CONSTRAINT "R_1633" FOREIGN KEY ("PRE_REQ_EVENT3")
      REFERENCES "CASEMAN"."STANDARD_EVENTS" ("EVENT_ID") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."PERSONALISE" ADD CONSTRAINT "R_1639" FOREIGN KEY ("CRT_CODE")
      REFERENCES "CASEMAN"."COURTS" ("CODE") ENABLE;



  ALTER TABLE "CASEMAN"."PRE_REQ_EVENTS" ADD CONSTRAINT "R_1640" FOREIGN KEY ("STD_EVENT_ID")
      REFERENCES "CASEMAN"."STANDARD_EVENTS" ("EVENT_ID") ENABLE;



  ALTER TABLE "CASEMAN"."REPORT_REPRINTS_XREF" ADD CONSTRAINT "R_1641" FOREIGN KEY ("REPRINTS_ID")
      REFERENCES "CASEMAN"."REPRINTS" ("ID") DISABLE;



  ALTER TABLE "CASEMAN"."REPORT_REPRINTS_XREF" ADD CONSTRAINT "R_1642" FOREIGN KEY ("USERNAME", "REPORT_REPRINTS_ID")
      REFERENCES "CASEMAN"."REPORT_REPRINTS" ("USERNAME", "REPORT_ID") DISABLE;



  ALTER TABLE "CASEMAN"."WARRANTS" ADD CONSTRAINT "R_1645" FOREIGN KEY ("EXECUTED_BY")
      REFERENCES "CASEMAN"."COURTS" ("CODE") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."VALID_VALUES" ADD CONSTRAINT "R_1646" FOREIGN KEY ("VALS_DETAILS_CODE")
      REFERENCES "CASEMAN"."ITEM_DETAILS" ("CODE") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."EVENT_TASK_XREF" ADD CONSTRAINT "R_1647" FOREIGN KEY ("EVENT_ID")
      REFERENCES "CASEMAN"."STANDARD_EVENTS" ("EVENT_ID") ENABLE;



  ALTER TABLE "CASEMAN"."CO_EVENTS" ADD CONSTRAINT "R_1648" FOREIGN KEY ("BMS_TASK_NUMBER")
      REFERENCES "CASEMAN"."TASKS" ("TASK_NUMBER") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."CO_EVENTS" ADD CONSTRAINT "R_1649" FOREIGN KEY ("AGE_CATEGORY")
      REFERENCES "CASEMAN"."AGE_CATEGORY" ("AGE_CATEGORY") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."CASE_EVENTS" ADD CONSTRAINT "R_1650" FOREIGN KEY ("BMS_TASK_NUMBER")
      REFERENCES "CASEMAN"."TASKS" ("TASK_NUMBER") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."CASE_EVENTS" ADD CONSTRAINT "R_1651" FOREIGN KEY ("AGE_CATEGORY")
      REFERENCES "CASEMAN"."AGE_CATEGORY" ("AGE_CATEGORY") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."AE_EVENTS" ADD CONSTRAINT "R_1652" FOREIGN KEY ("WARRANT_ID")
      REFERENCES "CASEMAN"."WARRANTS" ("WARRANT_ID") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."CO_EVENTS" ADD CONSTRAINT "R_1653" FOREIGN KEY ("WARRANT_ID")
      REFERENCES "CASEMAN"."WARRANTS" ("WARRANT_ID") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."WARRANTS" ADD CONSTRAINT "R_1656" FOREIGN KEY ("ISSUED_BY")
      REFERENCES "CASEMAN"."COURTS" ("CODE") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."CONSOLIDATED_ORDERS" ADD CONSTRAINT "R_1657" FOREIGN KEY ("ADMIN_COURT_CODE")
      REFERENCES "CASEMAN"."COURTS" ("CODE") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."MENU_ITEM_GROUP" ADD CONSTRAINT "R_1659_MENU" FOREIGN KEY ("MENU_ITEM_ID")
      REFERENCES "CASEMAN"."MENU_ITEM" ("MENU_ITEM_ID") DISABLE;



  ALTER TABLE "CASEMAN"."AE_APPLICATIONS" ADD CONSTRAINT "R_1661" FOREIGN KEY ("ISSUING_CRT_CODE")
      REFERENCES "CASEMAN"."COURTS" ("CODE") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."PARTY_TO_PARTY_RELATIONSHIP" ADD CONSTRAINT "R_1663" FOREIGN KEY ("PARTY_B_ID")
      REFERENCES "CASEMAN"."PARTIES" ("PARTY_ID") ENABLE;



  ALTER TABLE "CASEMAN"."PARTY_TO_PARTY_RELATIONSHIP" ADD CONSTRAINT "R_1664" FOREIGN KEY ("PARTY_A_ID")
      REFERENCES "CASEMAN"."PARTIES" ("PARTY_ID") ENABLE;



  ALTER TABLE "CASEMAN"."PARTY_TO_PARTY_RELATIONSHIP" ADD CONSTRAINT "R_1665" FOREIGN KEY ("PARTY_A_ROLE_CODE")
      REFERENCES "CASEMAN"."PARTY_ROLES" ("PARTY_ROLE_CODE") ENABLE;



  ALTER TABLE "CASEMAN"."PARTIES" ADD CONSTRAINT "R_1667" FOREIGN KEY ("ETHNIC_ORIGIN_CODE")
      REFERENCES "CASEMAN"."ETHNIC_ORIGIN" ("ETHNIC_ORIGIN_CODE") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."CASE_PARTY_ROLES" ADD CONSTRAINT "R_1668" FOREIGN KEY ("CASE_NUMBER")
      REFERENCES "CASEMAN"."CASES" ("CASE_NUMBER") ENABLE;



  ALTER TABLE "CASEMAN"."CASE_PARTY_ROLES" ADD CONSTRAINT "R_1669" FOREIGN KEY ("PARTY_ID")
      REFERENCES "CASEMAN"."PARTIES" ("PARTY_ID") ENABLE;



  ALTER TABLE "CASEMAN"."CASE_PARTY_ROLES" ADD CONSTRAINT "R_1670" FOREIGN KEY ("PARTY_ROLE_CODE")
      REFERENCES "CASEMAN"."PARTY_ROLES" ("PARTY_ROLE_CODE") ENABLE;



  ALTER TABLE "CASEMAN"."PARTY_TO_PARTY_RELATIONSHIP" ADD CONSTRAINT "R_1672" FOREIGN KEY ("PARTY_B_ROLE_CODE")
      REFERENCES "CASEMAN"."PARTY_ROLES" ("PARTY_ROLE_CODE") ENABLE;



  ALTER TABLE "CASEMAN"."PAYMENTS" ADD CONSTRAINT "R_1675" FOREIGN KEY ("PAYEE_ID")
      REFERENCES "CASEMAN"."PARTIES" ("PARTY_ID") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."PARTIES" ADD CONSTRAINT "R_1680" FOREIGN KEY ("PARTY_TYPE_CODE")
      REFERENCES "CASEMAN"."PARTY_TYPES" ("PARTY_TYPE_CODE") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."JUDGMENTS" ADD CONSTRAINT "R_1681" FOREIGN KEY ("CASE_NUMBER", "AGAINST_CASE_PARTY_NO", "AGAINST_PARTY_ROLE_CODE")
      REFERENCES "CASEMAN"."CASE_PARTY_ROLES" ("CASE_NUMBER", "CASE_PARTY_NO", "PARTY_ROLE_CODE") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."WARRANTS" ADD CONSTRAINT "R_1686" FOREIGN KEY ("CURRENTLY_OWNED_BY")
      REFERENCES "CASEMAN"."COURTS" ("CODE") ENABLE;



  ALTER TABLE "CASEMAN"."JUDGMENTS" ADD CONSTRAINT "R_1688" FOREIGN KEY ("JUDGMENT_COURT_CODE")
      REFERENCES "CASEMAN"."COURTS" ("CODE") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."CASE_EVENTS" ADD CONSTRAINT "R_1689" FOREIGN KEY ("CRT_CODE")
      REFERENCES "CASEMAN"."COURTS" ("CODE") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."CASE_EVENTS" ADD CONSTRAINT "R_1690" FOREIGN KEY ("CASE_NUMBER", "CASE_PARTY_NO", "PARTY_ROLE_CODE")
      REFERENCES "CASEMAN"."CASE_PARTY_ROLES" ("CASE_NUMBER", "CASE_PARTY_NO", "PARTY_ROLE_CODE") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."AE_APPLICATIONS" ADD CONSTRAINT "R_1691" FOREIGN KEY ("CASE_NUMBER", "PARTY_AGAINST_CASE_PARTY_NO", "PARTY_AGAINST_PARTY_ROLE_CODE")
      REFERENCES "CASEMAN"."CASE_PARTY_ROLES" ("CASE_NUMBER", "CASE_PARTY_NO", "PARTY_ROLE_CODE") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."AO_CAEO" ADD CONSTRAINT "R_1692" FOREIGN KEY ("ADMIN_COURT_CODE")
      REFERENCES "CASEMAN"."COURTS" ("CODE") ENABLE;



  ALTER TABLE "CASEMAN"."PAYMENTS" ADD CONSTRAINT "R_1693" FOREIGN KEY ("ADMIN_COURT_CODE")
      REFERENCES "CASEMAN"."COURTS" ("CODE") ENABLE;



  ALTER TABLE "CASEMAN"."CO_REPRINTS" ADD CONSTRAINT "R_1695" FOREIGN KEY ("ADMIN_COURT_CODE")
      REFERENCES "CASEMAN"."COURTS" ("CODE") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."DCS" ADD CONSTRAINT "R_1696" FOREIGN KEY ("ADMIN_COURT_CODE")
      REFERENCES "CASEMAN"."COURTS" ("CODE") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."LOCALCOPS_TEMP" ADD CONSTRAINT "R_1697" FOREIGN KEY ("ID")
      REFERENCES "CASEMAN"."REPRINTS" ("ID") ON DELETE SET NULL DISABLE;



  ALTER TABLE "CASEMAN"."TEMP" ADD CONSTRAINT "R_1698" FOREIGN KEY ("ID")
      REFERENCES "CASEMAN"."REPRINTS" ("ID") ON DELETE SET NULL DISABLE;



  ALTER TABLE "CASEMAN"."PAYABLE_ORDER_HEADER" ADD CONSTRAINT "R_1700" FOREIGN KEY ("ADMIN_COURT_CODE")
      REFERENCES "CASEMAN"."COURTS" ("CODE") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."PAYABLE_ORDERS" ADD CONSTRAINT "R_1701" FOREIGN KEY ("ADMIN_COURT_CODE")
      REFERENCES "CASEMAN"."COURTS" ("CODE") ENABLE;



  ALTER TABLE "CASEMAN"."PAYMENT_SUMMARY" ADD CONSTRAINT "R_1702" FOREIGN KEY ("ADMIN_COURT_CODE")
      REFERENCES "CASEMAN"."COURTS" ("CODE") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."REPORT_DATA" ADD CONSTRAINT "R_1703" FOREIGN KEY ("ADMIN_COURT_CODE")
      REFERENCES "CASEMAN"."COURTS" ("CODE") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."REPRINT_TEXT_ITEMS" ADD CONSTRAINT "R_1704" FOREIGN KEY ("EVENT_SEQ")
      REFERENCES "CASEMAN"."CASE_EVENTS" ("EVENT_SEQ") ON DELETE SET NULL DISABLE;



  ALTER TABLE "CASEMAN"."SECTIONS" ADD CONSTRAINT "R_1707" FOREIGN KEY ("ADMIN_COURT_CODE")
      REFERENCES "CASEMAN"."COURTS" ("CODE") ENABLE;



  ALTER TABLE "CASEMAN"."SYSTEM_DATA" ADD CONSTRAINT "R_1709" FOREIGN KEY ("ADMIN_COURT_CODE")
      REFERENCES "CASEMAN"."COURTS" ("CODE") ENABLE;



  ALTER TABLE "CASEMAN"."TASK_COUNTS" ADD CONSTRAINT "R_1710" FOREIGN KEY ("ADMIN_COURT_CODE")
      REFERENCES "CASEMAN"."COURTS" ("CODE") ENABLE;



  ALTER TABLE "CASEMAN"."CPR_TO_CPR_RELATIONSHIP" ADD CONSTRAINT "R_1714" FOREIGN KEY ("CPR_A_CASE_NUMBER", "CPR_A_CASE_PARTY_NO", "CPR_A_PARTY_ROLE_CODE")
      REFERENCES "CASEMAN"."CASE_PARTY_ROLES" ("CASE_NUMBER", "CASE_PARTY_NO", "PARTY_ROLE_CODE") ENABLE;



  ALTER TABLE "CASEMAN"."CPR_TO_CPR_RELATIONSHIP" ADD CONSTRAINT "R_1715" FOREIGN KEY ("CPR_B_CASE_NUMBER", "CPR_B_CASE_PARTY_NO", "CPR_B_PARTY_ROLE_CODE")
      REFERENCES "CASEMAN"."CASE_PARTY_ROLES" ("CASE_NUMBER", "CASE_PARTY_NO", "PARTY_ROLE_CODE") ENABLE;



  ALTER TABLE "CASEMAN"."RETURN_CODES" ADD CONSTRAINT "R_1757" FOREIGN KEY ("ADMIN_COURT_CODE")
      REFERENCES "CASEMAN"."COURTS" ("CODE") ENABLE;



  ALTER TABLE "CASEMAN"."CODED_PARTIES" ADD CONSTRAINT "R_1760" FOREIGN KEY ("PARTY_ID")
      REFERENCES "CASEMAN"."PARTIES" ("PARTY_ID") ENABLE;



  ALTER TABLE "CASEMAN"."GIVEN_ADDRESSES" ADD CONSTRAINT "R_1763" FOREIGN KEY ("PARTY_ID")
      REFERENCES "CASEMAN"."PARTIES" ("PARTY_ID") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."GIVEN_ADDRESSES" ADD CONSTRAINT "R_1765" FOREIGN KEY ("CASE_NUMBER", "CASE_PARTY_NO", "PARTY_ROLE_CODE")
      REFERENCES "CASEMAN"."CASE_PARTY_ROLES" ("CASE_NUMBER", "CASE_PARTY_NO", "PARTY_ROLE_CODE") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."GIVEN_ADDRESSES" ADD CONSTRAINT "R_1766" FOREIGN KEY ("ADDRESS_TYPE_CODE")
      REFERENCES "CASEMAN"."ADDRESS_TYPES" ("ADDRESS_TYPE_CODE") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."PAYMENTS" ADD CONSTRAINT "R_1767" FOREIGN KEY ("RELATED_TRANSACTION_NUMBER", "RELATED_ADMIN_COURT_CODE")
      REFERENCES "CASEMAN"."PAYMENTS" ("TRANSACTION_NUMBER", "ADMIN_COURT_CODE") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."CONSOLIDATED_ORDERS" ADD CONSTRAINT "R_1769" FOREIGN KEY ("COURT_OF_TRANSFER")
      REFERENCES "CASEMAN"."COURTS" ("CODE") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."GIVEN_ADDRESSES" ADD CONSTRAINT "R_1770" FOREIGN KEY ("CO_NUMBER")
      REFERENCES "CASEMAN"."CONSOLIDATED_ORDERS" ("CO_NUMBER") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."CODED_PARTIES" ADD CONSTRAINT "R_1781" FOREIGN KEY ("ADMIN_COURT_CODE")
      REFERENCES "CASEMAN"."COURTS" ("CODE") ENABLE;



  ALTER TABLE "CASEMAN"."NATIONAL_CODED_PARTIES" ADD CONSTRAINT "R_1782" FOREIGN KEY ("CODE", "ADMIN_COURT_CODE")
      REFERENCES "CASEMAN"."CODED_PARTIES" ("CODE", "ADMIN_COURT_CODE") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."TAPES" ADD CONSTRAINT "R_1783" FOREIGN KEY ("CUST_CODE")
      REFERENCES "CASEMAN"."NATIONAL_CODED_PARTIES" ("CODE") ENABLE;



  ALTER TABLE "CASEMAN"."PAYEES" ADD CONSTRAINT "R_1786" FOREIGN KEY ("PARTY_ID")
      REFERENCES "CASEMAN"."PARTIES" ("PARTY_ID") ENABLE;



  ALTER TABLE "CASEMAN"."GIVEN_ADDRESSES" ADD CONSTRAINT "R_1787" FOREIGN KEY ("ALD_SEQ")
      REFERENCES "CASEMAN"."ALLOWED_DEBTS" ("DEBT_SEQ") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."ALLOWED_DEBTS" ADD CONSTRAINT "R_1788" FOREIGN KEY ("CP_CREDITOR_ID")
      REFERENCES "CASEMAN"."PARTIES" ("PARTY_ID") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."ALLOWED_DEBTS" ADD CONSTRAINT "R_1789" FOREIGN KEY ("CP_PAYEE_ID")
      REFERENCES "CASEMAN"."PARTIES" ("PARTY_ID") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."WARRANTS" ADD CONSTRAINT "R_1792" FOREIGN KEY ("CASE_NUMBER", "DEF1_CASE_PARTY_NO", "DEF1_PARTY_ROLE_CODE")
      REFERENCES "CASEMAN"."CASE_PARTY_ROLES" ("CASE_NUMBER", "CASE_PARTY_NO", "PARTY_ROLE_CODE") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."WARRANTS" ADD CONSTRAINT "R_1793" FOREIGN KEY ("CASE_NUMBER", "DEF2_CASE_PARTY_NO", "DEF2_PARTY_ROLE_CODE")
      REFERENCES "CASEMAN"."CASE_PARTY_ROLES" ("CASE_NUMBER", "CASE_PARTY_NO", "PARTY_ROLE_CODE") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."WARRANTS" ADD CONSTRAINT "R_1794" FOREIGN KEY ("CASE_NUMBER", "REP_CASE_PARTY_NO", "REP_PARTY_ROLE_CODE")
      REFERENCES "CASEMAN"."CASE_PARTY_ROLES" ("CASE_NUMBER", "CASE_PARTY_NO", "PARTY_ROLE_CODE") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."GIVEN_ADDRESSES" ADD CONSTRAINT "R_1795" FOREIGN KEY ("COURT_CODE")
      REFERENCES "CASEMAN"."COURTS" ("CODE") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."HEARINGS" ADD CONSTRAINT "R_1797" FOREIGN KEY ("ADDRESS_ID")
      REFERENCES "CASEMAN"."GIVEN_ADDRESSES" ("ADDRESS_ID") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."WP_OUTPUT" ADD CONSTRAINT "R_1808" FOREIGN KEY ("CO_EVENT_SEQ")
      REFERENCES "CASEMAN"."CO_EVENTS" ("CO_EVENT_SEQ") ON DELETE SET NULL DISABLE;



  ALTER TABLE "CASEMAN"."WP_OUTPUT" ADD CONSTRAINT "R_1809" FOREIGN KEY ("EVENT_SEQ")
      REFERENCES "CASEMAN"."CASE_EVENTS" ("EVENT_SEQ") ON DELETE SET NULL DISABLE;



  ALTER TABLE "CASEMAN"."WP_OUTPUT" ADD CONSTRAINT "R_1810" FOREIGN KEY ("AE_EVENT_SEQ")
      REFERENCES "CASEMAN"."AE_EVENTS" ("AE_EVENT_SEQ") ON DELETE SET NULL DISABLE;



  ALTER TABLE "CASEMAN"."INFAVOUR_PARTIES" ADD CONSTRAINT "R_1812" FOREIGN KEY ("JUDG_SEQ")
      REFERENCES "CASEMAN"."JUDGMENTS" ("JUDG_SEQ") ENABLE;



  ALTER TABLE "CASEMAN"."INFAVOUR_PARTIES" ADD CONSTRAINT "R_1813" FOREIGN KEY ("CASE_NUMBER", "CASE_PARTY_NO", "PARTY_ROLE_CODE")
      REFERENCES "CASEMAN"."CASE_PARTY_ROLES" ("CASE_NUMBER", "CASE_PARTY_NO", "PARTY_ROLE_CODE") ENABLE;



  ALTER TABLE "CASEMAN"."CASE_EVENT_INSTIGATORS" ADD CONSTRAINT "R_1814" FOREIGN KEY ("EVENT_SEQ")
      REFERENCES "CASEMAN"."CASE_EVENTS" ("EVENT_SEQ") ENABLE;



  ALTER TABLE "CASEMAN"."CASE_EVENT_INSTIGATORS" ADD CONSTRAINT "R_1815" FOREIGN KEY ("CASE_NUMBER", "CASE_PARTY_NO", "PARTY_ROLE_CODE")
      REFERENCES "CASEMAN"."CASE_PARTY_ROLES" ("CASE_NUMBER", "CASE_PARTY_NO", "PARTY_ROLE_CODE") ENABLE;



  ALTER TABLE "CASEMAN"."AE_APPLICATIONS" ADD CONSTRAINT "R_1817" FOREIGN KEY ("CASE_NUMBER", "PARTY_FOR_CASE_PARTY_NO", "PARTY_FOR_PARTY_ROLE_CODE")
      REFERENCES "CASEMAN"."CASE_PARTY_ROLES" ("CASE_NUMBER", "CASE_PARTY_NO", "PARTY_ROLE_CODE") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."WARRANT_RETURNS" ADD CONSTRAINT "R_1818" FOREIGN KEY ("EVENT_SEQ")
      REFERENCES "CASEMAN"."CASE_EVENTS" ("EVENT_SEQ") ON DELETE SET NULL DISABLE;



  ALTER TABLE "CASEMAN"."JUDGMENTS" ADD CONSTRAINT "R_1819" FOREIGN KEY ("WARRANT_ID")
      REFERENCES "CASEMAN"."WARRANTS" ("WARRANT_ID") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."AE_APPLICATIONS" ADD CONSTRAINT "R_1820" FOREIGN KEY ("DEBTORS_EMPLOYERS_PARTY_ID")
      REFERENCES "CASEMAN"."PARTIES" ("PARTY_ID") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."AE_EVENTS" ADD CONSTRAINT "R_1821" FOREIGN KEY ("CASE_EVENT_SEQ")
      REFERENCES "CASEMAN"."CASE_EVENTS" ("EVENT_SEQ") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."REPORT_QUEUE" ADD CONSTRAINT "R_1822" FOREIGN KEY ("PARENT_ID")
      REFERENCES "CASEMAN"."REPORT_QUEUE" ("ID") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."REPORT_QUEUE" ADD CONSTRAINT "R_1823" FOREIGN KEY ("DOCUMENT_ID")
      REFERENCES "CASEMAN"."DOCUMENT_STORE" ("ID") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."USER_COURT" ADD CONSTRAINT "R_1826" FOREIGN KEY ("COURT_CODE")
      REFERENCES "CASEMAN"."COURTS" ("CODE") ENABLE;



  ALTER TABLE "CASEMAN"."AMR_REPORTS" ADD CONSTRAINT "R_1827" FOREIGN KEY ("ADMIN_COURT_CODE")
      REFERENCES "CASEMAN"."COURTS" ("CODE") ENABLE;



  ALTER TABLE "CASEMAN"."DJPRINT_TEMP" ADD CONSTRAINT "R_1828" FOREIGN KEY ("ID")
      REFERENCES "CASEMAN"."REPRINTS" ("ID") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."CASE_EVENTS" ADD CONSTRAINT "R_1830" FOREIGN KEY ("CREATING_SECTION", "CREATING_COURT")
      REFERENCES "CASEMAN"."SECTIONS" ("SECTION_NAME", "ADMIN_COURT_CODE") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."WP_OUTPUT" ADD CONSTRAINT "R_1831" FOREIGN KEY ("USER_ID")
      REFERENCES "CASEMAN"."DCA_USER" ("USER_ID") DISABLE;



  ALTER TABLE "CASEMAN"."TASK_COUNTS" ADD CONSTRAINT "R_1832" FOREIGN KEY ("CREATING_SECTION", "CREATING_COURT")
      REFERENCES "CASEMAN"."SECTIONS" ("SECTION_NAME", "ADMIN_COURT_CODE") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."CO_EVENTS" ADD CONSTRAINT "R_1833" FOREIGN KEY ("CREATING_SECTION", "CREATING_COURT")
      REFERENCES "CASEMAN"."SECTIONS" ("SECTION_NAME", "ADMIN_COURT_CODE") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."REPORT_OUTPUT" ADD CONSTRAINT "R_1834" FOREIGN KEY ("CO_EVENT_SEQ")
      REFERENCES "CASEMAN"."CO_EVENTS" ("CO_EVENT_SEQ") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."REPORT_OUTPUT" ADD CONSTRAINT "R_1835" FOREIGN KEY ("AE_EVENT_SEQ")
      REFERENCES "CASEMAN"."AE_EVENTS" ("AE_EVENT_SEQ") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."REPORT_OUTPUT" ADD CONSTRAINT "R_1836" FOREIGN KEY ("EVENT_SEQ")
      REFERENCES "CASEMAN"."CASE_EVENTS" ("EVENT_SEQ") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."REPORT_OUTPUT" ADD CONSTRAINT "R_1837" FOREIGN KEY ("USER_ID")
      REFERENCES "CASEMAN"."DCA_USER" ("USER_ID") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."WARRANT_RETURNS" ADD CONSTRAINT "R_1838" FOREIGN KEY ("CO_EVENT_SEQ")
      REFERENCES "CASEMAN"."CO_EVENTS" ("CO_EVENT_SEQ") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."USER_COURT" ADD CONSTRAINT "R_1843" FOREIGN KEY ("SECTION_NAME", "COURT_CODE")
      REFERENCES "CASEMAN"."SECTIONS" ("SECTION_NAME", "ADMIN_COURT_CODE") ENABLE;



  ALTER TABLE "CASEMAN"."JUDGES" ADD CONSTRAINT "R_1844" FOREIGN KEY ("COURT_CODE")
      REFERENCES "CASEMAN"."COURTS" ("CODE") ENABLE;



  ALTER TABLE "CASEMAN"."REPORT_REPRINTS" ADD CONSTRAINT "R_1845" FOREIGN KEY ("FW_REPORT_ID")
      REFERENCES "CASEMAN"."REPORT_QUEUE" ("ID") ON DELETE CASCADE DISABLE;



  ALTER TABLE "CASEMAN"."PAYMENTS" ADD CONSTRAINT "R_1846" FOREIGN KEY ("ENFORCEMENT_COURT_CODE")
      REFERENCES "CASEMAN"."COURTS" ("CODE") ENABLE;



  ALTER TABLE "CASEMAN"."PL_FILELEVEL_PREVAL_STATUS" ADD CONSTRAINT "R_1849" FOREIGN KEY ("FILE_TYPE")
      REFERENCES "CASEMAN"."CCBC_MEDIA_FILE_TYPE" ("FILE_TYPE_CODE") ENABLE;



  ALTER TABLE "CASEMAN"."NON_WORKING_DAYS_EXCEPTIONS" ADD CONSTRAINT "R_1852" FOREIGN KEY ("NON_WD_SEQ")
      REFERENCES "CASEMAN"."NON_WORKING_DAYS" ("NON_WD_SEQ") ENABLE;



  ALTER TABLE "CASEMAN"."NON_WORKING_DAYS_EXCEPTIONS" ADD CONSTRAINT "R_1853" FOREIGN KEY ("COURT_CODE")
      REFERENCES "CASEMAN"."COURTS" ("CODE") ENABLE;



  ALTER TABLE "CASEMAN"."FTP_QUEUE" ADD CONSTRAINT "R_1856" FOREIGN KEY ("DOCUMENT_ID")
      REFERENCES "CASEMAN"."DOCUMENT_STORE" ("ID") ON DELETE CASCADE ENABLE;



  ALTER TABLE "CASEMAN"."REPORT_MAP" ADD CONSTRAINT "R_1857" FOREIGN KEY ("REPORT_QUEUE_ID")
      REFERENCES "CASEMAN"."REPORT_QUEUE" ("ID") ENABLE;



  ALTER TABLE "CASEMAN"."JUDGMENTS" ADD CONSTRAINT "R_1858" FOREIGN KEY ("AGAINST_PARTY_ADDR_ID_JUDG_REG")
      REFERENCES "CASEMAN"."GIVEN_ADDRESSES" ("ADDRESS_ID") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."WP_OUTPUT" ADD CONSTRAINT "R_1859" FOREIGN KEY ("WARRANT_RETURNS_ID")
      REFERENCES "CASEMAN"."WARRANT_RETURNS" ("WARRANT_RETURNS_ID") DISABLE;



  ALTER TABLE "CASEMAN"."USER_ROLE" ADD CONSTRAINT "R_2" FOREIGN KEY ("USER_ID", "COURT_CODE")
      REFERENCES "CASEMAN"."USER_COURT" ("USER_ID", "COURT_CODE") ENABLE;



  ALTER TABLE "CASEMAN"."CMCS_DEFENDANTS" ADD CONSTRAINT "R_3" FOREIGN KEY ("TRANS_SEQ")
      REFERENCES "CASEMAN"."CMCS_CASES" ("TRANS_SEQ") ENABLE;



  ALTER TABLE "CASEMAN"."LOAD_CASES" ADD CONSTRAINT "R_38" FOREIGN KEY ("REJECT_CODE")
      REFERENCES "CASEMAN"."REJECT_REASONS" ("REJECT_CODE") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."REJECT_CASES" ADD CONSTRAINT "R_39" FOREIGN KEY ("REJECT_CODE")
      REFERENCES "CASEMAN"."REJECT_REASONS" ("REJECT_CODE") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."PL_RECORDLEVEL_PREVAL_STATUS" ADD CONSTRAINT "R_4" FOREIGN KEY ("FILE_NAME")
      REFERENCES "CASEMAN"."PL_FILELEVEL_PREVAL_STATUS" ("FILE_NAME") ENABLE;



  ALTER TABLE "CASEMAN"."LOAD_JUDGMENTS" ADD CONSTRAINT "R_40" FOREIGN KEY ("REJECT_CODE")
      REFERENCES "CASEMAN"."REJECT_REASONS" ("REJECT_CODE") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."REJECT_JUDGMENTS" ADD CONSTRAINT "R_41" FOREIGN KEY ("REJECT_CODE")
      REFERENCES "CASEMAN"."REJECT_REASONS" ("REJECT_CODE") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."LOAD_WARRANTS" ADD CONSTRAINT "R_42" FOREIGN KEY ("REJECT_CODE")
      REFERENCES "CASEMAN"."REJECT_REASONS" ("REJECT_CODE") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."REJECT_WARRANTS" ADD CONSTRAINT "R_43" FOREIGN KEY ("REJECT_CODE")
      REFERENCES "CASEMAN"."REJECT_REASONS" ("REJECT_CODE") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."LOAD_PAID_WO_DETAILS" ADD CONSTRAINT "R_44" FOREIGN KEY ("REJECT_CODE")
      REFERENCES "CASEMAN"."REJECT_REASONS" ("REJECT_CODE") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."REJECT_PAID_WO_DETAILS" ADD CONSTRAINT "R_45" FOREIGN KEY ("REJECT_CODE")
      REFERENCES "CASEMAN"."REJECT_REASONS" ("REJECT_CODE") ON DELETE SET NULL ENABLE;



  ALTER TABLE "CASEMAN"."CMCS_DEFENDANT_ADDRESSES" ADD CONSTRAINT "R_5" FOREIGN KEY ("TRANS_SEQ", "DEFT_CASE_NUMBER", "DEFT_ID")
      REFERENCES "CASEMAN"."CMCS_DEFENDANTS" ("TRANS_SEQ", "CASE_NUMBER", "ID") ENABLE;



  ALTER TABLE "CASEMAN"."MENU_ITEM" ADD CONSTRAINT "R_835" FOREIGN KEY ("PARENT_MENU_ITEM_ID")
      REFERENCES "CASEMAN"."MENU_ITEM" ("MENU_ITEM_ID") ON DELETE SET NULL DISABLE;



  ALTER TABLE "CASEMAN"."COURTS" ADD CONSTRAINT "R_99" FOREIGN KEY ("DFJ_AREA_ID")
      REFERENCES "CASEMAN"."DFJ_AREAS" ("DFJ_AREA_ID") ENABLE;



  ALTER TABLE "CASEMAN"."SUB_DETAIL_VARIABLES" ADD CONSTRAINT "SDV_DV_FK" FOREIGN KEY ("VARIABLE_CODE")
      REFERENCES "CASEMAN"."DOCUMENT_VARIABLES" ("CODE") ENABLE;



  ALTER TABLE "CASEMAN"."SUB_DETAIL_VARIABLES" ADD CONSTRAINT "SDV_ODT_FK" FOREIGN KEY ("OD_SEQ")
      REFERENCES "CASEMAN"."OUTPUT_DETAILS" ("OD_SEQ") ENABLE;



  ALTER TABLE "CASEMAN"."EVENT_TASK_XREF" ADD CONSTRAINT "TSK_EVE_FK" FOREIGN KEY ("TASK_NUMBER")
      REFERENCES "CASEMAN"."TASKS" ("TASK_NUMBER") ENABLE;



  ALTER TABLE "CASEMAN"."TASK_COUNTS" ADD CONSTRAINT "TSK_TCOUNT_FK" FOREIGN KEY ("TASK_NUMBER")
      REFERENCES "CASEMAN"."TASKS" ("TASK_NUMBER") ENABLE;



  ALTER TABLE "CASEMAN"."TASKS" ADD CONSTRAINT "TSK_TYP_FK" FOREIGN KEY ("TASK_TYPE")
      REFERENCES "CASEMAN"."TASK_TYPES" ("TASK_TYPE") ENABLE;



  ALTER TABLE "CASEMAN"."USERS_PRINTERS" ADD CONSTRAINT "USER_PRINT_P_FK" FOREIGN KEY ("PRINTER_ID")
      REFERENCES "CASEMAN"."PRINTERS" ("PRINTER_ID") ENABLE;



  ALTER TABLE "CASEMAN"."VARIATIONS" ADD CONSTRAINT "VARY_PAYABLE_ON" FOREIGN KEY ("JUDG_SEQ")
      REFERENCES "CASEMAN"."JUDGMENTS" ("JUDG_SEQ") ENABLE;



  ALTER TABLE "CASEMAN"."WFT_EXCLUSIONS" ADD CONSTRAINT "WFE_WFT_FK" FOREIGN KEY ("WFE_WFT_CASE_NUMBER", "WFE_WFT_ID")
      REFERENCES "CASEMAN"."WINDOW_FOR_TRIAL" ("WFT_CASE_NUMBER", "WFT_ID") ENABLE;



  ALTER TABLE "CASEMAN"."WINDOW_FOR_TRIAL" ADD CONSTRAINT "WFT_CASES_FK" FOREIGN KEY ("WFT_CASE_NUMBER")
      REFERENCES "CASEMAN"."CASES" ("CASE_NUMBER") ENABLE;


