
  ALTER TABLE "CASEMAN"."ENFORCEMENT_LETTERS" ADD CONSTRAINT "LETTER_UK" UNIQUE ("LETTER") ENABLE;



  ALTER TABLE "CASEMAN"."OUTPUT_DETAILS" ADD CONSTRAINT "OUTPUT_DETAILS_UK" UNIQUE ("ORDER_TYPE_ID", "LAYOUT_GROUP", "CODE") ENABLE;



  ALTER TABLE "CASEMAN"."WARRANTS" ADD CONSTRAINT "WARRANTS_UK" UNIQUE ("WARRANT_NUMBER", "ISSUED_BY", "CURRENTLY_OWNED_BY", "LOCAL_WARRANT_NUMBER", "CASE_NUMBER") ENABLE;


