
  ALTER TABLE "CASEMAN"."AE_APPLICATIONS" ADD CONSTRAINT "AE_APPLICATIONS_PK" PRIMARY KEY ("AE_NUMBER") using index CASEMAN.AE_APPLICATIONS_PK ENABLE;



  ALTER TABLE "CASEMAN"."AE_EVENTS" ADD CONSTRAINT "AE_EVENTS_PK" PRIMARY KEY ("AE_EVENT_SEQ") using index CASEMAN.AE_EVENTS_PK ENABLE;



  ALTER TABLE "CASEMAN"."AE_PER_ITEMS" ADD CONSTRAINT "AE_PER_ITEMS_PK" PRIMARY KEY ("AE_PER_SEQ") using index CASEMAN.AE_PER_ITEMS_PK ENABLE;



  ALTER TABLE "CASEMAN"."AGE_CATEGORY" ADD CONSTRAINT "AGE_PK" PRIMARY KEY ("AGE_CATEGORY") using index CASEMAN.AGE_PK ENABLE;



  ALTER TABLE "CASEMAN"."ALLOWED_DEBTS" ADD CONSTRAINT "ALLOW_DEBT_PK" PRIMARY KEY ("DEBT_SEQ") using index CASEMAN.ALLOW_DEBT_PK ENABLE;



  ALTER TABLE "CASEMAN"."AO_CAEO" ADD CONSTRAINT "AO_CAEO_PK" PRIMARY KEY ("AO_CAEO_NUMBER", "ADMIN_COURT_CODE") using index CASEMAN.AO_CAEO_PK ENABLE;



  ALTER TABLE "CASEMAN"."ACTION_TASK_XREF" ADD CONSTRAINT "ATX_PK" PRIMARY KEY ("ACTION_ID", "TASK_NUMBER") using index CASEMAN.ATX_PK ENABLE;



  ALTER TABLE "CASEMAN"."CO_EVENT_VALIDATIONS" ADD CONSTRAINT "C0_EVENT_VALIDATIONS_PK" PRIMARY KEY ("STD_EVENT_ID") using index CASEMAN.C0_EVENT_VALIDATIONS_PK ENABLE;



  ALTER TABLE "CASEMAN"."CASES" ADD CONSTRAINT "CASE_PK" PRIMARY KEY ("CASE_NUMBER") using index CASEMAN.CASE_PK ENABLE;



  ALTER TABLE "CASEMAN"."CO_CASE_EVENTS" ADD CONSTRAINT "CCE_PK" PRIMARY KEY ("ALD_DEBT_SEQ") using index CASEMAN.CCE_PK ENABLE;



  ALTER TABLE "CASEMAN"."CHANGED_EVENTS" ADD CONSTRAINT "CHEVT_PK" PRIMARY KEY ("RELEASE_DATE", "STD_EVENT_ID") using index CASEMAN.CHEVT_PK ENABLE;



  ALTER TABLE "CASEMAN"."COPS_MERGE_FIELDS" ADD CONSTRAINT "COP_PK" PRIMARY KEY ("CMF_SEQ_NO") using index CASEMAN.COP_PK ENABLE;



  ALTER TABLE "CASEMAN"."CO_EVENTS" ADD CONSTRAINT "CO_EVENTS_PK" PRIMARY KEY ("CO_EVENT_SEQ") using index CASEMAN.CO_EVENTS_PK ENABLE;



  ALTER TABLE "CASEMAN"."CO_PER_ITEMS" ADD CONSTRAINT "CO_PER_ITEMS_PK" PRIMARY KEY ("CO_PER_SEQ") using index CASEMAN.CO_PER_ITEMS_PK ENABLE;



  ALTER TABLE "CASEMAN"."CONSOLIDATED_ORDERS" ADD CONSTRAINT "CO_PK" PRIMARY KEY ("CO_NUMBER") using index CASEMAN.CO_PK ENABLE;



  ALTER TABLE "CASEMAN"."CPT_CLAIMS" ADD CONSTRAINT "CPT_CLAIMS_PK" PRIMARY KEY ("CLAIM_NUMBER") using index CASEMAN.CPT_CLAIMS_PK ENABLE;



  ALTER TABLE "CASEMAN"."COURTS" ADD CONSTRAINT "CRT_PK" PRIMARY KEY ("CODE") using index CASEMAN.CRT_PK ENABLE;



  ALTER TABLE "CASEMAN"."DEBT_DIVIDENDS" ADD CONSTRAINT "DD_PK" PRIMARY KEY ("DD_SEQ") using index CASEMAN.DD_PK ENABLE;



  ALTER TABLE "CASEMAN"."CPT_DEFENDANTS" ADD CONSTRAINT "DEFT_PK" PRIMARY KEY ("CLAIM_NUMBER", "ID") using index CASEMAN.DEFT_PK ENABLE;



  ALTER TABLE "CASEMAN"."DIVIDENDS" ADD CONSTRAINT "DIVIDEND_PK" PRIMARY KEY ("DIV_CO_NUMBER", "DIV_NUMBER") using index CASEMAN.DIVIDEND_PK ENABLE;



  ALTER TABLE "CASEMAN"."OBLIGATION_EVENTS" ADD CONSTRAINT "DMS_EVENTS_PK_I" PRIMARY KEY ("EVENT_ID") using index CASEMAN.DMS_EVENTS_PK_I ENABLE;



  ALTER TABLE "CASEMAN"."OBLIGATIONS" ADD CONSTRAINT "DMS_OBLN_PK_I" PRIMARY KEY ("OBLIGATION_SEQ", "CASE_NUMBER") using index CASEMAN.DMS_OBLN_PK_I ENABLE;



  ALTER TABLE "CASEMAN"."OBLIGATION_RULES" ADD CONSTRAINT "DMS_RULES_PK_I" PRIMARY KEY ("OBLIGATION_TYPE", "EVENT_ID") using index CASEMAN.DMS_RULES_PK_I ENABLE;



  ALTER TABLE "CASEMAN"."OBLIGATION_TYPES" ADD CONSTRAINT "DMS_TYPES_PK_I" PRIMARY KEY ("OBLIGATION_TYPE") using index CASEMAN.DMS_TYPES_PK_I ENABLE;



  ALTER TABLE "CASEMAN"."DOCUMENT_VARIABLES" ADD CONSTRAINT "DOC_VAR_PK" PRIMARY KEY ("CODE") using index CASEMAN.DOC_VAR_PK ENABLE;



  ALTER TABLE "CASEMAN"."CASE_EVENTS" ADD CONSTRAINT "EVENT_PK" PRIMARY KEY ("EVENT_SEQ") using index CASEMAN.EVENT_PK ENABLE;



  ALTER TABLE "CASEMAN"."EVENT_OUTPUTS" ADD CONSTRAINT "EVT_OUT_PK" PRIMARY KEY ("STD_EVENT_ID", "ORDER_TYPE_ID") using index CASEMAN.EVT_OUT_PK ENABLE;



  ALTER TABLE "CASEMAN"."EVENT_TASK_XREF" ADD CONSTRAINT "EVT_TSK_PK" PRIMARY KEY ("EVENT_ID", "TASK_NUMBER", "CASE_TYPE", "EVENT_TYPE_FLAG") using index CASEMAN.EVT_TSK_PK ENABLE;



  ALTER TABLE "CASEMAN"."HEARINGS" ADD CONSTRAINT "HRG_PK" PRIMARY KEY ("HRG_SEQ") using index CASEMAN.HRG_PK ENABLE;



  ALTER TABLE "CASEMAN"."ITEM_DETAILS" ADD CONSTRAINT "ITEM_DETS_PK" PRIMARY KEY ("CODE") using index CASEMAN.ITEM_DETS_PK ENABLE;



  ALTER TABLE "CASEMAN"."SYSTEM_DATA" ADD CONSTRAINT "ITEM_PK" PRIMARY KEY ("ITEM", "ADMIN_COURT_CODE") using index CASEMAN.ITEM_PK ENABLE;



  ALTER TABLE "CASEMAN"."JUDGMENTS" ADD CONSTRAINT "JUDG_PK" PRIMARY KEY ("JUDG_SEQ") using index CASEMAN.JUDG_PK ENABLE;



  ALTER TABLE "CASEMAN"."MCOL_MIG_PARTY_DATA" ADD CONSTRAINT "MCOL_MIG_PARTY_DATA_PK" PRIMARY KEY ("CASE_NUMBER", "CASE_PARTY_NO", "PARTY_ROLE_CODE") using index CASEMAN.MCOL_MIG_PARTY_DATA_PK ENABLE;



  ALTER TABLE "CASEMAN"."MCOL_MIG_WARRANT_DATA" ADD CONSTRAINT "MCOL_MIG_WARRANT_DATA_PK" PRIMARY KEY ("CASE_NUMBER", "WARRANT_NUMBER") using index CASEMAN.MCOL_MIG_WARRANT_DATA_PK ENABLE;



  ALTER TABLE "CASEMAN"."MENU_ITEM" ADD CONSTRAINT "MENU_ITEM_X1" PRIMARY KEY ("MENU_ITEM_ID") using index CASEMAN.MENU_ITEM_X1 ENABLE;



  ALTER TABLE "CASEMAN"."CCB_MESSAGES" ADD CONSTRAINT "MESSAGE_PK" PRIMARY KEY ("MSG_ID") using index CASEMAN.MESSAGE_PK ENABLE;



  ALTER TABLE "CASEMAN"."ORDER_TYPES" ADD CONSTRAINT "ORDER_TYPE_PK" PRIMARY KEY ("ORDER_ID") using index CASEMAN.ORDER_TYPE_PK ENABLE;



  ALTER TABLE "CASEMAN"."OSW" ADD CONSTRAINT "OSW_PK" PRIMARY KEY ("ID", "ADMIN_COURT_CODE") using index CASEMAN.OSW_PK ENABLE;



  ALTER TABLE "CASEMAN"."OUTPUT_DETAILS" ADD CONSTRAINT "OUTPUT_DETAILS_PK" PRIMARY KEY ("OD_SEQ") using index CASEMAN.OUTPUT_DETAILS_PK ENABLE;



  ALTER TABLE "CASEMAN"."PAYMENTS" ADD CONSTRAINT "PAY_PK" PRIMARY KEY ("TRANSACTION_NUMBER", "ADMIN_COURT_CODE") using index CASEMAN.PAY_PK ENABLE;



  ALTER TABLE "CASEMAN"."PER_DETAILS" ADD CONSTRAINT "PER_DETAILS_PK" PRIMARY KEY ("DETAIL_CODE") using index CASEMAN.PER_DETAILS_PK ENABLE;



  ALTER TABLE "CASEMAN"."DELETE_CANDIDATES" ADD CONSTRAINT "PK_CANDIDATES" PRIMARY KEY ("IDENTIFIER", "TYPE") using index CASEMAN.PK_CANDIDATES ENABLE;



  ALTER TABLE "CASEMAN"."ECHR_DETAILS" ADD CONSTRAINT "PK_ECHR_DETAILS" PRIMARY KEY ("EVENT_SEQ") using index CASEMAN.PK_ECHR_DETAILS ENABLE;



  ALTER TABLE "CASEMAN"."MCOL_MIG_JUDGMENT_DATA" ADD CONSTRAINT "PK_MCOL_MIG_JUDGMENT_DATA" PRIMARY KEY ("CASE_NUMBER", "AGAINST_CASE_PARTY_NO") using index CASEMAN.PK_MCOL_MIG_JUDGMENT_DATA ENABLE;



  ALTER TABLE "CASEMAN"."NON_WORKING_DAYS" ADD CONSTRAINT "PK_NWD" PRIMARY KEY ("NON_WD_SEQ") using index CASEMAN.PK_NWD ENABLE;



  ALTER TABLE "CASEMAN"."PAYABLE_ORDER_ITEMS" ADD CONSTRAINT "POITEM" PRIMARY KEY ("TRANSACTION_NUMBER", "PO_NUMBER", "ADMIN_COURT_CODE") using index CASEMAN.POITEM ENABLE;



  ALTER TABLE "CASEMAN"."PAYABLE_ORDERS" ADD CONSTRAINT "PONUM_PK" PRIMARY KEY ("PO_NUMBER", "ADMIN_COURT_CODE") using index CASEMAN.PONUM_PK ENABLE;



  ALTER TABLE "CASEMAN"."PRE_REQ_EVENTS" ADD CONSTRAINT "PRE_PK" PRIMARY KEY ("STD_EVENT_ID", "PRE_REQ_EVENT_ID1") using index CASEMAN.PRE_PK ENABLE;



  ALTER TABLE "CASEMAN"."PRINTERS" ADD CONSTRAINT "PRINTERS_PK" PRIMARY KEY ("PRINTER_ID") using index CASEMAN.PRINTERS_PK ENABLE;



  ALTER TABLE "CASEMAN"."CPT_PRINT_CLAIMS" ADD CONSTRAINT "PRINT_CLAIMS_PK" PRIMARY KEY ("ISSUE_DATE", "REC_NO") using index CASEMAN.PRINT_CLAIMS_PK ENABLE;



  ALTER TABLE "CASEMAN"."PRINTER_TYPES" ADD CONSTRAINT "PRINT_TYPES_PK" PRIMARY KEY ("MODEL") using index CASEMAN.PRINT_TYPES_PK ENABLE;



  ALTER TABLE "CASEMAN"."REPORT_PARAMETERS" ADD CONSTRAINT "PRM_PK" PRIMARY KEY ("REPORT_NAME", "PARAMETER_NAME") using index CASEMAN.PRM_PK ENABLE;



  ALTER TABLE "CASEMAN"."CODED_PARTIES" ADD CONSTRAINT "PTY_PK" PRIMARY KEY ("CODE", "ADMIN_COURT_CODE") using index CASEMAN.PTY_PK ENABLE;



  ALTER TABLE "CASEMAN"."REPORT_MAP" ADD CONSTRAINT "REPORT_MAP_PK" PRIMARY KEY ("LEGACY_PATH", "FILE_NAME") using index CASEMAN.REPORT_MAP_PK ENABLE;



  ALTER TABLE "CASEMAN"."REPORT_QUEUE" ADD CONSTRAINT "REPORT_QUEUE_PK" PRIMARY KEY ("ID") using index CASEMAN.XIE1REPORT_QUEUE ENABLE;



  ALTER TABLE "CASEMAN"."REPRINTS" ADD CONSTRAINT "REPRINTS_PK" PRIMARY KEY ("ID") using index CASEMAN.REPRINTS_PK ENABLE;



  ALTER TABLE "CASEMAN"."REPORTS" ADD CONSTRAINT "REP_PK" PRIMARY KEY ("REPORT_NAME") using index CASEMAN.REP_PK ENABLE;



  ALTER TABLE "CASEMAN"."REPORT_REPRINTS_XREF" ADD CONSTRAINT "REP_REP_XREF_PK" PRIMARY KEY ("REPRINTS_ID", "REPORT_REPRINTS_ID", "USERNAME") using index CASEMAN.REP_REP_XREF_PK ENABLE;



  ALTER TABLE "CASEMAN"."RETURN_CODES" ADD CONSTRAINT "RETURN_CODES_PK" PRIMARY KEY ("RETURN_CODE", "ADMIN_COURT_CODE") using index CASEMAN.RETURN_CODES_PK ENABLE;



  ALTER TABLE "CASEMAN"."SUB_DETAIL_VARIABLES" ADD CONSTRAINT "SDV_PK" PRIMARY KEY ("SDV_SEQ") using index CASEMAN.SDV_PK ENABLE;



  ALTER TABLE "CASEMAN"."SECTIONS" ADD CONSTRAINT "SEC_PK" PRIMARY KEY ("SECTION_NAME", "ADMIN_COURT_CODE") using index CASEMAN.SEC_PK ENABLE;



  ALTER TABLE "CASEMAN"."STANDARD_EVENTS" ADD CONSTRAINT "STD_PK" PRIMARY KEY ("EVENT_ID") using index CASEMAN.STD_PK ENABLE;



  ALTER TABLE "CASEMAN"."CO_STATE" ADD PRIMARY KEY ("CO_NUMBER") using index CASEMAN.SYS_C00416036 ENABLE;



  ALTER TABLE "CASEMAN"."CASE_STATE" ADD PRIMARY KEY ("CASE_NUMBER") using index CASEMAN.SYS_C00416038 ENABLE;



  ALTER TABLE "CASEMAN"."CDR_MCOL_EVENT_MAPPING" ADD PRIMARY KEY ("STD_EVENT_ID") using index CASEMAN.SYS_C00417937 ENABLE;



  ALTER TABLE "CASEMAN"."CDR_MCOL_STATUS_MAPPING" ADD PRIMARY KEY ("CLAIM_STATUS") using index CASEMAN.SYS_C00417939 ENABLE;



  ALTER TABLE "CASEMAN"."CPT_LIBERATA_TOTAL_FEES" ADD PRIMARY KEY ("ISSUE_DATE") using index CASEMAN.SYS_C00417959 ENABLE;



  ALTER TABLE "CASEMAN"."MCOL_MIG_CLAIM_DATA" ADD PRIMARY KEY ("CASE_NUMBER") using index CASEMAN.SYS_C00417998 ENABLE;



  ALTER TABLE "CASEMAN"."TMP_DPA_PARTIES_CACHE" ADD PRIMARY KEY ("PARTY_ID") using index CASEMAN.SYS_C00418064 ENABLE;



  ALTER TABLE "CASEMAN"."TMP_MCOL_MIG_CRED_CLAIMS" ADD PRIMARY KEY ("CASE_NUMBER") using index CASEMAN.SYS_C00418066 ENABLE;



  ALTER TABLE "CASEMAN"."TMP_MCOL_MIG_EVENT_MAPPING" ADD PRIMARY KEY ("STD_EVENT_ID") using index CASEMAN.SYS_C00418068 ENABLE;



  ALTER TABLE "CASEMAN"."TMP_MCOL_MIG_INFO" ADD PRIMARY KEY ("CRED_CODE") using index CASEMAN.SYS_C00418073 ENABLE;



  ALTER TABLE "CASEMAN"."TMP_MCOL_MIG_STATUS_MAPPING" ADD PRIMARY KEY ("CLAIM_STATUS") using index CASEMAN.SYS_C00418075 ENABLE;



  ALTER TABLE "CASEMAN"."DELETE_EXCEPTION_REASONS" ADD PRIMARY KEY ("EXCEPTION_REASON") using index CASEMAN.SYS_C00418144 ENABLE;



  ALTER TABLE "CASEMAN"."EVENT_DELETION_RULES" ADD PRIMARY KEY ("STD_EVENT_ID", "EVENT_TYPE") using index CASEMAN.SYS_C00418160 ENABLE;



  ALTER TABLE "CASEMAN"."WFT_EXPORTS" ADD PRIMARY KEY ("FILENAME") using index CASEMAN.SYS_C00432371 ENABLE;



  ALTER TABLE "CASEMAN"."TASK_ALLOCATIONS" ADD CONSTRAINT "TAL_PK" PRIMARY KEY ("TASK_NUMBER", "SECTION_NAME", "START_DATE", "ADMIN_COURT_CODE") using index CASEMAN.TAL_PK ENABLE;



  ALTER TABLE "CASEMAN"."TMP_MCOL_MIG_FAILURES" ADD CONSTRAINT "TMP_MCOL_MIG_FAILURES_PK" PRIMARY KEY ("CASE_NUMBER", "FAILURE_REASON") using index CASEMAN.TMP_MCOL_MIG_FAILURES_PK ENABLE;



  ALTER TABLE "CASEMAN"."TMP_RTL_CHARACTER_MAP" ADD CONSTRAINT "TMP_RTL_CHARACTER_MAP_PK" PRIMARY KEY ("ASCII_CODE") using index CASEMAN.TMP_RTL_CHARACTER_MAP_PK ENABLE;



  ALTER TABLE "CASEMAN"."TRAN_CODED_PARTIES" ADD CONSTRAINT "TRAN_CP_I" PRIMARY KEY ("CODE") using index CASEMAN.TRAN_CP_I ENABLE;



  ALTER TABLE "CASEMAN"."TRAN_SYSTEM_DATA" ADD CONSTRAINT "TRAN_ITEM_I" PRIMARY KEY ("ITEM") using index CASEMAN.TRAN_ITEM_I ENABLE;



  ALTER TABLE "CASEMAN"."TRAN_PER_DETAILS" ADD CONSTRAINT "TRAN_PER_DETS" PRIMARY KEY ("DETAIL_CODE") using index CASEMAN.TRAN_PER_DETS ENABLE;



  ALTER TABLE "CASEMAN"."TASKS" ADD CONSTRAINT "TSK_PK" PRIMARY KEY ("TASK_NUMBER") using index CASEMAN.TSK_PK ENABLE;



  ALTER TABLE "CASEMAN"."TASK_TYPES" ADD CONSTRAINT "TSK_TYP_PK" PRIMARY KEY ("TASK_TYPE") using index CASEMAN.TSK_TYP_PK ENABLE;



  ALTER TABLE "CASEMAN"."UNIX_OUTPUT" ADD CONSTRAINT "UNIX_OP_PK" PRIMARY KEY ("USERNAME", "LINE_NO") using index CASEMAN.UNIX_OP_PK ENABLE;



  ALTER TABLE "CASEMAN"."USERS" ADD CONSTRAINT "USERS_PK" PRIMARY KEY ("USERNAME") using index CASEMAN.USERS_PK ENABLE;



  ALTER TABLE "CASEMAN"."USER_INFO_CASE_EVENTS" ADD CONSTRAINT "USER_INFO_CE_PK" PRIMARY KEY ("USER_ID") using index CASEMAN.USER_INFO_CE_PK ENABLE;



  ALTER TABLE "CASEMAN"."USERS_PRINTERS" ADD CONSTRAINT "USER_PRINT_PK" PRIMARY KEY ("USERNAME", "PRINTER_ID") using index CASEMAN.USER_PRINT_PK ENABLE;



  ALTER TABLE "CASEMAN"."VARIATIONS" ADD CONSTRAINT "VARY_PK" PRIMARY KEY ("VARY_SEQ") using index CASEMAN.VARY_PK ENABLE;



  ALTER TABLE "CASEMAN"."WARRANTS" ADD CONSTRAINT "WARRANTS_PK" PRIMARY KEY ("WARRANT_ID") using index CASEMAN.WARRANTS_PK ENABLE;



  ALTER TABLE "CASEMAN"."WFT_EXCLUSIONS" ADD CONSTRAINT "WFE_PK_1" PRIMARY KEY ("WFE_WFT_CASE_NUMBER", "WFE_WFT_ID", "WFE_EXCLUSION_DATE") using index CASEMAN.WFE_PK_1 ENABLE;



  ALTER TABLE "CASEMAN"."WINDOW_FOR_TRIAL" ADD CONSTRAINT "WFT_PK_1" PRIMARY KEY ("WFT_CASE_NUMBER", "WFT_ID") using index CASEMAN.WFT_PK_1 ENABLE;



  ALTER TABLE "CASEMAN"."MENU_ITEM_GROUP" ADD CONSTRAINT "WORKGROUP_ITEM_X1" PRIMARY KEY ("MENU_ITEM_ID", "CONTEXT", "USERS_ROLE") using index CASEMAN.WORKGROUP_ITEM_X1 ENABLE;



  ALTER TABLE "CASEMAN"."ADDRESS_TYPES" ADD CONSTRAINT "XPKADDRESS_TYPES" PRIMARY KEY ("ADDRESS_TYPE_CODE") using index CASEMAN.XPKADDRESS_TYPES ENABLE;



  ALTER TABLE "CASEMAN"."ASYNC_COMMAND" ADD CONSTRAINT "XPKASYNC_COMMAND" PRIMARY KEY ("ID") using index CASEMAN.XPKASYNC_COMMAND ENABLE;



  ALTER TABLE "CASEMAN"."CASE_EVENT_INSTIGATORS" ADD CONSTRAINT "XPKCASE_EVENT_INSTIGATORS" PRIMARY KEY ("EVENT_SEQ", "CASE_NUMBER", "CASE_PARTY_NO", "PARTY_ROLE_CODE") using index CASEMAN.XPKCASE_EVENT_INSTIGATORS ENABLE;



  ALTER TABLE "CASEMAN"."CASE_PARTY_ROLES" ADD CONSTRAINT "XPKCASE_PARTY_ROLES" PRIMARY KEY ("CASE_NUMBER", "CASE_PARTY_NO", "PARTY_ROLE_CODE") using index CASEMAN.XPKCASE_PARTY_ROLES ENABLE;



  ALTER TABLE "CASEMAN"."CCBC_MEDIA_FILE_TYPE" ADD CONSTRAINT "XPKCCBC_MEDIA_FILE_TYPE" PRIMARY KEY ("FILE_TYPE_CODE") using index CASEMAN.XPKCCBC_MEDIA_FILE_TYPE ENABLE;



  ALTER TABLE "CASEMAN"."CMCS_CAPS_ORDERS" ADD CONSTRAINT "XPKCMCS_CAPS_ORDERS" PRIMARY KEY ("TRANS_SEQ") using index CASEMAN.XPKCMCS_CAPS_ORDERS ENABLE;



  ALTER TABLE "CASEMAN"."CMCS_CASES" ADD CONSTRAINT "XPKCMCS_CASES" PRIMARY KEY ("TRANS_SEQ") using index CASEMAN.XPKCMCS_CASES ENABLE;



  ALTER TABLE "CASEMAN"."CMCS_DEFENDANTS" ADD CONSTRAINT "XPKCMCS_DEFENDANTS" PRIMARY KEY ("TRANS_SEQ", "CASE_NUMBER", "ID") using index CASEMAN.XPKCMCS_DEFENDANTS ENABLE;



  ALTER TABLE "CASEMAN"."CMCS_DEFENDANT_ADDRESSES" ADD CONSTRAINT "XPKCMCS_DEFENDANT_ADDRESSES" PRIMARY KEY ("TRANS_SEQ", "DEFT_CASE_NUMBER", "DEFT_ID", "ADDR_SEQ") using index CASEMAN.XPKCMCS_DEFENDANT_ADDRESSES ENABLE;



  ALTER TABLE "CASEMAN"."CMCS_TRANSFER_CONTROL" ADD CONSTRAINT "XPKCMCS_TRANSFER_CONTROL" PRIMARY KEY ("TRANS_SEQ") using index CASEMAN.XPKCMCS_TRANSFER_CONTROL ENABLE;



  ALTER TABLE "CASEMAN"."CMCS_TRANSFER_STATUS" ADD CONSTRAINT "XPKCMCS_TRANSFER_STATUS" PRIMARY KEY ("TS_STATUS") using index CASEMAN.XPKCMCS_TRANSFER_STATUS ENABLE;



  ALTER TABLE "CASEMAN"."PAYEES" ADD CONSTRAINT "XPKCODED_CREDITORS" PRIMARY KEY ("PARTY_ID") using index CASEMAN.XPKCODED_CREDITORS ENABLE;



  ALTER TABLE "CASEMAN"."CONTENT_STORE" ADD CONSTRAINT "XPKCONTENT_STORE" PRIMARY KEY ("ID") using index CASEMAN.XPKCONTENT_STORE ENABLE;



  ALTER TABLE "CASEMAN"."CPR_TO_CPR_RELATIONSHIP" ADD CONSTRAINT "XPKCPR_TO_CPR_RELATIONSHIP" PRIMARY KEY ("CPR_A_CASE_NUMBER", "CPR_A_CASE_PARTY_NO", "CPR_A_PARTY_ROLE_CODE", "CPR_B_CASE_NUMBER", "CPR_B_CASE_PARTY_NO", "CPR_B_PARTY_ROLE_CODE") using index CASEMAN.XPKCPR_TO_CPR_RELATIONSHIP ENABLE;



  ALTER TABLE "CASEMAN"."CURRENCY" ADD CONSTRAINT "XPKCURRENCY" PRIMARY KEY ("CURRENCY_CODE") using index CASEMAN.XPKCURRENCY ENABLE;



  ALTER TABLE "CASEMAN"."DCA_USER" ADD CONSTRAINT "XPKDCA_USER" PRIMARY KEY ("USER_ID") using index CASEMAN.XPKDCA_USER ENABLE;



  ALTER TABLE "CASEMAN"."DFJ_AREAS" ADD CONSTRAINT "XPKDFJ_AREAS" PRIMARY KEY ("DFJ_AREA_ID") using index CASEMAN.XPKDFJ_AREAS ENABLE;



  ALTER TABLE "CASEMAN"."DOCUMENT_STORE" ADD CONSTRAINT "XPKDOCUMENT_STORE" PRIMARY KEY ("ID") using index CASEMAN.XPKDOCUMENT_STORE ENABLE;



  ALTER TABLE "CASEMAN"."ETHNIC_ORIGIN" ADD CONSTRAINT "XPKETHNIC_ORIGIN" PRIMARY KEY ("ETHNIC_ORIGIN_CODE") using index CASEMAN.XPKETHNIC_ORIGIN ENABLE;



  ALTER TABLE "CASEMAN"."FEES_PAID" ADD CONSTRAINT "XPKFEES_PAID" PRIMARY KEY ("FEES_PAID_ID") using index CASEMAN.XPKFEES_PAID ENABLE;



  ALTER TABLE "CASEMAN"."FTP_QUEUE" ADD CONSTRAINT "XPKFTP_QUEUE" PRIMARY KEY ("REQUEST_ID") using index CASEMAN.XPKFTP_QUEUE ENABLE;



  ALTER TABLE "CASEMAN"."GIVEN_ADDRESSES" ADD CONSTRAINT "XPKGIVEN_ADDRESSES" PRIMARY KEY ("ADDRESS_ID") using index CASEMAN.XPKGIVEN_ADDRESSES ENABLE;



  ALTER TABLE "CASEMAN"."INFAVOUR_PARTIES" ADD CONSTRAINT "XPKINFAVOUR_PARTIES" PRIMARY KEY ("JUDG_SEQ", "CASE_NUMBER", "CASE_PARTY_NO", "PARTY_ROLE_CODE") using index CASEMAN.XPKINFAVOUR_PARTIES ENABLE;



  ALTER TABLE "CASEMAN"."JUDGES" ADD CONSTRAINT "XPKJUDGES" PRIMARY KEY ("JUDGE_ID") using index CASEMAN.XPKJUDGES ENABLE;



  ALTER TABLE "CASEMAN"."LOCAL_AUTHORITY_CODES" ADD CONSTRAINT "XPKLOCAL_AUTHORITY_CODES" PRIMARY KEY ("LAC_CODE") using index CASEMAN.XPKLOCAL_AUTHORITY_CODES ENABLE;



  ALTER TABLE "CASEMAN"."NATIONAL_CODED_PARTIES" ADD CONSTRAINT "XPKNATIONAL_CODED_PARTIES" PRIMARY KEY ("CODE") using index CASEMAN.XPKNATIONAL_CODED_PARTIES ENABLE;



  ALTER TABLE "CASEMAN"."NON_WORKING_DAYS_EXCEPTIONS" ADD CONSTRAINT "XPKNON_WORKING_DAYS_EXCEPTIONS" PRIMARY KEY ("NON_WD_EX_SEQ") using index CASEMAN.XPKNON_WORKING_DAYS_EXCEPTIONS ENABLE;



  ALTER TABLE "CASEMAN"."PARTIES" ADD CONSTRAINT "XPKPARTIES" PRIMARY KEY ("PARTY_ID") using index CASEMAN.XPKPARTIES ENABLE;



  ALTER TABLE "CASEMAN"."PARTY_ROLES" ADD CONSTRAINT "XPKPARTY_ROLES" PRIMARY KEY ("PARTY_ROLE_CODE") using index CASEMAN.XPKPARTY_ROLES ENABLE;



  ALTER TABLE "CASEMAN"."PARTY_TO_PARTY_RELATIONSHIP" ADD CONSTRAINT "XPKPARTY_TO_PARTY_RELATIONSHIP" PRIMARY KEY ("PARTY_A_ID", "PARTY_A_ROLE_CODE", "PARTY_B_ID", "PARTY_B_ROLE_CODE") using index CASEMAN.XPKPARTY_TO_PARTY_RELATIONSHIP ENABLE;



  ALTER TABLE "CASEMAN"."PARTY_TYPES" ADD CONSTRAINT "XPKPARTY_TYPES" PRIMARY KEY ("PARTY_TYPE_CODE") using index CASEMAN.XPKPARTY_TYPES ENABLE;



  ALTER TABLE "CASEMAN"."PERSONALISE" ADD CONSTRAINT "XPKPERSONALISE" PRIMARY KEY ("CRT_CODE") using index CASEMAN.XPKPERSONALISE ENABLE;



  ALTER TABLE "CASEMAN"."PL_FILELEVEL_PREVAL_STATUS" ADD CONSTRAINT "XPKPL_FILELEVEL_PREVAL_STATUS" PRIMARY KEY ("FILE_NAME") using index CASEMAN.XPKPL_FILELEVEL_PREVAL_STATUS ENABLE;



  ALTER TABLE "CASEMAN"."PL_JOB_QUEUE" ADD CONSTRAINT "XPKPL_JOB_QUEUE" PRIMARY KEY ("REQUEST_ID") using index CASEMAN.XPKPL_JOB_QUEUE ENABLE;



  ALTER TABLE "CASEMAN"."PL_RECORDLEVEL_PREVAL_STATUS" ADD CONSTRAINT "XPKPL_RECORDLEVEL_PREVAL_STATU" PRIMARY KEY ("RECORDSEQNO", "FILE_NAME") using index CASEMAN.XPKPL_RECORDLEVEL_PREVAL_STATU ENABLE;



  ALTER TABLE "CASEMAN"."PL_XML_STATUS" ADD CONSTRAINT "XPKPL_XML_STATUS" PRIMARY KEY ("SEQUENCE_NO") using index CASEMAN.XPKPL_XML_STATUS ENABLE;



  ALTER TABLE "CASEMAN"."PRINT_JOB" ADD CONSTRAINT "XPKPRINT_JOB" PRIMARY KEY ("PRINT_JOB_ID") using index CASEMAN.XPKPRINT_JOB ENABLE;



  ALTER TABLE "CASEMAN"."REJECT_REASONS" ADD CONSTRAINT "XPKREJECT_REASONS" PRIMARY KEY ("REJECT_CODE") using index CASEMAN.XPKREJECT_REASONS ENABLE;



  ALTER TABLE "CASEMAN"."CCBC_REPORTS" ADD CONSTRAINT "XPKREPORTS" PRIMARY KEY ("ID") using index CASEMAN.XPKREPORTS ENABLE;



  ALTER TABLE "CASEMAN"."REPORT_OUTPUT" ADD CONSTRAINT "XPKREPORT_OUTPUT" PRIMARY KEY ("OUTPUT_ID") using index CASEMAN.XPKREPORT_OUTPUT ENABLE;



  ALTER TABLE "CASEMAN"."REPORT_REPRINTS" ADD CONSTRAINT "XPKREPORT_REPRINTS" PRIMARY KEY ("USERNAME", "REPORT_ID") using index CASEMAN.XPKREPORT_REPRINTS ENABLE;



  ALTER TABLE "CASEMAN"."REPORT_SEQUENCES" ADD CONSTRAINT "XPKREPORT_SEQUENCES" PRIMARY KEY ("FORM_NAME") using index CASEMAN.XPKREPORT_SEQUENCES ENABLE;



  ALTER TABLE "CASEMAN"."SERVER_SECRET" ADD CONSTRAINT "XPKSERVER_SECRET" PRIMARY KEY ("SERVER_SECRET_ID") using index CASEMAN.XPKSERVER_SECRET ENABLE;



  ALTER TABLE "CASEMAN"."TAPES" ADD CONSTRAINT "XPKTAPES" PRIMARY KEY ("SEQNO") using index CASEMAN.XPKTAPES ENABLE;



  ALTER TABLE "CASEMAN"."TAPE_FILES" ADD CONSTRAINT "XPKTAPE_FILES" PRIMARY KEY ("ORDERSEQ") using index CASEMAN.XPKTAPE_FILES ENABLE;



  ALTER TABLE "CASEMAN"."TRAN_ADDRESS" ADD CONSTRAINT "XPKTRAN_ADDRESS" PRIMARY KEY ("CRT_CODE", "ADDR_TYPE", "ADDR_TYPE_SEQ") using index CASEMAN.XPKTRAN_ADDRESS ENABLE;



  ALTER TABLE "CASEMAN"."TRAN_COURTS" ADD CONSTRAINT "XPKTRAN_COURTS" PRIMARY KEY ("CODE") using index CASEMAN.XPKTRAN_COURTS ENABLE;



  ALTER TABLE "CASEMAN"."USER_COURT" ADD CONSTRAINT "XPKUSER_COURT" PRIMARY KEY ("USER_ID", "COURT_CODE") using index CASEMAN.XPKUSER_COURT ENABLE;



  ALTER TABLE "CASEMAN"."USER_ROLE" ADD CONSTRAINT "XPKUSER_ROLE" PRIMARY KEY ("USER_ID", "COURT_CODE", "ROLE_ID") using index CASEMAN.XPKUSER_ROLE ENABLE;



  ALTER TABLE "CASEMAN"."WARRANT_RETURNS" ADD CONSTRAINT "XPKWARRANT_RETURNS" PRIMARY KEY ("WARRANT_RETURNS_ID") using index CASEMAN.XPKWARRANT_RETURNS ENABLE;



  ALTER TABLE "CASEMAN"."WP_OUTPUT" ADD CONSTRAINT "XPKWP_OUTPUT" PRIMARY KEY ("OUTPUT_ID") using index CASEMAN.XPKWP_OUTPUT ENABLE;



  ALTER TABLE "CASEMAN"."WP_TRANSFORMATIONS" ADD CONSTRAINT "XPKWP_TRANSFORMATIONS" PRIMARY KEY ("DOCUMENT_TEMPLATE") using index CASEMAN.XPKWP_TRANSFORMATIONS ENABLE;


